grafana/pyroscope

webapp/javascript/util/format.js
Currently there are not enough colors so often two filenames/packages look like they're one (i.e. if a function in `filename_a.py` calls a function `filename_b.py` they may both be orange making it hard to tell that the two functions come from different files. 
This just adds a few more colors to help fix that without making the flame graph look too busy.
Fixes #12
=> Adds a few more colors to flamegraph color palette

webapp/javascript/components/CustomDatePicker.jsx, webapp/javascript/components/DateRangePicker.jsx, webapp/javascript/util/formatDate.js, webapp/sass/components/daterangepicker.scss
this PR fixes #54 and #60 
any remarks about the code or the comments let me know
I tested the functionality before this pr but if something isn't working open an issue or mention it here so I can fix it
=> improved the date range selector and fixed #54 #60

pkg/config/config.go, pkg/server/controller.go, webapp/javascript/util/update_requests.js, webapp/templates/index.html
This PR adds a config option to add a [base](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) meta tag in the pyroscope webapp.
The rationalle behind this is to allow the app to be served as a path behind a reverse proxy (ie. `https://some.host/pyroscope/`)
This can technically be done via the `EXTRA_METADATA` env var, but requires a path to a file which makes it a bit more cumbersome. (And the render path would need to be made relative still.)
---
In order to test this out you can do so in a local docker-compose with caddy.
You'll need a `docker-compose.yml`:
```yml
version: "3.8"
services:
caddy:
image: caddy
container_name: caddy
ports:
- 8080:8080
volumes:
- ./Caddyfile:/etc/caddy/Caddyfile:ro
pyroscope:
image: pyroscope/pyroscope:dev
container_name: pyroscope
ports:
- …
```
=> Add config option for setting the app's base url

pkg/agent/upstream/remote/remote.go
Currently the upload URL overrides the whole path on the server URL given to the agent.
Assuming the server URL of `https://localhost/pyroscope/` is given to the agent, it will attempt to upload to `https://localhost/ingest` instead of the (imo at least) expected `https://localhost/pyroscope/ingest`.
If you think this might break things please let me know of any better ways of dealing with this issue and I can update the PR. :)
Thank you very much in advance!
=> fix upload URL to include existing path

pkg/agent/upstream/remote/remote.go, pkg/server/controller.go
When I use pyroscope with golang, I got some problem, as the same with the issue [#70](https://github.com/pyroscope-io/pyroscope/issues/70), and I found something with wireshark as blow:
The Server closed connection, the reason is: without setting `IdleTimeout` in `http.Server`,  `ReadTimeout` will be used instead,  We can find instructions [here](https://github.com/golang/go/blob/release-branch.go1.14/src/net/http/server.go#L2560),  besides,  the agent will sent to server at 10s intervals, so that's what happens in the picture above。
So I set `IdleTimeout` with magic number `30`, so the connection can be reused.
=> fix connection reuse

.gitignore
- ignore `.idea` for IDEA or GoLand
- ignore `. vscode ` for VSCode
- ignore `vendor/ ` for Golang
=> Add ignore directory

pkg/storage/key.go, revive.toml
This PR addresses
- the ParseKey functions cognitive complexity
- the ParseKey functions cyclomatic complexity
- whitelist the strings.Builder.WriteString() method from unhandled error check
=> Go lint updates

pkg/config/config.go, pkg/dbmanager/cli.go, pkg/storage/segment/fuzz_test.go, pkg/storage/segment/segment.go, pkg/storage/segment/segment_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/testing/time.go
This PR addresses some bugs found in segment tree implementation and adds some tests.
Addresses #28
=> Segment Tree bug fixes

pkg/cli/cli.go
I was reading code and stumbled on this command that wasn't set up. It looks like it was accidentally included in a66f8b3408f77109b93bf5f44553c48b37cecbb2
=> Remove broken upload command

.dockerignore, Dockerfile
This does some small cleanup in the Dockerfile
1. Remove the `apk install cargo rust`. This is being done in the next line, and it gives the following warning -
```
---> Running in 0851d6e7854d
info: downloading installer
warning: it looks like you have an existing installation of Rust at:
warning: /usr/bin
warning: rustup should not be installed alongside Rust. Please uninstall your existing Rust first.
warning: Otherwise you may have confusion unless you are careful with your PATH
warning: If you are sure that you want both rustup and your already installed Rust
warning: then please reply `y' or `yes' or set RUSTUP_INIT_SKIP_PATH_CHECK to yes
warning: or pass `-y' to ignore all ignorable checks.
error: cannot install while Rust is installed
warning: continuing (because the -y flag is …
```
=> Improvements to Dockerfile

pkg/agent/csock/csock.go, pkg/storage/dict/trie.go, pkg/util/attime/attime_test.go
Continuation of #49
Warnings fixed -
```
pkg/agent/csock/csock.go
(60, 2)  https://revive.run/r#unhandled-error  Unhandled error in call to function json.Unmarshal  
(68, 2)  https://revive.run/r#unhandled-error  Unhandled error in call to function rw.Write 
pkg/util/attime/attime_test.go
(10, 37)  https://revive.run/r#empty-lines  extra empty line at the start of a bloc
pkg/storage/dict/trie.go   
(116, 11)  https://revive.run/r#superfluous-else      if block ends with a continue statement, so drop this else and outdent its block  
(73, 10)   https://revive.run/r#indent-error-flow     if block ends with a return statement, so drop this else and outdent its block
```
Unified diff is slightly difficult to read, easier to view the split one to ensure nothing has changed
=> Fix some Revive lint warnings

scripts/generate-build-flags.sh, scripts/pinned-tool.sh
Fixes a `Bad Substitution` error when running `make lint` on Ubuntu 18.04. `/bin/sh` doesn't have the `${@:2}` syntax. Error:
```
$ make lint                             
scripts/pinned-tool.sh github.com/mgechev/revive -config revive.toml -exclude ./vendor/... -formatter stylish ./...
scripts/pinned-tool.sh: 5: scripts/pinned-tool.sh: Bad substitution
Makefile:73: recipe for target 'lint' failed
make: *** [lint] Error 2
```
After fixing this, the `$(go list -m -f '{{.Dir}}' $1)` part was returning empty string, which resulted in `go run: cannot run non-main package` error. Found after adding some debug statements -
```
$ make lint
scripts/pinned-tool.sh github.com/mgechev/revive -config revive.toml -exclude ./vendor/... -formatter stylish ./...
+ echo github.com/mgechev/revive …
```
=> Use bash to run scripts

pkg/agent/upstream/direct/direct.go, pkg/agent/upstream/remote/remote.go
panic callstack
```bash
INFO[227235] storage.Put                                   endTime="2021-04-03 01:13:00 +0000 UTC" key="pyroscope.server.cpu{}" samples=14 startTime="2021-04-03 01:13:00 +0000 UTC"
panic: division by zero
goroutine 8 [running]:
math/big.(*Rat).SetFrac64(0xc027d889c0, 0x0, 0x0, 0x0)
math/big/rat.go:321 +0xff
math/big.NewRat(...)
math/big/rat.go:34
github.com/pyroscope-io/pyroscope/pkg/storage/segment.overlapWrite(0x0, 0xed7cbcd80, 0x1bf0b00, 0x0, 0xed8646400, 0x1bf0b00, 0x0, 0xed7f9b81c, 0x1bf0b00, 0x0, ...)
github.com/pyroscope-io/pyroscope/pkg/storage/segment/overlap.go:45 +0x229
github.com/pyroscope-io/pyroscope/pkg/storage/segment.(*streeNode).overlapWrite(0xc02360c1e0, 0x0, 0xed7f9b81c, 0x1bf0b00, 0x0, 0xed7f9b81c, 0x1bf0b00, 0xed7f9b81c) …
```
=> fix upload panic(do upload with recover)

.github/workflows/lint-go.yml, Makefile, cmd/pyroscope/main.go, pkg/config/config.go, pkg/storage/segment/constants.go, pkg/storage/segment/fuzz_test.go, pkg/storage/segment/segment.go, pkg/storage/segment/segment_test.go, pkg/storage/segment/serialization.go, pkg/storage/segment/serialization_test.go, pkg/storage/segment/timeline_test.go, pkg/storage/storage.go, pkg/testing/config.go
This refactors `pkg/storage/segment` and makes certain parameters constants instead.
=> Cleans up pkg/storage/segment and global state

Dockerfile, Makefile, examples/php/Dockerfile, examples/php/docker-compose.yml, examples/php/main.php, pkg/agent/phpspy/phpspy.go, pkg/agent/phpspy/placeholder.go, pkg/agent/session.go, pkg/agent/spy/spy.go, pkg/analytics/analytics.go, third_party/phpspy/phpspy.h
These are instructions on how to test changes in this PR
* clone pyroscope repo
```
git clone https://github.com/pyroscope-io/pyroscope
```
* clone phpspy library repo
```
git clone https://github.com/pyroscope-io/phpspy
```
To test changes you make in phpspy repo:
* first, build phpspy library:
```bash
cd phpspy
docker build . --tag pyroscope/phpspy:dev
```
* second, build a new pyroscope version:
```bash
cd pyroscope
docker build . --tag pyroscope/pyroscope:dev
```
* third, build and run the example application with the new pyroscope version:
```bash
cd pyroscope/examples/php
docker-compose build && docker-compose up
```
=> Adds PHP support via phpspy

pkg/agent/dotnetspy/dotnetspy.go, pkg/agent/dotnetspy/dotnetspy_suite_test.go, pkg/agent/dotnetspy/dotnetspy_test.go, pkg/agent/dotnetspy/session.go
There is a case when `dotnetspy` couldn't establish a connection to Diagnostics Server before the next snapshot/stop call (e.g, target process exited, or the socket file cannot be found, etc).
This fix adds a check whether the session has been actually created before accessing it. Given that there are no race conditions between reset/stop/snapshot calls, redundant mutexes were removed.
=> Fix dotnetspy panic on premature exit and add tests.

examples/golang/main.go
Otherwise, `work` function is inlined (go1.16.4 windows/amd64) and flamegraph becomes slightly less demonstrative.
Inlined:
With `go:noinline`:
=> Disable inlining for golang example

pkg/agent/cli/agent.go, pkg/agent/gospy/gospy.go, pkg/agent/profiler/profiler.go, pkg/agent/selfprofile.go, pkg/agent/session.go, pkg/agent/spy/spy.go, pkg/agent/types/types.go, pkg/agent/upstream/remote/remote.go, pkg/agent/upstream/upstream.go, pkg/cli/cli.go, pkg/config/config.go, pkg/exec/cli.go, pkg/server/ingest.go, pkg/storage/segment/segment.go, pkg/storage/segment/serialization.go, pkg/storage/storage.go, pkg/storage/tree/flamebearer.go
make the sample rate configured for python, ruby and go, but it doesn't take affect for go, because we use the the 'runtime profile' of golang, we need to find the way to build the customer profiler for go.
=> Fix issue #154: Add ability to change sampling rate

pkg/cli/cli.go, pkg/convert/parser.go, pkg/exec/cli.go
the output format is like:
INFO[25-05-2021 23:05:56] cli/cli.go:415 starting HTTP server
=> fix the issue #188: add the file name and code line

Dockerfile
Do not merge before:
https://github.com/pyroscope-io/phpspy/pull/3
=> Make phpspy use direct read from mem

pkg/agent/dotnetspy/session.go
Due to how dotnet profiler is different comparing to other spies, there is an obscure transforming of reported CPU time, which may be misleading. This PR is aimed to shed light on why it takes place.
=> Document dotnet magic denominator

pkg/storage/mem.go, pkg/storage/mem_linux.go
I introduced a pretty big bug in the latest version where it would detect amount of RAM available incorrectly. E.g here we can see pyroscope thought it had 8EB of RAM. So that threw off cache evictions procedure and led to OOM events.
This PR fixes that issue.
This is before / after this fix on a linux machine:
=> Fixes max memory available detection on linux

pkg/exec/cli.go, pkg/exec/cli_unix.go, pkg/exec/cli_windows.go
A regression has been introduced with graceful shutdown refactoring: signals (including `SIGINT`) are not sent to child process on Windows in `exec` mode. As a workaround, `CTRL_BREAK_EVENT` event will be send instead of `SIGINT`, any other signal will cause process termination.
Event `CTRL_C_EVENT` which is more close analogue of `SIGING` is sent to all processes sharing the current console (including parent): https://github.com/golang/go/issues/6720#issuecomment-66087740. Although, there is a way to disable signal handler, it may cause `pyroscope exec` process would become unresponsive.
It is worth it to mention that not all processes on Windows will exit on `CTRL_BREAK_EVENT` (it depends on the handler function the application sets for events), in particular, GUI applications would …
=> Fix signal sending on Windows

package.json, webapp/javascript/components/FlameGraphRenderer.jsx, webapp/javascript/index.jsx, webapp/sass/flamebearer.scss, yarn.lock
- moved some values computing into RenderCanvas
- rewrite tooltip positioning from absolute top-left values to transform CSS property.
There's still a render lag. It's not so long but still visible.  As the next step, I can put tooltip rendering inside canvas
=> improve tooltip rendering

scripts/decode-resp/decode.go, scripts/decode-resp/decode_suite_test.go, scripts/decode-resp/decode_test.go, scripts/decode-resp/main.go
This PR adds scripts/decode-resp for decoding response.
```
Decode response from pyroscope, for debugging
Usage: decode-resp -file <response.json>
where <response.json> is the body response from /render API
example: http://localhost:4040/render?from=now-1h&until=now&name=pyroscope.server.alloc_objects{}&max-nodes=1024&format=json
Flags:
-file string
path to response file (required)
-out string
name of output file (default to NAME.out.EXT)
```
=> scripts/decode-resp: decode flamebearer response for debugging

pkg/agent/gospy/gospy.go
Hello:
There is a problem happen with me: when I use custom sampling, the pyroscope can not display CPU profiles.
Discover by debug, there is an err: cpu profiling already in use
I found that custom sampling did not stop, so unable to call startCPUProfile from the second time.
=> fix(gospy.go): Snapshot add custom_pprof.StopCPUProfile()

pkg/config/config.go, pkg/server/controller.go
Allowing unauthentified users accessing /config and /build endpoints may be considered as a disclosure ([CWE-200](https://cwe.mitre.org/data/definitions/200.html)).
I general, it may make sense to restrict access to /build and /config endpoint to only admin users (or connections from localhost).
=> Protect diagnostic endpoints

pkg/agent/profiler/profiler.go
instead of the default list of ProfileTypes
=> fix(agent): use the ProfileTypes from the configuration

scripts/traffic-duplicator/example.sh, scripts/traffic-duplicator/main.go
This is a script that acts as a reverse proxy and duplicates profiling data between multiple upstream servers.
This will be useful for all sorts of demos — we could have one client report data to multiple servers (demo server, pr servers, etc)
=> Traffic duplicator

pkg/storage/migration.go, pkg/storage/storage.go
Refer to #310 for the detailed description. The goal of the migration is to prevent further corruption of trees caused by incorrect dictionary keys.
Depending on the version, the migration has different impact:
* < 0.0.34: Dictionary keys to be renamed to app name format. No negative impact.
* \> 0.0.33: No impact. Data ingested prior to the update to 0.0.34/0.0.35 is corrupted, which results in "label not found" nodes. Repairing of malformed trees is not implemented. Please let me know if you consider it needed.
=> Fix dictionary keys

pkg/server/controller.go, pkg/server/handler.go, pkg/server/render.go, pkg/storage/tree/flamebearer.go, pkg/storage/tree/treediff.go, pkg/storage/tree/treediff_test.go, webapp/javascript/components/ComparisonDiffApp.jsx, webapp/javascript/components/FlameGraphRenderer.jsx, webapp/javascript/components/ProfilerHeader.jsx, webapp/javascript/components/ProfilerTable.jsx, webapp/javascript/components/Sidebar.jsx, webapp/javascript/index.jsx, webapp/javascript/util/color.js, webapp/javascript/util/flamebearer.js, webapp/javascript/util/format.js, webapp/javascript/util/updateRequests.js, webapp/sass/profile.scss
This PR implements diff rendering:
Depends: #288
=> implement diff rendering

pkg/storage/tree/tree.go, pkg/storage/tree/treediff.go
This PR fixes `CombineToFlamebearerStruct()` when there are `other` nodes from both side.
=> fix diff tree

scripts/decode-resp/decode.go, scripts/decode-resp/decode_test.go
This PR updates scripts/decode-resp for decoding response with `format: double`.
=> scripts/decode-resp: update script for format double

pkg/storage/tree/tree.go
`v0.0.37` has a problem with memory consumption: some tree nodes are not garbage collected:
This is more than 50% of available memory, which causes endless cache evictions (and consequent GC calls) with no results.
(pprof snapshot has been taken for a different time window)
```
(pprof) list wrap  
Total: 18.30GB
ROUTINE ======================== github.com/pyroscope-io/pyroscope/pkg/server.wrapConvertFunction.func1.1 in github.com/pyroscope-io/pyroscope/pkg/server/ingest.go
16.10GB    16.10GB (flat, cum) 88.00% of Total
.          .    132:
.          .    133:func wrapConvertFunction(convertFunc func(r io.Reader, cb func(name []byte, val int)) error) func(io.Reader) (*tree.Tree, error) {
.          .    134:	return func(r io.Reader) (*tree.Tree, error) {
.          .    135:		t := …
```
=> Revert "improve tree.Insert"

pkg/util/debug/cpu.go
On Linux, if there are no file descriptors available, the call returns an empty slice, which results in server crash.
=> Fix CPU check

jest.config.js, webapp/javascript/components/CustomDatePicker.jsx, webapp/javascript/components/DateRangePicker.jsx, webapp/javascript/components/DownloadButton.jsx, webapp/javascript/components/Footer.jsx, webapp/javascript/components/Notifications.jsx, webapp/javascript/components/ProfilerHeader.jsx, webapp/javascript/components/RefreshButton.jsx, webapp/javascript/components/Sidebar.jsx, webapp/javascript/components/ZoomOutButton.jsx, webapp/javascript/redux/store.js, webapp/javascript/util/formatDate.js, yarn.lock
Before: 546.1 KB
After: 471.44 KB
^ these are gzipped production numbers from webpack bundle analyzer
This is what it currently looks like:
=> reduces bundle size

pkg/cli/command.go, pkg/cli/command_test.go, pkg/cli/testdata/clitest.non-yml-extension, pkg/cli/testdata/clitest.yml
This fixes a couple of bugs, particularly:
* setting config file path via `-config` or `PYROSCOPE_CONFIG` were broken
* setting config file path to a file with extension that's not `.yml` was broken
I also added tests, they're somewhat similar to existing ones (in `flags_test.go`) but test the cli from a slightly higher lever, so they should catch these kinds of bugs better in the future.
=> Config fixes, test cases

cypress/integration/basic.ts, webapp/javascript/components/ComparisonApp.jsx, webapp/javascript/components/ComparisonDiffApp.jsx, webapp/javascript/components/FlameGraphRenderer.jsx, webapp/javascript/components/PyroscopeApp.jsx, webapp/javascript/components/TagsBar.jsx, webapp/javascript/redux/actions.js, webapp/javascript/util/abort.js
Initially the cypress tests where flaky, as they were failing due the `.then` callbacks of `fetch` trying to access an unmounted component (think `setState`).
I added a nasty `waitInDevMode` to avoid that.
This PR cleans it up.
Since I was at it (ie. these weren't necessarily affecting the tests), I decided to add code to abort other requests too.
=> cypress: cleanup nasty waitInDevMode

.github/workflows/cypress-tests.yml, .github/workflows/tests-go.yml, Dockerfile, Dockerfile.windows, Makefile, go.mod, go.sum
**Not ready for merge:**
1. There is no official Golang 1.17 image for alpine-3.12;
2. There is a problem with building libunwind-1.3.1 on alpine > 3.12;
3. Updating libunwind to the latest version (1.5.0) breaks rustdeps build.
=> Bump go version to 1.17.0

webapp/javascript/components/FlameGraph/FlameGraphComponent/index.jsx, webapp/javascript/components/FlameGraph/FlameGraphRenderer.jsx
cypress tests were flaky due to a race condition (eg
https://github.com/pyroscope-io/pyroscope/actions/runs/1219594752)
just added checks to not access an unitialized variable
=> fix race conditions that were crashing cypress tests

benchmark/.gitattributes, benchmark/internal/cireport/screenshotter.go, benchmark/internal/cireport/screenshotter_test.go, monitoring/benchmark-pr.jsonnet, monitoring/gen/benchmark-pr.json
previously we assumed the dashboard we are taking screenshots doesn't have any rows
that, however, makes generating it with jsonnet a bit difficult (see the `gridPos` math below)
in this pr we support dashboards with rows, which then allow us to just add panels to a row and they will be placed correctly
=> support taking screenshot of dashboard with rows

cypress/integration/basic.ts, webapp/__tests__/__snapshots__/ProfilerHeader.spec.js.snap, webapp/javascript/components/FlameGraph/FlameGraphComponent/index.jsx, webapp/javascript/components/FlameGraph/FlameGraphRenderer.jsx, webapp/javascript/components/ProfilerHeader.jsx
Fixes #409 
Ended up adding a debounce to the search to make it faster (otherwise on every keystroke we would rerender the flamegraph)
No tests yet since they require visual testing, @ruslanpascoal2 will look into it later.
I think we should merge this as soon as possible and worry about the tests later.
BTW reset view is also broken, working on it in a different PR.
=> Fix search bar

cypress/fixtures/simple-golang-app-cpu.json, cypress/integration/basic.ts, webapp/javascript/components/FlameGraph/FlameGraphComponent/index.jsx, webapp/javascript/components/FlameGraph/FlameGraphRenderer.jsx, webapp/javascript/components/ProfilerHeader.jsx
The "Reset View" button wasn't working properly. This PR fixes it
Also added a simple test that clicks on the flamegraph, so maybe we could move that to a bigger test that tests the drill effect and whatnot.
@ruslanpascoal2 I've created a new fixture based on real profiling data (the go example), I think it's best to use this one from now on, since it makes testing easier since you have real, consistent data to base on (for example the previous `render.json` file produces a broken flamegraph).
=> Fix reset view

pkg/agent/profiler/profiler.go, pkg/agent/session.go, pkg/agent/session_test.go
For #433 
The issue mentions adding tests but I was a little unsure about the best way to add tests to the `profiler` because of the `upstream` instantiation. I added a couple of unit tests to the `session` which the profiler wraps instead but happy to revisit tests if y'all have some guidance on the best way to test the profiler
=> profiler: add support for dynamic tags

examples/ruby/Gemfile, examples/ruby/README.md
Updating these images thanks to the collapse feature that @eh-am added in #480 ... 
i.e. from this:
to this:
=> Updating ruby example images

webapp/javascript/components/ProfilerTable.jsx
This PR builds upon https://github.com/pyroscope-io/pyroscope/pull/480 (ie after that is merged I will rebase this one)
It improves flamegraph rendering performance by memoizing the table (on the left).
For illustration (With CPU throttling of 4x):
Before:
After:
`performance.measure` between the moment we click and after the canvas is rendered:
(With 4x throttling)
Before:
```
0: 2114.0999999940395
1: 2020
2: 2100.2000000029802
3: 2009.2000000029802
4: 2045.7999999970198
```
After:
```
0: 207.5
1: 142.40000000596046
2: 158.90000000596046
3: 154.59999999403954
4: 106.70000000298023
```
(Without CPU throttling):
```
1: 508.79999999701977
2: 510.20000000298023
3: 495.5
4: 498
5: 493.59999999403954
6: 673.0999999940395
7: 561.5
8: 488.3999999910593
9: 491.29999999701977
10: 512.8000000119209 …
```
=> Canvas performance

webapp/javascript/components/Sidebar.jsx, webapp/javascript/components/Sidebar.spec.tsx
This can happen if the location changes without using the sidebar (pressing back/next in browser).
The sidebar component will now subscribe to changes.
closes https://github.com/pyroscope-io/pyroscope/issues/320.
=> Fix sidebar getting out of sync

webapp/javascript/components/FlameGraph/FlameGraphComponent/Header.tsx, webapp/javascript/components/FlameGraph/FlameGraphComponent/canvas.module.css, webapp/javascript/components/FlameGraph/FlameGraphComponent/index.spec.tsx, webapp/javascript/components/FlameGraph/FlameGraphComponent/index.tsx, webapp/javascript/components/FlameGraph/FlameGraphComponent/styles.css, webapp/javascript/components/FlameGraph/FlameGraphComponent/testData.ts
If the selected application or range does not have data to show, we'll render a message saying so. Additionally, we won't show the "Frame width represents" text if there's nothing to show.
closes https://github.com/pyroscope-io/pyroscope/issues/483
=> Improve text when there is no data available

webapp/__tests__/ShortcutsModal.spec.js, webapp/javascript/components/Sidebar.jsx, webapp/javascript/components/Sidebar.spec.tsx
This PR uses the NavLink component on the sidebar to make these act as links. Because the history state is now managed by a 3rd party, we can safely remove the previous test as well (otherwise we would be basically testing the 3rd party library...).
closes https://github.com/pyroscope-io/pyroscope/issues/305
=> Make sidebar links

cmd/pyroscope/command/connect.go, cmd/pyroscope/command/exec.go, pkg/analytics/analytics_test.go, pkg/cli/server.go, pkg/dbmanager/cli.go, pkg/exec/cli.go, pkg/exec/cli_unix.go, pkg/exec/config.go, pkg/exec/config_test.go, pkg/exec/exec_test.go, pkg/server/build_test.go, pkg/server/config_test.go, pkg/server/controller_gzip_test.go, pkg/server/controller_https_test.go, pkg/server/ingest_test.go, pkg/server/render_test.go, pkg/storage/codec.go, pkg/storage/config.go, pkg/storage/config_test.go, pkg/storage/local.go, pkg/storage/periodic.go, pkg/storage/query_test.go, pkg/storage/storage.go, pkg/storage/storage_test.go, pkg/testing/load/cmd/dataloader/main.go
Internal components' configuration is coupled to public CLI configuration, which makes evolving public and internal configurations independently is harder than it should. This goes both
ways, e.g.:
- Deprecated configuration variables are still accessible internally.
- Adding internal configuration variables without exposing them publicly is hard.
The case of the storage component is worse, as it has access to a lot of unneeded server configuration variables.
While this problem already shows in the code (in how `dbmanager` was implemented, or exec/connect distinction, for example), it may become worse with `adhoc` mode (where we may want to use in-memory storage, direct upload, remove server app, etc.).
This refactor tries to solve this problem by isolating public and private …
=> Decouple internal config from public CLI config in exec and server/storage

pkg/storage/db.go
Without size-based retention policies, forced compaction does not give us any benefits, meanwhile consumes lots of resources.
=> Remove Flatten call before Badger GC call

scripts/webpack/webpack.dev.js
Starting from a clean env
```
make install-dev-tools
make build-third-party-dependencies
make install-web-dependencies
make dev
``` 
Should work now
@abeaumont pleeease can you check it works for you?
If it works I will update the documentation later.
---
Just some explanation, by moving `WebpackPluginServe` to the front, we wait for the build to be finished (`waitForBuild`), which generates `webapp/public/assets`, which the go server serves. The `HtmlWebpackPlugin` hits the go server and serves that under the port `4041`. Whew.
=> simplify local dev

cypress.json
we noticed tests sometimes fail with false negatives (specially the screenshot ones)
this commit uses Test Retries
https://docs.cypress.io/guides/guides/test-retries#Only-upload-videos-for-specs-with-failing-or-retried-tests
to retry each failed test up to 3 times
that should be enough to get rid of most flakyness and also not be slow
enough to delay real failures too much
=> chore: retry cypress tests

pkg/admin/http_over_uds_server_test.go
@abeaumont mentioned while [running linux tests](https://github.com/pyroscope-io/pyroscope/pull/532), that one of the admin tests was failing:
```
------------------------------ 
• Failure [0.000 seconds] 
HTTP Over UDS 
/home/abeaumont/p/pyroscope/pkg/admin/http_over_uds_server_test.go:17 
when passed a non existing socket address 
/home/abeaumont/p/pyroscope/pkg/admin/http_over_uds_server_test.go:32 
should give an error [It] 
/home/abeaumont/p/pyroscope/pkg/admin/http_over_uds_server_test.go:33 
Expected an error to have occurred. Got: 
<nil>: nil 
/home/abeaumont/p/pyroscope/pkg/admin/http_over_uds_server_test.go:38 
------------------------------ 
••• 
Summarizing 1 Failure: 
[Fail] HTTP Over UDS when passed a non existing socket address [It] should give an error …
```
=> chore: skip admin test that creates files in non accessible path when root

cmd/pyroscope/command/admin.go, pkg/admin/cli.go
Since the delete API is idempotent, ie, it won't fail if delete a non existent app, the cli ux could be a bit weird, since typos won't be immediately noticed.
We decided that as an easy improvement is to add autocomplete to the delete command, now at least it's less prone to typo.
For illustration, on my machine, `pyroscope admin app delete [tab][tab]` yields
=> feat: add shell completion for 'admin app delete' cmd

pkg/storage/storage_test.go
The storage was not being consistently closed, leaving the periodic
tasks alive, generating a race condition that was, only sometimes,
detected by the race detector.
=> Fix storage testsuite: always close the storage in the end.

package.json
Downgrading supports older v10 versions, which seem to work fine.
=> Downgrade minimal node engine version required from 11 to 10.

Dockerfile
Currently, running the published pyroscope binary or running a docker
container on exec mode to run Python programs causes a segmentation
fault, due to a stack overflow.
This doesn't seem to affect to binaries generated by other Linux
distributions, so Alpine setting a smaller default stack size maybe
the cause.
The default is overridden with a 2MB stack, which seems to be enough to
solve the problem.
Fixes #503
=> Fix the stack overflow on Alpine generated binaries.

pkg/admin/cli.go, pkg/admin/client.go, pkg/cli/server.go
For illustration: 
```
$ pyroscope admin app get
Error: failed to contact the admin socket server. 
this may happen if 
a) the admin socket server is not running 
b) the socket path is incorrect 
additional info: 2 errors occurred:
* failed to make a request
* Get "http://pyroscope/v1/apps": dial unix /tmp/pyroscope.sock: connect: no such file or directory
```
=> chore: improve error message for when admin server is not up

pkg/util/updates/updates.go
The testsuite (sometimes) fails due to this race condition.
Even if runOnce guarantees that there's a single writer, there can
still be concurrent read and writes. A read/write lock prevents this
from happening.
=> Fix race condition in version update.

go.mod, go.sum, pkg/admin/controller.go, pkg/admin/controller_test.go, pkg/admin/http_over_uds_server.go, pkg/admin/server.go
This was previously discussed in a meeting. In the long run we want to use a framework (we chose gorilla)  for our http servers.
This PR adds gorilla for the admin server, which is a bit more scoped and therefore easier to understand its impacts.
Unfortunately the API isn't exactly 1:1 with `net.ServeMux` so it required a little refactor (to receive `http.Handler` instead).
Also add a logging middleware as 
a) an example of how to add a middleware 
and b) I often find useful to check in the logs whether the request got received or not.
=> chore: use gorilla mux for admin server

pkg/admin/admin_integration_test.go, pkg/admin/client_test.go, pkg/admin/http_over_uds_client.go, pkg/admin/http_over_uds_server.go, pkg/admin/http_over_uds_server_test.go, pkg/admin/utils_test.go, pkg/cli/server.go
In https://github.com/pyroscope-io/pyroscope/pull/551 I increased the timeout, since the server may be busy (for ex when you are just starting the server, it happens often in local dev). But I didn't realize it also affected the tests.
This PR makes the HTTPOverUDSServer to receive a `HTTPClient` dependency which will be used to probe if there's an already runnign server. That `HTTPClient` can then be customized (here in tests we set a ver low timeout).
Just for reference, the timeout is set to 30 seconds by default, so tests (for `pkg/admin` bit) where taking at least that long. Now it's under half a second.
=> chore: make tests faster by reducing the timeout

pkg/admin/http_over_uds_server.go, pkg/admin/http_over_uds_server_test.go, pkg/cli/server.go
While debugging code with @kolesnikovae we noticed the admin socket server wasn't handling shutdown properly, which was affecting other things such as the cache writeback.
=> fix: ignore ErrServerClosed when admin server is closed

README.md, webapp/sass/profile.scss
https://github.com/pyroscope-io/pyroscope/issues/552
alignment adjust of the helper text above the timeline charts (comparison view)
=> fix: timeline guide text alignment

pkg/cli/server.go, pkg/config/config.go, pkg/storage/storage_get.go
As previously discussed in slack.
Motivations are:
a) reduce clutter when running locally (specially the logs)
b) reduce disk/mem usage for certain cases
c) maybe incorporate in adhoc? cc @abeaumont 
I was considering adding a `noopAgent` or something like that, but I guess simply not launching `selfProfiling` is the easiest way to go about this.
=> chore: add a flag to enable/disable self profiling

pkg/server/ingest.go
Since we are using a value receiver and a value pool, it was
efectively being copied.
Thanks @kolesnikovae for spotting it.
=> fix: Prevent byte buffer pool copy.

examples/golang/main.go
The comment refers to a hostname that was removed in 3286f05dae2235cc84248b81caa89a6af5e60e9d
=> docs: remove Go example obsolete comment

pkg/scrape/pprof.go
See #575: `trie.Insert` overrides values by default.
=> fix: generate trie from pprof at scraping correctly

pkg/adhoc/push.go, pkg/agent/clib/clib.go, pkg/agent/profiler/profiler.go
For native applications to work, they need to support the overriding
of the upstream address that ahdoc uses for this mode.
Instead of reusing PYROSCOPE_SERVER_ADDRESS enviroment variable,
a new variable PYROSCOPE_ADHOC_SERVER_ADDRESS has been used.
The users shouldn't be bothered with this override, using a separate
name should make it harder to see some undesired interactions.
Note that once this is merged the native integrations should be
upgraded to make use of this new clib for adhoc push to work.
=> feat: Add adhoc push mode support in clib.

benchmark/internal/config/config.go, go.mod, go.sum, pkg/cli/command.go, pkg/cli/command_test.go, pkg/cli/testdata/test-config.yml, pkg/config/config.go
Before, pyroscope server read the configuration from the default path only if the appropriate flag or env var was provided. In fact, the server ignored the default config file in most cases.
=> fix: use default config file

pkg/storage/segment/retention.go, pkg/storage/segment/timeline.go, pkg/storage/storage.go
Pyroscope server ignores the `retention` period configuration option if retention levels are not specified.
=> fix: trigger retention task when no levels are configured

package.json, webapp/javascript/components/AdhocSingle.jsx, webapp/javascript/components/ComparisonApp.jsx, webapp/javascript/components/ComparisonDiffApp.jsx, webapp/javascript/components/CustomDatePicker.jsx, webapp/javascript/components/FlameGraph/index.jsx, webapp/javascript/components/Footer.jsx, webapp/javascript/components/Header.jsx, webapp/javascript/components/NameSelector.jsx, webapp/javascript/components/PyroscopeApp.jsx, webapp/javascript/components/ShortcutsModal.jsx, webapp/javascript/components/Sidebar.jsx, webapp/javascript/components/TagsBar.jsx, webapp/javascript/components/TimelineChart.jsx, webapp/javascript/components/TimelineChartWrapper.jsx, webapp/javascript/redux/hooks.ts, webapp/javascript/redux/reducers/index.js, webapp/javascript/redux/reducers/views.ts, webapp/javascript/redux/store.ts, yarn.lock
Since more and more things are gonna be lifted to the redux store
we might as well start migrating to the official redux toolkit
This PR then introduces redux toolkit, which should be the way moving forward to create new reducers. We can slowly rewrite the existing code to use it.
One nuisance is that currently there's a single reducer, which makes difficult to run with them (old way/toolkit) side by side, so I had to move all the state into `state.root`.
=> refactor(frontend): use redux toolkit

package.json, yarn.lock
Version 0.13.1 doesn't seem to work with node v17.
=> chore: bump eslint-import-resolver-webpack dependency.

pkg/agent/clib/clib.go
This fixes a regression introduced in when automatic start in upstream
was removed.
=> fix: start upstream in clib.

benchmark/internal/cireport/tablereport.go, pkg/admin/admin_integration_test.go, pkg/admin/controller_test.go, pkg/agent/pprof/proto.go, pkg/agent/upstream/remote/remote.go, pkg/agent/upstream/remote/remote_test.go, pkg/analytics/analytics.go, pkg/analytics/analytics_test.go, pkg/cli/agent.go, pkg/convert/parser.go, pkg/convert/parser_test.go, pkg/convert/profile_extra_bench_test.go, pkg/scrape/config/config_http.go, pkg/server/build_test.go, pkg/server/config_test.go, pkg/server/controller_gzip_test.go, pkg/server/handler.go, pkg/server/render_test.go, pkg/storage/mem_linux.go, pkg/testing/load/cmd/dataloader/main.go, pkg/testing/tmpdir.go, pkg/util/updates/updates.go, scripts/decode-resp/main.go, scripts/generate-sample-config/main.go, scripts/pprof-view/main.go, scripts/traffic-duplicator/main.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
=> refactor: move from io/ioutil to io and os packages

webapp/javascript/components/ComparisonApp.jsx, webapp/javascript/components/ExportData.tsx, webapp/javascript/components/FlameGraph/FlameGraphComponent/Header.tsx, webapp/javascript/components/FlameGraph/FlameGraphRenderer.jsx, webapp/javascript/components/PyroscopeApp.jsx, webapp/javascript/redux/reducers/filters.js
Not optimal but it works.
Currently scoped to `single` flamegraphs (ie. singel view, comparison diff but NOT diff view, since we don't support importing that yet).
Had to store the raw response from /render in the store since that's what adhoc expects. Yadda yadda `deltaDiffWrapper` is troublesome.
=> feat(frontend): allow to export flamegraph json

package.json, yarn.lock
@grafana/ui was pulling a new jquery version
which was breaking the flot library
=> fix(frontend): set a specific jquery version

.devcontainer/Dockerfile
To use it:
```
devcontainer open .
```
then in the terminal:
```
make install-dev-tools
ENABLED_SPIES=none make dev
```
=> build: improves devcontainer

benchmark/docker-compose.yml
These names match the name expected int the start script.
=> chore: set image and container name explicitly in benchmarks.

webapp/javascript/components/AdhocComparison.tsx
Otherwise, the file list component's height is unbounded. cc: @eh-am
=> fix(frontend): add tab panel styles to adhoc comparison component.

Dockerfile, webapp/README.md
This PR does 2 things:
* Move installing yarn dependencies at the top of the Dockerfile. That way we don't have to pull dependencies if `package.lock/yarn.lock` haven't changed.
* Use [`RUN --mount=type=cache`](https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache) to cache dependencies between builds. This required updating our CI scripts to use the env var `DOCKER_BUILDKIT=1`
There's more room for improvements, but this should be a good start.
=> build: speed up docker builds

package.json, setupAfterEnv.ts, webapp/javascript/components/CustomDatePicker.tsx, webapp/javascript/util/formatDate.js, webapp/javascript/util/formatDate.spec.ts, yarn.lock
=> chore(frontend): replace momentjs for date-fns

cypress/integration/webapp/routes.ts, webapp/javascript/index.jsx, webapp/javascript/util/history.js
Closes #671 
This was introduced when we added baseUrl support, where we replaced the barebones `Router` for `BrowserRouter`, which broke the `react-query-sync` library, since it doesn't expose the `history` object which is handled under the hood.
(see more details at https://github.com/Treora/redux-query-sync/issues/13#issuecomment-327361957)
I spoke with @petethepig and the only reason we did that  was to allow passing a `basename`, which `BrowserRouter` support.
So I just replaced `BrowserRouter` for `Router` to get `redux-query-sync` working (which is the may issue this PR resolves), and then adds the basename to the history object.
The only thing here is that `basename` was removed from `history` from version 5 and onwards (https://github.com/remix-run/history/issues/810), so that …
=> fix(frontend): keep query param when changing routes

pkg/server/controller.go
`debug/pprof/goroutine` and many other pprof endpoints return 404.
Gorilla router doesn't automatically serve subpaths. Given that profiles like `goroutine`, `block`, and `mutex` are supposed to be handled by `pprof.Index`, the router configuration needs to be updated.
Although it is possible to use `PathPrefix("/debug/pprof/")`, it does not integrate with our routing setup well, therefore I decided to add handlers explicitly.
=> fix: register all pprof handlers

webapp/javascript/components/FlameGraph/FlameGraphComponent/ContextMenu.module.scss, webapp/javascript/components/FlameGraph/FlameGraphComponent/ContextMenu.tsx
Closes #668
After we stopped importing `node_modules/@szhsin/react-menu/dist/index.css` from `styles.scss`, it stopped being included by default. Instead, it's being imported when one component that uses it is imported (for example, the `DropdownComponent`). Hence, it works on the webapp.
However, `ContextMenu` also requires that style, and in the grafana panel plugin, we don't use a `DropdownComponent`, therefore that style is not present.
This PR makes the `ContextMenu` import the required style, fixing the problem above.
=> fix(panel): import @szhsin/react-menu styles in contextmenu

cypress/integration/webapp/basic.ts, cypress/integration/webapp/sidebar.ts, package.json, webapp/javascript/components/Sidebar.spec.tsx, webapp/javascript/components/Sidebar.tsx, webapp/javascript/index.jsx, webapp/javascript/redux/reducers/ui.ts, webapp/javascript/redux/store.ts, yarn.lock
Implements sidebar performance (related to https://github.com/pyroscope-io/pyroscope/issues/591)
The code is based on https://github.com/pyroscope-io/pyroscope/pull/681, except we only do the sidebar here.
The logic is similar to what twitch does:
* If the user has never interacted with the sidebar (state called 'pristine'):
* If the window is small, we set to collapsed
* If the window width is large, we set to uncollapsed
* If the user resizes the screen, these rules should be still be valid.
* If the user HAS interacted with the sidebar
* then we assume they know what they are doing and ALWAYS use what've chosen
* for example, if they had manually collapsed, we will always have it collapsed, even in bigger screens
---
Also added migrations, which currently don't do much but with new …
=> feat(frontend): persist sidebar collapsed state

cypress/integration/webapp/e2e.ts, webapp/javascript/components/Header.jsx, webapp/javascript/components/NameSelector.spec.tsx, webapp/javascript/components/NameSelector.tsx, webapp/javascript/components/TagsBar.jsx, webapp/javascript/redux/store.ts
When one opens up the app, there's no `query` set, so it uses a default based on certain heuristics.
That makes it a bit annoying when you refresh the page, since the app you were just lookign at may have changed (depending on these heuristics).
This PR does the following:
* if there's no query set in the url
* use the FIRST one, ordered alphabetically via what the store is returning
* pushes that to the store and CONSEQUENTELY updates the query param
https://user-images.githubusercontent.com/6951209/148997182-7f97b40e-c081-498a-be2f-3380323774cc.mp4
Also handles https://github.com/pyroscope-io/pyroscope/issues/656
https://user-images.githubusercontent.com/6951209/148997289-d9896e93-c3ce-453d-821f-184b1a8a0be0.mp4
=> chore(frontend): set a default query when there's nothing in the url

pkg/adhoc/server/server.go, pkg/adhoc/util/util.go, pkg/adhoc/util/util_darwin.go, pkg/adhoc/writer.go, pkg/cli/flags.go, pkg/cli/flags_test.go, pkg/cli/server.go, pkg/config/config.go
- Add instructions on how to launch the server / view profiling data after using `pyroscope adhoc`.
- Make adhoc data directory configurable.
- Use `$HOME/.pyroscope` by default adhoc data directory in macOS.
- Replace Walk by WalkDir and avoid recursive walking.
=> chore: adhoc polishing

pkg/storage/segment/serialization.go, pkg/storage/segment/serialization_bench_test.go, revive.toml
Segment tree serialization was done traversing the tree in depth
iteratively, using slices.
This causes a lot of slice insertions which caused an important amount
of allocations to grow these slices.
Serialization is now changed to do a recursive traversal instead,
which doesn't require any explicit data structure and thus all these
allocations are removed. Since the depth of segment trees is, in
practice, both bounded and small, it should be more efficient in all
cases, but especially as the segment trees grow.
A benchmark has also been included to be able to compare results
between the old and new implementations.
`benchstat` shows good results:
```
$ benchstat old.txt new.txt
name                            old time/op  new time/op  delta
Serialize/serialize_10-16       5.13µs ± 2% …
```
=> perf: optimize segment tree serialization.

webapp/javascript/services/appNames.spec.ts, webapp/javascript/services/appNames.ts
Due to circumstances, some of our old apps have empty strings as name. This PR ashamedly skips those when fetching from the backend.
Highlighted an app with empty name (which this PR skips)
=> fix(frontend): don't allow selecting empty apps

scripts/webpack/webpack.common.ts, webapp/README.md
That makes local builds faster https://webpack.js.org/guides/build-performance/#avoid-production-specific-tooling
We went from (dev, incremental build)
```
webpack 5.65.0 compiled with 1 warning in 1257 ms
```
to
```
webpack 5.65.0 compiled with 1 warning in 223 ms
```
@petethepig I even removed that ["optimization" we didn't like](https://github.com/pyroscope-io/pyroscope/pull/686#discussion_r780840358) since it doesn't seem to be relevant here anymore :)
=> chore: don't calculate webpack hash when in local dev

pkg/server/controller.go, pkg/storage/segment/segment.go, pkg/storage/storage_get.go
The PR adds pprof trace for storage Get. This is aimed at improving our ability to debug issues similar to https://github.com/pyroscope-io/pyroscope/issues/715.
The trace can be collected via the default `/debug/pprof/trace` endpoint:
1. Ensure pyroscope server is running and pprof endpoint is enabled (by default).
2. Start tracing (substitute URL as appropriate) - note that the duration is limited to 15s (we use 10 as it should be enough in most cases):
```
curl "http://localhost:4040/debug/pprof/trace?seconds=10" -o /tmp/trace
```
3. Execute the query of interest via UI/API.
4. Open collected trace with `go tool trace`:
```
go tool trace -http=localhost:7532 /tmp/trace
```
5. Navigate to the opened page, **User-defined tasks**, **storage.Get**.
6. You should see logs similar to: …
=> feat: storage.Get tracing

examples/ebpf/docker-compose.yml
I added the pid=host option to the ebpf docker example
The process ID of the host cannot be recognized from within the container, so the frame result will be UNKNOW.
However, with this PR fix, the result will be as follows.
```
Client:
Version:           20.10.12
API version:       1.41
Go version:        go1.17.5
Git commit:        e91ed5707e
Built:             Mon Dec 13 22:31:40 2021
OS/Arch:           linux/amd64
Context:           default
Experimental:      true
Server:
Engine:
Version:          20.10.12
API version:      1.41 (minimum version 1.12)
Go version:       go1.17.5
Git commit:       459d0dfbbb
Built:            Mon Dec 13 22:30:43 2021
OS/Arch:          linux/amd64
Experimental:     false
containerd:
Version:          v1.5.9
GitCommit: …
```
=> fix: add --pid=host option

Makefile
This was brought up by @petethepig, it's annoying how you run `make dev` then to only realize the app is not working because there are new dependencies. 
This PR makes  the `install-web-dependencies` run before `make dev`.
Also cleans up other tasks that don't seem to be used anymore.
=> chore: install yarn dependencies when running 'make dev'

pkg/adhoc/cli.go, pkg/analytics/analytics_test.go, pkg/cli/server.go, pkg/dbmanager/cli.go, pkg/health/controller.go, pkg/server/build_test.go, pkg/server/config_test.go, pkg/server/controller_gzip_test.go, pkg/server/controller_https_test.go, pkg/server/ingest_test.go, pkg/server/render_test.go, pkg/storage/storage.go, pkg/storage/storage_delete_test.go, pkg/storage/storage_put.go, pkg/storage/storage_test.go, pkg/testing/load/cmd/dataloader/main.go
The check was mistakenly removed in https://github.com/pyroscope-io/pyroscope/pull/456. Meanwhile, this is essential in some scenarios: pyroscope server won't start if it can't create a LOCK file.
=> fix: return disk space check

pkg/server/controller.go, pkg/storage/debug.go
The PR is aimed at improving debuggability. In order to solve issues like https://github.com/pyroscope-io/pyroscope/issues/715 more efficiently we need an option to export data from the storage in a user-friendly way. We extend our `/debug` endpoints list with `/debug/storage/export/{db}` that exports values from the storage via HTTP.
Example:
```
curl -G -o /tmp/segment --data-urlencode "k=s:pyroscope.server.cpu{}" http://localhost:4040/debug/storage/export/segments
```
The request will write `s:pyroscope.server.cpu{}` segment raw bytes to /tmp/segment.
NOTE: We have set 15 seconds HTTP server timeout, and it is not configurable. I'm wondering if this should be lifted - say, a minute, or two.
=> feat: add debug storage export endpoint

webapp/javascript/components/AdhocComparison.tsx, webapp/javascript/components/AdhocComparisonDiff.tsx, webapp/javascript/components/AdhocSingle.jsx
Currently tabs default to `~/.pyroscope`, but when we first release this that director will be empty. However, I suspect that people will have some pprof files laying around which they can use with Pyroscope adhoc mode, so lets default to the drag and drop view instead
=> Swap default tabs in adhoc mode

pkg/storage/retention.go
If an invalid key is discovered in the segment DB during "retention task", it should be logged.
=> fix: log raw segment key value if it can't be parsed

pkg/adhoc/server/convert.go, pkg/adhoc/server/server.go
This is a follow-up to #757. After some further discussion with @eh-am
we agreed that making these functions versioned gives a safer path to
handle version changes.
This is technically a backward-incompatible change that could be
avoided by creating both versioned and unversioned variants pointing
to the same code, but I think it's quite safe to break compatibility
here and avoid that burden.
=> refactor: make converted functions versioned.

pkg/storage/tree/tree_profile.go
due to empty string, the unsafeStrToSlice will result in the panic of the pyroscope server.
=> improve: fix unsafeStrToSlice panic due to empty string

webapp/javascript/ui/Dropdown.module.scss
Continuation of https://github.com/pyroscope-io/pyroscope/pull/750
=> chore(frontend): load css from ~node_modules instead of relative path

pkg/convert/parser.go, pkg/server/ingest.go
I created a very basic app (below) and noticed that it causes panic (below), at least in v0.8.0.
I dug in and found out that is caused by an empty profile, that is sent just when the app started.
Here is my proposal to fix it.
```go
package main
import (
"net/http"
"time"
"github.com/pyroscope-io/client/pyroscope"
"github.com/sirupsen/logrus"
)
func main() {
logger := logrus.New()
logger.Level = logrus.TraceLevel
pyroscope.Start(pyroscope.Config{
ApplicationName: "test-crash",
ServerAddress:   "http://localhost:4040",
Logger:          logger,
})
http.ListenAndServe(":8081", nil)
}
```
```
http: panic serving 172.22.0.1:55336: runtime error: invalid memory address or nil pointer dereference
goroutine 678 [running]:
net/http.(*conn).serve.func1()
net/http/server.go:1801 +0xb9 …
```
=> fix: Solve panic on an empty profile ingest

pkg/adhoc/server/model.go, pkg/adhoc/server/server.go, pkg/adhoc/server/server_suite_test.go, pkg/adhoc/server/server_test.go
This is an initial step towards improving the upload functionality in
adhoc. This allows the frontend to upload profiles in other supported
formats (frontend work still pending).
This still won't work for diff uploads, that will come later.
This is part of #784
=> feat: add upload support in adhoc server.

webapp/javascript/components/AdhocComparison.tsx, webapp/javascript/components/AdhocComparisonDiff.tsx, webapp/javascript/components/AdhocSingle.jsx, webapp/javascript/components/ComparisonApp.jsx, webapp/javascript/components/ComparisonDiffApp.jsx, webapp/javascript/components/ExportData.tsx, webapp/javascript/components/PyroscopeApp.jsx, webapp/javascript/components/exportToFlamegraphDotCom.hook.ts, webapp/javascript/models/flamegraphDotComResponse.ts, webapp/javascript/services/TestData.ts, webapp/javascript/services/share.spec.ts, webapp/javascript/services/share.ts, webapp/javascript/util/handleError.ts
* Add support for exporting to flamegraph.com for all adhoc pages and diff
* Add a notification for when request fails
* Lift the state up so that the export to flamegraph.com functionality can be implemented for the grafana plugins
* Support custom base url (not tested, but should work)
=> feat(frontend): export diff to flamegraph.com

pkg/adhoc/server/model.go, pkg/structs/flamebearer/flamebearer.go
This is a first step towards API documentation.
=> docs: add OpenAPI annotations for the data format and adhoc models.

pkg/config/config.go, pkg/server/controller.go
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials):
> The Access-Control-Allow-Credentials header works in conjunction with the [XMLHttpRequest.withCredentials](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) property or with the credentials option in the [Request()](https://developer.mozilla.org/en-US/docs/Web/API/Request/Request) constructor of the Fetch API. For a CORS request with credentials, for browsers to expose the response to the frontend JavaScript code, both the server (using the Access-Control-Allow-Credentials header) and the client (by setting the credentials mode for the XHR, Fetch, or Ajax request) must indicate that they’re opting into including credentials.
Without this option, …
=> fix: CORS allow credentials

scripts/webpack/webpack.common.ts
Closes https://github.com/pyroscope-io/pyroscope/issues/854
=> fix(frontend): only inline svg if imported via react

grafana-plugin/datasource/grafana-provisioning/datasources/datasources.yml, grafana-plugin/datasource/src/ConfigEditor.tsx, grafana-plugin/datasource/src/plugin.json, grafana-plugin/datasource/src/types.ts
The PR adds support for authentication to Grafana datasource plugin.
E2E test to be added later.
=> feat: adds support for auth to grafana datasource plugin

webapp/javascript/components/Settings/Preferences/index.tsx
Solves #907 
This pull request removes the required attribute from the email field on the Edit Profile page (/settings).
The initial issue also states that the Full Name field has a non-empty requirement, however, this does not seem to be the case on the latest build. (See [this image](https://user-images.githubusercontent.com/82543732/156444148-f7ba2a66-5d3f-4276-8ff8-ce0140acc057.png) which was the 3 input fields before I started)
=> chore: allow empty email on edit profile page

.github/workflows/publish-lib-to-npm.yml
Closes https://github.com/pyroscope-io/pyroscope/issues/913
* don't publish Pull Requests from forks, since the NPM_TOKEN  is not available.
=> ci: fetch pull request

webapp/javascript/components/Settings/APIKeys/APIKeyAddForm.tsx, webapp/javascript/redux/reducers/settings.ts
This pull request solves #905 :
The only time the errors in the form are set is when the `createAPIKey` function throws an error, however, in `createAPIKey` an error notification is already set whenever it throws an error. This resulted in duplicated error messages. The `StatusMessage` for errors is therefore seemingly redundant. I have left the success StatusMessage in place as it still includes valuable information.
The name field has also been made required to prevent making API calls that will always fail due to an empty name.
Furthermore, there were some typescript warnings that occurred because the `APIKeyAddProps` (or more specifically the `APIKey`) was missing `errors` and `ttlSeconds` on the type. I have instead extended `APIKey` into `APIKeyAddProps` and added (optional) fields …
=> chore: remove redundant error message and satisfy typescript warnings

scripts/oauth-mock/pyroscope-config.yml
the idea is to make it easier to test it
since most likely the test will go over the settings page
which require admin permissions
=> chore: use Admin as the default role when using oauth-mock

cmd/pyroscope/command/admin.go, pkg/admin/admin_integration_test.go, pkg/admin/cli.go, pkg/admin/client.go, pkg/admin/controller.go, pkg/admin/controller_test.go, pkg/admin/server.go, pkg/cli/server.go, pkg/config/config.go, pkg/server/controller.go, pkg/server/render.go, pkg/server/render_test.go, pkg/storage/cleanup.go, pkg/storage/profile.go, pkg/storage/profile_test.go, pkg/storage/retention.go, pkg/storage/segment/key.go, pkg/storage/storage.go, pkg/storage/storage_delete_test.go, pkg/storage/storage_get.go, pkg/storage/storage_merge.go, pkg/storage/storage_put.go
The PR adds a dedicated storage for trace profiles with support for time-based retention policy. See the retention policy configuration docs to learn how to set the data retention period: https://pyroscope.io/docs/data-retention/#time-based-retention-policy.
The change is not backward compatible: trace profiles created by previous versions are not accessible in the new version and are not removed automatically. Prior to the change, we did not store time information for profiles, therefore they can't be migrated automatically, but you can remove the data via admin CLI (depending on the number of saved profiles, cleaning may take a long time - 15 minutes and more):
```
```
---
We also extended the HTTP API with a new `/merge` endpoint:
```
--request POST \
--data …
```
=> feat: add dedicated profiles storage with support for retention policy

packages/pyroscope-flamegraph/package.json
Otherwise it fails with
```
$ yarn add -W @pyroscope/flamegraph
yarn add v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "browserslist@4.16.6" is incompatible with requested version "browserslist@4.14.2"
error Couldn't find package "@pyroscope/models@^0.0.3" required by "@pyroscope/flamegraph" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```
=> chore(flamegraph): remove models as a dependency

packages/pyroscope-flamegraph/src/FlamegraphRenderer.tsx, packages/pyroscope-flamegraph/src/index.node.ts, packages/pyroscope-flamegraph/src/index.tsx, scripts/webpack/webpack.flamegraph.ts
Since people may run the component in nodejs environments (think testing), they should be able to import the component.
It's not super simple to use outside the browser, but for testing we present a couple alternatives in the following example:
https://github.com/pyroscope-io/flamegraph-renderer-example
=> feat(flamegraph): publish FlamegraphRenderer for nodejs

go.mod, go.sum, pkg/convert/jfr/parser.go, pkg/convert/jfr_parser.go, pkg/server/ingest.go
Java Flight Recorder format is a binary format integrated into Java
and used by AsyncProfiler, which is the native profiler used for our
Java integration.
It's the only AsyncProfiler format that supports profiling multiple
events concurrently and, in order to support this, we have created a
JFR parser.
This is a first iteration towards full, multi-event JFR ingestion
support. In this initial work, only CPU events (cpu, itimer, wall) are
supported. Support for other events should come later.
=> feat(ingestion): initial support for JFR format ingestion.

pkg/storage/db.go, pkg/storage/storage.go
When a retention policy is enforced for the first time and the dataset is big, pyroscope server can go OOM because cache eviction is blocked during deleting old data.
=> fix: allow cache eviction while purging storage

scripts/webpack/shared.ts, scripts/webpack/webpack.flamegraph.ts
Reasoning is that the build sometimes fail with
```
#55 33.29 $ yarn run clean && yarn run build:standalone && yarn run build:webapp
#55 33.29 $ rm -rf public/assets && rm -rf public/*.html
#55 33.29 $ webpack --config ../scripts/webpack/webpack.standalone.ts
#55 33.29 assets by status 1.07 MiB [cached] 3 assets
#55 33.29 Entrypoint app = app.d504bc01b763df4f5fb9.css 0 bytes app.js
#55 33.29 Entrypoint styles = styles.d504bc01b763df4f5fb9.css 0 bytes styles.js
#55 33.29 orphan modules 234 KiB (javascript) 2.75 KiB (runtime) [orphan] 30 modules
#55 33.29 runtime modules 663 bytes 3 modules
#55 33.29 cacheable modules 745 KiB (javascript) 76.1 KiB (css/mini-extract)
#55 33.29   modules by path ../ 740 KiB (javascript) 47.9 KiB (css/mini-extract)
#55 33.29     javascript modules 740 KiB 15 …
```
=> build: don't generate css sourcemaps

pkg/convert/jfr/parser.go, pkg/server/ingest.go
When the Java profiler sends allocation events, four new profile types
will be generated. These events can be sent along with CPU profiling
events, which means initial support for multiple concurrent event
support in Java too.
=> feat(ingestion): add support for memory allocation events in JFR.

examples/tracing/honeycomb/go.mod, examples/tracing/honeycomb/go.sum, examples/tracing/honeycomb/log/log.go, examples/tracing/honeycomb/ride/ride.go, examples/tracing/honeycomb/rideshare/rideshare.go, examples/tracing/jaeger/go.mod, examples/tracing/jaeger/go.sum, examples/tracing/jaeger/ride/ride.go, examples/tracing/jaeger/rideshare/rideshare.go, pkg/storage/profile.go, pkg/storage/profile_test.go, pkg/storage/storage_get.go, pkg/storage/tree/profile_extra.go
The PR adds examples of tracing integration with support for baseline profiles.
Depends on https://github.com/pyroscope-io/otelpyroscope/pull/1 - otelpyroscope is referenced by the commit hash. Must be updated before merge. Until the release of the server, you can use the dev build for docker-compose:
```
PYROSCOPE_IMAGE=pyroscope/pyroscope-dev:git-111d45ec49ca9fbe00dfec7ee015e586783c9bd1
```
=> chore: add baseline profile examples

pkg/config/config.go, pkg/storage/config.go, pkg/storage/profile_test.go, pkg/storage/retention.go, pkg/storage/segment/retention.go, pkg/storage/storage.go
Closes #963
Although I named this parameter `exemplars-retention`, it's not entirely true: in fact we store all profiles with a `profile_id` label, therefore `exemplar` term can hardly be applied. On the other hand, perhaps we may consider implementing [sampling](https://opencensus.io/tracing/sampling).
=> feat: separate retention policy for exemplars

pkg/convert/pprof/pprof_test.go, pkg/scrape/config/config.go, pkg/storage/storage_get.go, pkg/storage/tree/pprof.go
In pull mode, the aggregation type is always `sum` because of the incorrect default configuration. This means that profiles that imply `average` value (for example, Go `inuse_objects` and `inuse_space`) report wrong data.
The PR fixes the default configuration and makes it so that already deployed configurations will also be handled properly.
=> fix(pull-mode): makes it so that memory profiles in pull mode report an average instead of sum

go.mod, go.sum, pkg/convert/jfr/parser.go
When wall is used for CPU profiling, the thread state can be used to
differentiate between runnable and sleeping threads.
Using this information, we can extract two different profile types:
- wall profile type, with all the execution samples.
- cpu profile type, with only the runnable threads.
In order to do so, jfr-parser version has been upgraded, as thread
state was not being properly retrieved.
Related to https://github.com/pyroscope-io/pyroscope-java/issues/3
=> feat(jfr): Split wall events into both CPU and Wall profile types.

pkg/server/render.go
See my comment [here](https://github.com/pyroscope-io/pyroscope/pull/1004#issuecomment-1092346973) for more context.
I intentionally added it to the controller (presentation layer), and not storage, because there's value in distinguishing between outputs like:
* successful reads, `out != nil`
* no data reads, `out == nil`
=> fix(server): always returns timeline even if there's not data

webapp/javascript/redux/async-thunk.ts, webapp/javascript/redux/reducers/continuous.ts, webapp/javascript/redux/reducers/notifications.ts, webapp/javascript/redux/reducers/serviceDiscovery.ts, webapp/javascript/redux/reducers/settings.ts, webapp/javascript/redux/reducers/user.ts, webapp/javascript/redux/store.ts, webapp/javascript/services/base.ts
The problem:
Sometimes components require access to the underlying error, so that we can do stuff like `error instanceof RequestIncompleteError` or `error.code == 401`. However, redux by default serializes/normalizes the error, making us lose these fields (https://github.com/reduxjs/redux-toolkit/blob/db0d7dc20939b62f8c59631cc030575b78642296/packages/toolkit/src/createAsyncThunk.ts#L98).
Also it's nice to have access to the underlying error when reporting to for example, sentry.
The solution
This PR creates a wrapper around `createAsyncThunk`, which then bakes an identity function `(x => x)` to the `serializeError`. We also need to skip serializable checks to the `error` field.
=> chore(webapp): don't serialize errors

.air.conf
As per https://github.com/pyroscope-io/docs/pull/59
Ideally we would use a allowlist instead of denylist, but... `¯\_(ツ)_/¯`
=> chore: reduce list of watched files by air

pkg/storage/cache/cache.go, pkg/storage/cache/cache_test.go, pkg/storage/storage.go, pkg/storage/storage_delete.go
Pyroscope server uses BadgerDB [`DropPrefix`](https://github.com/dgraph-io/badger/blob/156819ccb106bbeb207e985f561780e2929344bc/db.go#L1646-L1656) call to delete all the application keys (for example, when an application is removed or when a series ceased to exist because of the retention policy). The problem is that it blocks writes and forces LSM compaction which affects overall performance.
The fix removes the call - instead, keys are iterated and removed in batches in an explicit way.
=> fix: delete data in batches instead of using badgerDB DropPrefix

examples/tracing/jaeger/docker-compose.yml, examples/tracing/jaeger/grafana/provisioning/datasources/datasources.yml
The goal is to eventually add a derived field for pyroscope in addition to jaeger:
For example this configuration:
Allows us to cick directly on a log and create a query on the opposite side with the `trace_id` in the query box for jaeger
We'd like to be able to do the same thing eventually with Pyroscope i.e.
Note: This will be slightly broken at first because not all spans have corresponding profiles (only the root spans do)
cc/ @pavelpashkovsky
=> Add loki for logging and derived fields in tracing example

pkg/storage/exemplars.go
A regression has been introduced in https://github.com/pyroscope-io/pyroscope/pull/1018: BadgerDB `Flatten` call that is performed before dropping old exemplars in order to speed up the iterator causes huge overhead if the database is big.
=> fix: remove force compation

webapp/sass/profile.scss
Closes https://github.com/pyroscope-io/pyroscope/issues/1049
This solution uses https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode which should be supported in the majority of modern browsers.
Be aware that this solution is not super great for a few colors (see example below), but it's definitely an improvement from what we previously had
=> fix(flamegraph): fix table contrast

examples/tracing/jaeger/jaeger-ui/Dockerfile
This adds a diff from the baseline to the jaeger ui (not interesting in this picture because all requests are the same):
=> chore: Update commit so baseline profiles appear in jaeger ui

packages/pyroscope-flamegraph/README.md
Updates npm readme #1078 
Turns out there was no bug and I was just following old documentation. This updates the documentation to the proper API. 
We still have the issue of the css not being applied to the table:
I'll created a new issue for this #1080
=> Update npm readme

webapp/javascript/ui/Notifications.module.scss, webapp/javascript/ui/Notifications.tsx
Closes https://github.com/pyroscope-io/pyroscope/issues/1085
* Don't close when clicked (instead the only way to close is clicking on the X button)
* Increase the close button size
* Change the cursor to indicate it can be copied
https://user-images.githubusercontent.com/6951209/166822622-01fa7df7-5aea-469b-8193-7f7b4b6b2a6e.mp4
=> feat(frontend): allow copying notification message

pkg/storage/cleanup.go, pkg/storage/config.go, pkg/storage/db.go, pkg/storage/debug.go, pkg/storage/exemplars.go, pkg/storage/storage.go, pkg/storage/storage_delete_test.go, pkg/storage/types.go
Main changes:
* there's a new `NewBadger` function, allows to initialize badger differently
* `storage.Storage` takes an interface instead of a `*db` wrapper. The interface is too bloated and far from being perfect, fixing that is out of scope for this PR
=> chore: storage api changes

pkg/storage/tree/serialize.go
In contrast to the existing functions this one preserves `total` value.
=> chore: add SerializeTruncateNoDict

pkg/convert/jfr/parser.go, pkg/parser/parser.go, pkg/server/ingest_test.go
The issue is that jfr parser was built slightly differently compared to other parsers. It reused the same PutInput structure for multiple inserts within one request.
Moreover, pi.Val was set to nil at the after all writes were finished. 
This flaw was exposed after we merged #1104 because PutInput structs were now stored a little bit longer in memory and inserted asynchronously.
I refactored the jfr parser code to create new PutInput structs for each input, I also DRYed the code up a bit.
---
The tests didn't catch this because in tests the controller was initialized without a queue. This was my mistake, for some reason I thought tests were using the queue as well, and that's why I approved #1104. I updated tests to use a queue.
=> fix: jfr ingestion issue in 0.17.0

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/DiffLegendPaletteDropdown.module.css, webapp/sass/variables.css
Edited by Eduardo:
before it was like this
=> fix: flamegraph palette selector checkmark styles

examples/tracing/jaeger/grafana/provisioning/datasources/datasources.yml, examples/tracing/jaeger/main.go, examples/tracing/jaeger/ride/ride.go
Fixes derived field for loki integration and logs root span only (since that's where profiles are available)
=> Fix derived field in exemplar example for Loki

webapp/javascript/components/Continuous.tsx
This fixes an issue where if you don't have any apps it will have an infinite loop trying to get app names.
To reproduce, run  something like:
```
rm -rf tmp/pyroscope-storage
PYROSCOPE_NO_SELF_PROFILING=true make dev
```
I think this PR fixes it.  @eh-am I'm not sure if this is the right fix, please review.
=> fix: infinite loop when no apps are available

examples/tracing/jaeger/ride/ride.go
Removes (comments out) extra logging for POC of derived fields in loki
=> docs: remove extra logging from exemplars

pkg/cli/flags_test.go, pkg/cli/server.go, pkg/cli/testdata/server.yml, pkg/config/config.go, pkg/remotewrite/client.go, pkg/remotewrite/client_test.go
Allow writing to multiple targets.
Config example:
```yaml
remote-write:
enabled: true
targets:
bar:
address: http://localhost:4050
auth-token: "mytoken"
tags:
foo: bar
baz:
address: http://localhost:4060
auth-token: "mytoken"
tags:
foo: baz
```
There's a somewhat relevant point here: we are using maps instead of arrays due to how maps are easier to merge.
=> feat: multiple remote write targets

webapp/javascript/components/NameSelector.module.scss, webapp/javascript/components/NameSelector.tsx, webapp/javascript/components/Settings/APIKeys/APIKeyAddForm.tsx, webapp/javascript/components/Settings/Security/ChangePasswordForm.tsx, webapp/javascript/components/Settings/Users/UserAddForm.tsx, webapp/javascript/components/Settings/Users/Users.module.css, webapp/javascript/components/Settings/Users/index.tsx, webapp/javascript/components/TagsBar.tsx, webapp/javascript/ui/Input.module.scss, webapp/javascript/ui/Input.tsx, webapp/javascript/ui/InputField/index.tsx, webapp/sass/common.scss, webapp/sass/login.scss, webapp/sass/mixins/outline.scss
REF: https://github.com/pyroscope-io/pyroscope/issues/1126, https://github.com/pyroscope-io/pyroscope/pull/1127
All `<input/>` usages were updated to use `@ui/Input`, including it's styles
=> refactor(webapp): Text Input as standalone component

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/color.spec.ts, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/color.ts
Adds coloring for java:
https://flamegraph.com/share/8022667e-e6d7-11ec-925c-fab0c2c9d0a0
Tested with:
https://regex101.com/r/W5U0uD/2
cc @korniltsev @petethepig
=> chore: Add javaspy coloring for flamegraphs

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/color.ts
=> fix: Fix typo in regexp for javaspy

webapp/javascript/components/TagsBar.tsx, webapp/javascript/ui/Dropdown.module.scss, webapp/sass/components/tagsbar.scss
Missed a style in #1152... This will be easier to automatically check for in tests when we add tags to self profiling in #1137 . 
also worth noting that in #1136 we started to unify all of the inputs so there is a part of this that may be worth making part of the input component as I had to duplicate it in this pr.
before:
After:
=> fix: Fix missed style in tags submenu

pkg/remotewrite/queue_metrics.go
As mentioned by @kolesnikovae in the docs repo https://github.com/pyroscope-io/docs/pull/83/files/ed96e73a7bea232ccd7c37f6bf2c70655f650bd8#diff-b21ab40374e4bc443cf120a99fa819ba24abc66b82886ca59124c6d9841dde3a
We already use snake_case, so we should keep it for consistency.
=> chore(remotewrite): use snake case for target_{name,address}

pkg/cli/server.go, pkg/config/config.go, pkg/dbmanager/cli.go, pkg/selfprofiling/upstream.go
Closes https://github.com/pyroscope-io/pyroscope/issues/1137
Usage example:
```yaml
self-profiling-tags:
foo: bar
```
---
I tried to use
```go
SelfProfiling   SelfProfiling `yaml:"self-profiling" desc:"self profiling configurations"`
type SelfProfiling struct {
Tags map[string]string `name:"tag" desc:"tag in key=value form. The flag may be specified multiple times" mapstructure:"tags"`
}
```
But IIRC our viper setup doesn't play well with nested structs/maps?
Therefore I just inlined the config as `self-profiling-tags` at the root.
The advantage is that it works with cli flags :) eg `--self-profiling-tag=test=123`
=> feat(self-profiling): allow tags to be set

pkg/convert/profile/profile.go, pkg/convert/profile/profile_suite_test.go, pkg/convert/profile/profile_test.go
A regression was introduced recently, when the parser logic was refactored: parser callback recursively calls itself causing a stack overflow.
=> fix: stack overflow in parser callback when using exported-metrics functionality

pkg/config/config.go, pkg/server/index.go, webapp/javascript/components/ExportData.spec.tsx, webapp/javascript/components/ExportData.tsx, webapp/javascript/pages/ContinuousComparisonView.tsx, webapp/javascript/pages/ContinuousDiffView.tsx, webapp/javascript/pages/ContinuousSingleView.tsx, webapp/javascript/util/features.ts
Closes https://github.com/pyroscope-io/pyroscope/issues/1186 and https://github.com/pyroscope-io/pyroscope/issues/1119
I kept our standard of using `--disable/--no` for backend flags, and in the frontend to use `enable`.
There's some repetition in the `<FlamegraphRenderer>` (having to pass the same flags multiple times), but it gives us flexibility to change as we want. At some point when we make all the continuous pages have feature parity (eg export to pprof doesn't work with diff) we may clean this up.
=> feat(frontend): support disabling exporting to flamegraph.com

pkg/server/render_diff.go, webapp/javascript/components/ExportData.tsx, webapp/javascript/pages/ContinuousDiffView.tsx, webapp/javascript/util/formatDate.ts
examples:
diff_pyroscope.server.inuse_objects_last_3_hours
diff_pyroscope.server.inuse_objects_last_12_hours
diff_pyroscope.server.inuse_objects_2022-06-30_0209-to-2022-06-30_1034
diff_pyroscope.server.mutex_duration_last_3_hours
diff_pyroscope.server.mutex_duration_2022-06-30_1014-to-2022-06-30_1120
if we leave spaces and capitalized L
=> fix: default name when exporting diff

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
This was raised by @kolesnikovae  
We introduced a bug in https://github.com/pyroscope-io/pyroscope/pull/1184
Basically when flamegraphs change, we may not always be able to calculate the bar contents, since the flamegraphs may have different sizes.
=> fix(frontend): don't crash when flamegraph changes

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
Closes https://github.com/pyroscope-io/pyroscope/issues/1192
Changed the naive `numTicks` for a deep comparison. Although JSON serialization is slow, which is a not big deal (since our flamegraphs are small), but they could be in the future, hence why I left a comment as a hint.
=> fix(flamegraph): do a deep comparison for whether the flamegraph is the same

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/murmur3.ts
I don't know how this happened but we introduced this bug at some point. I changed it to proper math. E.g see code [here](https://github.com/jsdelfino/murmurhash-32/blob/master/murmurhash3_gc.js#L44-L47)
=> fix: improved nodes coloring by fixing murmur math

.github/workflows/tests-go.yml
=> ci: update to go 1.18 in tests

webapp/javascript/ui/Button.module.scss, webapp/javascript/ui/Select.module.scss, webapp/sass/variables.css
When using the flamegraph component in light mode as we intend to for #1219 the colors are a little weird expecially for the buttons. This fixes them _somewhat_. Still not a huge fan of the green for the selected button, but I think its slightly better than it was before.. on light mode I'm thinking of replacing the green with blue for the selected item
Before:
After:
=> chore: update light-mode colors for flamegraph component

packages/pyroscope-flamegraph/package.json
Before this PR, the flamegraph was shipping with js files. We instead only want to ship a bundled version + types (with souremap).
=> build(flamegraph): only build types

webapp/javascript/components/Footer.spec.tsx, webapp/javascript/components/Footer.tsx, webapp/javascript/standalone.module.scss, webapp/javascript/standalone.tsx, webapp/javascript/util/buildInfo.ts
Now the frontend checks if latest version is indeed NEWER (ie semantic version check).
Instead of pulling a library or writing a more robust parser, I decided to just support our specific case (exact matches), since we don't do anything fancy (`>^~`).
Also adds tests and make standalone footer be the same as the webapp's footer.
Hopefully closes https://github.com/pyroscope-io/pyroscope/issues/835 and https://github.com/pyroscope-io/pyroscope/issues/494
=> fix(frontend): latest version do semantic checks

cypress/fixtures/cart-service-dotnet-cpu.json, cypress/fixtures/hotrod-python-driver-cpu.json, cypress/fixtures/hotrod-ruby-driver-cpu.json, cypress/fixtures/pyroscope.server.alloc_objects.json, cypress/fixtures/pyroscope.server.alloc_space.json, cypress/fixtures/pyroscope.server.cpu.json, cypress/fixtures/pyroscope.server.inuse_objects.json, cypress/fixtures/pyroscope.server.inuse_space.json, cypress/fixtures/render.json, cypress/fixtures/render2.json, cypress/fixtures/shipping-service-go-cpu.json, cypress/fixtures/simple-dotnet-app-cpu.json, cypress/fixtures/simple-golang-app-cpu-diff.json, cypress/fixtures/simple-golang-app-cpu.json, cypress/fixtures/simple-golang-app-cpu2.json, cypress/fixtures/simple-java-app-cpu.json, cypress/fixtures/simple-php-app-cpu.json, cypress/fixtures/simple-python-app-cpu.json, cypress/fixtures/simple-ruby-app-cpu.json, pkg/server/render.go, pkg/storage/storage_get.go, pkg/structs/flamebearer/flamebearer.go, webapp/javascript/services/render.ts
To test:
```shell
curl -X POST --data 'foo;bar;baz 100' 'http://localhost:4040/ingest?name=0-app%7Bfoo%3D%22bar%22%7D'
curl -X POST --data 'foo;bar;baz 100' 'http://localhost:4040/ingest?name=0-app%7Bfoo%3D%22baz%22%7D'
curl 'http://localhost:4040/render?from=now-1m&until=now&query=0-app&groupBy=foo&format=json' | jq .groups
```
=> feat: adds support for group-by queries on the backend

packages/pyroscope-flamegraph/package.json, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Flamegraph.ts, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Flamegraph_render.ts, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Header.tsx, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.tsx, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/utils.ts, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx, packages/pyroscope-flamegraph/src/FlameGraph/decode.ts, packages/pyroscope-flamegraph/src/ProfilerTable.tsx, packages/pyroscope-flamegraph/src/convert/convert.ts, packages/pyroscope-flamegraph/src/format/format.ts, packages/pyroscope-models/package.json, webapp/javascript/components/ExportData.spec.tsx, webapp/javascript/components/ExportData.tsx, webapp/javascript/components/exportToFlamegraphDotCom.hook.ts, webapp/javascript/index.jsx, webapp/javascript/models/flamebearer.ts, webapp/javascript/pages/AdhocComparison.tsx, webapp/javascript/pages/AdhocDiff.tsx, webapp/javascript/pages/AdhocSingle.tsx, webapp/javascript/pages/ContinuousComparisonView.tsx, webapp/javascript/pages/ContinuousDiffView.tsx, webapp/javascript/pages/ContinuousSingleView.tsx, webapp/javascript/redux/reducers/continuous.ts, webapp/javascript/services/TestData.ts, webapp/javascript/services/render.ts, webapp/javascript/services/share.ts, webapp/javascript/standalone.tsx, webapp/javascript/util/testData.ts
Ship `FlamegraphRenderer.tsx` directly (without bundling/minifying). For clarification, we still ship the flamegraph bundled for the people that want it.
This allows people to use the unminified version if they want, which allows for better tree shaking.
For us, it allows not having to build the flamegraph separately while running locally, which is faster and doesn't contain race conditions (https://github.com/pyroscope-io/pyroscope/pull/1161).
Some other arguments against bundling/minification https://www.briefs.fm/3-minutes-with-kent/221
Did the same thing for `@pyroscope/models`.
=> chore(flamegraph): ship raw files

.github/lint-js.yml, .github/workflows/lint-js.yml, .github/workflows/tests-js.yml, package.json, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.spec.tsx, scripts/jest-snapshots/run-snapshots.sh
* Set jest `max-workers` to be the number of cores (as per https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server)
* Split js lint/tests into different actions (since tests don't require building the dependencies)
For comparison
Before:
Now:
Thought slowest tests are still the cypress.
=> ci: improve js tests/lint speed

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.module.scss, webapp/sass/variables.css
Updated light mode colors for tooltip... Created an issue  (#1274) for biggest remaining "light mode" color change needed before merging (mostly the non-css stuff) 
Before:
After:
=> chore: Update light mode for tooltip

.github/workflows/cypress-panel.yml, package.json, packages/pyroscope-panel-plugin/cypress.json
For panel plugin cypress tests:
* Disable cypress videos (to make it faster)
* Remove wrong `make server` call, since in this case we don't run the server
* Setup `cypress-image-snapshot/reporter`, which should create a diff file when screenshot does not match.
* Make the action run `cy:panel:ci`, just to keep it consistent and somewhat reproducible when running locally.
=> ci(panel): improvements

.github/workflows/lint-js.yml, .github/workflows/size-limit.yml, .github/workflows/tests-js.yml, scripts/jest-snapshots/run-snapshots.sh
As per the docs
```
Don’t generate a yarn.lock lockfile and fail if an update is needed.
If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass --frozen-lockfile flag.
```
=> ci: run yarn --frozen-lockfile

packages/pyroscope-models/package.json
Long story short, since pyroscope webapp uses `@pyroscope/models/src`, so if you use `@pyroscope/webapp` you also need access to `@pyroscope/models/src`, therefore src needs to be shipped.
=> chore: @pyroscope/models ship ts files too

pkg/cli/server.go, pkg/config/config.go, pkg/ingestion/noop.go
One of our users reported that even after [disabling local writes](https://pyroscope.io/docs/remote-write/#disabling-local-writes), data was still being written to the database.
Turns out it's purely a configuration issue.
After that, Parallelizer was panicing due to ingester being null, instead of second guessing myself with if `ingester != null` checks, I used a `NoopIngester`.
=> fix: don't write to local db when `disable-local-writes` is set

.github/workflows/publish-lib-to-npm.yml, package.json, scripts/ci-skip-husky.js
Apparently there's a race condition in `yarn install` when you use a github repo as a dependency (this repo) AND that repo contains a `prepare` script. The race condition makes it pull some dependencies concurrently, corrupting them.  https://github.com/yarnpkg/yarn/issues/7212
Just removed the `prepare` script and moved to `bootstrap`, which people have to run manually anyway.
=> chore: remove `prepare` script

pkg/server/merge.go, pkg/storage/exemplars.go, pkg/storage/exemplars_test.go, pkg/storage/segment/key.go, pkg/storage/storage_merge_exemplars.go, pkg/storage/storage_put.go
If an exemplar is written separately from its baseline profile, we don't have access to its metadata. The fix introduces a stub segment for the whole application, which would be present regardless of whether we have a regular baseline profile for the exemplar or not.
In addition, now exemplar timestamps are honoured on querying. For backward compatibility a query w/o time range selects exemplars regardless of its timestamps.
=> fix: exemplars metadata and timestamps

webapp/javascript/services/base.spec.ts, webapp/javascript/services/base.ts
Since people may display the error message to users. Let's make it more friendly:
Becomes
```
Error(s) were found: "empty organization name"
```
=> chore(frontend): make error message more user friendly

README.md
- Re-ordered list of Pyroscope benefits so that both the points mentioning tags are beside eachother
- ". for example here" -> ". For example, here"
- Minor punctuation corrections
=> docs: minor reorganizing and grammar changes in README.md

webapp/javascript/components/AppSelector/SelectButton.tsx
Adds a `title` parameter to the `app selector button` component. This is so that at least it's >possible< to read the entire app name.
https://user-images.githubusercontent.com/6951209/180785398-be5ffd70-1334-4d4e-a3f5-f56951ad1838.mp4
Related https://github.com/pyroscope-io/pyroscope/issues/1265
=> chore(frontend): add title on hover for select app button

pkg/storage/segment/serialization.go
Recently introduced stub segment for exemplars (a segment for the whole app) may fail to deserialize since it may not have nodes.
=> fix: segment stub deserialization

pkg/adhoc/server/convert.go
As implemented in https://github.com/pyroscope-io/pyroscope/pull/1300
Only a certain list of spyNames are allowed (https://github.com/pyroscope-io/pyroscope/pull/1300/files#diff-4470a525fa07e3755143aea910fec818e7ad9dc18fd97f5f60203a7f43b73e79R3-R19)
In adhoc we were by default in pprof/collapsed to use the appName as the spyName.
With this PR we use `unknown` instead.
=> chore(adhoc): if not spyName is available, use 'unknown'

packages/pyroscope-flamegraph/src/Tooltip/Tooltip.tsx
Don't know if this is a case that can ever happen in the wild, but nevertheless it's better to not show anything instead of `TBD
https://user-images.githubusercontent.com/6951209/182663231-197c3f9a-86d5-4c66-99b3-301eade7a153.mp4
`
=> chore(flamegraph): don't show <TBD> for unknown case in tooltip footer

scripts/obfuscate.js
Sometimes we need to post flamegraph json files (for reproducibility, example https://github.com/pyroscope-io/pyroscope/pull/1341#issuecomment-1204048760), but we don't want to expose function names etc. This simple scripts just replaces these somewhat confidential data (app name and node names) for random strings.
=> chore: add a script to obfuscate json files

packages/pyroscope-models/src/spyName.spec.ts, packages/pyroscope-models/src/spyName.ts
When a non officially supported `spyName` is passed, default to `unknown`.
=> chore(models): default spyName to 'unknown' when not detected

packages/pyroscope-flamegraph/package.json, yarn.lock
Edited by Eduardo:
- remove true-myth frmo dependencies, since we publish the flamegraph bundled, there should be no need to pull that dependency
- ship with typings downleved to typescript 3.4 (original PR https://github.com/pyroscope-io/pyroscope/pull/1347)
=> chore(flamegraph): reduce barrier for usage [final version]

packages/pyroscope-models/src/profile.ts
I do see empty names in our profiles every once in a while. While those might be caused by bugs, I could also see people uploading stacktraces with empty names, and in that case that wouldn't be a bug and we should probably still render them.
Therefore I'm relaxing this rule. @eh-am what do you think?
=> chore: allows empty names in names array

pkg/adhoc/cli.go, pkg/adhoc/server/server.go, pkg/adhoc/writer.go, pkg/adhoc/writer/datadir_writer.go, pkg/adhoc/writer/external_writer.go, pkg/adhoc/writer/writer.go, webapp/javascript/redux/reducers/adhoc.ts
Closes https://github.com/pyroscope-io/pyroscope/issues/1317
https://user-images.githubusercontent.com/6951209/182932596-653c8400-74b4-415f-be9e-5dbcedb1c301.mp4
The frontend can be simplified/improved:
* have a single path of loading a profile (from file list)
* auto select profile after uploading
=> feat(webapp): persist uploaded data via adhoc ui

pkg/cli/flags_test.go, pkg/cli/server.go, pkg/config/config.go, pkg/health/disk_pressure.go, pkg/health/disk_pressure_test.go, pkg/util/disk/disk.go, pkg/util/disk/usage_test.go, pkg/util/disk/usage_unix.go, pkg/util/disk/usage_windows.go
Currently, we have a hardcoded threshold 512MB for the low free disk space alert. The change makes this value configurable (`storage-disk-threshold` option), and instead of an absolute value it takes a percent of available disk space (disk size), which defaults to 5%.
Essentially, the value also serves as a space quota size, that is reserved and not used by storage: once server hits the threshold, storage writes start being dropped. This should allow us to prevent cases when pyroscope server can't start because of BadgerDB failing to acquire the lock file due to the lack of free space.
Although it is not entirely clear how we get into this situation with a hardcoded value, my best guess is that this might be related to how BadgerDB deletes data: effectively, garbage collection rewrites …
=> feat: configurable disk alert threshold

packages/pyroscope-flamegraph/src/format/format.spec.ts, packages/pyroscope-flamegraph/src/format/format.ts
Makes table value say 0 when it is actually 0 instead of `"<0.01 seconds"`
=> fix: make table value say 0 when it is 0

pkg/adhoc/server/model.go
Just noticed @pavelpashkovsky needs this for https://github.com/pyroscope-io/pyroscope/pull/1392. This is just the backend part.
Basically allow passing custom spyName/units when uploading adhoc files. It **does not work** with diff, since diff takes 2 profile json files (which we assume are already in the correct shape).
RE implementation:
Added to the model's `Convert` so that we can reuse same functionality in other places transparently.
Modeled fields after @dogfrogfog's implementation in flamegraph.com
=> feat(adhoc): support passing custom spyName/unit

webapp/javascript/util/formatDate.spec.ts, webapp/javascript/util/formatDate.ts
Original issue:
When selecting a time range and hitting the back button
https://user-images.githubusercontent.com/6951209/185229101-47444c01-7644-460e-b194-404750e681c8.mp4
This happens due to `redux-sync`, which syncs the URL with the redux state both ways.
The url changes all at once (both `from` and `until` parameters), while in redux only a single action is dispatched at a time:
Which leads to a somewhat inconsistent state, where we are mixing relative values (like `from`) with absolute values (unix `timestamp`)
Which then generates a wrong date, crashing `date-fns` (https://github.com/pyroscope-io/pyroscope/blob/e2128b9e7fdde0fc823985c098b1b86ddcf710f9/webapp/javascript/util/formatDate.ts#L56-L58)
So my lazy solution is to just check whether it's a valid date, and if not, to just …
=> fix(webapp): fixes crash when hitting back button

pkg/adhoc/server/model.go, pkg/adhoc/server/server_test.go
I introduced this test failure in https://github.com/pyroscope-io/pyroscope/pull/1417
Basically the implementation adds a wrapper around `model.Converter` that returns a function that does the conversion + overrides any fields. 
Although it's possible to just let users to override any fields they want, I preferred to implement this as part of converter, so that we can implement more intelligent rules. Eg: `goroutines` is only valid for when `spyName` is go.
However adding that wrapper breaks the tests, since they are inspecting the actual function addresses. 
To not have to refactor all this, I decided to simply test the wrapper function `convert` (as opposed to `Convert`).
Honestly not very happy with it, but it is what it is.
=> chore(adhoc): fix converter test

webapp/javascript/ui/Table.spec.tsx
- fix Test ui component tests warnings
- ensure that test render and real one are as close to each other as possible
- wrap hook export function call in `act`
- to make your test run closer to how React works in the browser, every component update function call should be wrapped in `act` (https://reactjs.org/docs/test-utils.html#act)
-
=> chore: Table ui component tests warn

packages/pyroscope-models/src/profile.spec.ts, packages/pyroscope-models/src/profile.ts
Follow up from https://github.com/pyroscope-io/pyroscope/pull/1321
Previous to this PR we would just render nodes with empy names.
However down the road code assumes it's non empty, eg:
So to maintain the invariant and simplify all this, decided to default to `unknown` instead.
Keep in mind values on the table still don't make full sense though.
=> chore(models): default flamebearer names to 'unknown' when it's empty

scripts/webpack/webpack.common.ts, webapp/javascript/components/TimelineChart/TimelineChart.tsx, webapp/javascript/globals.tsx, webapp/javascript/index.tsx
Let's treat `jQuery` as a global dependency, ie. as if it's always present.
Before it was scopped to the `TimelineChart.tsx` component, but from an architecture POV this is not the only place jQuery is used. And repeating the same import multiple times is cumbersome.
=> chore(webapp): import jquery globally

packages/pyroscope-flamegraph/src/Tooltip/FlamegraphTooltip.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1398
- now tooltip works correct with color blind palette 
-
https://user-images.githubusercontent.com/23450818/186697652-d2e3e608-9bed-464c-8743-b09ad1a3f0ea.mov
=> fix(flamegraph): fixed tooltip display with color blind palette

packages/pyroscope-flamegraph/src/format/format.spec.ts, packages/pyroscope-flamegraph/src/format/format.ts
- https://github.com/pyroscope-io/pyroscope/issues/1393
- added ms and μs support for trace_samples formatter 
- added tests for μs, ms, hour, day, month and year 
-
=> feat(flamegraph): added sub-second units support for trace visualization

packages/pyroscope-flamegraph/src/Toolbar.module.css, webapp/sass/common.scss
Fix incorrect colors for UI elements on Flamegraph for light mode.
- imported `sanitize.css` re-writes assigned styles
=> fix(flamegraph): table, buttons colors for light mode

webapp/javascript/pages/tagExplorer/components/TagsSelector.module.scss, webapp/javascript/pages/tagExplorer/components/TagsSelector.spec.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1445
- added comparison tag selector scroll
- added comparison tag selector text-overflow
- added tests for 'selected' state and dropdown close 
-
https://user-images.githubusercontent.com/23450818/187423387-edfb1704-4550-473d-9a97-80bfb586a5ef.mov
=> Сomparison dropdown styles

packages/pyroscope-flamegraph/README.md, packages/pyroscope-flamegraph/src/Tooltip/Tooltip.module.scss
Same as https://github.com/pyroscope-io/pyroscope/pull/1463
added to the wrong element (╯°□°）╯︵ ┻━┻
=> fix(flamegraph): table width

webapp/javascript/components/TimelineChart/TooltipWrapper/styles.module.scss
Initially raised https://github.com/pyroscope-io/pyroscope/pull/1469#discussion_r964867470
We always render a tooltip, even if there's no body:
It's a bit tricky to solve this, since it would require the parent to know whether the children is empty. Instead of manually rendering I decided to just use CSS to hide the tooltip if it's empty (ie its children is null).
=> fix(webapp): hide timeline tooltip if there's no data

webapp/javascript/components/TimelineChart/Tooltip.plugin.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1467
- Hide Explore tooltip if there is no profiling data
- I hid the tooltip, but we still have this red line which follows the cursor. If you want to hide it as well I have to extract `react-flot/flot/jquery.flot.crosshair.min` into the project and make up it there. `{hoverable: boolean}` doesn't influence on this red line.
=> fix(webapp): Don't show tooltip when there's no data

webapp/javascript/redux/reducers/continuous.ts, webapp/javascript/services/render.ts
- https://github.com/pyroscope-io/pyroscope/issues/1464
- filter empty series just after they were received from backend and before they get to the redux store
-
=> chore(webapp): Don't show empty series in timeline or table

webapp/javascript/ui/Box.module.scss
- remove `overflow:hidden` for CollapseBox content
- removed oveflow:hidden
=> fix(webapp): hotfix CollapseBox overflow

pkg/api/annotation.go, pkg/api/annotation_test.go, pkg/api/testdata/annotation/create_request_no_timestamp.json
Closes https://github.com/pyroscope-io/pyroscope/issues/1503
=> fix(backend): don't set an annotation timestamp in controller

pkg/adhoc/server/convert.go, pkg/adhoc/server/model.go, pkg/adhoc/server/server_test.go, pkg/convert/perf/script.go, pkg/convert/perf/script_test.go
The goal is to upload perf data to pyroscope/flamegraph:
- First idea was to try to parse perf data at server side with [perf_data_converter](https://github.com/google/perf_data_converter). But the perf and converted pprof has no symbols so we can't do it on serverside
- Second idea was to parse `perf script` output (what this pr does) like `perf script | curl  --data-binary @- http://flamegraph.com`, the problem with it is that it may be huge (like 65M for 16 cores profiling for 10 seconds).
- Third idea is to use embeded stackcollapse script `perf script report stackcollapse | curl --data-binary @- flamegraph.com`  . stackcollapse is not huge so it is better. We might decline this PR and go with third solution. Only flamegraph.com changes are required, to allow to post profiles to `/`. …
=> feat: add 'perf script' format upload

webapp/javascript/components/TimelineChart/Selection.plugin.ts, webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx, webapp/javascript/pages/ContinuousComparisonView.tsx, webapp/javascript/pages/ContinuousDiffView.tsx
Closes https://github.com/pyroscope-io/pyroscope/issues/1497
Before:
After:
tl;dr
Problem is that we mix `markings` with `selection`, as pointed by this commented https://github.com/pyroscope-io/pyroscope/blob/d8e0d21bde92d7c5f6a07c9cb728607d1c2cd2c0/webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx#L205-L208
But anyway, the `selection` plugin ALWAYS 
https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/TimelineChart/Selection.plugin.ts#L425 draws a selection, using markings https://github.com/pyroscope-io/pyroscope/blob/main/webapp/javascript/components/TimelineChart/Selection.plugin.ts#L429 
But in the annotations case, we draw a marking that's not an annotation!
This will be solved after we create our own plugin …
=> fix(webapp): weird marking when adding annotation

pkg/model/annotation.go, pkg/service/annotation.go, pkg/service/annotation_test.go, pkg/sqlstore/migrations/migrations.go
Closes https://github.com/pyroscope-io/pyroscope/issues/1509
Plus refactors the `upsert` as per @kolesnikovae's here https://github.com/pyroscope-io/pyroscope/pull/1508#discussion_r972034413
Here's the sql schema (generated with `.schema annotations`):
```
CREATE TABLE `annotations` (`id` integer,`app_name` text NOT NULL DEFAULT null,`timestamp` datetime,`content` text NOT NULL DEFAULT null,`created_at` datetime,`updated_at` datetime,PRIMARY KEY (`id`));
CREATE UNIQUE INDEX `idx_appname_timestamp` ON `annotations`(`app_name`,`timestamp`);
```
---
offtopic/self documenting: had to turn on sql log to make sense out of what the orm is doing
```diff
diff --git a/pkg/sqlstore/sqlstore.go b/pkg/sqlstore/sqlstore.go
index 642ad7ca..06c7e429 100644
--- a/pkg/sqlstore/sqlstore.go
+++ …
```
=> chore: make pair (timestamp, appName) unique

webapp/javascript/components/TimelineChart/Annotation.spec.tsx, webapp/javascript/components/TimelineChart/Annotation.tsx, webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx, webapp/javascript/util/formatDate.ts
Closes https://github.com/pyroscope-io/pyroscope/issues/1506
(UTC)
(BROWSER, mine is currently utc - 3)
Ideally we would handle this better in https://github.com/pyroscope-io/pyroscope/issues/1521
=> fix(webapp): format annotation using timezone

packages/pyroscope-flamegraph/src/__snapshots__/Toolbar.spec.tsx.snap, stories/Dialog.stories.tsx, webapp/__tests__/__snapshots__/RefreshButton.spec.js.snap, webapp/javascript/ui/Button.module.scss, webapp/javascript/ui/Button.tsx, webapp/javascript/ui/Dialog/Dialog.module.css, webapp/javascript/ui/Dialog/Dialog.tsx, webapp/javascript/ui/Dialog/index.ts
Add a generic dialog, based off https://mui.com/base/api/modal-unstyled/
* breaks down the api into 4 elements: `<Dialog><DialogBody><DialogHeader><DialogFooter>`
* supports scrolling `<DialogBody>` (see video below)
* automatically set a backdrop
Related https://github.com/pyroscope-io/pyroscope/issues/1542
After this we should refactor the multiple dialogs we have to use this one.
=> chore: add a dialog modal

stories/Dialog.stories.tsx, webapp/javascript/ui/Button.tsx, webapp/javascript/ui/Dialog/Dialog.module.css, webapp/javascript/ui/Dialog/Dialog.tsx, webapp/sass/reset.scss
Follow up from https://github.com/pyroscope-io/pyroscope/pull/1544
* Force the `Dialog` to have a `aria-labelledby`, which should be the header id.
* Remove `sanitize.css`'s `outline` styling to use the browser's. This is due to `sanitize`'s being too difficult to see, specially next to buttons
* allow buttons to have an `autoFocus` attribute, althought with a disclaimer that it should ONLY be used with modals.
It works, although there's no visual indicator that it is focused. I haven't investigated much further.
Also
* reset Heading's (`h1, h2, h3, h4`) margins in `DialogHeader`, this is just to make it easier for users (not having to redefine them every time)
* allow `Dialog{Footer, Body, Header}` to pass custom `className`
Some references for anybody interested:
* …
=> chore(webapp): improve acessibility

pkg/server/controller.go, webapp/javascript/components/Heatmap/index.tsx, webapp/javascript/components/Heatmap/useHeatmapSelection.hook.spec.tsx, webapp/javascript/components/Heatmap/useHeatmapSelection.hook.ts, webapp/javascript/components/Heatmap/utils.ts, webapp/javascript/services/exemplarsTestData.ts
- 
- fix heatmap test warning
- fix 404 error after /exemplars/single, /exemplars/merge pages reload
- add ability to start selection from already drawn selected area 
https://user-images.githubusercontent.com/47758224/192308231-77bf299e-2b55-4e79-8fc5-37a612a04fd3.mov
-
=> fix: heatmap small fixes

webapp/javascript/ui/Button.module.scss
existing buttons with variation (secondary/primary) have `border: none`, which when paired with normal buttons show this lack of border, making them having different sizes:
This PR just sets a border with background color, so that's counted as the button size but not really visible.
Before:
After:
=> chore: set a transparent border on buttons

webapp/javascript/components/Heatmap/Heatmap.module.scss, webapp/javascript/components/Heatmap/index.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1556
- add "Count" title above heatmap scale
-
=> feat: add "Count" title above heatmap scale

webapp/javascript/components/Heatmap/index.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1555
- change background-color of selection div to orange
- add border to selected area
- add `mix-blend-mode: 'overlay'` property
https://user-images.githubusercontent.com/47758224/193031586-3f79ecce-32b5-47b9-959d-e06aa5158d9c.mov
-
=> feat: change color of the selected area of the heatmap

webapp/javascript/pages/tagExplorer/components/TagsSelector.tsx, webapp/javascript/ui/Modals/ModalWithToggle.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1518
- close modal when clicking outside 
https://user-images.githubusercontent.com/47758224/193231881-bed4cc05-83ab-41ae-bce2-86a0a5f7bdb7.mov
-
=> fix: tag explorer modal should close when another one is clicked

webapp/javascript/components/Heatmap/HeatmapTooltip.module.scss, webapp/javascript/components/Heatmap/HeatmapTooltip.spec.tsx, webapp/javascript/components/Heatmap/HeatmapTooltip.tsx, webapp/javascript/components/Heatmap/index.tsx, webapp/javascript/components/Heatmap/useHeatmapSelection.hook.spec.tsx, webapp/javascript/components/Heatmap/utils.ts, webapp/javascript/components/TimelineChart/TooltipWrapper/index.tsx, webapp/javascript/components/TimelineChart/TooltipWrapper/styles.module.scss
- https://github.com/pyroscope-io/pyroscope/issues/1577
- add buckets duration and buckets count to heatmap tooltip
https://user-images.githubusercontent.com/47758224/193300399-a9bdb3cd-5de1-4658-8f2b-2a1d27e7b1d8.mov
-
=> feat: add count and duration to heatmap tooltip

webapp/javascript/pages/TagExplorerView.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1365
- add sorting to explore view table
https://user-images.githubusercontent.com/47758224/193820833-c68c90a4-2537-44b9-9932-78d319f01104.mov
-
=> feat: add sorting to explore view table

.github/workflows/publish-lib-to-npm.yml
Previously when PRs were created by a non member of the pyroscope org, this `checkout` step would fail, due to the lack of access to the secrets:
This PR basically skips the entire pipeline if that secret is not present.
=> build: skip publish npm if user not part of pyroscope org

pkg/convert/jfr/parser.go, pkg/convert/jfr/parser_jvm_generated_class_merge_test.go
`./tmp/libamazonCorrettoCryptoProvider5bc2d45365367baa.so (deleted)`
update jfr symbol merge regexps for 
- ` (deleted)` suffix
- `/tmp` prefix
- `./tmp` prefix
=> fix: update regexes for deleted so names

webapp/javascript/components/FileList.module.scss, webapp/javascript/components/FileList.tsx, webapp/javascript/models/adhoc.ts, webapp/javascript/ui/Table.module.scss
- https://github.com/pyroscope-io/pyroscope/issues/1581
- make adhoc table fit width
- change adhoc table time format to _MMM d, yyyy_ at _H:mm_ 
- add "tooltip" (`title` span attribute) to Filename cells
- ~~add suffix column, the `suffix` value should be part of `/api/adhoc/v1/profiles` reponse~~
- ~~FileNames column values are hidden when  screen width is small (thats not a problem since we are adding suffix column?)~~
=> fix: make adhoc table fit width

.air.conf, cmd/pyroscope/command/convert.go, pkg/server/render.go, pkg/storage/tree/flamebearer.go, pkg/storage/tree/minval.go, pkg/storage/tree/serialize.go, pkg/storage/tree/serialize_nodict_test.go, pkg/storage/tree/serialize_test.go, pkg/storage/tree/truncation_test.go
This PR improves tree truncation algorithm. This results in less nodes being dropped (and replaced with `other` nodes).
This also introduces ability to set `max-nodes-serialization` to `-1` which effectively disables truncation.
I ran some benchmarks with a ruby app with a very leafy flamegraph. I ingested 5000 profiles and measured storage size, wall time and cpu time for the ingestions and put together a table that represents the difference between old version, new version with defaults and new version with `max-nodes-serialization` set to -1.
  | storage size | profile time | flamegraph
-- | -- | --| --
old version | 220 MB | 47s | https://flamegraph.com/share/747cf1c2-4ab2-11ed-81e2-52cfe0251908
new version defaults | 228 MB | 52s | …
=> refactor: tree serialization improvements

webapp/javascript/components/AppSelector/AppSelector.module.scss, webapp/sass/components/daterangepicker.scss
Before:
After:
---
Implementation: values may seem arbitrary, but the intention is to create different layers (0-9, 10-99, 100-999 etc). Didn't think too much through about this so feel free to change if a better approach comes up.
=> fix(webapp): make app selector/timerange dropdowns to be above loading overlay

examples/dotnet/fast-slow/docker-compose.yml, examples/dotnet/web/docker-compose.yml, pkg/exec/cli_linux.go
`dotnetspy` currently requires setting `SYS_PTRACE` capability when running on linux. However, this check is redundant: ptrace is never called by the agent.
=> fix: disable ptrace capability check for dotnetspy

pkg/storage/segment/key.go, pkg/storage/segment/key_bech_test.go
In certain scenarios we observe surprisingly high CPU consumption and allocation rate in the key parser:
This is a quick and safe optimisation that should decrease the overall CPU time consumption by ~3-5% (GC will have to do less work):
Before:
```
BenchmarkKey_Parse-10    	  142854	      8411 ns/op	    4178 B/op	     445 allocs/op
```
After:
```
BenchmarkKey_Parse-10    	  456100	      2302 ns/op	    1475 B/op	      26 allocs/op
```
Further optimisation may replace the labels map with a slice.
=> perf: optimize segment key parser allocations

pkg/storage/db.go, pkg/storage/storage.go, pkg/storage/types.go
The aim is to close databases and flush caches in deterministic order and allow using a single BadgerDB instance.
=> fix: close databases in deterministic order

webapp/javascript/redux/reducers/continuous.ts
Closes https://github.com/pyroscope-io/pyroscope/issues/1620
The problem is stated in the issue. 
To give more context, imagine the user has some data loading (let's call it `A`), then changes the app. The `useEffect` cleanup calls the action's abort. 
https://github.com/pyroscope-io/pyroscope/blob/f9f7d4c4fde0221419783fbf3ccb39c1986f3146/webapp/javascript/pages/ContinuousSingleView.tsx#L49
Then a new dispatch is sent https://github.com/pyroscope-io/pyroscope/blob/f9f7d4c4fde0221419783fbf3ccb39c1986f3146/webapp/javascript/pages/ContinuousSingleView.tsx#L48
Naturally one would think that the cancellation happens before the new dispatch. However, since the abort is only acted in the thunk 
https://github.com/pyroscope-io/pyroscope/blob/f9f7d4c4fde0221419783fbf3ccb39c1986f3146/webapp/javascri …
=> fix(webapp): make ui consistent when request is cancelled

webapp/javascript/services/base.spec.ts, webapp/javascript/services/base.ts, webapp/javascript/services/testdata/example.html
Sometimes server returns HTML, normally when a URL is malformed, which produces an error message such as
Now we try to handle this case and just return a generic message instead
=> chore(webapp): identify server returned HTML

pkg/agent/ebpfspy/symtab/gosym_test.go
since /proc filesystem is only available on linux
https://man7.org/linux/man-pages/man5/proc.5.html
Otherwise it fails with (on a mac, assume the same happens in windows)
```
--- FAIL: TestGoSymSelfTest (0.00s)                                                                                                              
gosym_test.go:15: failed to create symtab open /proc/self/exe: no such file or directory
FAIL
```
=> chore: skip ebpfspy test outside linux

webapp/javascript/components/Heatmap/Heatmap.module.scss, webapp/javascript/components/Heatmap/utils.ts
- https://github.com/pyroscope-io/pyroscope/issues/1634
- fix heatmap y-axis tick value align
demo link: https://pr-1644.pyroscope.io/exemplars/single?query=rideshare-app-golang.cpu%7B%7D&from=now-3h
-
=> fix: exemplars page shows weird y-axis numbers

stories/Notifications.stories.tsx, webapp/javascript/ui/Notifications.tsx
Support a `warning` level:
Also support an arbitrary JSX element to be passed as message, as opposed to only strings:
=> feat(webapp): [notifications] support 'warning' status and arbitrary jsx element

pkg/convert/jfr/profile.go, pkg/convert/pprof/profile.go
Currently, when ingesting a JFR or pprof profile exceeding 32MB, pyroscope server uses /tmp file system. The problem is that after parsing, files remain that are never deleted automatically (by the pyroscope server).
May fix https://github.com/pyroscope-io/pyroscope/issues/1665
=> fix: remove tmp multipart files

.github/workflows/cypress-tests.yml, cypress/integration/auth/cypress.json, cypress/integration/auth/oauth.ts, pkg/server/controller.go, scripts/oauth-mock/oauth-mock.js, scripts/oauth-mock/pyroscope-config-base-url.yml, webapp/README.md
It was raised in our [slack channel](https://pyroscope.slack.com/archives/C01FJRYENPQ/p1666858222507879) that baseUrl + oauth did not work properly.
This path is only reached when both auth and baseUrl are enabled.
The way it was implemented, certain redirects would be fully encoded, including the path, producing URLs such as:
```
/pyroscope/auth/gitlab/redirect%3Fcode=d79c3ebf-4367-4c64-862e-c11cc89c58fa&scope=read_api&state=5db3bd88832f9a2900c71ed14d58957d&tls=false
```
Where `%3F` should be the `?` which represents the start of the query string.
With the change, we simply concatenate as strings, not escaping anything.
> **Warning**
Notice that a better solution should involve using more clear data structures, such as `net/url.URL`, which can hold host/path/query string separately.
* …
=> fix: preserve query param when redirecting when baseUrl is set

webapp/javascript/pages/ContinuousComparisonView.tsx, webapp/javascript/pages/ContinuousDiffView.tsx
Closes https://github.com/pyroscope-io/pyroscope/issues/1675
Don't make loading spinners granular (timelines/left/right side). Instead, if any of them is loading, all of them are loading.
=> chore(webapp): don't make loading granular

webapp/javascript/redux/reducers/continuous.ts, webapp/javascript/redux/reducers/continuous/annotations.thunks.ts, webapp/javascript/redux/reducers/continuous/comparisonView.thunks.ts, webapp/javascript/redux/reducers/continuous/diffView.thunks.ts, webapp/javascript/redux/reducers/continuous/selectors.ts, webapp/javascript/redux/reducers/continuous/singleView.thunks.ts, webapp/javascript/redux/reducers/continuous/state.ts, webapp/javascript/redux/reducers/continuous/tagExplorer.thunks.ts, webapp/javascript/redux/reducers/continuous/tags.thunks.ts, webapp/javascript/redux/reducers/continuous/timelines.thunks.ts
The continuous reducer file was too big (>1k lines), so I moved the thunks to their own files, also moved selectors to a single `selectors.ts` file.
=> refactor(webapp): cleanup store

packages/pyroscope-flamegraph/src/Toolbar.tsx
- 
- disable sandwich view for diff page 
demo link: https://pr-1693.pyroscope.io/?query=rideshare-app-golang.alloc_objects%7B%7D
https://user-images.githubusercontent.com/47758224/200874752-91d416e3-eac9-4f8c-8bdb-b33dc22d4890.mov
-
=> feat: disable sandwich view for diff page

webapp/javascript/components/Heatmap/Heatmap.module.scss
- https://github.com/pyroscope-io/pyroscope/issues/1667
- fix y-axis values
demo link:  https://pr-1694.pyroscope.io/exemplars/single?query=rideshare-app-golang.cpu%7B%7D&from=now-30d
1st ss is before fix, 2nd is after fix
-
=> fix: heatmap y-axis value with "<"

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1699
- set `isFlamegraphDirty` when clicking on table 
- reset table selected item when clicking _reset_ button 
demo link:  https://pr-1703.pyroscope.io/?query=
https://user-images.githubusercontent.com/47758224/201331118-eabc3998-2232-4642-8a04-945a9933aebb.mov
- nope
=> feat: enable "reset view" button when table item is highlighted

packages/pyroscope-flamegraph/src/Toolbar.module.scss, webapp/sass/variables.css
Light mode icon colors were a little too harsh:
before:
after:
modeled after colors from google sheets
also changed light mode prompt color:
also made separator match border colors
=> chore: update icon colors

pkg/agent/ebpfspy/sd/k8s.go, pkg/agent/ebpfspy/sd/k8s_test.go
=> fix(ebpf): update regexps for sd cgroupv1 matching

packages/pyroscope-flamegraph/src/ProfilerTable.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1708
- change text
- i would remove search input outline
=> fix: table should not say unsupported when search filter doesn't find anything

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx, packages/pyroscope-flamegraph/src/Toolbar.tsx, packages/pyroscope-flamegraph/src/__snapshots__/Toolbar.spec.tsx.snap
- https://github.com/pyroscope-io/pyroscope/issues/1710
- DEMO: https://pr-1728.pyroscope.io/
- display only flamegraph + **NO** ExportData
- display only flamegraph + ExportData
- "display only" disabled + ExportData
=> refactor(flamegraph): Hide ExportData and ChangeView dividers when it necessary

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx, packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1727
- fix ability to reset flamegraph from ContextMenu components
https://user-images.githubusercontent.com/47758224/202425277-b60efba4-ee6a-4501-aa8d-8bfc72f5a63e.mov
-
=> fix: make reset view available in sandwich mode context menu

webapp/javascript/pages/tagExplorer/components/TagsSelector.module.scss, webapp/javascript/pages/tagExplorer/components/TagsSelector.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1517
- remove fixed width
=> feat: make tag explorer modal adapt to content

packages/pyroscope-flamegraph/src/convert/subtract.ts
There were 2 somewhat related issues:
* `self` was not included when calculating `total` for each node
* `numTicks` had a flaw where it was possible for it to be lower when you subtract nodes that don't exist in the destination tree (minuend)
=> chore: fixes subtract function

webapp/javascript/redux/reducers/continuous/selectors.ts
- https://github.com/pyroscope-io/pyroscope/issues/1376
- DEMO: https://pr-1748.pyroscope.io/
https://user-images.githubusercontent.com/7372044/203017090-4fc5eee3-df03-46ed-a3b4-198110848f7f.mp4
=> fix(webapp): Tag Explorer loading spinner consistent with other pages

webapp/javascript/ui/Menu.tsx
When building an application that reuses the webapp code, I got;
```
export 'ClickEvent' (reexported as 'ClickEvent') was not found in '@szhsin/react-menu' (possible exports: ControlledMenu, FocusableItem, Menu, MenuButton, MenuDivider, MenuGroup, MenuHeader, MenuItem, MenuRadioGroup, SubMenu, useMenuState)
```
Don't know the exact cause, only that `import type` solves the issue.
=> chore(webapp): fix type

packages/pyroscope-flamegraph/src/ProfilerTable.tsx, webapp/sass/common.scss
- https://github.com/pyroscope-io/pyroscope/issues/1764
- increase width of profile table columns
https://user-images.githubusercontent.com/47758224/204250123-288dbb04-2a31-4cbb-a369-6024b9600aea.mov
=> fix: make table rows only take one line

webapp/javascript/components/TagsBar.module.css, webapp/javascript/components/TagsBar.module.scss, webapp/javascript/components/TagsBar.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1782
- loading tag value when user hovering on tag. Loading indicator during tag values loading process
DEMO: https://pr-1784.pyroscope.io/
=> fix(webapp): Tags are not being displayed 

webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx
- fixes https://github.com/pyroscope-io/pyroscope/issues/1604
- added `minTickSize` option for timelines.
https://user-images.githubusercontent.com/7372044/205306728-c7a6e689-0c18-4747-a60c-e27c80ed5bd0.mp4
DEMO: https://pr-1786.pyroscope.io/
=> fix(webapp): Timeline ticks overlapping

webapp/javascript/hooks/colorMode.hook.ts, webapp/javascript/pages/ContinuousSingleView.tsx
- https://github.com/pyroscope-io/pyroscope/issues/1788
- added color for Single View timeline chart on light mode (I set primary color for light mode as bars color, but it can be changed after review)
- added logic which tracks changing color mode for `<body data-theme="light | dark">`. There are 2 source where we set current color mode - redux store (`ui.colorMode`) and `<body data-theme="light | dark">`. I extended `useColorMode` logic to have synced both these source. When some logic changes color mode in `data-theme` there is react-side handler which updates UI according to new theme.
- DEMO: https://pr-1790.pyroscope.io/
=> chore(webapp): color mode for timeline [Single View]

pkg/adhoc/pull.go, pkg/adhoc/push.go, pkg/cli/server.go, pkg/config/config.go, pkg/convert/pprof/profile.go, pkg/scrape/config/config.go, pkg/scrape/manager.go, pkg/scrape/scrape.go, pkg/server/ingest.go, pkg/util/cumulativepprof/cumulative.go
Do the same thing as in client https://github.com/pyroscope-io/client/pull/24 for scrape and before ingestion
=> feat: cumulative pprof merge for pull mode

examples/golang-pull/file/Dockerfile, examples/golang-pull/file/README.md, examples/golang-pull/file/docker-compose.yml, examples/golang-pull/file/main.go, examples/golang-pull/file/server.yml, examples/golang-pull/file/targets.json
The PR adds an example configuration of the [file service discovery mechanism](https://github.com/pyroscope-io/pyroscope/pull/662) which was implemented almost a year ago but has not been documented
=> chore: add file service discovery example

webapp/javascript/components/Settings/APIKeys/index.tsx
Making a minor fix to the `HeadRow` of Api Keys table to ensure that headings match the actual content
=> [MINOR] Fix order of table header for API Keys

stories/Table.stories.tsx, webapp/javascript/ui/Table.module.scss, webapp/javascript/ui/Table.spec.tsx, webapp/javascript/ui/Table.tsx
* Adds very simple frontend pagination to the `Table` component:
(sorry, having trouble generating gifs right now)
The use case is for some internal visualization code I am writing which has a large number of items.
To have it enabled, just pass an `itemsPerPage` prop.
* Also add tests for this pagination, and a storybook example.
* Left only previous/next page button, so that implementing api pagination is easier (specially when using cursors, as opposed to offsets).
=> chore(webapp): add table pagination

webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx, webapp/javascript/pages/ContinuousComparisonView.tsx, webapp/javascript/pages/ContinuousDiffView.tsx, webapp/javascript/pages/ContinuousSingleView.tsx, webapp/javascript/pages/TagExplorerView.tsx, webapp/javascript/redux/reducers/continuous.ts, webapp/javascript/redux/reducers/continuous/selectors.ts, webapp/javascript/redux/reducers/continuous/state.ts, webapp/javascript/redux/reducers/continuous/timelines.thunks.ts, webapp/javascript/services/render.ts
Originally raised by @korniltsev 
Render annotations in the timeline for all pages, including TagExplorer:
Keep in mind this is only about RENDERING annotations. For creation it's still only possible in Single View.
=> feat(webapp): add annotations rendering to all timelines

pkg/scrape/scrape.go
Signed-off-by: Ben Ye <benye@amazon.com>
This pr unsets the `Accept-Encoding=gzip` header in scraper.
See more context from slack discussion https://pyroscope.slack.com/archives/C01FJRYENPQ/p1673835553042149.
=> unset gzip header when scraping

pkg/scrape/config/config.go
introduce an option `use-delta-profiles` which will enable new delta profiles and make scraper go to new delta endpoints https://github.com/pyroscope-io/client/pull/28/files#diff-0373c4cce76bc8bd39c8c6b636420424b74140f3e3da03a10612373a32f9c348R21-R23
```
enabled-profiles: [cpu, mem, block, mutex]
use-delta-profiles: true # << 
```
=> chore: add scrape config for  delta profiles

pkg/server/controller.go, pkg/server/controller_admin_test.go, pkg/server/controller_https_test.go
- tries to fix a data race 
<details>
==================
WARNING: DATA RACE
Read at 0x00c00021a530 by goroutine 11548:
github.com/pyroscope-io/pyroscope/pkg/server.(*Controller).Stop()
/home/korniltsev/pyroscope/pyroscope/pkg/server/controller.go:502 +0x9e
github.com/pyroscope-io/pyroscope/pkg/server.glob..func3.3.2()
/home/korniltsev/pyroscope/pyroscope/pkg/server/controller_admin_test.go:91 +0x39
runtime.gopanic()
/usr/local/go/src/runtime/panic.go:890 +0x261
github.com/onsi/gomega/internal.(*Assertion).match()
/home/korniltsev/go/pkg/mod/github.com/onsi/gomega@v1.17.0/internal/assertion.go:100 +0x302
github.com/onsi/gomega/internal.(*Assertion).To()
/home/korniltsev/go/pkg/mod/github.com/onsi/gomega@v1.17.0/internal/assertion.go:58 +0xe8 …
=> chore(tests): improve pkg/server test

pkg/convert/pprof/streaming/parser_streaming_writebatch.go, pkg/convert/pprof/streaming/structs.go
There was an attempt to do the whole hashing on the stack
```
var hashes [64 + 32]uint64
s := hashes[:]
```
unfortunately it should have been 
```
s := hashes[:0]
```
also 
with this code 
```
sh.Data = uintptr(unsafe.Pointer(&s[0]))
```
hashes escapes to heap
and with this does not escape
```
ps := uintptr(unsafe.Pointer(&s[0]))
sh.Data = ps
```
which is weird
I rewrote to just hash on a single preallocated  heap/arena slice
=> fix(pprof parsing): decrease number of allocations during stack hash

pkg/convert/pprof/streaming/vt_function.go
before this change, when the parser is pooled if a function message has no some field it would reuse some garbage from previous pool usage
=> fix(pprof parsing): initialize function to zero values before parsing

.github/workflows/ci-profiling.yaml, webapp/javascript/components/PageTitle.spec.tsx
* Increase timeout for flaky frontend tests
* Export golang ci profiles to flamegraph.com
=> chore: ci profiling

pkg/server/render.go
`expectFormats` check is already done inside `renderParametersFromRequest` at [pkg/server/render.go#L264](https://github.com/pyroscope-io/pyroscope/blob/main/pkg/server/render.go#L264).
=> chore: remove duplicated expectFormats check

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx, packages/pyroscope-flamegraph/src/FlamegraphRenderer.tsx, webapp/javascript/pages/exemplars/ExemplarsSingleView.tsx
A tricky one raised by @Rperry2174 
In light mode, the title (which i highlighted with red) is white.
The reason is that it inherits the color from the topmost component with has an explicit color set, in this case `pyro-flamegraph`. However, the css variables for light mode were only available in a div UNDER `pyro-flamegraph`. 
To put in other terms, title used whatever color `pyro-flamegraph` had, but `pyro-flamegraph` didn't have any color set!
Solution here is to move the theme attribute (`data-`) to be defined in the `pyro-flamegraph` component.
=> fix(flamegraph): fix styling when in light mode

LICENSING.md
Adds clarifications that our frontend packages are Apache 2:
* `@pyroscope/flamegraph`
* `@pyroscope/models`
=> chore: adds clarifications RE Apache 2 packages to LICENSING.md

webapp/javascript/components/Heatmap/index.tsx
When querying exemplars and there's no data, the backend will return `minValue: 0, maxValue: 0`, which breaks the y axis calculation. Worse, it will generate duplicate values (a bunch of `0.0`s), which are used as the [`key`](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key) in the React component. This confuses React, which upon querying exemplars that exist, will not be aware that the items must be removed (since the key is duplicated).
It's better exemplified in the following screenshots:
To fix this I just make it very clear that the Y axis can not be constructed, and default to a single value: 0.
=> fix(webapp): fix heatmap y axis

packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts
If the node name is part of a property from the prototype chain (like `toString`), `childrenMap[node.children[i].name] ||= node.children[i];` won't set up the correct value, since there's already a property there! Long story short, it crashes the calculation and therefore the flamegraph.
By using a `map` it correctly ignores these default properties.
A full list of function names this should fix is below:
<details>
`"toString, toLocaleString, valueOf, hasOwnProperty, isPrototypeOf, propertyIsEnumerable, __defineGetter__, __defineSetter__, __lookupGetter__, __lookupSetter__, __proto__, constructor" `
</details>
Also a reproducible flamebearer:
<details>
```json
{
"version": 1,
"flamebearer": {
"names": [
"total",
"runtime.main",
"toString",
"main.work",
"main.main",
"main.fastFunction"
], …
```
=> fix(pyroscope-flamegraph): use map in sandwich conversion to not conflict with properties from the prototype

webapp/javascript/hooks/timeline.hook.ts
When queries are not set and trying to load the timelines, the backend will return an error:
Here we just skip loading the timelines, unless both queries are set.
This has the side effect of requiring BOTH queries to be set, which is fine for now, since we auto set the query automatically (based on application name). But could be a problem in the future if we ever decide to allow using different queries.
=> fix(webapp): only load timelines when both queries are set

webapp/javascript/components/AppSelector/AppSelector.module.scss, webapp/javascript/components/AppSelector/Label.tsx, webapp/javascript/components/AppSelector/index.tsx, webapp/javascript/components/Toolbar.tsx
Follow up from https://github.com/grafana/pyroscope/pull/1923 because I didn't notice same string was used in other places (┛ಠ_ಠ)┛彡┻━┻
=> chore: allow overwriting app selector label

webapp/javascript/components/TimelineChart/TimelineChart.tsx, webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx, webapp/javascript/components/TimelineChart/Tooltip.plugin.tsx
So that we can 1) override most timeline code downstream and 2) it type checks with react 18
=> chore(webapp): use aliased imports and do type assertion

Dockerfile, Makefile, pkg/adhoc/connect.go, pkg/adhoc/exec.go, pkg/agent/phpspy/phpspy.go, pkg/agent/session.go, pkg/agent/spy/spy.go, pkg/config/config.go, pkg/exec/connect.go, pkg/exec/exec.go, third_party/phpspy/phpspy.h
update phpspy
what's changed:
- do not use USE_ZEND=1 (allow profiling all php versions other then 7.3 and simillar)
- fix bug when reading from /proc/pid/mem and process is dead and we did not notice it and was sampling the dead process forever
- add a new api to pass args to php_spy via phpspy_init_spy - it accepts comma separated list of arguments, for now only two args are supported direct_mem=true/false (default is false), libphp_awk_pattern=foobar(default is "libphp[78]?")
- allow selecting direct_mem/proc_vm_read at runtime
- allow overriding libphp awk pattern
=> fix(phpspy): update phpspy

pkg/convert/pprof/bench/parser_test.go, pkg/convert/pprof/streaming/vt_profile.go
when parser is reused(pooled) there was a bug - parser was using more functions/locations than parsed - used data from previous parse invocation
=> fix(pprof): bug reusing slices

benchmark/internal/cireport/imagereport.go, benchmark/internal/cireport/metareport.go, benchmark/internal/cireport/tablereport.go
strings.Builder uses *(*string)(unsafe.Pointer(&b.buf)) to save the application memory operation when converting to a string
=> benchmark: use the more efficient strings.Builder

pkg/sqlstore/migrations/migrations.go
fix the typo in the gorm tag of the annotation table
=> fix the typo in the gorm tag of the annotation table

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx, packages/pyroscope-flamegraph/src/FlameGraph/decode.ts, packages/pyroscope-flamegraph/src/FlameGraph/normalize.spec.ts, packages/pyroscope-flamegraph/src/FlameGraph/normalize.ts, packages/pyroscope-flamegraph/src/FlameGraph/uniqueness.spec.ts, packages/pyroscope-flamegraph/src/FlameGraph/uniqueness.ts, packages/pyroscope-flamegraph/src/ProfilerTable.tsx, packages/pyroscope-flamegraph/src/convert/subtract.ts
we were naively deep copying the profile by serializing to/parsing from json, which in big cases (>5 MB) is very slow.
Also memoize the `ProfilerTable`.
I've investigated it a little bit more and found that great part of the slowness with a huge flamegraph comes from 
https://github.com/grafana/pyroscope/blob/72e54ccfcbb4812f87f8fc6840545079096c5462/packages/pyroscope-flamegraph/src/ProfilerTable.tsx#L415-L439
Which in turn creates n handlers
https://github.com/grafana/pyroscope/blob/72e54ccfcbb4812f87f8fc6840545079096c5462/packages/pyroscope-flamegraph/src/ProfilerTable.tsx#L354
So yeah there's room for more improvement.
=> perf(flamegraph): improve performance

examples/grafana-agent/README.md, examples/grafana-agent/agent/config/agent.yaml, examples/grafana-agent/agent/config/config.river, examples/grafana-agent/docker-compose.yml, examples/grafana-agent/grafana-provisioning/dashboards/main.json, examples/grafana-agent/grafana-provisioning/dashboards/main.yml, examples/grafana-agent/grafana-provisioning/datasources/datasources.yml, examples/grafana-agent/grafana/grafana.ini, examples/grafana-agent/grafana/home.json, examples/grafana-agent/phlare/config.yaml, examples/grafana-agent/pyroscope/config.yaml
=> chore: adds a Grafana Agent example

pkg/server/labels.go, pkg/server/labelvalues.go
For now,  `/labels` and `/label-values` handlers do not set `Content-Type` explictly, so `net/http` wrongly sets it to `text/plain`.
This PR fixes the problem by using `httpUtils.WriteResponseJSON` function.
=> fix(server): set `Content-Type` to JSON in label handlers

examples/adhoc/README.md
@korniltsev can you please help me make the docs more generic / make sense to run from scratch in our examples folder?
i.e. pyroscope-cli vs ./bin/pyroscope which one should I use? Should I already have both downloaded, etc.
=> Update adhoc readme for more adhoc modes

package.json, yarn.lock
- Force version of:
```
"optionator": "^0.9.3",
```
to ensure import of an alternative implementation of `word-wrap`, which doesn't trigger security concerns.
=> fix: repace word-wrap with secure variant

pkg/phlaredb/query/iters.go
I'm not fully sure this solves the problem mentioned https://github.com/grafana/pyroscope/issues/2137 but should alleviate it at least
=> Fix IteratorResult pool usage

pkg/util/loser/tree.go, pkg/util/loser/tree_test.go
When an error happened on a single one of the iterators during initialisation, then `Close()` would call `close` with a `null/nil` value,  causing some panic. It also would not close the remaining iterators.
This adds tests and the fix
=> Ensure loser tree closes underlying sequences properly on error

webapp/javascript/components/DateRangePicker.tsx
- Progress toward #1999
The new maximum time range preset if 90 days.
=> fix: limit time picker presets

pkg/iter/iter.go, pkg/iter/profiles_test.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/block_querier_test.go
This PR fix a goroutine on the query path that can trigger if we don't call Close correctly or leave the buffer full (no calling next).
It adds changes:
- Close all iterator in case of failure when building them
- Add cancellation when pushing to channel.
=> Fix goroutine leak in BufferedIterator

docs/sources/configure-client/language-sdks/ebpf.md
reopened https://github.com/grafana/phlare/pull/864
=> fix(ebpf): use grafana agent in docs. copypaste docs from grafana agent

pkg/iter/iter.go, pkg/iter/tree.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/block_symbols_appender.go, pkg/phlaredb/block_symbols_reader.go, pkg/phlaredb/block_symbols_writer.go, pkg/phlaredb/compact.go, pkg/phlaredb/compact_test.go, pkg/phlaredb/deduplicating_slice.go, pkg/phlaredb/head.go, pkg/phlaredb/sample_merge.go, pkg/phlaredb/schemas/v1/profiles.go, pkg/phlaredb/symdb/format.go, pkg/phlaredb/symdb/interfaces.go, pkg/phlaredb/symdb/partition_memory.go, pkg/phlaredb/symdb/partition_memory_test.go, pkg/phlaredb/symdb/stacktrace_tree_test.go, pkg/phlaredb/symdb/symbols_reader_file.go, pkg/phlaredb/symdb/symbols_reader_file_test.go, pkg/phlaredb/symdb/symbols_writer_file.go, pkg/phlaredb/symdb/symbols_writer_file_test.go, pkg/phlaredb/symdb/symdb.go
The PR contains implementation of the symbols rewriter which is used in compaction. The design of the implementation is heavily influenced by the following factors:
- On compaction, we may want to get only a subrange of profiles from a source block. The range may be limited to a specific series set, time range, or both.
- Symbolic information of a source block must be loaded into memory entirely, because there is no efficient way to load it in parts.
TODO:
Currently, the complete compaction flow is incomplete which complicates further testing. Specifically, I didn't manage to query any data from a storage with a compacted block: it either returns empty result, or fails with the error `panic: label hash conflict`.
Nevertheless, I think that we should pull this change into the main …
=> Compact symdb

pkg/phlaredb/block/metadata.go, pkg/phlaredb/block/metadata_test.go
This is going to be used for creating meta of splitted sharded blocks.
=> Adds a clone function for meta file

pkg/phlaredb/compact.go, pkg/phlaredb/compact_test.go, pkg/phlaredb/head.go, pkg/phlaredb/head_test.go
The original block should have all source IDS which is itself, then compacted should merge source of parents.
Also adds test for both case.
=> Correctly setup compaction sources in block meta files

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml
This lets us test out the new directory in the website repository preview builds.
Once we are happy with the preview of the `publish-to-pyroscope` branch in the website repository, we can merge that PR in the website repository, updating the production website.
Then we will need to update this workflow again to commit back to the primary website branch.
=> Update workflows to publish to different website branch and new target directory

.github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/weekly-release.yml
This will avoid running into the rate limiting, which we hit on the bot account
=> Use app auth for release/weekly-release/deploy

pkg/querier/timeline/timeline.go, pkg/querier/timeline/timeline_test.go
closes https://github.com/grafana/pyroscope/issues/2147
This PR fixes the timeline bug where some timelines would have lots of 0 values towards the end. It also fixes some slice copy bugs, where slices would be copied incorrectly back on to other slices, adding erroneous values.
This also has fixes for small alignment issues in the timeline values, though these are unlikely to ever be noticed as it previously would only miss at most 2 padded values (one at the beginning and one at the end).
=> Fix timeline backfills

pkg/querier/timeline/timeline.go, pkg/querier/timeline/timeline_test.go
In https://github.com/grafana/pyroscope/pull/2200 ([comment](https://github.com/grafana/pyroscope/pull/2200#discussion_r1282708713)), it was noted that there could be a performance improvement when allocating slices. This PR changes how slices are allocated such that only one allocation is necessary at the beginning of the function.
Here's a quick benchmark that generally describes the performance change compared to the old method:
```
$ go test -bench=. -run=xxx -benchtime=5s -benchmem                                      
goos: darwin
goarch: arm64
pkg: github.com/grafana/pyroscope/pkg/querier/timeline
Benchmark_Backfill/New-12               5614            961086 ns/op         3942035 B/op          6 allocs/op
Benchmark_Backfill/Old-12                  1       72707588750 ns/op …
```
=> refactor: reduce allocs when building timeline

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/validation/limits.go
The recently introduced limit on the number of samples per profile (of specific type) is overly conservative. This change increases the default value from 4K to 16K.
=> Increase the default limit on number of samples per profile

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/validation/limits.go
Backporting the fix to the latest release. For some reason, I'm unable to push directly to the `weekly/f26` branch
=> Weekly 26: increase samples limit

docs/Makefile
The check is specific to storing assets in the repository as part of Hugo leaf bundles. Current advice is to instead store assets in the website asset uploader service following the instructions in https://grafana.com/docs/writers-toolkit/writing-guide/image-guidelines/#where-to-store-media-assets. This makes the check raise false errors.
=> Skip image validation in doc-validator

docs/sources/configure-client/_index.md, docs/sources/get-started/_index.md
Fixes broken links and I think _at least_ the top of our Getting Started page should say Pyroscope to not confuse people -- another pr in https://github.com/grafana/pyroscope/pull/2209
=> Fix broken links after reorganizing docs structure

api/buf.gen.yaml, api/gen/proto/go/google/v1/profile_vtproto.pb.go, docs/sources/configure-server/reference-configuration-parameters/index.md
Reusing tiny pprof protobuf objects is more expensive than allocating new: `(*Profile).ReturnToVTPool` consumes 23% of total CPU time. It makes sense to revisit the decision to use pools for pprof proto.
=> Disable pools for locations, functions, and lines

.golangci.yml, Makefile
Bumped the golangci-lint to 1.54.0. The main change is we need to upgrade the depguard from v1 to v2. You can see more at: https://github.com/golangci/golangci-lint/pull/3795/files
=> Bump golangci-lint to 1.54.0

Makefile
This was affected by the helm charts renaming
=> Ensure local micro-services still works after rename

ebpf/symtab/kallsyms.go, ebpf/symtab/kallsyms_test.go, ebpf/symtab/symbols.go
This will save couple of megabytes when `CollectKernel=false` ( /proc/kallsyms is 2M on our dev nodes and 16M on my machine)
=> fix(ebpf): make kallsyms lazy

ebpf/symtab/elf.go, ebpf/symtab/elf/elf_sym.go, ebpf/symtab/elf/elfmmap_test.go, ebpf/symtab/elf/symbol_table.go, ebpf/symtab/elf_test.go, ebpf/symtab/gosym/pcindex.go, ebpf/symtab/proc_linux_test.go, ebpf/symtab/symbols.go
for golang binaries we create symbol table from `.gopclntab` section. it is useful for striped binaries.
It may be usefull to still look into `.sym`  sections for non go functions ie cgo . Thus there's a GoTableWithFallback. 
However for unstripped binaries it now keeps in memory duplicate symbols for go functions  (both from   `.gopclntab` and  `.sym` )
This PR:
- disable gotable fallback by default
- when  gotable fallback is enabled, do not duplicate symbols between gotable and `.sym` table
=> fix(ebpf): disable gotable fallback by default, make gotablefallback smarter

ebpf/symtab/gosym/pcindex.go, ebpf/symtab/gosym/pcindex_test.go
PCIndex.FindIndex is not super hot, it is only 3%. However the change is not hard so I do it anyway. "It ain't much, but it's honest work"
In this PR I've inlined sort.Search in PCIndex.FindIndex.
```
goos: linux
goarch: amd64
pkg: github.com/grafana/pyroscope/ebpf/symtab/gosym
cpu: AMD Ryzen 9 5950X 16-Core Processor            
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
BinSearch-32   3.354m ± 11%   1.716m ± 1%  -48.83% (p=0.000 n=10)
```
=> fix(ebpf): improve pcindex binary search speed

ebpf/symtab/elf/go_table.go, ebpf/symtab/elf/symbol_table.go, ebpf/symtab/elf_cache.go, ebpf/symtab/gcache.go, ebpf/symtab/proc.go, ebpf/symtab/symbols.go
fix bug: ElfCache.Cleanup should clear the whole cache, only Close all files, and remove entries witch did not update for couple of rounds .
In this PR:
- fix the bug
- improve debug info a bit - add pointers to the expensive objects, add last_updated_round bits.
=> fix(ebpf): do not clear ElfCache

docs/sources/configure-client/language-sdks/dotnet.md
=> Update dotnet docs

cypress/ci-base-path.ts, cypress/e2e/smoke.cy.ts, pkg/api/api.go, pkg/phlare/phlare.go, public/app/components/Sidebar.tsx, public/app/services/render.ts, public/execute_template.go, public/execute_template_test.go
I split it from [the old PR](https://github.com/grafana/pyroscope/pull/2190). 
The idea is to:
* move what's currently `/` to `/admin`
* move what's currently `/ui` to `/`
I fixed the issue Christian reported in the original PR. The issue was that when I changed the route from `/ui` to `/` it started matching everything, so I had to make sure `/` route is the very last we create.
Currently the routing table looks like this (I added `PYROSCOPE_PRINT_ROUTES=1` env variable to trigger a print of all routes):
```
* ^/metrics$
* ^/debug/pprof
GET ^/admin$
GET ^/api/swagger\.json$
GET,POST,PUT,DELETE,HEAD,OPTIONS ^/api
GET ^/debug/fgprof$
GET ^/static/
GET ^/ui
GET ^/assets/
GET ^/memberlist$
* ^/agent\.v1\.AgentService/GetTargets$
GET,POST ^/overrides-exporter/ring$
GET,POST ^/ring$
* …
```
=> chore: moves UI to / from /ui, moves old / to /admin

Makefile, cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/configure-disk-storage.md, docs/sources/configure-server/reference-configuration-parameters/index.md, operations/pyroscope/helm/pyroscope/values.yaml, pkg/phlaredb/phlaredb.go, pkg/phlaredb/profile_store.go
As far as I can tell we don't use this config parameter anywhere. I left some names untouched, because that would break hard, so I think we should change those later e.g:
* https://github.com/pyroscope-io/pyroscope/blob/d97de8a608786a23270b167de18e495f61cfeceb/pkg/storegateway/bucket.go#L45
* https://github.com/pyroscope-io/pyroscope/blob/5dbd4fb1fe294f57651fa70405acf5a666b13d2e/pkg/phlaredb/profile_store.go#L68
=> chore: renames phlaredb to pyroscopedb

docs/sources/configure-client/language-sdks/rust.md
Important for grafana cloud users
=> Update rust.md with details for using basic auth

pkg/frontend/frontend_diff.go, pkg/frontend/frontend_label_names.go, pkg/frontend/frontend_label_values.go, pkg/frontend/frontend_profile_types.go, pkg/frontend/frontend_select_merge_profile.go, pkg/frontend/frontend_select_merge_stacktraces.go, pkg/frontend/frontend_select_series.go, pkg/frontend/frontend_series.go, pkg/model/flamegraph_diff.go, pkg/phlare/modules.go, pkg/util/connectgrpc/connectgrpc.go, pkg/util/connectgrpc/connectgrpc_test.go
Resolves #2133. The change allows to deprecate the [`querier.Diff`](https://github.com/grafana/pyroscope/blob/1596f8a119d74d9272a523444dbb2ff0f84cecf4/api/querier/v1/querier.proto#L16) method.
=> Handle OG Pyroscope endpoints in query frontend

.github/workflows/release.yml
cc @simonswine 
I figured this might be the issue we saw with weekly releases — but they work now, so I'm not sure.
=> chore: fixes release pipeline's GITHUB_TOKEN

pkg/model/tree.go, pkg/phlaredb/delta.go, pkg/phlaredb/schemas/v1/profiles.go
An attempt to fix #2282 and #2179.
=> Remove negative samples

operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
This makes sure no more than a single pod of a stateful set can be interrupted by e.g. node updates.
=> Add pod disruption budget

pkg/phlaredb/block_querier.go, pkg/phlaredb/symdb/block_reader.go
Now that we read symbols from parquet tables at query time, reader buffers may take up quite significant amount of memory. The current value is 2MB (defaults to 64KB), and the buffer is allocated for each column chunk (and dictionary page). I've been testing various values and can conclude that decreasing it to 256KB for both symbols and profile tables do not increase latency to any noticeable extent:
Although it makes sense to make this configurable and even allocate buffers of different sizes depending on the media (disk or object storage), I decided to set the default value first, as I imagine it would be difficult for users to determine the appropriate value.
=> Adjust default parquet reader buffer size

pkg/phlaredb/block_querier.go, pkg/phlaredb/head.go, pkg/phlaredb/head_test.go
* #2196 introduced a bug where `SeriesNum` field of the index file in the `meta.json` is always zero. This information duplicates `BlockStats.NumSeries` and is not used anywhere in the read path, however it is better to maintain it for consistency with existing blocks.
* Added test that validates `meta.json` generated with `head.Flush`.
* A micro optimisation of how tsdb index file is read: `io.ReadAll` is replaced with `io.ReadFull` as it allocates less memory.
=> Fix TSDB file meta

pkg/phlaredb/block_querier_symbols.go, pkg/phlaredb/sample_merge.go, pkg/phlaredb/symdb/block_reader.go, pkg/phlaredb/symdb/resolver.go, pkg/phlaredb/symdb/resolver_test.go
Fixes #2291
Additionally we could check if the tree/table is nil, but in case if ref counting is not respected it will lead to a memory leak
=> Fix reference counting

pkg/querier/http.go
If profile types in the diff view don't match, the handler panics:
=> Fix profile type mismatch

ebpf/go.mod, ebpf/go.sum, go.mod, go.sum, pkg/phlare/phlare.go, pkg/util/cli/banner.go
I breaks through the 80 character width though
=> Bring the Pyroscope banner back

pkg/validation/validate.go, pkg/validation/validate_test.go
Resolves #2215. Also makes stack trace truncation to cut deepest frames as per #2189 (but without a stub frame, like "other")
=> Clarify profile validation errors

cmd/pyroscope/Dockerfile, cmd/pyroscope/debug.Dockerfile, og/Dockerfile, tools/docker-compose/golang/Dockerfile
Addresses those:
```grafana/pyroscope:1.0.0-rc.0 (alpine 3.17.4)
Total: 6 (UNKNOWN: 0, LOW: 0, MEDIUM: 6, HIGH: 0, CRITICAL: 0)
┌────────────┬───────────────┬──────────┬───────────────────┬───────────────┬─────────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability │ Severity │ Installed Version │ Fixed Version │                            Title                            │
├────────────┼───────────────┼──────────┼───────────────────┼───────────────┼─────────────────────────────────────────────────────────────┤
│ libcrypto3 │ CVE-2023-2975 │ MEDIUM   │ 3.0.9-r1          │ 3.0.9-r2      │ AES-SIV cipher implementation contains a bug that causes it │
│            │               │          │                   │               │ to ignore empty... …
```
=> Update alpine version to 3.18.3

operations/pyroscope/helm/pyroscope/Chart.yaml, operations/pyroscope/helm/pyroscope/README.md, operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
Update helm chart to be 1.0.0, as otherwise it is not used as the default and the broken chart version 0.5.4 is used.
See #2302
=> Update helm chart release to be 1.0.0

pkg/phlaredb/head.go, pkg/phlaredb/phlaredb.go, pkg/phlaredb/phlaredb_test.go
The change makes `PhlareDB` responsible for tracking the `Head` block flush conditions.
Resolves #2284
=> Fix head flush orchestration

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/pyroscope.yaml, docs/sources/configure-server/about-configurations.md, docs/sources/reference-pyroscope-architecture/components/distributor.md, pkg/phlare/modules.go, pkg/phlare/phlare.go, pkg/storegateway/gateway_ring.go
This activate the store-gateway when using single binary mode with object storage configured properly.
This doesn't work for filesystem because of https://github.com/grafana/pyroscope/issues/2029.
I'm still testing this and found https://github.com/grafana/pyroscope/issues/2317 that affect PGO feature when using single binary and querying for historical timerange.
In this PR I also changed the default for replication factor of the store-gateway to 1.
Closes #2247
=> Activate store-gateway when using single binary mode.

operations/pyroscope/helm/pyroscope/Chart.yaml, operations/pyroscope/helm/pyroscope/README.md, operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
I had this issue too locally https://github.com/grafana/pyroscope/issues/2328 and I had to update my helm version. Not sure we want to force people to upgrade helm just for this.
FYI The grafana agent requires kubernetes 1.22.
=> helm: Removes kubeVersion check

.github/workflows/e2e.yaml, .github/workflows/frontend.yml, .github/workflows/helm-release.yml, .github/workflows/publish-technical-documentation-next.yml, .github/workflows/test.yml, README.md
removes references to `next` branch now that the `main` branch is back
=> chore: s/next/main/g

operations/pyroscope/jsonnet/pyroscope-mixin/pyroscope-mixin/config.libsonnet, operations/pyroscope/jsonnet/pyroscope-mixin/pyroscope-mixin/dashboards.libsonnet, operations/pyroscope/jsonnet/pyroscope-mixin/pyroscope-mixin/dashboards/pyroscope-reads.libsonnet, operations/pyroscope/jsonnet/pyroscope-mixin/pyroscope-mixin/dashboards/pyroscope-writes.libsonnet, operations/pyroscope/jsonnet/pyroscope-mixin/pyroscope-mixin/mixin.libsonnet
Before this fix:
```
❯ mixtool generate all mixin.libsonnet
2023/08/31 10:02:14 RUNTIME ERROR: couldn't open import "dashboards/phlare-writes.libsonnet": no match locally or in the Jsonnet library paths
dashboards.libsonnet:2:2-45     $
mixin.libsonnet:2:2-31  $
2:16-40 thunk <mixin> from <$>
4:21-26 thunk from <$>
<std>:1548:21-22        thunk from <function <anonymous>>
<std>:1548:5-32 function <anonymous>
4:4-47  $
During evaluation
```
After:
```
❯ mixtool generate all mixin.libsonnet
❯ ls dashboards_out
pyroscope-reads.json    pyroscope-writes.json
```
=> Mixin: Change from Phlare to Pyroscope

pkg/frontend/frontend_select_merge_stacktraces.go, pkg/frontend/frontend_select_series.go
Currently we only record query params in the querier, which makes it hard to find the source query time range if it has been split into multiple sub-queries.
=> Record query parameters before parallelization

pkg/phlaredb/schemas/v1/functions.go, pkg/phlaredb/schemas/v1/locations.go, pkg/phlaredb/schemas/v1/mappings.go, pkg/phlaredb/symdb/rewriter.go
The fix allows using the same block symbols reader by multiple stack trace rewrites. Note that this will cause excessive memory usage. We likely need a better way of handling this.
The failing test is irrelevant to the change.
=> Fix symbols split-compaction

pkg/phlaredb/profiles.go
When reading the len(pi.profilesPerFP) we need to be under the lock first.
=> Fixes a race when flushing indexes of rowgroups

ebpf/go.mod, ebpf/go.sum, go.mod, pkg/objstore/objstore.go, pkg/objstore/providers/filesystem/bucket_client.go, pkg/objstore/reader.go, pkg/objstore/sse_bucket_client.go, pkg/objstore/sse_bucket_client_test.go, pkg/objstore/testutil/objstore.go, pkg/objstore/user_bucket_client.go, pkg/phlaredb/block/block.go, pkg/phlaredb/block/fetcher.go, pkg/phlaredb/block/fetcher_test.go, pkg/phlaredb/block/global_markers.go, pkg/phlaredb/block/global_markers_bucket_client.go, pkg/phlaredb/block/global_markers_bucket_client_test.go, pkg/phlaredb/block/global_markers_test.go, pkg/phlaredb/block/markers.go, pkg/phlaredb/block/metadata.go, pkg/phlaredb/block/testutil/create_block.go, pkg/phlaredb/compact_test.go, pkg/phlaredb/head.go, pkg/phlaredb/phlaredb.go, pkg/phlaredb/sample_merge_test.go, pkg/util/extprom/tx_gauge.go
Also introduces markers for deletions
Most of the code is adapted from Mimir.
=> Introduce a meta fetcher that synchronize filtered metadata locally

pkg/objstore/parquet/reader.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/block_querier_symbols.go, pkg/phlaredb/symdb/block_reader.go
This will remove one get_range request to the bucket per table and block in the SymDB.
Unsure if this was left out on purpose. But that saves a 4 byte round trip to object store.
=> Use the optimized querier for symdb

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_ring.go, pkg/distributor/distributor_test.go, pkg/phlare/modules.go, pkg/phlare/phlare.go, pkg/querier/store_gateway_querier.go, pkg/scheduler/schedulerdiscovery/config.go, pkg/scheduler/schedulerdiscovery/ring.go, pkg/scheduler/schedulerdiscovery/ring_test.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go, pkg/util/ring_config.go, pkg/validation/exporter/exporter_test.go, pkg/validation/exporter/ring.go, pkg/validation/exporter/ring_test.go, pkg/validation/limits.go
I was about to copy the code again for compaction and decided to end it here.
This basically refactors all component to use the same `RingConfig` struct. Added bonus the generated doc is now more consistent.
=> Refactoring: Create a common ring configuration

cmd/pyroscope/help-all.txt.tmpl, pkg/phlare/phlare.go
In https://github.com/grafana/pyroscope/pull/2391, a change was made to factor out a common ring config to reduce duplication of ring settings across components. In doing so, a change was added to set default port values if no value was provided:
https://github.com/grafana/pyroscope/commit/2c73692f18f99b00dfb336088b7211b953a9ae12#diff-e94eca41c9ef18ab2a324780565931df687280a46d570e6d08ebc54f73bf541dR167-R170
In doing so, this fouled up a separate process where (if no default was provided for instance-port) it would fallback to the http listen port.
This PR removes the change where a default port value would be used, allowing the fallback mechanism to work correctly.
=> fix: Rings are using the incorrect port

pkg/util/http.go
https://github.com/grafana/pyroscope/issues/2393
```
ts=2023-09-12T10:30:57.130450314Z caller=http.go:190 level=info traceID=1cfcc3ccda0a068b tenant=238 msg="POST /ingest?aggregationType=&from=1694514641&name=simple.golang.app-new%7B%7D&sampleRate=0&spyName=gospy&units=&until=1694514656 (200) 556.059µs"
```
=> fix: log tenant id

pkg/phlaredb/validate.go, pkg/phlaredb/validate_test.go
This will allow us to ensure blocks downloaded locally are valid before uploading or compacting.
For now I'm using file system bucket storage for simplicity but it might be more efficient in the future to just use the filesystem.
=> Adds a way to validate local blocks

public/app/components/TimelineChart/TimelineChart.tsx, public/app/components/TimelineChart/util.spec.tsx, public/app/components/TimelineChart/util.ts
It was detected that for very small selections on the timeline, the date range would be left in an invalid state. This is often due to there being no data points in the new selection, resulting in a corruption of subsequent range selection.
This PR avoids the issue by doing a few checks before accepting a range selection on the time line. If there are too few points in the new selection, it is aborted, thus preventing the resulting bugs.
=> fix: various bugs that occur when selection is too small

api/gen/proto/go/querier/v1/querier_vtproto.pb.go, api/gen/proto/go/querier/v1/querierv1connect/querier.connect.go, api/querier/v1/querier.proto
This was something I have clarified in slack, just adding back to the code
=> Explain querier API calls with a brief comment

pkg/objstore/parquet/file.go, pkg/objstore/parquet/file_test.go, pkg/objstore/parquet/reader.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/block_querier_symbols.go, pkg/phlaredb/symdb/block_reader.go, pkg/phlaredb/symdb/block_reader_load.go
Opening a parquet files currently involves 6 RTT to the object store bucket, this PR will reduce this to one. (🤞)
- ~Consider storing the correct size in `meta.json` and use those~ #2419
=> Reduce roundtrips to object store, when opening parquet files

docs/sources/deploy-kubernetes/helm.md, examples/tracing/jaeger/grafana/provisioning/datasources/datasources.yml
The only correct values are `phlare` and `grafana-pyroscope-datasource`
=> Docs: Use the correct data source type

cmd/pyroscope/main.go
I think the minimum we can do about https://github.com/grafana/pyroscope/issues/2421 is to use be explicit and error.
=> Handle pyroscope 0.37 modes more gracefully

operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml, operations/pyroscope/helm/pyroscope/templates/configmap-agent.yaml, operations/pyroscope/helm/pyroscope/templates/configmap-overrides.yaml, operations/pyroscope/helm/pyroscope/templates/configmap.yaml, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml, operations/pyroscope/helm/pyroscope/templates/ingress.yaml, operations/pyroscope/helm/pyroscope/templates/memberlist-service.yaml, operations/pyroscope/helm/pyroscope/templates/rbac.yaml, operations/pyroscope/helm/pyroscope/templates/serviceaccount.yaml, operations/pyroscope/helm/pyroscope/templates/services.yaml
This PR adds namespace values for each resource created by the helm chart. Previously, everything would be installed in the default namespace, e.g. `helm -n pyroscope-test install pyroscope grafana/pyroscope` would not install into the `pyroscope-test` namespace. 
Not sure if there was a specfic reason for this.
=> fix(helm): set correct namespace for all resources

public/app/hooks/useAppNames.ts
- If no app is selected, choose the first cpu option as default
- If it can't find a cpu app, just choose the first as it did before
=> feature: prefer cpu app default if none selected

README.md, docs/internal/contributing/README.md
Also fixes: https://github.com/grafana/pyroscope/issues/2451
=> chore: specify versions for FE tools, fix doc links

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, pkg/distributor/distributor.go, pkg/ingester/ingester.go, pkg/ingester/limiter.go, pkg/ingester/limiter_test.go, pkg/phlaredb/profile_test.go, pkg/phlaredb/profiles.go, pkg/validation/limits.go, pkg/validation/limits_mock.go, pkg/validation/testutil.go, pkg/validation/validate.go, pkg/validation/validate_test.go
This change removes of order validation and instead make sure the ingested profiles are within the ingestion window, which will by default reach from now-1h to now+10m.
This will ensure a smoother experience with workloads that don't have unique labels sets
=> Distributor/Ingestor: Replace out of order validation with ingestion window

tools/packaging/postinstall.sh, tools/packaging/pyroscope.service, tools/packaging/test-install.sh
This will make it easier to validate RPM/DEB pacakges.
I noticed a problem with the systemd unit after install: Basically the data directory was not created and also not specified correctly.
With this it will use `/var/lib/pyroscope` and create it as part of the `./postinstall`
cc @wilfriedroset
=> Add script to test packaging artifacts

cmd/profilecli/main.go, cmd/profilecli/query.go
This command allows to query the profile series available from pyroscope. It support querier/ingester/store-gateway APIs.
The results are written to stdout, so they e.g. can be processed further with `jq`.
=> profilecli: Add query series command

api/buf.gen.yaml, api/gen/proto/go/google/v1/profile_vtproto.pb.go
I would prefer the PR merged after the next weekly release.
Resolves #2457. I'll attach a flamegraph-diff once I get some representative data but the gist is that GC overhead will likely be less that the pool overhead (~15% of the total CPU time). 
https://github.com/grafana/pyroscope/assets/12090599/49ca2f13-cca5-425f-a623-bed2d1427a1f
=> Disable protobuf pools for all but profiles

pkg/og/convert/pprof/profile.go, pkg/test/integration/helper.go, pkg/test/integration/ingest_pprof_test.go
Overriding the profile time with the request `StartTime` causes precision loss since `pyroscope-go` specifies time in seconds, which triggers #2483. I'm not sure if we need to update our SDKs, but created PR for Go: https://github.com/grafana/pyroscope-go/pull/54.
=> Preserve profile timestamp

public/app/components/ExportData.spec.tsx, public/app/components/ExportData.tsx, public/app/util/features.ts
This PR to let `ExportData` honour the value of the `exportFlamegraphDotCom` prop.
This is needed for the work on the Grafana plugin, see https://github.com/grafana/pyroscope-app-plugin/pull/87
=> feat: 'ExportData' now respects the 'flamegraph.com' related prop

docs/internal/contributing/README.md
This PR just to improve the contributing guidelines for Mac users with Apple Silicon chips.
=> docs: Added section for Apple arm64 builds

docs/sources/configure-client/grafana-agent/go_pull.md
the old module has been deprecated and it's been moved inside, so I updated it with the correct link.
=> Update go_pull.md with new module link

public/app/hooks/useAppNames.ts, public/app/hooks/util/determineDefaultApp.spec.ts, public/app/hooks/util/determineDefaultApp.ts
In this PR, we separate the business logic from the rest of the code to support code reusability and extensibility.
=> refactor(Frontend): Extract the logic to determine the default app for continuous profiling pages

docs/sources/configure-server/about-server-api.md, docs/sources/configure-server/configure-disk-storage.md, docs/sources/configure-server/configure-object-storage-backend.md
original server api docs https://github.com/pyroscope-io/docs/blob/main/docs/server-api-reference.mdx
TODO: 
- How does authentication work in new server API docs (with grafana cloud) 
- add more examples to examples folder
=> docs: adds server api docs

pkg/phlaredb/phlaredb.go
This should improve the spread of flushes per ingester. Not only I've increase the jitter, but it's re-evaluated on each run, making it even more randomized.
We still need a flush queue for large multitenant cluster.
=> Improve flush spread

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/phlaredb/compact.go, pkg/phlaredb/phlaredb.go
This now set 1h the block duration default and compaction range to 1h, 2h, and 8h.
This should be much better default based on my overall experience with the compactor.
The commit also include a big performance improvement where compacting large amount of blocks. This is done by reducing the row buffer  from 1024 to 32.
=> Tweak compaction configuration and performance.

pkg/compactor/split_merge_grouper.go, pkg/compactor/split_merge_grouper_test.go
This fixes an issue where if the minTime of a block would fall exactly on the end of a fixed range it would be considered overlapping (discarded).
In fact if that is the case it only means the block doesn't start within that range and we should move on to the next range.
=> Fixes compaction range block grouping

public/app/components/ChartTitle.tsx
This reverts commit b4e6cef43718aef5ecee5ed555891e7be9cca3bf and applies recommendations from
- #2565
=> Revert "fix: remove "Flamegraph" from timeline chart title (#2565)"

cmd/pyroscope/help-all.txt.tmpl, pkg/compactor/compactor.go
I think 1h was too high based on the default block duration 1h too.
Also we can open more block at once without any problem.
=> Increase default compaction interval

operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml, operations/pyroscope/helm/pyroscope/values.yaml, operations/pyroscope/jsonnet/values.json
Hi there, I added an additional field to be able to perform https readiness/health checks on Pyroscope when TLS is set up.
=> allow https health checks in the Helm chart

pkg/compactor/bucket_compactor.go, pkg/phlaredb/symdb/block_reader_load.go, pkg/phlaredb/symdb/resolver_test.go, pkg/phlaredb/symdb/symdb.go
When we compact blocks, it is preferable to load all symbols into memory
/cc @cyriltovena
=> Load symbols into memory at compaction

pkg/test/integration/helper.go, pkg/test/integration/ingest_pprof_test.go
This is trying to tune the integration tests for speed and stability.
Instead of default ports, it will detect free ports on the system to bind to for memberlist and http.
~It also reduces a few memberlist time duration to ensure there is a quick convergence.~
Update: I am ignoring memberlist all together in favour of the inmemory kv, which improves the test runtime by quite a bit.
=> Improve integration test stabiltity speed

pkg/phlaredb/profile_store.go
Again we had an incident where crashlooping pods would fill up the disk with parquet file buffer pages.
Turns out this is more harmful than helpful.
We're actually compacting faster since we don't need to go through a file firsrt and ingesters are using less ressources without this.
We should use file buffer page only if we consider that flushing a single rowgroups can't be done solely in-memory, but right now we actually have a way to flush intermediary row groups for this reason so this is not really helpul.
=> Remove the usage of file buffer for parquet pages.

public/app/components/TimelineChart/SyncTimelines/useSync.ts
Update on https://github.com/grafana/pyroscope/pull/1615: with a fixed value of 5m the user could end up in a situation where narrow selections wouldn't make the sync banner appear.
This PR:
- changes from fixed buffers (5m) to a dynamic buffers: we now allow 10% of the timeline duration on both sides of the timeline
- not related to the issue but... fixes the "Ignore" button that had no effect (the banner wouldn't disappear)
=> fix(SyncBanner): Add 10% buffer on both sides of the timeline

pkg/phlaredb/profile_store.go, pkg/phlaredb/profile_store_test.go
We've found instances where if an error happens during cut of rowgroups, there will be a file left over that will make next attempts fail.
This PR adds a test for this and fixes this by removing the segment if it exist, it will also log an error.
=> Cleanup failed segment before flushing.

pkg/phlaredb/block/fetcher.go, pkg/storegateway/bucket_index_metadata_fetcher.go, pkg/storegateway/bucket_index_metadata_fetcher_test.go
Since we merged the compactor, store-gateways rely on it to write the block index to quickly list blocks.
@cyriltovena not particularly pretty or performant, but I think might do its job
=> Fallback to manual listing, when bucket index is not available

examples/golang-push/rideshare/utility/pool.go, examples/golang-push/rideshare/utility/utility.go
Creates a worker pool that will keep a byte buffer around, causing memory in `us-east` to inflate. Tuning the buffer size and the number of workers that hang will adjust the impact of the memory leak.
Supersedes https://github.com/grafana/pyroscope/pull/2469 as this implementation is more straightforward.
=> Add worker pool that can leak a byte buffer
