public/app/pages/TagExplorerView.tsx
When there are more than N timelines in the tag explorer, the timelines that don't meet the top N criteria, are aggregated into a pseudo timeline called "Other."
Primarily, this is for calculations used in the pie chart and the table that appear below the timeline. In creating a pseudo timeline, this was causing an "Other" entry to show up in the legend, and passed invalid `startTime` and `durationDelta` values, they have `N-totalNumberOfTimelines` times more samples than the other timelines, and thus cannot be charted properly anyway.
How it looked before:
How it looks now:
=> fix: don't show `Other` aggregate on Tag explorer timeline

pkg/storegateway/bucket_index_metadata_fetcher.go
For backward compatibility we decided to not use on-disk cache in the metadata fetcher. It does affect performance, as metas are cached in memory.
=> fix: disable metadata fetcher on-disk cache

pkg/phlaredb/block_querier.go
Discovered by accident while running Pyroscope built with `-race`. I checked other places (`errgroup.Go` arg capturing in a loop), it seems this is the only case
=> fix: Series query race condition

public/app/pages/tagExplorer/components/TotalSamplesChart/index.tsx
Relative imports cannot be overridden.
=> fix: absolute imports for PieChart

public/app/redux/store.ts
It was noted that `?query=` would automatically be appended to the URL.
Now, `query` will only be set if there is an actual change in the query.
=> fix: prevent automatically setting blank query to url parameters

public/app/services/apps.spec.ts, public/app/services/apps.ts, public/app/services/base.spec.ts, public/app/services/base.ts, public/app/services/render.ts, public/app/services/tags.ts, public/app/services/tenant.ts
- Remove old `request`, which is virtually identical to `fetchAndHandleErrors`
- Rename `requestWithOrgID` to `request`
- Make non-imported functions in `base` not exportable
=> fix: remove `request` which is handled by `fetchAndHandleErrors`

examples/golang-push/rideshare/docker-compose.yml, examples/golang-push/rideshare/main.go, examples/golang-push/rideshare/rideshare/rideshare.go, examples/golang-push/rideshare/utility/pool.go, examples/golang-push/rideshare/utility/utility.go
Adds some environment variables to help configure the "memory leak" in the Go rideshare example.
- `PARAMETERS_POOL_SIZE` sets the max size of the pool (aka the max number of goroutines that will hang before a reset)
- `PARAMETERS_POOL_BUFFER_SIZE_KB` sets the amount of memory each goroutine will allocate in kb
=> Make rideshare golang-push memory configurable

operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
This will use a subvolume of volume `data` for the compactor instead of a separate volume. This will ensure we are able to handle persistence options in the same way for the compactor.
=> Helm: Fix persistence for compactor's data path

examples/golang-push/rideshare/utility/pool.go
In https://github.com/grafana/pyroscope/pull/2632 I added a memory leak example, but didn't properly reset the pool, causing the slice to grow unbounded and create panics when we tried to close channels that were already closed.
=> fix: Reset pool slice

pkg/phlaredb/block_querier.go, pkg/phlaredb/filter_profiles_bidi.go, pkg/phlaredb/sample_merge.go
This PR attempts to improve our tracing integration.
Some span specially `filterProfiles` were noisy and moved up, outside of the batching, we don't need a span per batch a log is enough.
I've improve some span by adding the block ULID they touch as a tag.
=> Removes noisy span and adding block ULID inside span tags

cmd/profilecli/upload.go, docs/sources/configure-server/about-server-api.md
=> Provide a default service_name label for profilecli uploads

ebpf/session_python.go, ebpf/symtab/symbols.go
Not too sure about other side effects, but I am getting errors for `make test` for a while on darwin/arm64
=> Fix build tag, so ebpf/python tests can be run on darwin

pkg/distributor/distributor.go, pkg/model/labels.go
https://github.com/grafana/pyroscope/pull/2656 introduced a regression caused by a bug in `HashWithoutLabels`: it ignores `__name__` label. I'm removing this function as it is not used anywhere and is misleading at best
=> Remove HashWithoutLabels

public/app/pages/TagExplorerView.tsx
- Corrected the dependency list and boolean check for a useEffect which resulted in an additional fetch under certain conditions
- The condition was when `groupBy` and `groupByValue` URL parameters are undefined (but everything else is defined)
=> fix: reduce redundant tag explorer fetches

pkg/querier/replication.go
A follow up to  #2586, which will make the deduplication more robust.
(All blocks should have Compaction, a compaction Level of 0 means a head blcok)
=> Make deduplication decision more robust

pkg/phlaredb/symdb/block_reader.go, pkg/phlaredb/symdb/resolver.go, pkg/phlaredb/symdb/resolver_test.go, pkg/util/refctr/refctr.go
Fixes https://github.com/grafana/pyroscope/issues/2644: the problem was that, on context cancellation, a partition could be released while still being used by resolver.
=> Fix symbols resolver race condition

pkg/phlaredb/block_querier.go
The change makes ingester to ignore blocks outside the time range on `LabelNames` call
=> Fix LabelNames block getter

docs/sources/deploy-kubernetes/helm.md
Adds a requested example for in-query URL for single binary config for the K8s Helm doc. 
Fixes: https://github.com/grafana/pyroscope/issues/2625
=> [DOC] Add in-cluster query for k8s Helm

pkg/querier/ingester_querier.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/replication.go
When a plan has been acquired, we need to make sure we do query all underlying stores. If a particular replica from one store is not part of the plan, we will eliminate this later in `forPlannedIngesters|StoreGateways(...)`.
=> Handle block plans correctly when splitToStores

operations/pyroscope/helm/pyroscope/templates/services.yaml
Closes https://github.com/grafana/pyroscope/issues/2689 by statically encoding the type to ClusterIP
This allows us to set service.Type="LoadBalancer" such that we can expose the service (and send profiles from non-Kube services)
NOTE(s):
- This PR has NOT been tested! If someone can point me to an "idiots guide to testing helm packages", rather just some way to import them locally, would be happy to
- This PR doesn't resolve my other issue of serviceAnnotations (to add the GCP LB annotations to make it an internal LB), but I'll follow that up with a separate PR and issue
=> Allow service.Type="LoadBalancer"

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/compactor/blocks_cleaner_test.go, pkg/compactor/bucket_compactor.go, pkg/compactor/bucket_compactor_e2e_test.go, pkg/compactor/bucket_compactor_test.go, pkg/compactor/compactor.go, pkg/compactor/compactor_test.go, pkg/compactor/job.go, pkg/compactor/job_test.go, pkg/compactor/split_merge_compactor.go, pkg/compactor/split_merge_grouper.go, pkg/phlaredb/compact.go, pkg/phlaredb/compact_test.go, pkg/validation/limits.go
Number of compactor split shards is limited to the number of blocks we can write concurrently. There are two significant factors:
- Symbols size in memory. Varies depending on the sharding key.
- Memory utilized by parquet writer / row group buffer. Varies depending on the row group size and contents.
I propose to compact blocks in stages to circumvent these limitations. Potentially, we can mitigate them (and we will, I believe), however we can't eliminate them.
There are multiple ways to implement staging. The PR contains the simplest of them: at compaction, we only populate limited number of output blocks (stage size), and re-read source blocks as many times as many stages specified. For example, if we have 16 blocks at input, 64 split shards, and stage size is 8, we re-read …
=> feat: compaction staging

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/values-micro-services.yaml, operations/pyroscope/jsonnet/values-micro-services.json, pkg/querier/store_gateway_querier.go, pkg/storegateway/gateway.go, pkg/storegateway/gateway_ring.go
Note: The replication factor before was always hardcoded to 3. In order
to retain same behaviour, the flag
`-store-gateway.sharding-ring.replication-factor` needs to be set on
querier and store-gateways.
=> Propagate store-gateway ring config correct

operations/pyroscope/helm/pyroscope/Chart.yaml, operations/pyroscope/helm/pyroscope/README.md, operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
This was omitted for 1.2 release.
Closes https://github.com/grafana/pyroscope/issues/2725
=> helm: release a new version for 1.2

pkg/querier/replication.go
The panics fail a query hard, when one of the assertions is not met.
With e.g changing compactor shards, it panics and fails the query. This changes behaviour, so that it instead falls back to deduplication.
This should be backported into weekly/f41
=> Fallback to deduplication when hitting problem block planning

pkg/phlaredb/block_querier.go
This will avoid to grow the `lbls` on every runs and instead copy the slice.
I also removed the safety guard which shouldn't be there and is very expensive to run.
=> Improve SelectMatchingProfiles performance

public/app/components/ChartTitle.tsx, public/app/constants/profile-metrics.json, public/app/legacy/flamegraph/FlameGraph/FlameGraphComponent/Header.tsx, public/app/legacy/flamegraph/Tooltip/Tooltip.tsx, public/app/legacy/models/units.ts, public/app/pages/ContinuousComparisonView.tsx, public/app/pages/ContinuousDiffView.tsx, public/app/pages/ContinuousSingleView.tsx, public/app/util/flamebearer.ts
In the case of (e.g.) `lock_time` profiles, the units were incorrect (count instead of ns). This is because the backend service returns `nanoseconds` as a unit, but the UI doesn't recognize it.
This PR introduces a static JSON file for describing all profile metrics and starts using it in:
- the header of the timeline
- the flamegraph
Note that a lot more work would be needed to ensure that all units/names/descriptions are always properly displayed across the application. 
|Before|After|
|---|---|
| <img width="1455" alt="Screenshot 2023-11-20 at 16 30 19" src="https://github.com/grafana/pyroscope/assets/146180665/c8f33e51-7732-4f83-a472-1d4ec8312d86">|<img width="1457" alt="Screenshot 2023-11-20 at 16 29 15" src="https://github.com/grafana/pyroscope/assets/146180665/c50f46a6-9e75-4cc5-b0a …
=> fix(Units): Fix incorrect units in the UI

operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
I noticed a bug, when setting extraArgs on a single component (`.values.pyroscope.components.querier.extraArgs`) they would completely overwrite the whole global (`.values.pyroscope.extraArgs`) array.
This change will make sure we do a merge of global and component based `extraArgs`.
=> Helm: Handle overriding extraArgs in components correctly

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/objstore/client/config.go, pkg/objstore/providers/azure/bucket_client.go, pkg/objstore/providers/azure/config.go
This PR fixes #2412 #2680 
It does that by refactoring the config to align with mimir's azure config.
It also avoids retrying for too often and too long, by lowering MaxRetries and making sure retries are done without exponential backoff. 
This depends on #2741
=> Refactor Azure bucket configs

ebpf/sd/procfs.go, ebpf/sd/target.go, ebpf/sd/target_test.go
if we have a target specific to process, we should use, even if it is in a container(instead of creating a generic container target)
=> fix(ebpf): prefer pid targets over container targets

pkg/operations/tool.blocks.detail.gohtml, pkg/operations/tool.blocks.index.gohtml, pkg/operations/tool.blocks.list.gohtml
I noticed that the entrypoint page in https://github.com/grafana/pyroscope/pull/2724 works as expected but all the links stop working when the web application is running with a different base URL (e.g., `/store-gateway/ops/object-store/...` instead of just `/ops/object-store/....`). 
This fixes the problem by resorting to relative URLs. It makes the back URLs uglier in code, but there is also less repetition overall.
=> Switch to relative links in block viewer tool

.gitignore, ebpf/cmd/playground/main.go, ebpf/pprof/pprof.go, ebpf/pprof/pprof_test.go, ebpf/python_ebpf_test.go, ebpf/session.go, ebpf/session_python.go
Regular stacktraces are agregated in ebpf program by increasing value in the ebpf maps
Python stacktraces are different, they are sent to userspace as is without any aggregation, so we may end up with multiple equal samples and values=1.
In this PR I aggregate python samples so that pprofs are smaller.
In the future we may try to aggregate python samples in ebpf (this require adding hashing function to ebpf)
=> fix(ebpf): merge equal samples

public/app/constants/profile-metrics.json, public/app/pages/TagExplorerView.tsx
|Before|After| 
|---|---|
|![image](https://github.com/grafana/pyroscope/assets/146180665/9fa0edb0-d44f-41a1-952c-783e543fc51e)| ![image](https://github.com/grafana/pyroscope/assets/146180665/1defe7bf-4722-465f-b24d-b93cf1d49ffa) |
=> refactor(TagExplorer): Human friendly metric names in the Tag Explorer page

ebpf/session.go
There was  a tiny time window when we already attach ebpf program to perf event (start profiling) and not yet attached a reader for pid info requests.
So this line some times return 2 (ENOENT) instead of 0, causing userspace program miss some processes to profile.
https://github.com/grafana/pyroscope/blob/8dc366aa5027608f62510faaa871a4f5a6397c7f/ebpf/bpf/profile.bpf.c#L50
This PR changes order of enabling profiling - start reading events first, then start profiling
=> fix(ebpf): start profiling after attaching perf reader

pkg/phlaredb/block_querier.go, pkg/querier/querier.go
The recent optimisation (https://github.com/grafana/pyroscope/pull/2813) introduced a bug where a query may result in empty response
=> fix: span query read path

pkg/distributor/distributor.go, pkg/distributor/model/push.go, pkg/distributor/model/push_test.go, pkg/ingester/pyroscope/ingest_adapter.go, pkg/ingester/pyroscope/ingest_handler_test.go, pkg/model/labels.go, pkg/og/convert/jfr/parser_suite_test.go, pkg/og/convert/jfr/pprof.go, pkg/og/convert/pprof/profile.go, pkg/pprof/pprof.go, pkg/pprof/pprof_test.go
Closes #2777 
1. If the profile has the `pyroscope_spy` label, we use it to determine the language
2. If we do need to look into the string table, we use prefix and suffix matching instead of regular expressions
Here is a summary of the gains with 2:
Regexp:
```
go.cpu.labels.pprof-10         	  330040	     10853 ns/op
heap-10                        	  195819	     18407 ns/op
dotnet.labels.pprof-10         	  143966	     24949 ns/op
profile_java-10                	   61840	     58016 ns/op
profile_nodejs-10              	  109437	     32871 ns/op
profile_python-10              	  391418	      9156 ns/op
profile_ruby-10                	  307896	     11783 ns/op
profile_rust-10                	  636633	      5668 ns/op
```
String matching (prefix or suffix):
```
go.cpu.labels.pprof-10 …
```
=> Improve language detection performance

public/app/components/ExportData.module.scss, public/app/sass/variables.css
Tweaks the grey to match grafana grey and then makes the export button not float weirdly
https://github.com/grafana/pyroscope/assets/23323466/430edb03-4422-4bf7-9da7-2e27397820c4
=> Update styling to match grafana

pkg/querier/store_gateway_querier.go
I was looking at a trace and  thought we have a bug selecting Series when asking for Flamegraph.
In fact the span name was incorrect probably from copy-pasta.
=> Fixes span name for BlockSelect from store-gateway

pkg/querier/querier.go
While looking at the ingesters memory usage in a high-load environment I noticed that a big portion of it came from `(*singleBlockQuerier) openTSDBIndex`. 
Looking at the `pyroscopedb_blocks_currently_open` metric, many ingesters have a large number of opened blocks (300+ in some cases). Narrowing that further with traces, the large number of open blocks came from requests to `LabelNames` and `LabelValues` with long query intervals. Currently these requests are served entirely by ingesters because until recently such requests didn't contain a `start` and `end` in the body (the client didn't send the range).
With https://github.com/grafana/grafana/pull/78861, clients started sending a `start` and `end` for the LabelNames and LabelValues APIs. This means we can now properly split the …
=> Fix query split logic for LabelNames, LabelValues and ProfileTypes

docs/sources/configure-client/grafana-agent/go_pull.md
https://github.com/grafana/pyroscope/issues/2773
=> docs: update go-pull.md

pkg/phlaredb/compact.go, pkg/phlaredb/compact_test.go
The file is hardlinked or fully copied and so the original file is safe to delete.
=> bugfix: Properly cleanup dst folder on compaction

pkg/compactor/bucket_compactor.go
I want to give a try to this in our largest cluster.
load vs fetch
=> feat: Only load all symbols when splitting

pkg/compactor/blocks_cleaner.go, pkg/compactor/bucket_compactor.go, pkg/phlaredb/block/block.go, pkg/phlaredb/block/block_test.go, pkg/phlaredb/block/fetcher_test.go, pkg/phlaredb/block/global_markers_bucket_client_test.go
We often log this error:
```
  | ts=2023-12-21T09:46:56.652203687Z caller=block.go:164 level=warn component=compactor component=compactor tenant=27821 msg="requested to mark for deletion, but file already exists; this should not happen; investigate" err="file 01HJ5FB5R2Z145HJPBYQB0ZBMN/deletion-mark.json already exists in bucket" |  
-- | -- | --
```
This is confusing when it's actually from recurring cleanup this is fine that multiple compactor does try to delete the same file.
=> bugfix: Warn only when deleting twice during compaction

pkg/phlare/modules.go, pkg/phlare/phlare.go
Wasn't there at first cause it was experimental but it seems to be doing good so let's add it to `all` target.
Fixes https://github.com/grafana/pyroscope/issues/2863
=> feat: Adds the compactor for the all target

pkg/scheduler/scheduler_test.go, pkg/test/integration/helper.go
When the firewall is enabled in MacOS, some tests that involve networking will trigger the firewall popups. Allowing or denying the connections has a temporary effect, once the binary changes the popups are back.
This change makes it so that we listen to 127.0.0.1 in networking tests, which should avoid the popups entirely for most developers.
=> Listen on 127.0.0.1 in tests to avoid firewall popups on MacOS

docs/sources/configure-client/grafana-agent/ebpf/_index.md
We recently did a YouTube short on what is ebpf (1 minute).  This is optional for docs users but lets them get more info if they wish.
Full link to video:  https://www.youtube.com/shorts/UX5aeL5KeZs
=> add 1 min youtube short video on ebpf

Makefile
This uses a wildcard target to cleanup subsequent go.mods. I was looking into #2605 before realising we removed it in main 😆
=> chore: Makefile cleanup go.mod tidying

operations/pyroscope/helm/pyroscope/Chart.yaml, operations/pyroscope/helm/pyroscope/README.md, operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml, operations/pyroscope/helm/pyroscope/templates/NOTES.txt, operations/pyroscope/helm/pyroscope/templates/_helpers.tpl, operations/pyroscope/helm/pyroscope/templates/configmap-agent.yaml, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml, operations/pyroscope/helm/pyroscope/values.yaml, operations/pyroscope/jsonnet/values.json
Hello grafana pyroscope team!
This PR fix used FQDN with hardcoded domain `cluster.local`.  
Main idea - don't use FQDN if you deploy resources, use svc short names.
=> fix FQDN to short names

operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/values-micro-services.yaml, operations/pyroscope/jsonnet/values-micro-services.json, pkg/compactor/bucket_compactor.go
I've seen traces where it took 10m to compact. When we rollout a new version  it can get cancelled in the upload and deletion which is usually less than 2m.
I think we should leave a grace period for uploads and marking blocks deleted.
=> feat: Improve compaction shutdown

pkg/storegateway/query.go
Currently store-gateways are panicing if profile types are not found.
=> Handle profile types call properly without bucket store

pkg/ingester/retention.go, pkg/ingester/retention_test.go
Fixes https://github.com/grafana/pyroscope/issues/2915
Some file systems will create a `lost+found` directory. This will never contain data relevant to Pyroscope, so we should skip inspecting this directory.
More generally, this skips any directory that doesn't have a `local` subdirectory.
=> fix: Skip non-tenant directories during block cleanup

pkg/phlaredb/compact_test.go
Trying to run it today and found a panic, logger was missing, probably during a refactoring
=> bugfix: Fixes panic in compaction benchmark

pkg/phlaredb/block_querier.go, pkg/phlaredb/profile_store.go
Page sizes for parquet files tent to be larger than the current read buffer which results in more page reads than ideal. This change increases the size from 256KB to 2MB. In tests against a GCS backed storage this yields around 5-10% improved response time for the `SelectMergeByStacktraces` API and in a synthetic test with higher latencies towards the object store gains of up to 20% can be observed.
@cyriltovena
=> Increase parquet read buffer size

Makefile
Make deploy manually creates a service to have the same endpoint for
single-binary and micro-services, which then interferes with the next
deployment of microservces.
=> Fix deploying `make deploy-micro-services` after `make deploy`

ebpf/go.mod, ebpf/go.sum
=> Use api/v0.4.0 after releasing it with connect-go

api/gen/proto/go/ingester/v1/ingester_vtproto.pb.go, api/gen/proto/go/ingester/v1/ingesterv1connect/ingester.connect.go, api/gen/proto/go/storegateway/v1/storegateway_vtproto.pb.go, api/gen/proto/go/storegateway/v1/storegatewayv1connect/storegateway.connect.go, api/ingester/v1/ingester.proto, api/storegateway/v1/storegateway.proto, pkg/querier/ingester_querier.go, pkg/querier/querier.go, pkg/querier/querier_test.go, pkg/querier/store_gateway_querier.go
This will allow us to remove the ProfileType endpoints from Ingesters and store-gateways in release v1.4 or later
=> Use LabelValues for ProfileTypes call in querier

docs/sources/configure-client/aws-lambda.md
Presently, we don't distribute Lambda layers tailored to specific runtimes, therefore users have to manage SDK dependency on their own.
While AWS offers comprehensive guidance on this, it might be worthwhile for us to consider packaging our SDKs as layers. Please refer to [AWS Distro for OpenTelemetry](https://aws-otel.github.io/docs/getting-started/lambda) (ADOT) for example. Created a separate issue: https://github.com/grafana/pyroscope-lambda-extension/issues/34
/cc @Rperry2174 @knylander-grafana
=> docs(lambda): AWS Lambda extension SDK support

docs/sources/configure-client/grafana-agent/go_pull.md
The Pyroscope.write block in the river config didn't next the `basic_auth` block within the endpoint block.
=> Correct river config in go_pull.md

docs/sources/release-notes/v1-2.md, docs/sources/release-notes/v1-3.md
Cherrypick https://github.com/grafana/pyroscope/pull/2949 release notes from main to the v1.3 branch.
=> [DOC] Add 1.3 release notes for docs (#2949)

pkg/storegateway/bucket_index_metadata_fetcher.go
=> Store-gateway: Handle index read error properly

pkg/operations/admin.go, pkg/operations/handlers.go, pkg/operations/handlers_test.go, pkg/operations/model.go, pkg/operations/tool.blocks.list.gohtml, pkg/phlare/modules.go
The code assumed MinTime is aligned to 0 seconds, but we've found a case where this is not the case. This could happen due to clock-skew on a node, or code-related factors. 
The assumption is now changed to be aligned to either 0 or 30 minutes instead. 
cc. @cyriltovena
=> Improve block grouping in admin block viewer

pkg/phlaredb/symdb/dedup_slice.go
Previously `HasLineNumber` in `mappingsKey` used the value of `HasFunctions`. This appears to not have caused correctness problems, but this PR fixes it anyways to avoid subtle bugs in the future.
=> fix: Use correct field in `mappingsKey`

pkg/iter/batch_async.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/head_queriers.go, pkg/phlaredb/query/iters.go
The PR addresses one of the issues with data streaming in the block read path: when we select profile rows for filtering (by profile series ID and the query time range) we synchronously collect the list of filtered profiles, blocking the data flow. This behaviour has been changed so that filtered profiles are passed down to the stream in batches, asynchronously.
It's not expected that the overall query performance will improve in all cases. Usually the delay caused by the described blocking is very small and does not have impact on the overall query latency and/or resource consumption. However, it may be helpful with huge datasets of high cardinality.
=> feat: async profile row iterator

Makefile
This fixes a problem when deploying using `make deploy-microservices`:
```
❯ make deploy-micro-services
[...]
Error: UPGRADE FAILED: error validating "": error validating data: kind not set
make: *** [Makefile:403: deploy-micro-services] Error 1
```
A bit shameful but it needed a `git bisect` to find this.
=> Remove tenant settings from microservices deploy

operations/pyroscope/helm/pyroscope/templates/servicemonitor.yaml, operations/pyroscope/helm/pyroscope/templates/services.yaml
Add label to headless service fix double scraping of metrics with service monitor
=> fix: Double scraping with servicemonitor due to headless service

pkg/frontend/frontend_select_merge_span_profile.go, pkg/frontend/frontend_select_merge_stacktraces.go
Starting from Go 1.21.0, type parameters are part of the function name in pprof, which often makes them unreadable
The change reverts https://github.com/grafana/pyroscope/pull/2343 (replaces Go type parameters with ellipses `[...]`) as it makes it impossible to find the selected node in the source profile in backend (needed for #2228, and #2727 and https://github.com/grafana/pyroscope-app-plugin/issues/207).
The presentation aspects are to be managed on the frontend. Ideally, there should be an option for user to disable all the decorations. Note that a function name change usually causes changes in the tree/flamegraph structure, which we used to [fix](https://github.com/grafana/pyroscope/blob/main/pkg/model/tree.go#L161). I believe we don't have to do this.
=> fix: disable Go names decoration

public/app/app.tsx, scripts/webpack/webpack.common.js, scripts/webpack/webpack.dev.js
Fixes #2978
This was made possible with https://github.com/grafana/grafana/pull/76191. Alternatively we could just point to the Grafana CDN, but icons take longer to load and we it adds a runtime dependency.
=> Fix missing icon assets

pkg/phlaredb/downsample/downsample.go
Addresses "unsupported value type" in 
`ts=2024-02-09T13:13:02.072918921Z caller=downsample.go:162 level=debug component=compactor component=compactor msg="flushing downsampled profile" interval="unsupported value type" aggregation="unsupported value type" sourceProfileCount=20 sampleCount=250`
=> Fix downsampler debug log message

examples/php/php-fpm/docker-compose.yml
According to docker-compose file host for php-fpm should be `php` instead of `pyroscope_php-fpm`.
=> Fix invalid php-fpm host

pkg/pprof/merge.go, pkg/pprof/merge_test.go
Introduced in https://github.com/grafana/pyroscope/pull/3010/files#diff-1716fbe09b95462c58b96e3abdc3b60585159cad6f026e731598ca62859ea5e5R49
When we insert an empty profile we still would consider the next one as new and rewrite string from the original twice.
This has caused the pprof API to fail recently.
cc @bryanhuhta @grafakus 
Sneaky one !
=> Fixes merge of empty samples in pprof

pkg/phlaredb/block_querier.go, pkg/phlaredb/sample_merge.go
This change forces block querier to wait until all outgoing queries to finish at `Close` call. Resolves https://github.com/grafana/pyroscope/issues/2845
The solution does not completely address the issue of block ownership. Since our queries involve stateful processes (block iteration + series iteration + deduplication + merge), and our replicas (ingesters and store gateways) lack awareness of the query context, there is a possibility that a block may be closed while the query is still running. This occurs because replicas may not retain any references to the block in-between query stages.
For instance, if a block is evicted immediately after the list of replica blocks has been returned to the querier, attempting to retrieve profiling data from the block will result in an empty response. …
=> fix: wait for ongoing queries to finish at close

public/app/pages/TagExplorerView.tsx, public/app/pages/tagExplorer/components/ExploreHeader.tsx
A small refactor to extract `<ExploreHeader />`.
=> refactor(TagExplorer): Extract ExploreHeader component

pkg/pprof/fix_go_heap_truncated.go
After testing #3014 with more data, I discovered a case when an attempt to restore the profile may result in excessive CPU usage, and possibly an infinite loop. In the PR I improve handling of edge cases and add a protection from recursive references.
=> fix: do not repair Go profiles with deeply recursive stacks

docs/internal/RELEASE.md
This clarify our release docs and also adds a note about the backport label requried for automated backports.
=> internal-docs: Add note about backports

ebpf/cmd/playground/main.go
Find this quite useful, when debugging things.
=> ebpf: Public PID and EXE labels for debugging

examples/language-sdk-instrumentation/nodejs/express-pull/Dockerfile, examples/language-sdk-instrumentation/nodejs/express-pull/agent.config.river, examples/language-sdk-instrumentation/nodejs/express-pull/docker-compose.yml, examples/language-sdk-instrumentation/nodejs/express-pull/package.json, examples/language-sdk-instrumentation/nodejs/express-pull/yarn.lock, examples/language-sdk-instrumentation/nodejs/express-ts/Dockerfile, examples/language-sdk-instrumentation/nodejs/express-ts/package.json, examples/language-sdk-instrumentation/nodejs/express-ts/yarn.lock, examples/language-sdk-instrumentation/nodejs/express/Dockerfile, examples/language-sdk-instrumentation/nodejs/express/package.json, examples/language-sdk-instrumentation/nodejs/express/yarn.lock, package.json, yarn.lock
Updates pyrsocope-nodejs to latest version and it also fixes a small bug in nodejs memory scraping example express-pull.
=> Upgrade pyroscope-nodejs to v0.2.9

docs/sources/configure-client/_index.md, docs/sources/configure-client/go-span-profiles.md
Backport 87423e4c3f2c7a21323d8e9290220c382350c5fb from #3028
---
This PR does two things: 
* Corrects capitalization for Grafana Agent and makes some minor edits outlined in #2771. 
* Updates the Span Profiles doc and adds a link to the Traces to profiles doc in the Pyroscope documentation
Fixes https://github.com/grafana/pyroscope/issues/2771
=> [release/v1.4] [DOC] Update Configure the client and span profiles doc

docs/sources/configure-client/trace-span-profiles/_index.md, docs/sources/configure-client/trace-span-profiles/go-span-profiles.md, docs/sources/configure-client/trace-span-profiles/java-span-profiles.md, docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md, docs/sources/view-and-analyze-profile-data/profile-tracing/traces-to-profiles.md
Backport 91df6b0691211416a5e3a274dce906939258af90 from #3063
---
Adds span profiles docs for java and ruby. Also first attempt at nesting them under a folde
=> [release/v1.4] docs: Add additional span profiles docs

pkg/ingester/retention.go, pkg/phlaredb/block_querier.go, pkg/querier/replication.go, pkg/querier/replication_test.go
Fixes #3088.
The problem manifests when compactor does not keep up with the ingestion rate, and store-gateways load sharded L2 blocks (with duplicates).
Normally, L3 blocks supersede all the parent blocks in the query plan, and presence of L2 blocks does not pose any issues. However, when an L3 shard is incomplete, all its blocks are removed from the plan before this step, preserving L2 shards in the query plan (partial shards are ignored in the plan). This happens, when L3 compaction delay exceeds `blocks-storage.bucket-store.ignore-blocks-within`. The way query plan is built expects that L2 blocks do not contain duplicate series, which is not true if blocks are shared. As a result, query returns duplicated data.
=> fix: query plan optimisation

pkg/phlaredb/head_queriers.go, pkg/phlaredb/head_test.go, pkg/phlaredb/profile_store.go
=> fix: head data duplication

docs/sources/configure-client/trace-span-profiles/_index.md, docs/sources/configure-client/trace-span-profiles/go-span-profiles.md, docs/sources/configure-client/trace-span-profiles/java-span-profiles.md, docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md
Fixes a missing period in the Span profiles doc. Also, minor wording fixes in the links.
=> [DOC] Fix minor issues in Span profiles doc

examples/language-sdk-instrumentation/rust/basic/Cargo.lock, examples/language-sdk-instrumentation/rust/rideshare/server/Cargo.lock
Supersedes relevant dependabot's PRs
=> chore: update rust example dependencies

pkg/model/tree.go
This is a pretty obvious optimization that we should have implemented much earlier. This function may contribute up to 25% of the total query CPU time in rare cases. The larger the tree, the more significant the benefit.
=> perf: optimize tree node insertion

examples/tracing/tempo/README.md, examples/tracing/tempo/docker-compose.yml
The tracing integration feature has been released a long time ago, but in the demo we're still building the pyroscope image locally, which might be challenging for users
=> chore: use pyroscope:latest in tracing integration demo

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, docs/sources/configure-server/reference-configuration-parameters/index.template, pkg/phlare/phlare.go
In production environments, users may not want the banner to be printed because doesn't conform to any logging format, which can muddle logs. This PR adds a flag which allows users to disable printing the banner.
=> feat: Add flag to disable printing banner

docs/sources/release-notes/v1-4.md, docs/sources/release-notes/v1-5.md
=> Add release notes for v1.5

pkg/util/disk/disk.go
Hi folks 👋🏻 
I was looking into putting together a FreeBSD port of Pyroscope, and encountered the following compilation issue as I was building it. I hope you find this useful 🙇🏻 
On FreeBSD, the struct returned by the [fstat syscall](https://man.freebsd.org/cgi/man.cgi?statfs(2))'s `f_bavail` field is represented as an `int64`, rather than a `uint64` like on linux and macos platforms.
As a result, comparisons such as ` stat.Bavail * uint64(stat.Bsize)` won't compile on FreeBSD, as it would lead to applying a multiplication between a signed and unsigned 64-bit integer.
This commit refactors the logic of computing the disk available bytes and the percentage available to cater to OS differences. Note that I chose this approach as opposed to having a dedicated `disk_freebsd.go` file with a …
=> Adapt disk util to FreeBSD

examples/grafana-agent-auto-instrumentation/java/README.md
Updates grafana agent java example to have some more details explaining what the example actually does and how it works
=> docs: Update grafana agent java example readme

docs/sources/configure-client/grafana-agent/ebpf/setup-linux.md, docs/sources/configure-client/grafana-agent/go_pull.md, examples/grafana-agent-auto-instrumentation/ebpf/k8s/config.river
The component [`discovery.relabel`](https://grafana.com/docs/agent/latest/flow/reference/components/discovery.relabel/) exports a label [`output`](https://grafana.com/docs/agent/latest/flow/reference/components/discovery.relabel/#exported-fields), but some code examples are trying to get `targets` field instead and failing.
This PR fixes such invalid references.
=> docs: Fix invalid references to `targets` in discovery.relabel

pkg/phlare/phlare.go, pkg/test/integration/cluster/cluster.go, pkg/test/integration/microservices_test.go
I am currently trying to understand some behaviour while running with an unhealthy ingester/store-gateway each.
For this purpose I've  create this testing helper that can spin up multiple microservices locally.
=> Add integration testing of microservices/replication for label queries

cmd/profilecli/upload.go
Usage `profilecli upload --override-timestamp cpu.pprof`
=> Add an option to override the profile timestamp before upload

.github/workflows/e2e.yaml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/test_ebpf.yml, .github/workflows/weekly-release.yml, .goreleaser.yaml, examples/golang-pgo/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/simple/Dockerfile
```
http2: close connections when receiving too many headers
Maintaining HPACK state requires that we parse and process all HEADERS and CONTINUATION frames on a connection. When a request's headers exceed MaxHeaderBytes, we don't allocate memory to store the excess headers but we do parse them. This permits an attacker to cause an HTTP/2 endpoint to read arbitrary amounts of header data, all associated with a request which is going to be rejected. These headers can include Huffman-encoded data which is significantly more expensive for the receiver to decode than for an attacker to send.
Set a limit on the amount of excess header frames we will process before closing a connection.
Thanks to Bartek Nowotarski (https://nowotarski.info/) for reporting this issue.
This is CVE-2023-45288 and Go …
```
=> Update golang version to 1.21.9

.goreleaser.yaml
The last release (https://github.com/grafana/pyroscope/releases/tag/v1.5.0) had some documentation updates included in its changelog . This happened because we exclude commits that start with `docs:` and this exclusion didn't cover all documentation updates.
I personally don't mind having documentation updates in release changelogs but would be curious to see how others feel. 
Thanks @simonswine for pointing out the root cause.
=> Include documentation updates in generated changelogs

examples/language-sdk-instrumentation/golang-push/migrating-from-standard-pprof/README.md
This adds a link that shows people an example of how to use pprof + pyroscope sdk simultaneously. This is mostly so that we have easy access to a link to direct people to. I would say in most cases this is an edge case.
=> docs: Add link to use pprof and go sdk simultaneously

ebpf/symtab/table.go, ebpf/symtab/table_test.go
It is more appropriate for `SymTab` and `Sym` structures to be separated into test files since they are only used in tests, not in general code.  Additionally, adding the `Mock` prefix will clearly indicate to other developers that these structures are intended for testing purposes only, reducing the potential for confusion.
Therefore, I propose moving these two structures to test files and renaming them.
=> chore: Move mock struct to test file

go.mod, pkg/test/integration/cluster/cluster.go
This adds a health check for the write path before pushing profiles. (Saw flakes based on this)
It also moves listening to `127.0.0.1` in order to avoid this dialogue:
=> integration: Check distributor health before push

examples/grafana-agent-auto-instrumentation/ebpf/k8s/config.river
```
Error: /etc/agent/config.river:61:47: field "targets" does not exist
60 |     forward_to = [pyroscope.write.endpoint.receiver]
61 |     targets = discovery.relabel.specific_pods.targets
|                                               ^^^^^^^
62 | }
ts=2024-03-21T16:17:33.064918553Z level=error msg="failed to start reporter" err="context canceled"
interrupt received
Error: could not perform the initial load successfully
```
=> [documentation] update config.river sample for k8s ebpf use case

pkg/phlaredb/symdb/resolver_pprof_truncate.go
I have not gotten to the bottom of why the mapping ID is missing when
maxNodes!=0.
This is presenting a workaround until we full understand the issue.
Fixes #3164
=> Fix panic when dealing with missing mapping ID

pkg/pprof/merge.go
Fixes #3197
The issue was that empty `ValueType` values (both period type and sample type) were used in the pprof response along the read path as they added after the profile merge. An empty `ValueType` references string with index 0, assuming that the value is `""`. However, in practice, we cannot guarantee that it's always true, which leads to period/sample type mismatches in rare cases.
This was necessary in the past because the original `profile.Merge` verified the compatibility of profiles. Now that we have our own specialized pprof merge, this is no longer needed. The fix ensures that empty `ValueType` is ignored during the merge. I believe this could be further simplified by removing the stubs entirely. Although a quick attempt revealed that this would require quite a few changes, …
=> fix: pprof export incompatible period types

cmd/profilecli/main.go, cmd/profilecli/tsdb.go
This is useful connecting SeriesIndex to the one in profiles.parquet.
```
❯ go run ./cmd/profilecli admin tsdb series ./my-block/index.tsdb
{"SeriesRef":247850,"SeriesIndex":16992,"Labels":{"__name__":"process_cpu","__period_type__":"cpu","__period_unit__":"nanoseconds","__profile_type__":"process_cpu:cpu:nanoseconds:cpu:nanoseconds", ...}}
[...]
```
=> Add profilecli command to dump the tsdb index

pkg/phlaredb/schemas/v1/profiles.go, pkg/phlaredb/schemas/v1/profiles_test.go, pkg/phlaredb/symdb/resolver.go, pkg/pprof/merge.go
It's been discovered that some of the persisted profiles may contain invalid samples (stack trace ID == 0). As an immediate fix, such samples should be discarded, as further processing does not expect "empty" stack traces. This has led to numerous cryptic failures (#3164 and #2377, for example).
We should also ensure that such profiles are discarded before they gets writtien to the block (see #3194)
=> fix: discard invalid samples at read

docs/sources/configure-client/_index.md, docs/sources/configure-client/grafana-agent/_index.md, docs/sources/configure-client/grafana-agent/ebpf/_index.md, docs/sources/configure-client/grafana-agent/ebpf/setup-docker.md, docs/sources/configure-client/grafana-agent/ebpf/setup-kubernetes.md, docs/sources/configure-client/grafana-agent/ebpf/setup-linux.md, docs/sources/configure-client/grafana-agent/java/_index.md
With the release of Grafana Alloy, we're adding an admonition to the Agent-related documenation notifying people about Alloy and the deprecation of Agent.
This admonition is contained in a shared file that is in the Alloy repository. When used, the admonition looks like this:
=> [DOC] Add note for Agent to Alloy to docs

pkg/pprof/merge.go, pkg/pprof/merge_test.go
This fixes a bug in handling 0 references to mappings, locations and functions.
See also #3203
=> Handle zero references when merging

operations/pyroscope/helm/pyroscope/templates/ingress.yaml
The backend Service is no longer available as it was removed in #2922.
Honestly, I don't know what it was in detail but the PR said the service is not relevant when running outside of Grafana Cloud so I believe this ingress path setting can be removed as well.
=> Remove tenant-settings from Ingress

.github/workflows/fuzzer.yml, pkg/pprof/merge_test.go
Not too sure if there is a better/more performant way of doing that. But this also uncovered a few cases already 🙂
=> Implement fuzzer for Merge_Single

docs/sources/configure-client/grafana-agent/ebpf/setup-linux.md, docs/sources/configure-client/grafana-agent/go_pull.md, examples/grafana-agent-auto-instrumentation/ebpf/k8s/config.river
Backport 65be0e07d548a7f6e048fb419f9a0c8f58bb9465 from #3153
---
The component [`discovery.relabel`](https://grafana.com/docs/agent/latest/flow/reference/components/discovery.relabel/) exports a label [`output`](https://grafana.com/docs/agent/latest/flow/reference/components/discovery.relabel/#exported-fields), but some code examples are trying to get `targets` field instead and failing.
This PR fixes such invalid references.
=> [release/v1.5] docs: Fix invalid references to  in discovery.relabel

ebpf/session.go, ebpf/symtab/elf.go, ebpf/symtab/elf/symbol_table.go, ebpf/symtab/elf_cache.go, ebpf/symtab/gcache.go, ebpf/symtab/proc.go
Noticed this as part of https://github.com/grafana/alloy/pull/678
=> Ensure the ebpf debug info supports both river and alloy

docs/sources/configure-client/trace-span-profiles/_index.md, docs/sources/configure-client/trace-span-profiles/python-span-profiles.md, examples/language-sdk-instrumentation/python/rideshare/flask/Dockerfile, examples/language-sdk-instrumentation/python/rideshare/flask/lib/server.py, examples/tracing/tempo/docker-compose.yml
- enables OpenTelemetry based tracing in the Python ride share Flask example
- adds the Python ride share Flask app to examples/tracing/tempo, to demonstrate span profiles in Python
- adds docs for Python span profiles
=> Example and docs for Python span profiles

ebpf/sd/target.go, ebpf/session.go
This is something that would be nice to test, but I guess we don't want to get into circular dependecies with alloy :cry:
I also migrated the targets to be fully structured, so they display better than:
=> Fix debug info attribute

docs/sources/configure-client/trace-span-profiles/_index.md, docs/sources/configure-client/trace-span-profiles/python-span-profiles.md, examples/language-sdk-instrumentation/python/rideshare/flask/Dockerfile, examples/language-sdk-instrumentation/python/rideshare/flask/lib/server.py, examples/tracing/tempo/docker-compose.yml
Backport 960fc3221b738f4cf374ffa29ae3528588435313 from #3252
---
- enables OpenTelemetry based tracing in the Python ride share Flask example
- adds the Python ride share Flask app to examples/tracing/tempo, to demonstrate span profiles in Python
- adds docs for Python span profiles
=> [release/v1.5] Example and docs for Python span profiles

pkg/pprof/fix_go_profile.go, pkg/pprof/merge.go, pkg/pprof/merge_test.go
`pprof.MergeNoClone` has particularly tricky semantics which is very easy to misuse: specifically, it may cause duplication of samples. Although the function is significantly cheaper than `pprof.Merge` and can be fixed, I think it's better to deprecate it in favour of safety
=> fix: deprecate pprof MergeNoClone

docs/sources/configure-server/configure-object-storage-backend.md
Making sure it's less likely that people use `grafana-pyroscope-data` as their bucket name.
=> docs: improves S3 example config

docs/sources/configure-client/grafana-agent/ebpf/setup-docker.md, docs/sources/configure-client/grafana-agent/ebpf/setup-kubernetes.md, docs/sources/configure-client/grafana-agent/ebpf/setup-linux.md, docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md, docs/sources/configure-client/trace-span-profiles/go-span-profiles.md, docs/sources/configure-client/trace-span-profiles/java-span-profiles.md, docs/sources/configure-client/trace-span-profiles/python-span-profiles.md, docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md, docs/sources/view-and-analyze-profile-data/_index.md
Something seems to have changed to the place where pyroscope grafana-cloud docs are.
=> docs: Fix some broken links

docs/sources/configure-client/language-sdks/dotnet.md
This adds some instructions how to make sure profiling is working in dotnet 8.
See https://github.com/dotnet/runtime/issues/96227
=> docs: Add note about environment variable `DOTNET_EnableDiagnostics`

pkg/querier/vcs/service.go, pkg/querier/vcs/token.go, pkg/querier/vcs/token_test.go
Currently we use the same global session encryption secret, for each tenant. In order to ensure tenant isolation, this change will derive a custom secret per tenant.
By using sha256 we also increase the secret used for encryption from 128bit to 256bit, while allowing to get an arbitrary secret specified. 
Note: This change will require all users to re-authenticate, as the the previous GitSession won't be decrypted by this. It is possible to implement this without this breaking change, but given session length is 8 hours, I rather would re-authenticate instead.
=> vcs: Derive per tenant key

pkg/util/http.go
This makes it easier to parse by logfmt and log size is useful to understand distribution of traces
=> Use logfmt for http request logs and collect request size

examples/language-sdk-instrumentation/nodejs/express-pull/index.js, examples/language-sdk-instrumentation/nodejs/express-pull/package.json, examples/language-sdk-instrumentation/nodejs/express-pull/yarn.lock, examples/language-sdk-instrumentation/nodejs/express-ts/index.ts, examples/language-sdk-instrumentation/nodejs/express-ts/package.json, examples/language-sdk-instrumentation/nodejs/express-ts/yarn.lock, examples/language-sdk-instrumentation/nodejs/express/package.json, examples/language-sdk-instrumentation/nodejs/express/yarn.lock
This was required to support node v22 and to get rid of upstream pprof in favour of datadog/pprof
=> examples: Update pyroscope-nodejs integration

examples/tracing/tempo/README.md
Just fix the link for the `spanprofiler` application in the examples.
=> Fix link to spanprofiler

Makefile, api/go.mod, api/go.sum, cmd/profilecli/query.go, cmd/profilecli/upload.go, ebpf/cmd/playground/main.go, ebpf/go.mod, ebpf/go.sum, go.mod, go.sum, go.work.sum, pkg/api/api.go, pkg/api/connect/codec.go, pkg/api/connect/connect.go, pkg/clientpool/store_gateway_client_pool.go, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/phlaredb/phlaredb_test.go, pkg/querier/grpc_handler.go, pkg/querier/grpc_roundtripper.go, pkg/querier/querier.go, pkg/querier/store_gateway_querier.go, pkg/test/integration/cluster/cluster.go, pkg/test/integration/helper.go
This implements a custom codec for use with connect-go. It uses the vtproto provided methods UnmarhsalVT rather than the upstream protobuf decoder/encoder.
=> Connect: Use custom codec for vtproto

Makefile, pkg/api/connect/compression.go, pkg/api/connect/connect.go
Now that we have shared options between all connect Handlers/Clients it is easy to swap out compress/gzip with klauspost/compress/gzip.
At the same time this makes sure that all handlers and clients use the same compressor pool. Otherwise every new handler and client maintains its own pool (And we create a lot of clients dynamically).
Relies on the work of #3310
=> connect: Use klauspost/compress/gzip decompression

pkg/frontend/frontend.go, pkg/frontend/frontend_diff_test.go, pkg/frontend/frontend_select_merge_stacktraces.go
This fixes a panic, that could happen when one of the query results in the diff are empty.
Also adds some more coverage to the Diff handler in the frontend.
Note: We should pull this into f68.
=> Fix bug in query frontend diff handling

pkg/querier/timeline/calculator.go, pkg/querier/timeline/calculator_test.go
In Grafana's native Explore Profiles view, the default step is 15 seconds. This is only used when the data source doesn't supply a configured min step:
https://github.com/grafana/grafana/blob/24d65fa32f6ba7af3dc2e0ffa115c64aa7c97184/pkg/tsdb/grafana-pyroscope-datasource/query.go#L71-L87
=> Align default step for /render with Grafana

pkg/querier/analyze_query.go, pkg/querier/analyze_query_test.go, pkg/querier/querier_test.go, pkg/querier/replication.go
In standalone mode the ingester and store-gateway are represented with the same replica address. This doesn't cause real issues in the query path (the same physical block plan is re-used for both query paths), however it does impact query analysis because we end up including one of the paths only.
Not sure if this would break something else, but seems fairly safe to me.
=> Improve block plan creation for standalone binary mode

pkg/querier/vcs/github.go, pkg/querier/vcs/service.go
The first request the UI makes when interacting with the GH integration is to call `/GithubApp`. This change has that endpoint verify the server is configured correctly to support the GH integration feature. If it isn't it will return an "unimplemented" error.
=> Return error when GH configuration is missing

pkg/validation/validate.go, pkg/validation/validate_test.go
We're currently using [prometheus](https://prometheus.io/docs/concepts/data_model/) data model for labels (including those that are set as pprof tags) for consistency with other products:
> Labels may contain ASCII letters, numbers, as well as underscores. They must match the regex [a-zA-Z_][a-zA-Z0-9_]*.
Although we can not easily loosen the requirement, I'm not very sure if discarding profiles that violate it is the best strategy.
There is ongoing work on support for UTF-8 labels in Prometheus: 
https://github.com/prometheus/prometheus/issues/13095:
> OTel allows UTF-8 in label names while Prometheus has a much [more restrictive set](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels). This is causing friction for users when using Prometheus. In particular, . (dot) …
=> chore: support dots in label names

pkg/phlaredb/filter_profiles_bidi.go
We seem to ignore errors during the filterProfiles deduplication, at the stage when we received the decisions if something should be kept or not.
=> Fix error handling in filterProfiles

cmd/profilecli/tsdb.go, cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/model/labels.go, pkg/model/labels_test.go, pkg/phlaredb/head.go, pkg/phlaredb/head_test.go, pkg/phlaredb/labels/labels.go, pkg/phlaredb/labels/labels_test.go, pkg/phlaredb/schemas/v1/testhelper/profile.go, pkg/phlaredb/tsdb/index.go, pkg/validation/limits.go
Series order determines the physical placement of profiling data in blocks. It has been observed that the standard prometheus label and series order is not aligned with our access patterns, leading to an increase in the read amplification factor and query latency.
The PR proposes an option to enforce the optimized order. The main access pattern is a query that targets a specific profile/sample type of a specific service, therefore we want all the profiles matching such query to be stored sequentially. To achieve this, we ensure that the first labels of any series are `__profile_type__` and `__service_name__`.
The change should be applied with great caution. Since we can only enforce the order in ingesters (`__profile_type__` is not available in distributors), we need to ensure that all …
=> feat: optimize series order

.github/workflows/weekly-release.yml, .goreleaser.yaml, Makefile
goreleaser 2.0 has been released and brought some nice but incompatible changes: https://github.com/grafana/pyroscope/actions/runs/9441815396/job/26003085405
The change is already in weekly/f70: https://github.com/grafana/pyroscope/actions/runs/9443073885
=> fix: goreleaser compatibility issue

operations/pyroscope/helm/pyroscope/rendered/micro-services-hpa.yaml, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
ArgoCD cannot handle a disagreement in replica count between a Deployment/Statefulset definition and HorizontalPodAutoscaler definition. When an HPA is enabled, it is better to omit the replicas field on the Deployment/StatefulSet and let the HPA manage it instead
=> Omit replicas for components with HPA enabled

pkg/model/stacktraces.go, pkg/model/tree.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/block_querier_test.go, pkg/phlaredb/compact_test.go, pkg/phlaredb/head_queriers.go, pkg/phlaredb/sample_merge.go, pkg/phlaredb/sample_merge_test.go, pkg/phlaredb/symdb/resolver.go, pkg/phlaredb/symdb/resolver_tree.go, pkg/phlaredb/symdb/resolver_tree_test.go, pkg/storegateway/bucket_stores_test.go
The PR is aimed at optimizing the way we resolve a tree from stack traces at read.
Specifically, I replaced the `model.Tree` with `model.StacktaceTree` that we've optimized for pprof symbolication.
---
Here is a comparison of queries that build a flame graph that includes 3M unique stack traces, and 10M nodes (real-case dataset) in a singe thread: 
```
Before    	       9615096375 ns/op	4244433576 B/op	26203002 allocs/op
After    	       3626939417 ns/op	1399753624 B/op	  497736 allocs/op
```
The improvement is appx. 60% (9.6s -> 3.8s). In the test, I used the default 16k max nodes limit. However, even without the limit (tested on ~1-10M node trees), the performance is sustainable:
```
goos: darwin
goarch: arm64
pkg: github.com/grafana/pyroscope/pkg/phlaredb/symdb …
```
=> perf: optimize tree resolve

pkg/distributor/distributor.go, pkg/model/labels.go, pkg/model/labels_test.go
The recently added series order optimization (#3345) has a bug, leading to invalid `group by` results. The cause is that `BytesWithLabels` assumed the standard order. The requirement has been relaxed: this makes the function less efficient, but not to the extent that it is a concern.
Also cleaned up the package a bit.
=> fix: group by with enforced labels order

pkg/iter/batch_async.go, pkg/phlaredb/query/repeated.go, pkg/phlaredb/query/util.go
It's been observed that the async batch iterator we're using for fetching Parquet rows might be using too much memory. Note the `query.CloneParquetValues` call under `iter.(*AsyncBatchIterator[...]).fillBuffer` in the flame graph:
The problem manifests when the query hits downsampled (aggregated) profiles: a row may contain thousands of values. Another factor is the misalignment of the query split interval and the block duration: each sub-range is processed independently, with its own iterator, thus multiplying the memory requirement.
In practice, a large buffer is not required here, as it is only needed to avoid waiting for fetches from individual columns by reading the data from them ahead of time. In turn, each of the columns has it's own "read ahead" buffer, which should minimaize …
=> perf: tune async batch iterator

pkg/model/labels_test.go, pkg/phlaredb/labels/labels.go, pkg/phlaredb/phlaredb_test.go, pkg/phlaredb/tsdb/index/index.go, pkg/phlaredb/tsdb/index/index_test.go
Manual backporting of https://github.com/prometheus/prometheus/pull/12505. Thanks @pracucci!
I only wonder why it took so long to surface.
=> fix: infinite loop in index writer

pkg/phlaredb/symdb/partition_memory.go
=> fix: remove unused stacktracesPartition.header field

cmd/profilecli/client.go, cmd/profilecli/query.go
Follow up to #3368, it looks like the default protocol value (`grpc`) breaks many commands (the canary exporter, upload, ...). 
cc @simonswine
=> Change protocol default for profilecli

pkg/api/api.go
This will ensure that the backend reports 404s for wrong paths.
=> UI: Only mount UI index at known paths

cmd/profilecli/main.go, cmd/profilecli/query.go
This allows to find the source of cardinality increases easier.
```
❯ profilecli query label-values-cardinality
level=info msg="query label names" url=http://localhost:8080 from=2024-06-19T13:09:11.417419+01:00 to=2024-06-19T14:09:11.417419+01:00
level=info msg="received 87 label names"
+------------------------------------+-------------+
|             LABELNAME              | VALUE COUNT |
+------------------------------------+-------------+
| pod                                |      67,397 |
| instance                           |      48,438 |
| pod_template_hash                  |      12,000 |
| resource_version                   |       9,007 |
| tenant                             |       7,795 |
| node                               |       6,986 |
| org …
```
=> feat(profilecli): Add a label values cardinality subcommand

.github/workflows/release.yml
I am currently trying to cut a v1.6.1 to address #3355 and this was missed as part of #3347
=> Update release workflow to be v2 compatible

docs/sources/configure-client/trace-span-profiles/java-span-profiles.md
I had been going through those docs with one of our customers, I think the code blocks are very confusing and I think settings should be set using environment variables.
I do hope I did not misunderstand anything.
=> Update outdated java span profile information

.github/workflows/release.yml, .github/workflows/weekly-release.yml, Makefile
Avoids problems like encountered in #3347
=> chore: Ensure we use a fixed goreleaser version in github actions

operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
Fixes #3004 by changing the template in question. Verified with Helm 3.8.1 and 3.15.2.
=> chore: Fix template issue with older Helm versions

pkg/phlaredb/block_querier_symbols.go, pkg/phlaredb/schemas/v1/functions.go, pkg/phlaredb/schemas/v1/locations.go, pkg/phlaredb/schemas/v1/mappings.go, pkg/phlaredb/schemas/v1/profiles.go, pkg/phlaredb/schemas/v1/read_writer.go, pkg/phlaredb/schemas/v1/schema_test.go, pkg/phlaredb/schemas/v1/stacktraces.go, pkg/phlaredb/schemas/v1/strings.go, pkg/phlaredb/symdb/block_reader.go, pkg/phlaredb/symdb/block_writer.go
- remove `Persister[].SortingColumns` which is ued only in tests
- remove index argument from `Desconstruct`
- remove index return value from `Reconstruct`
- remove sorting from `ReaderWriter` test helper 
The PR does not change behavior or data, just tiny cleanup
=> chore: remove Persister[].SortingColumns method

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/model/labels.go, pkg/model/relabel/relabel.go, pkg/model/relabel/relabel_test.go, pkg/phlare/modules.go, pkg/phlare/runtime_config.go, pkg/validation/limits.go, pkg/validation/limits_test.go, pkg/validation/relabeling.go, pkg/validation/relabeling_test.go, pkg/validation/runtime_config.go, pkg/validation/validate.go
This is an important operational tool: It allows us to deal with problems in the ingested profile labels.
The relabeling rules cover both series label and also sample labes.
By default we supply relabeling rules, which do remove the `godeltaprof_` prefix from profiles generated by pyroscope-go.
=> feat(distributor): Relabel profiles at ingest

pkg/phlaredb/symdb/stacktrace_tree.go, pkg/phlaredb/symdb/stacktrace_tree_test.go
The PR adds a way to convert a parent pointer tree to a full tree, which allows for tree traversal and quick reverse lookups (call site -> stack trace identifiers). This lightweight operation is instrumental for implementing #3219, #3384, #3220, and #2729. As of now, it is not used anywhere, but I'm afraid of forgetting the algorithm, so I'm adding it to the codebase.
=> feat: implement parent pointer tree recovery

docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/frontend/frontend_diff_test.go, pkg/test/integration/helper.go, pkg/validation/validate.go, pkg/validation/validate_test.go
In https://github.com/grafana/explore-profiles/pull/15, I ran across a bug where the UI was sending queries without a time range. It was a little tricky to track down because Pyroscope would respond with a success status code, but an empty payload. This made me wonder if there was a bug in Pyroscope's query logic.
I think we should classify queries with no time range an error. I don't know of any use cases in which we want to have a time range, but allow it to be optionally provided.
=> Reject queries without a time range

operations/pyroscope/helm/ct.yaml
Small follow-up to #3332 
This fixes the kubeVersion to match the one from the makefile and compares to the correct branch.
=> chore: Update kubeVersion and branch to main

pkg/phlaredb/downsample/downsample.go, pkg/phlaredb/downsample/downsample_test.go, pkg/phlaredb/schemas/v1/profiles.go, pkg/phlaredb/symdb/rewriter.go, pkg/phlaredb/symdb/stacktrace_tree.go, pkg/phlaredb/symdb/stacktrace_tree_test.go
Fixes https://github.com/grafana/pyroscope/issues/3406.
Currently, during compaction, when the downsampler aggregates profiles, the stack trace partition is ignored. The initial assumption was that profiles of the same series (label set) would always have the same stack trace partition. This is almost always the case; however, this is not guaranteed as the partitioning heuristic also depends on the main mapping name (see [#3262](https://github.com/grafana/pyroscope/issues/3262)).
We've recently discovered a few cases where this led to data inconsistencies. Specifically, profiles that refer to the wrong partition, and therefore can't be read: their samples refer to stack traces that can't be found in the partition. Another issue is that such occurrences are not handled properly: a wrong …
=> fix: honor stacktrace partitions at downsampling

pkg/phlaredb/symdb/rewriter.go
Increasing the LRU cache size from 2 to 8 turned out to be quite a problem for large deployments and might be causing OOMs, so I'm reverting it
See #3408
=> fix: revert rewriter LRU cache size

pkg/phlaredb/symdb/resolver_pprof.go, pkg/phlaredb/symdb/resolver_pprof_test.go, pkg/phlaredb/symdb/resolver_pprof_tree.go, pkg/phlaredb/symdb/stacktrace_selection.go
Fixes #3411
Instead of resolving the selected stack trace to function identifiers to optimize the search (which is not trivial if there are functions with identical names, which is totally possible), frames will be compared by their string values
=> fix: stack trace selector ignores conflicting functions

pkg/phlaredb/schemas/v1/profiles.go, pkg/phlaredb/schemas/v1/profiles_test.go
noticed last columns appends are allocating
=> profiles parquet encoding: fix profile column count

pkg/phlaredb/profile_store.go
There is an error check of err value from cutRowGroup call. If cutRowGroup returns err, the rowsLock seem to be never released
=> profileStore: fix unlocking rowsLock

.github/workflows/weekly-release.yml, .goreleaser.yaml
This will allow to have more meaningful ways of debugging core dump and live processes in all environments.
I tested this quickly:
```
❯ goreleaser build --clean --snapshot --single-target
[...]
❯ dlv exec dist/profilecli_darwin_arm64/profilecli
could not launch process: decoding dwarf section info at offset 0x0: too short - debuggee must not be built with 'go run' or -ldflags='-s -w', which strip debug info
❯ GORELEASER_STRIP_DEBUG_INFO=false goreleaser build --clean --snapshot --single-target
[...]
❯ dlv exec dist/profilecli_darwin_arm64/profilecli
Type 'help' for list of commands.
(dlv)
```
=> chore: Build weeklies with debug information

Makefile, cmd/pyroscope/frontend.Dockerfile, pkg/phlare/modules.go, pkg/phlare/phlare.go
This will likely slowdown (already slow) ingesters rollouts due to `  [min_ready_duration: <duration> | default = 15s]`
As a side quest I made `make frontend/build` use docker.
=> fix: readiness check for ingesters and frontend

README.md
I think is better to link to docs, in order to stay up-to-date.
=> docs: Link to supported languages

docs/sources/configure-client/trace-span-profiles/java-span-profiles.md
I would like to get rid of the rich READMEs and link everything into docs. This is something that our docs don't have.
=> docs: Add parameters from otel-profiling-java

.goreleaser.yaml
This is a follow up to #3437 as there are no distroless images provided by upstream.
=> chore: Drop linux/arm/v6 architecture

cmd/pyroscope/Dockerfile, cmd/pyroscope/debug.Dockerfile
This apparently was missed in #2875
```
ts=2024-07-31T14:22:52.491454333Z caller=compactor.go:646 level=error component=compactor component=compactor msg="failed to compact user blocks" tenant=anonymous err="mkdir data-compactor: permission denied"
```
=> bug: Docker image ensure data folder for compactor exists

.github/workflows/publish-technical-documentation-next.yml, .github/workflows/publish-technical-documentation-release.yml, docs/Makefile, operations/pyroscope/helm/pyroscope/values.yaml
I had noticed a couple of paths, which still point to the old path /docs/phlare instead of /docs/pyroscope
=> chore: Move paths from docs/phlare to docs/pyroscope

.github/workflows/e2e.yaml
Related: https://github.com/actions/runner-images/issues/9692
=> chore: Apparently github broke docker compose:

pkg/adhocprofiles/adhocprofiles.go, pkg/adhocprofiles/adhocprofiles_test.go
Pyroscope currently allows any character to be user specified at upload. This limits that character set. It also makes sure only IDs are listed and retrieve with get, when they are fulfilling the character limit.
This validation will ensure that the generated identifiers are within the allowed set used by object stores.
Note: I don't think this is a security problem, as object store treat `..` as a "normal folder name". Also the adhoc profiles are not enabled, when there is not bucket specified.
=> adhocprofile: Validate IDs and santize names properly

.github/workflows/pyrobench.yaml
Pyrobench is a hackathon 2024-08 project, which provides a github action that can run go microbenchmarks on demand. It will:
- Double check the code for the package with the Benchmarks in has  changed (comparing base..head of PR)
- Will run the benchmarks multiple times for base and head and then compare it using benstat (WIP).
- Each benchmark run will also collect profiles and upload them to flamegraph.com
https://github.com/grafana/hackathon-2024-08-pyrobench (README is WIP)
Example project
https://github.com/grafana/hackathon-2024-08-pyrobench-dskit/pull/1#issuecomment-2275953511
=> feat: Add pyrobench github action

.github/workflows/test.yml
In #3388, I added a workaround to bypass some bugs in reviewdog that were breaking CI on large diffs. The workaround relies on the PR head commit SHA, which is not available when merging to main and causes CI to fail. I could have added a separate doc-validation action or modified the script to work in both cases. Instead, I'm removing the workaround to fix the CI pipeline for now. Large diffs (20K+ lines, 300+ files) will break CI.
/cc @jdbaldry
=> fix(ci): remove reviewdog hack

pkg/og/flameql/flameql.go, pkg/og/flameql/flameql_test.go
The dot will be replaced with underscore later anyways.
https://github.com/grafana/pyroscope/pull/3335
=> fix(flameql): allow dots in tag name

pkg/experiment/metastore/metastore_boltdb.go
This blocks weekly build: https://github.com/grafana/pyroscope/actions/runs/10445827891/job/28922337156
I doubt we want to support arm7. Either way, I think 2GiB of the initial mmap size might be a little too much. However, the size determines how many writes can be handled without being blocked by the ongoing snapshot capturing, so we want to be very generous here. This clearly should be a configurable parameter.
=> fix: int overflow on arm7

examples/language-sdk-instrumentation/dotnet/rideshare/Dockerfile, examples/language-sdk-instrumentation/dotnet/rideshare/docker-compose.yml, examples/language-sdk-instrumentation/dotnet/rideshare/example/Example.csproj, examples/language-sdk-instrumentation/dotnet/rideshare/musl.Dockerfile, examples/tracing/tempo/docker-compose.yml
Unfortunately this problem #3288 has come back to me. 🙂 
I think I have a solution now based on (https://github.com/dotnet/dotnet-docker/issues/3832): It uses a multi-stage build in order to overcome build problems on dotnet sdk7+ on Rosetta based macs, when emulating amd64.
It will cross compile using the linux/arm64 dotnet sdk for the linux/amd64 target. (which is the only arch we support)
=> chore: Add dotnet SDKv8 support for examples

docs/sources/configure-client/language-sdks/dotnet.md, docs/sources/view-and-analyze-profile-data/profiling-types/_index.md
This was a profiler in the dotnet sdk I noticed we are missing.
=> docs: Add notice about heap profiling

.github/workflows/weekly-release.yml
We've been experiencing issues with the ubuntu-latest image recently, which [has affected our weekly build](https://github.com/grafana/pyroscope/actions/runs/10447953800/job/28929135845#step:1:108) pipeline:
```
You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 80 MB
```
My understanding is that the image was updated recently, and our build no longer fits within the available space. There are numerous reports of similar issues in various projects using this image. One workaround has been to use the new ubuntu-22.04 image. While this has helped, we should consider using dedicated Grafana runners.
=> fix: use ubuntu-24.04 in goreleaser-weekly

cmd/profilecli/main.go, cmd/profilecli/ready.go
When doing some local testing, I came across the problem where I wanted to quickly check if pyroscope was up. A similar problem was described here https://github.com/grafana/pyroscope/pull/3468 and @korniltsev commented a similar solution https://github.com/grafana/pyroscope/pull/3468#issuecomment-2272830497.
```
$ profilecli ready --help
usage: profilecli ready [<flags>]
Check Pyroscope health.
Flags:
-h, --help              Show context-sensitive help (also try --help-long and --help-man).
--version           Show application version.
-v, --verbose           Enable verbose logging.
--url="http://localhost:4040"  
URL of the profile store.
--tenant-id=""      The tenant ID to be used for the X-Scope-OrgID header.
--username=""       The username to be used for basic auth.
--password="" …
```
=> [profilecli] Add ready command

pkg/querier/http.go, pkg/querier/ingester_querier.go, pkg/querier/querier.go, pkg/querier/store_gateway_querier.go
selectTree was using the a errgroup context past calling `Wait()`. This caused some errors when store-gateways were used for queries, that required deduplication.
https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22yce%22%3A%7B%22datasource%22%3A%22Em2icyuMk%22%2C%22queries%22%3A%5B%7B%22query%22%3A%2277764ad0d6f03fb3bab49a2c0176dad%22%2C%22queryType%22%3A%22traceql%22%2C%22refId%22%3A%22A%22%2C%22datasource%22%3A%7B%22type%22%3A%22tempo%22%2C%22uid%22%3A%22Em2icyuMk%22%7D%2C%22limit%22%3A20%2C%22tableType%22%3A%22traces%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221724071628719%22%2C%22to%22%3A%221724072528719%22%7D%7D%7D&orgId=1
This fix also updated all errgroups returned contexts to use `gCtx`, as an additional measure we could consider using a block to limit the use `gCtx` …
=> Fix: Handle context correctly in the querier

.github/workflows/update-contributors.yml, Makefile, tools/update-contributors/main.go
I think it is a nice to have this appreciation, but we haven't updated in a while, as the nodejs of the old tools no longer maintained.
Just threw some go together quickly.
=> docs: Bring back update-contributors but in go

.github/workflows/update-contributors.yml
Apart from using a shell script to determine when to update this also debugs problems with the token better (using `gh auth status`). Also disabling the persisting of credentials, avoids using wrong credentials.
=> Update credentials: Use git directly

pkg/querier/vcs/client/github.go, pkg/querier/vcs/service.go, pkg/querier/vcs/service_test.go
GitHub's API [documentation](https://github.com/grafana/pyroscope/pull/3518) states:
> `ref` string Required
The commit reference. Can be a commit SHA, branch name (`heads/BRANCH_NAME`), or tag name (`tags/TAG_NAME`)."
This PR enhances our commit retrieval to align with this specification:
- Implements logic to try different prefixes (none, `heads/`, `tags/`) when fetching commits
- Introduces `gitHubCommitGetter` interface for better abstraction
- Adds unit tests to cover multiple scenarios
=> Enhance commit retrieval with branch & tag prefix support

docs/sources/view-and-analyze-profile-data/profile-cli.md
We recently ran into a case where a customer wanted to use `profilecli` but was using the wrong URL. This PR updates the docs to make it more clear which URL to use (and which one not to use).
=> [docs] Clarify which URL to use with profilecli

pkg/experiment/metastore/metastore.go, pkg/experiment/metastore/metastore_bootstrap.go, tools/dev/experiment/values-micro-services-experiment.yaml
Wrong server id resulted to deduplication failure
```
Failed to resolve bootstrap peers" err="expected number of bootstrap peers not reached: got 4, expected 3\n[
...
{Suffrage:Voter ID:pyroscope-metastore-2.pyroscope-metastore-headless.pyroscope-test.svc.cluster.local. Address:pyroscope-metastore-2.pyroscope-metastore-headless.pyroscope-test.svc.cluster.local.:9099}
{Suffrage:Voter ID:pyroscope-metastore-2.pyroscope-metastore-headless.pyroscope-test.svc.cluster.local.:9099 Address:pyroscope-metastore-2.pyroscope-metastore-headless.pyroscope-test.svc.cluster.local.:9099}]"
```
- fix bootstrap of metastore with correct server id
- add bootstrap retries
=> fix(metastore): local raft server id

pkg/querier/vcs/commit.go
Follow-up PR for https://github.com/grafana/pyroscope/pull/3529#discussion_r1737536976. 
Refactor the `getCommits` function in the VCS service to use `errgroup` instead of `sync.WaitGroup`.
- Implement `errgroup` for better concurrency management
- Set a limit (10) on concurrent requests to GitHub API
I kept the existing error handling approach, collecting errors explicitly through the channel rather than relying on errgroup's built-in error handling, since it will only return the first encountered error.
=> chore(vcs): refactor getCommits to use errgroup

pkg/experiment/metastore/metastore_state_poll_compaction_jobs.go, pkg/experiment/metastore/metastore_state_poll_compaction_jobs_test.go
Fixes an issue where compaction block queues are stored correctly in memory but not persisted in bolt db because we are using the wrong key. Updates the tests as well to cover this.
=> fix: compaction block queue persistence

pkg/experiment/metastore/metastore_fsm.go, pkg/experiment/metastore/metastore_fsm_test.go, pkg/experiment/metastore/metastore_state_poll_compaction_jobs.go, pkg/experiment/metastore/metastore_state_poll_compaction_jobs_test.go
The metastore FSM recovers from any panics in Raft command handlers. This change adds a custom error type which when used in a panic will result in a real panic. It also downgrades a few existing error cases, when the underlying issue is a logical one (a bug) as opposed to a technical problem.
The intention is to terminate replicas when they encounter a real error, e.g., failing to persist the state to the DB.
=> feat: do not recover from panics with fatal errors

pkg/experiment/metastore/metastore_compaction_planner.go, pkg/experiment/metastore/metastore_compaction_queue.go, pkg/experiment/metastore/metastore_state.go, pkg/experiment/metastore/metastore_state_poll_compaction_jobs.go, pkg/experiment/metastore/metastore_state_poll_compaction_jobs_test.go
When we encounter a job that has no valid blocks (e.g., because they were deleted by the truncation logic) we currently remove it from the in-memory store but not from bolt DB. This causes a burst of new (invalid) jobs every time we restore from a snapshot.
This change ensures that such jobs are removed. There are a few other (mostly cosmetic) changes as well.
=> fix (v2): remove outdated compaction jobs from storage

pkg/experiment/metastore/metastore_hack.go
Currently in the v2 arch we delete all blocks older than 12 hours. This was added when compaction wasn't fully in place, as a way to prevent ever increasing resource usage. Compaction is now in place, but without the metastore index and its time-based block partitioning we can still accumulate many blocks over a longer period. Aside from high resource usage, this can make the read path slower since we currently scan all blocks to create query plans.
This PR makes truncation less aggressive. Alternatively we could remove truncation altogether but I think it makes more sense to do that once we have the metastore index.
=> feat(v2): extend period for truncation, do not truncate all blocks

.github/workflows/backport.yml
For more information, refer to https://github.com/grafana/grafana-github-actions/pull/224.
I'd like to try backporting this to at least one release branch to check if it behaves correctly.
=> Test backport workflow with branch that doesn't make a GraphQL call

operations/pyroscope/helm/pyroscope/README.md, operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml, operations/pyroscope/helm/pyroscope/values.yaml, operations/pyroscope/jsonnet/values.json
basic support for topologySpreadConstraint
=> feat(helm): add topologySpreadConstraint (#3538)

pkg/distributor/distributor.go, pkg/experiment/ingester/memdb/head.go, pkg/experiment/ingester/segment.go, pkg/experiment/ingester/segment_test.go, pkg/experiment/ingester/service.go, pkg/model/pprof_split/pprof_split.go, pkg/phlare/modules_experimental.go, pkg/pprof/pprof.go, pkg/pprof/pprof_test.go, pkg/slices/slices.go
The change enables pprof split in segment writers. The implementation does not include any optimisations: symbolic information and samples are copied and indexed repeatedly (same as in the current version) – this is to be improved in follow up PRs
=> feat: move pprof split to segment writer

.github/workflows/update-contributors.yml
[skip ci]  may prevent running goreleaser
=> chore(update-contributors): do not skip CI

pkg/frontend/frontend_select_merge_profile.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/symdb/resolver.go, pkg/pprof/merge.go, pkg/querier/querier.go, pkg/querier/select_merge.go
The PR makes`pprof.ProfileMerge.Merge` method synchronous: we call it in multiple places and almost always concurrently, therefore we use an external synchronisation (just a mutex).
Moreover, many other "mergers" that we use are synchronous, which makes use of `pprof.ProfileMerge` prone to errors. Specifically, recently added read path router does not protect it from the concurrent access, which causes panics on pprof export (query-backend only)
=> fix: make pprof merge thread-safe

README.md, docs/sources/configure-client/_index.md, examples/README.md
=> docs: Update deployment diagram

pkg/distributor/distributor.go, pkg/experiment/ingester/segment.go, pkg/model/pprof_split/pprof_split.go, pkg/model/pprof_split/pprof_split_test.go
Follow-up on #3561
* Added optimisation for the case when sample export may be avoided
* Refactored unit tests
=> perf: optimize pprof split

.github/workflows/update-contributors.yml
Closes https://github.com/grafana/pyroscope/issues/3574
This reverts commit e56265f5faeef13ae1eae370419419cc11ec7871.
=> Revert "chore(update-contributors): do not skip ci (#3556)"

pkg/experiment/ingester/memdb/head.go, pkg/phlaredb/compact.go, pkg/phlaredb/symdb/block_writer_v2.go, pkg/phlaredb/symdb/block_writer_v3.go, pkg/phlaredb/symdb/partition_memory.go, pkg/phlaredb/symdb/partition_memory_test.go, pkg/phlaredb/symdb/resolver_tree_test.go, pkg/phlaredb/symdb/symdb.go
The PR disables stack trace range chunking because it results in higher CPU and memory consumption and complicates the implementation.
Our aim was to limit the memory consumption of the symbolication process. However, loading chunks synchronously drastically increases latency while still consuming a significant amount of memory. Currently, all the chunks are loaded into memory concurrently, so we are not seeing any benefits.
<details>
<summary>Spoiler warning</summary>
```
Stacks per chunk:  10M(∞)  2M      1M     512k    256k    
------------------------------------------------------------------------------------
Total size on disk (MiB):  27.6    30.5    33     36.8    41.8
Total in-memory size (MiB):  44.6    51.5    58     67.7    79.5
Max chunk in-memory size (MiB):  44.6    30.9 …
```
=> chore: disable stack trace range chunking

.github/workflows/backport.yml
Used for unassigning default reviewers. If you don't have it, you get cryptic comments posted back on the PR after the backport PRs are opened with the message `Validation Failed: "Could not resolve to a node with the global id of '<NODE ID>."`
Like in https://github.com/grafana/pyroscope/pull/3557#issuecomment-2348613956
Behavior was documented in https://github.com/grafana/grafana-github-actions/pull/226 and made configurable in 
https://github.com/grafana/grafana-github-actions/pull/227
=> Ignore default reviewers

README.md
Updates readme to highlight explore profiles
=> docs: Update readme to highlight explore profiles

pkg/frontend/dot/graph/graph.go
The intention here should be to initialize a slice with a capacity of len(prof.Location)  rather than initializing the length of this slice.
=> fix: fix slice init length

docs/sources/release-notes/v1-9.md
Add release notes for release https://github.com/grafana/pyroscope/releases/tag/v1.9.0
=> docs: Add pyroscope v1.9 release notes

docs/sources/configure-client/grafana-agent/_index.md, docs/sources/configure-client/grafana-agent/go_pull.md, docs/sources/configure-client/grafana-agent/java/_index.md, docs/sources/get-started/_index.md, docs/sources/introduction/pyroscope-in-grafana.md
Fix broken links reported for the Pyroscope docs. Includes community fixes from 
https://github.com/grafana/pyroscope/pull/3611
https://github.com/grafana/pyroscope/pull/3333
Partial fix for https://github.com/grafana/tempo-squad/issues/495
=> [DOC] Fix broken links from doc report

cmd/profilecli/main.go, cmd/profilecli/output.go, cmd/profilecli/query-blocks.go, cmd/profilecli/query.go, pkg/phlaredb/block_querier.go, pkg/phlaredb/block_querier_test.go
In this PR we introduce a new profilecli command: `query-blocks`. With this command, you can execute queries directly to single or multiple blocks hosted in your localhost or a remote bucket.
Partially solves https://github.com/grafana/pyroscope/issues/3559, `profile query-blocks merge` will come in a later PR.
This feature gives similar capabilities as `profilecli query series`but for a specified local/remote blocks:
* It has support for checking label values with `--label-names` or specify the query with `--query`.
* You may choose to use it locally (`--local-path`) or remotely (`--bucket-name`, `--tenant-id` and `--object-store-type` - only gcs supported right now).
* You specify queried blocks with the `--block-ids` flag.
* Time ranges (`to` and `from`) are not needed: it will query …
=> feat: profilecli query-blocks series

pkg/experiment/metastore/metastore.go, pkg/experiment/metastore/metastore_read_index.go, pkg/experiment/metastore/metastore_readindex.go, pkg/experiment/metastore/metastore_state_get_profile_stats.go, pkg/experiment/metastore/metastore_state_query_metadata.go, pkg/experiment/metastore/test/create.go
This PR implements the ReadIndex in the Metastore to ensure linearizable reads, as described in the Raft consensus algorithm. The implementation leverages the Hashicorp Raft library's existing features while adding necessary checks to guarantee read consistency.
Key changes:
1. Update `ReadIndex` method to verify leadership and return current commit index.
2. Added `readIndex` method to ensure the node is up-to-date before serving reads.
3. Modified `QueryMetadata` and `GetProfileStats` to use `readIndex` before querying data.
4. Updated `CheckReady` method to use `readIndex` for consistency checks.
Raft Algorithm Considerations:
- Hashicorp's Raft implementation [already sends](https://github.com/hashicorp/raft/blob/main/raft.go#L565-L572) a no-op log entry when `runLeader` is called for …
=> feat(v2): implement ReadIndex for linearizable reads

Makefile
CI pipeline fails on `main` due to:
> GOBIN=/home/runner/work/pyroscope/pyroscope/.tmp/bin GOPRIVATE=github.com/grafana/deployment_tools go install github.com/grafana/deployment_tools/drone/plugins/cmd/updater@d64d509
go: downloading github.com/grafana/deployment_tools/drone/plugins v0.0.0-20220712102523-d64d5092c42b
go: downloading github.com/grafana/deployment_tools v0.0.0-20220712102523-d64d5092c42b
go: github.com/grafana/deployment_tools/drone/plugins/cmd/updater@d64d509: loading deprecation for github.com/grafana/deployment_tools/drone/plugins: no matching versions for query "latest"
make: *** [Makefile:353: /home/runner/work/pyroscope/pyroscope/.tmp/bin/updater] Error 1 
I'm not entirely sure what caused this (it may be modcache, or expired token), but it looks like we haven't been …
=> chore: update updater

cmd/profilecli/main.go, cmd/profilecli/query-blocks.go
In this PR:
* We move `query-blocks` to `admin blocks query`.
=> refactor: move query-blocks to admin blocks query

cmd/profilecli/main.go, cmd/profilecli/query-blocks.go, cmd/profilecli/query.go, docs/sources/view-and-analyze-profile-data/profile-cli.md
Simple refactor here: just renaming `profilecli query merge` to `profilecli query profile` (same for `profilecli admin blocks query merge`), while keeping the old `merge` subcommand as a valid alias.
Doc updated accordingly
=> refactor: renaming `merge` commands to `profile`

.github/workflows/update-contributors.yml
Fixes #3574 by scheduling the workflow to run on the first ~~day~~ Sunday of every month and removing the [skip ci] flag in the commit. 
We don't really need frequent updates imo and if we run it monthly we don't have to worry about it being wasteful. 
~~There is a small chance of jobs getting cancelled if someone merges a PR right around when this runs (midnight UTC, on the first day of the month), I don't think this is a real problem but we could update the concurrency config if it becomes an issue.~~
This probability is now reduced by having it run on the first Sunday of the month, at 00:00 UTC.
=> chore: make the update-contributors workflow run monthly

.github/workflows/helm-release.yml
As per https://github.com/grafana/helm-charts/blob/main/.github/workflows/update-helm-repo.yaml#L27-L32
Related to https://github.com/grafana/pyroscope/actions/runs/11386238456
=> fix: helm release secret key

pkg/experiment/query_backend/block/dataset.go, pkg/experiment/query_backend/block/section_tsdb.go, pkg/objstore/read_only_file.go
This fixes cryptic errors like `failed to initialize query context: openning section tsdb: opening tsdb: read postings table: invalid checksum` that may occur if the tsdb index uses memory referenced from the shared buffer pool after disposal.
=> fix(v2): opening tsdb: read postings table: invalid checksum

package.json, yarn.lock
- CVE-2024-45296 : remove path-to-regex and dev server to decrease CVE noise
- CVE-2024-21489 : bump uplot
Tested with `make frontend/build` and opening some flamegraphs in debug ui
=> chore: frontend dependencies bumps

pkg/experiment/ingester/client/client.go, pkg/experiment/ingester/segment.go, pkg/experiment/ingester/segment_test.go, pkg/experiment/ingester/service.go, pkg/experiment/metastore/client/client.go, pkg/experiment/metastore/client/methods.go, pkg/experiment/metastore/metastore.go, pkg/experiment/metastore/test/create.go, pkg/phlare/modules.go, pkg/phlare/modules_experimental.go, pkg/phlare/phlare.go, pkg/util/health/health.go, pkg/util/inflight_requets.go, pkg/util/recovery.go
Due to how the grpc server and services are managed, we can't rely on the (de-)initialization order, which causes major issues. Moreover, many of the components are accessed directly through various discovery mechanisms, which provide different (and, generally, week) guarantees on the instance readiness.
Health checks at the connection level help to partially eliminate the problem: a well behaving client won't experience any significant issues when server instances go offline.
=> feat(v2): revive grpc health checks

ebpf/symtab/proc.go, ebpf/symtab/procmap.go
Fixes #3650
@korniltsev I think this should be fine?
=> Use uint64 for `proc` offset

README.md, docs/sources/configure-client/aws-lambda.md, docs/sources/configure-client/grafana-alloy/_index.md, docs/sources/configure-client/grafana-alloy/ebpf/_index.md, docs/sources/configure-client/grafana-alloy/java/_index.md, docs/sources/configure-client/language-sdks/_index.md, docs/sources/configure-client/language-sdks/dotnet.md, docs/sources/configure-client/language-sdks/go_push.md, docs/sources/configure-client/language-sdks/java.md, docs/sources/configure-client/language-sdks/nodejs.md, docs/sources/configure-client/language-sdks/python.md, docs/sources/configure-client/language-sdks/ruby.md, docs/sources/configure-client/language-sdks/rust.md, docs/sources/configure-client/memory-overhead.md, docs/sources/configure-client/profile-types.md, docs/sources/configure-client/trace-span-profiles/_index.md, docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md, docs/sources/configure-server/about-server-api.md, docs/sources/introduction/continuous-profiling/_index.md, docs/sources/introduction/profiling-types/_index.md, docs/sources/introduction/profiling.md, docs/sources/introduction/pyroscope-in-grafana.md, docs/sources/shared/available-profile-types.md, docs/sources/shared/index.md
Updates and expands the supported profiling content. 
- Splits the profile type by instrumentation method table into three tables:  SDK vs auto instrumentation, language SDK, and span profiles.
- Puts the tables on it’s own page and moves it to the Configure the client section on a new page
- Change links to the profile types page in the other Configure the client pages
- Updates the page weight for Introduction and Configure the client sections
- Updates any links to the new page
Fixes: https://github.com/grafana/pyroscope/issues/3259
=> [DOC] Update and expand profiling types doc

examples/language-sdk-instrumentation/dotnet/rideshare/Dockerfile, examples/language-sdk-instrumentation/dotnet/rideshare/musl.Dockerfile, tools/update_examples.go
There were some changes in examples/language-sdk-instrumentation/dotnet/rideshare/Dockerfile and old regex does not work anymore
=> fix(docs): update examples fixes

docs/sources/configure-client/_index.md, docs/sources/configure-client/grafana-alloy/_index.md, docs/sources/configure-client/grafana-alloy/receive_profiles.md
**DO NOT MERGE** until next Alloy release happens. 
As of now, latest is https://github.com/grafana/alloy/releases/tag/v1.4.3
This PR adds documentation for the new feature that allows sending profiles from Pyroscope SDKs through Alloy.
=> docs: add documentation for Pyroscope SDK profiles through Alloy

operations/pyroscope/helm/pyroscope/Chart.yaml, operations/pyroscope/helm/pyroscope/README.md
This is useful to display some links on the artifacthub page: https://artifacthub.io/packages/helm/grafana/pyroscope
For example, you can check the cert-manager one: https://artifacthub.io/packages/helm/cert-manager/cert-manager
=> docs: add home link and sources in Helm chart

pkg/experiment/query_backend/client/client.go, pkg/experiment/query_backend/concurrency.go
I missed one important change in #3675, it got accidentally reverted in one of my tests. We need to set the global `grpc.WithMaxCallAttempts(500)` in addition to the `"MaxAttempts": 500` on the method retry policy.
As per https://github.com/grpc/grpc-go/blob/5e99daea2f11c6f9fab99470e71c6a92138f1875/service_config.go#L284-L286, the per-method `maxAttempts` is only used if it is smaller than the global `maxAttempts` which defaults to 5.
=> fix(v2): set grpc.WithMaxCallAttempts() for the query backend client

docs/sources/release-notes/v1-10.md, docs/sources/release-notes/v1-3.md, docs/sources/release-notes/v1-4.md, docs/sources/release-notes/v1-5.md, docs/sources/release-notes/v1-6.md, docs/sources/release-notes/v1-7.md, docs/sources/release-notes/v1-8.md, docs/sources/release-notes/v1-9.md, docs/sources/view-and-analyze-profile-data/profile-cli.md
Add release notes for Pyroscope v1.10, fix the page weights for the release notes pages, and add links to documentation, when available. 
Fixes #3689
=> [DOC] Add v1.10 release notes and fix page weights

docs/sources/configure-server/about-server-api.md
* Fix typo
* About [JFR format](https://github.com/grafana/pyroscope/blob/main/docs/sources/configure-server/about-server-api.md#jfr-format), and describing the supported profile types
* Check that 
* the description referes to the outside of tlab
* the referered to the tlab was defined previosly
=> doc(docs.sources.configureServer.aboutServerAPI): fix typo

docs/sources/introduction/profiling.md
* Fix wrong indentation
* In profiling fundamentals, https://grafana.com/docs/pyroscope/latest/introduction/profiling/#benefits-1, you can realize about the wrong indentation typo at the end
* Check that it's marked as 7, matching with the sequence of benefits referred
=> doc(docs.sources.introduction.profiling): fix wrong indentation

examples/grafana-agent-auto-instrumentation/ebpf-otel/README.md, examples/grafana-agent-auto-instrumentation/ebpf-otel/docker/Dockerfile, examples/grafana-agent-auto-instrumentation/ebpf-otel/docker/config/otel-collector-config.yaml, examples/grafana-agent-auto-instrumentation/ebpf-otel/docker/docker-compose.yml, examples/grafana-agent-auto-instrumentation/ebpf-otel/docker/grafana-provisioning/datasources/pyroscope.yml, examples/grafana-agent-auto-instrumentation/ebpf-otel/kubernetes/Dockerfile, examples/grafana-agent-auto-instrumentation/ebpf-otel/kubernetes/cpu-stress.yaml, examples/grafana-agent-auto-instrumentation/ebpf-otel/kubernetes/grafana.yaml, examples/grafana-agent-auto-instrumentation/ebpf-otel/kubernetes/otel-collector.yaml, examples/grafana-agent-auto-instrumentation/ebpf-otel/kubernetes/profiler.yaml, examples/grafana-agent-auto-instrumentation/ebpf-otel/kubernetes/pyroscope.yaml
This PR adds examples for running the OpenTelemetry eBPF profiler on both Docker and Kubernetes. These examples demonstrate the following:
- The OTel eBPF profiler collecting system-wide profiles.
- The OpenTelemetry Collector receiving and processing profiler data.
- Pyroscope visualizing the profiles via Grafana.
=> docs: Add example for OTel eBPF profiler

docs/sources/get-started/_index.md
Explore profiles is awesome, and a great starting experience for exactly this part of getting started, and it's already in the latest Grafana images that the tutorial prompts people to run.
=> Update quickstart to include explore profiles

ebpf/python/procinfo.go, ebpf/python/pyperf_pid_data.go, ebpf/sd/target.go, ebpf/session.go
- allow forcing python profiling type with `__meta_pyroscope_ebpf_options_python_profiling_type=true` target label.
- assume `streamlit` is python
- assume a process is python if the process has `python` or `libpython` proc mappings
=> fix(ebpf): improve python process detection

pkg/experiment/ingester/client/client.go, pkg/experiment/metastore/client/client.go, pkg/experiment/query_backend/client/client.go, pkg/phlare/modules_experimental.go, pkg/phlare/phlare.go
The added metric helps investigating latency issues.
=> chore(v2): add gRPC client call duration metric

pkg/og/flameql/flameql.go, pkg/og/flameql/flameql_test.go
This was originally reported in Alloy grafana/alloy#2158.
The change extends service name validation to allow slashes, enabling hierarchical service naming patterns. After this change is validated, I'll create the proper PR in Alloy since the validation isn't reused in Alloy but ported from Pyroscope.
Closes grafana/pyroscope#3721
=> fix(flameql): allow slashes in tag name

go.mod, go.sum
Include these fixes https://github.com/grafana/jfr-parser/issues?q=is%3Apr+author%3Asivachandran fir flight recorder parsing.
See https://github.com/grafana/jfr-parser/issues/44
=> chore: bump jfr parser dependency

pkg/experiment/compactor/compaction_worker.go
It is currently possible that during shutdown, the compaction worker may skip sending status updates for jobs that finish between the last poll and the exit of the poll loop. While this is a rare occurrence in practice, we want to avoid unnecessary job reassignments and reprocessing.
=> fix(v2): compaction worker drops final status updates

docs/sources/configure-client/opentelemetry/ebpf-profiler.md
Adds the OpenTelemetry profiles documentation to:
- Add current limitations
- Clarify protocol development status and compatibility concerns
- Add link to OpenTelemetry proto files
- Add link to examples repository
=> docs: add otel ebpf profiling support

docs/sources/configure-client/language-sdks/java.md, examples/language-sdk-instrumentation/java/fib/Dockerfile, examples/language-sdk-instrumentation/java/rideshare/Dockerfile, examples/language-sdk-instrumentation/java/rideshare/build.gradle.kts, examples/language-sdk-instrumentation/java/simple/Dockerfile
Update java examples to the latest SDK version (`0.15.0`). See https://github.com/grafana/pyroscope-java/pull/170 for more information.
=> Update examples and docs with the latest java sdk

pkg/experiment/query_backend/block_reader.go
Was fairly useful, giving v2 a spin locally. As it improves the detail of query information that can be seen in distributed tracing.
I might be better placed in the earlier Invoke calls, but I this one has the validation and is closet to the actual work being done, hence I put it there.
=> chore(v2): Add span tags into BlockReader.Invoke

examples/language-sdk-instrumentation/python/rideshare/flask/Dockerfile
This fixes this build error:
```
ERROR: Cannot install pyroscope-io==0.8.8 and pyroscope-otel==0.1.0 because these package versions have conflicting dependencies.
```
=> fix(examples): Update python rideshare to latest otel-profiling-python

public/app/components/ExportData.spec.tsx, public/app/components/ExportData.tsx
Due to privacy concerns, it's been decided to remove the button from the UI.
=> feat(Ui): Remove export to flamegraph.com

docs/sources/deploy-kubernetes/helm.md
The problem with the grafana helm is that we don't have the profiling port exposed as part of the containerPorts of the container. So I had to reuse/abuse the gossip-tcp port in order to get it to be scraped.
It also was using the wrong annotation of "pyroscope.grafana.com" instead of "profiles.grafana.com".
Fixes #3523
=> fix(docs): Make sure helm Grafana example works as expected.

operations/pyroscope/helm/pyroscope/README.md, operations/pyroscope/helm/pyroscope/rendered/micro-services-hpa.yaml, operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml, operations/pyroscope/helm/pyroscope/values.yaml, operations/pyroscope/jsonnet/values.json
This removes misleading annotations for minion:
* Minio cannot be profiled without authentication
* phlare.grafana.com annotations were invalid for a while
Also noticed an old phlare reference.
=> Helm: Remove misleading annotations for minio

.editorconfig, Makefile
Trunk was partially removed here  https://github.com/grafana/phlare/commit/388b36e4ecd1f039cf7b7105b263ccb2ac76748f
My main motivation for the PR is .editorconfig file which assumes we should use spaces, but we are using tabs.
=> remove trunk leftovers

Makefile
Updates local k8s cluster tool kind to latest version.
Also the makefile needs to be ignoring errors on the delete of the extra service removed from the single binary deployment.
=> chore: Update kind and allow errors removing extra service

.github/workflows/update-examples-cron.yml, Makefile.examples, tools/update_examples.Dockerfile, tools/update_examples.go
This will create PR's like this https://github.com/korniltsev/pyroscope/pull/7/files
=> chore(examples): add cron job to update examples

docs/sources/get-started/ride-share-tutorial.md, examples/language-sdk-instrumentation/python/README.md
In #3769 I renamed the `flask-ride-sharing-app` to `ride-sharing-app` to align with the shared README, where it is referred to in this way. However, in the KillerCoda tutorial, we're still using `flask-ride-sharing-app`. I'm updating the tutorial to reflect the new name and add a link to README.
=> chore(examples): rename flask-ride-sharing-app in tutorial

.github/workflows/test-examples.yml, Makefile, examples/examples_test.go, examples/language-sdk-instrumentation/dotnet/web-new/docker-compose.yml
I am sure this is something that we all felt during this docs week: It is quite hard keeping the examples working.
I spent a bit of time automating building and running the examples:
My observation was often problems happen already at built or startup stage. So for now that will only cover problems during docker-compose build and will only detect failures that occur during the first 5 seconds after docker-compose up.
=> test(examples): Introduce some basic testing for examples/

docs/sources/configure-client/_index.md, docs/sources/configure-client/grafana-alloy/java/_index.md, docs/sources/configure-client/grafana-alloy/receive_profiles.md, docs/sources/configure-client/language-sdks/_index.md, docs/sources/configure-client/language-sdks/dotnet.md, docs/sources/configure-client/language-sdks/go_push.md, docs/sources/configure-client/language-sdks/java.md, docs/sources/configure-client/language-sdks/python.md, docs/sources/configure-client/language-sdks/ruby.md, docs/sources/configure-client/opentelemetry/ebpf-profiler.md, docs/sources/configure-client/trace-span-profiles/go-span-profiles.md, docs/sources/configure-client/trace-span-profiles/python-span-profiles.md, docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md, docs/sources/configure-server/reference-configuration-parameters/index.md, docs/sources/get-started/ride-share-tutorial.md, docs/sources/introduction/profiling.md
We did not always backport the changes, also there was quite a few that were not that atomic.
I suggest we do this: Takes the changes from /docs in main and commit them to the release branch.
Wdyt?
=> chore(examples): Update release-1.10 with changes from /docs

docs/sources/configure-client/language-sdks/java.md, docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md, docs/sources/configure-client/trace-span-profiles/go-span-profiles.md, docs/sources/configure-client/trace-span-profiles/java-span-profiles.md, docs/sources/configure-client/trace-span-profiles/python-span-profiles.md, docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md, examples/language-sdk-instrumentation/java/fib/Dockerfile, examples/language-sdk-instrumentation/java/rideshare/Dockerfile, examples/language-sdk-instrumentation/java/rideshare/build.gradle.kts, examples/language-sdk-instrumentation/java/simple/Dockerfile, examples/tracing/java/Dockerfile, examples/tracing/java/README.md, examples/tracing/java/build.gradle.kts, examples/tracing/java/docker-compose.yml, examples/tracing/java/src/main/java/org/example/rideshare/Main.java, examples/tracing/java/src/main/java/org/example/rideshare/OrderService.java
Updates the Java tracing example:
- otel SDK bump from `0.10.1.11` to `0.11.0` (https://github.com/grafana/otel-profiling-java/pull/13)
- adds back the [Pyroscope Java SDK](https://github.com/grafana/pyroscope-java) with static and dynamic labels
- minor improvements to the readme file
Also updates other examples as well as docs to refer to the latest Java SDKs.
Static and dynamic labels:
Tracing-Profiling correlation:
=> Update java examples with latest SDKs

pkg/distributor/distributor_test.go, pkg/test/integration/ingest_pprof_test.go, pkg/validation/validate.go, pkg/validation/validate_test.go
backport https://github.com/grafana/pyroscope/pull/3818 to f/97
=> fix(distributor): validate string table accesses

docs/sources/configure-server/about-tenant-ids.md
=> Fix broken link in configure client

pkg/util/http.go
When debugging a possible issue with the `vcs` API, I realized we don't log 400 family errors. This makes it appear as if the requests succeeded, when in reality they may not have.
=> feat: Log 400 and 500 errors

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/model/profile.go, pkg/model/profile_test.go, pkg/phlaredb/head.go, pkg/phlaredb/phlaredb.go
Resolves #3262 
The PR adds a configuration option (`-pyroscopedb.symbols-partition-label`) to control how symbols are partitioned. 
Currently, we infer the partition key based on the main binary mapping, aiming to create shared partitions for binaries with the same name. This helps optimize memory usage during writes when the same binary runs in different contexts. As a fallback, the `service_name` label value is used as the symbols partition key.
However, this approach is quite fragile and may result in poor performance during query or compaction operations.
=> feat: configurable symbols partitioning

cmd/pyroscope/help-all.txt.tmpl, pkg/objstore/providers/s3/bucket_client.go, pkg/objstore/providers/s3/config.go, pkg/objstore/providers/s3/config_test.go, pkg/phlare/phlare.go
Hi Pyroscope Team!
This pull request targets the [issue](https://github.com/grafana/pyroscope/issues/3451). 
There are a few details I would like to point out:
- We have discussed previously that it would be great to show `a warning if force-path is set to true, that this flag is deprecated and might be removed going forward`. Unfortunately, I haven't found an elegant solution to do that and just put a deprecation message to flag's usage. There are [flagext](https://github.com/grafana/dskit/blob/main/flagext/deprecated.go) package, but it is used to replace deprecated flag completely. [Pflag](https://github.com/spf13/pflag?tab=readme-ov-file#deprecating-a-flag-or-its-shorthand) library has deprecation feature, but you use plain flag library here.
- It seems that s3 config is not validated …
=> Added bucket-lookup-type field to s3 config

pkg/objstore/client/config.go, pkg/phlare/phlare.go
We seem to have not linked up the validation for a few components.
=> Fix: Acutally validate config struct

.github/workflows/e2e.yaml, .github/workflows/fuzzer.yml, .github/workflows/release.yml, .github/workflows/test-examples.yml, .github/workflows/test.yml, .github/workflows/test_ebpf.yml, .github/workflows/weekly-release.yml, docs/sources/configure-server/reference-configuration-parameters/index.md
This PR adds a new job `check-generated` to verify that all generated files (documentation, protobuf, etc.) are up to date with their sources. This helps prevent situations where generated files drift from their sources.
Also, bumping workflows checkout action.
=> chore: add check for generated files drift

pkg/distributor/model/push.go, pkg/distributor/write_path/router.go, pkg/distributor/write_path/router_metrics.go, pkg/distributor/write_path/write_path.go, pkg/distributor/write_path/write_path_test.go, pkg/frontend/read_path/read_path.go
The PR fixes a bug in write path router that leads to concurrent access. I also added two new options (hidden):
1. `async-ingest`: if set, writes to segment-writer are not blocking (from the distributor client perspective). Writes to ingesters are always blocking.
2. `write-path.segment-writer-timeout`: defaults to 5s (the current timeout we use in distributors).
=> fix(v2): write path router dual ingestion

pkg/experiment/compactor/compaction_worker.go
Currently, compaction-worker does not cleanup the directory it uses for "staging" (kind of _temp_).
Typically, this is not a problem, because the intermediate data is deleted during the compaction process. However, the disk space (including ephemeral volumes) might be exhausted in case if the compactor fails to finish the compaction.
=> fix(v2): compaction-worker temp directory cleanup

pkg/experiment/ingester/client/client.go, pkg/experiment/ingester/client/client_test.go
Currently, client timeouts may trigger the segment-writer client circuit breaker, causing a specific segment-writer service instance to be temporarily removed from the connection pool. On one hand, this behavior is justified because if one of the instances is temporarily overloaded (e.g., due to a burst), we want to send fewer requests to it.
In practice, however, this is a very rare case, and the adaptive load balancing we have is usually fast enough to prevent hot spots. What we may observe instead is that either all the instances are overloaded (evenly) or the client (the distributor) itself is overloaded. In such cases, the availability of the write path might degrade due to circuit breaker flapping. Another interesting side effect is an increase in the number of segments created …
=> fix(v2): ignore client timeouts in write-path circuit breaker

pkg/api/api_experimental.go, pkg/experiment/metastore/admin/admin.go, pkg/experiment/metastore/admin/metastore.client.gohtml, pkg/experiment/metastore/admin/pages.go, pkg/experiment/metastore/client/client.go, pkg/experiment/metastore/client/methods.go, pkg/experiment/metastore/discovery/kuberesolver.go, pkg/experiment/metastore/discovery/kuberesolver_test.go, pkg/phlare/modules_experimental.go, pkg/phlare/phlare.go
**Background**
We have observed metastore client latency spikes during rollouts / leadership changes.
The client relies on error responses containing the new leader, however there is a mismatch in what the client expects and what metastore nodes return.
**Problem**
The metastore client discovers servers using the grpc port (9095) and maintains a map with addresses such as 
```pyroscope-metastore-0.pyroscope-metastore-headless.profiles-dev-003:9095```
Metastore nodes return the leader using the Raft port (9099) and the `svc.cluster.local` domain:
```pyroscope-metastore-0.pyroscope-metastore-headless.profiles-dev-003.svc.cluster.local.:9099```
This causes a failed check here: https://github.com/grafana/pyroscope/blob/f4cec5d93dfbb8b49940e569520655ef1a47731b/pkg/experiment/metastore/client/me …
=> Metastore client fix + admin test page

pkg/experiment/compactor/compaction_worker.go, pkg/experiment/metastore/compaction_raft_handler.go
Currently, a compaction job is abandoned by compaction workers if the blocks cannot be found in storage or if the metadata for the blocks cannot be retrieved. Such jobs remain incomplete and linger in the scheduler table indefinitely. This change enforces that compaction workers report an "empty" result for jobs that are known a priori to be uncompletable. The job entry is then removed from the compaction planner queue and the job scheduler, without replacing any blocks.
We need a mechanism that will evict such jobs, but this is out of scope of the PR.
=> chore(v2): improve error handling in compaction-worker

pkg/ingester/otlp/ingest_handler.go
With the new offcpu profiler, the profiler sends two profiles in a single request and the offcpu profile is empty if it is not enabled.
https://github.com/open-telemetry/opentelemetry-ebpf-profiler/blob/10b4b224857bcaab2fb0819e5a5c7c0cf6e03b07/reporter/internal/pdata/generate.go#L32-L36
Which leads to us sending empty requests 
```
time="2025-01-22T06:23:24Z" level=error msg="Request failed: rpc error: code = Unknown desc = failed to make a GRPC request: invalid_argument: no │
│  profiles received"            
```
=> fix(otel): ignore empty offcpu profile

docs/sources/configure-client/opentelemetry/ebpf-profiler.md
Removing misleading auto-generated block since it doesn't apply to otel ebpf.
=> docs: remove otel support misleading block

.github/workflows/test.yml, Makefile, docs/internal/contributing/README.md
- push to `grafana/` in dockerhub instead of `gcr`
- do not push `latest` tag
=> chore: migrate main builds from gcr to dockerhub

.github/workflows/test.yml, Makefile, cmd/pyroscope/debug.Dockerfile
Currently, we build only `linux/amd64` images on the main branch. This change adds support for the `linux/arm64` platform.
In addition, I disabled `debug` builds in CI for _the main branch_: they are rarely needed, especially urgently (since no guarantees are provided for the main branch builds). The debug image can still be built on demand, as debugging often requires multiple iterations, making `main` debug images less useful. Debug images for weekly builds and release versions are preserved.
=> chore(ci): push multi-arch image for main branch

.github/workflows/test.yml, Makefile
There are two issues in #3877: the multi-arch manifest is not pushed and the arch override may not be propagated properly. The PR fixes both.
I'm also adding `arm64` to the `build-image` step, so it runs on PRs.
=> fix(ci): push multi-arch manifest

.github/workflows/test.yml
We use different versions of `docker/setup-qemu-action` and `docker/setup-buildx-action` in various workflows: v2 for weekly builds and v1 for main and pr branches.
=> chore(ci): bump docker github actions

Makefile
Starting from `buildx` v0.10.0, `docker manifest` can no longer be used to create multi-platform images. This is due to a change in the output format, which now includes a _provenance attestation_ and creates a manifest list – something that `docker manifest` does not expect and cannot handle. Instead, `docker buildx imagetools` should be used to craft multi-architecture manifests.
We should also consider using `docker buildx imagetools` in weekly builds, where we re-push images using the standard Docker, which does not add attestation and, therefore, avoids this issue.
=> fix(ci): multi-arch build

.github/workflows/e2e.yaml, .github/workflows/test.yml
* Enables Go unit tests on arm64.
* arm64 e2e: enabled for the `regular path` only. The canvas library cypress depends on is not released for `linux/arm64`, so I had to add some dependencies.
* The test will take longer and will likely determine the overall CI workflow duration. Given that the test is not very extensive, we may consider disabling it. However, even a smoke test is better than nothing – this is why I kept it.
* Linting is still only run for `linux/amd64`. As long as we don't have arch-dependent code, this is fine. Let me know if you want to enable linting for arm64 as well.
Resolves #3880
=> chore(ci): run tests on both amd64 and arm64

examples/language-sdk-instrumentation/golang-push/rideshare-alloy/README.md, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/config.alloy, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/docker-compose.yml
This PR extends the rideshare-alloy example by adding label enrichment capabilities to demonstrate how to add meaningful metadata to profiles through the `pyroscope.relabel` component.
=> examples: Add pyroscope relabel componet in rideshare-alloy example

pkg/compactor/compactor_ring.go, pkg/distributor/distributor_ring.go, pkg/experiment/metastore/discovery/kuberesolver.go, pkg/scheduler/schedulerdiscovery/ring.go, pkg/scheduler/schedulerdiscovery/ring_test.go, pkg/storegateway/gateway_ring.go, pkg/validation/exporter/ring.go
Use Go's `net.JoinHostPort` instead of string formatting in ring lifecycler configuration to properly handle IPv6 addresses.
Fixes https://github.com/grafana/pyroscope/issues/3900
=> fix(ring): use net.JoinHostPort to support IPv6 addresses

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/ingest_limits/config.go, pkg/validation/usage_groups.go, pkg/validation/usage_groups_test.go
Continuation of #3879, adding support for reacting to externally configured ingestion limits for usage groups. The config model is extended from before:
```
ingestion_limit:
period_type: hour
period_limit_mb: 2048
limit_reached: true
next_limit_reset: 1738274400
sampling:
num_requests: 1
period: 2m
usage_groups:
group-1:
limit_reached: true
period_limit_mb: 1024
group-2:
limit_reached: false
period_limit_mb: 128
```
When the limit is reached, we add the usage group to the error response:
```
resource_exhausted: limit of 1.0 GiB/hour reached for usage group group-1, next reset at 2025-02-13T19:00:00Z
```
Usage groups use the global (tenant-level) period type and sampling config for simplicity, this might change in the future if needed.
=> Usage group support for ingestion limits

pkg/api/version/version.go, pkg/frontend/frontend.go
Add IPv6 support in 2 missing places.
Follow-up of https://github.com/grafana/pyroscope/pull/3903.
=> fix: add IPv6 support in missing places

.github/workflows/e2e.yaml, .github/workflows/fuzzer.yml, .github/workflows/release.yml, .github/workflows/test-examples.yml, .github/workflows/test.yml, .github/workflows/test_ebpf.yml, .github/workflows/weekly-release.yml, .goreleaser.yaml, examples/golang-pgo/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/simple/Dockerfile, examples/tracing/golang-push/Dockerfile, examples/tracing/golang-push/Dockerfile.load-generator
Now that 1.24.0 has been released, we should move on to 1.23
=> chore: Update golang version to 1.23.6

pkg/experiment/distributor/distributor.go, pkg/experiment/distributor/distributor_test.go
The PR fixed a bad seed chosen for Fisher-Yates permutations forming the shard mapping in the new distribution algorithm.
I've noticed that in case of unavailability, the data distribution has pronounces skews and decided to test this case. I discovered that with low number of nodes and shards, the mapping we generate is very poor – the random choice is extremely unfortunate: 
```
instance-0 [  35%][   6%] ###################################
instance-1 [  32%][  -3%] ################################
instance-2 [  32%][  -3%] ################################
-
instance-0 [   0%][ -99%]
instance-1 [  68%][ 105%] ####################################################################
instance-2 [  32%][  -3%] ################################
-
instance-0 [  35%][   6%] …
```
=> fix(v2): use better seed for shard placement

cmd/profilecli/canary_exporter.go
The change adds `service_name` label to the profiles ingested by canary exporter, and the label selector used to query it back. Without the `service_name` label selector, in the newest versions, the query hits tenant-wide dataset index, which is only created after L0 compaction and is usually delayed by ~15-30s. Therefore, canary-exporter queries return no data until then, and the probe fails due to empty response.
=> fix: add service_name label to the canary exporter

docs/sources/configure-client/language-sdks/nodejs.md, docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md, docs/sources/get-started/_index.md, docs/sources/get-started/ride-share-tutorial.md, docs/sources/shared/intro/continuous-profiling.md, docs/sources/shared/intro/flame-graphs.md, docs/sources/shared/use-explore-profiles.md, docs/sources/view-and-analyze-profile-data/_index.md, docs/sources/view-and-analyze-profile-data/explore-profiles.md, docs/sources/view-and-analyze-profile-data/pyroscope-ui.md
Updates for renaming Explore Traces to Traces Drilldown.  These changes were originally made in https://github.com/grafana/website/pull/23993
Repository: grafana/pyroscope
=> Rename Explore Apps to App Drilldown

docs/sources/configure-client/language-sdks/nodejs.md, docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md, docs/sources/get-started/_index.md, docs/sources/get-started/ride-share-tutorial.md, docs/sources/shared/intro/continuous-profiling.md, docs/sources/shared/intro/flame-graphs.md, docs/sources/shared/use-explore-profiles.md, docs/sources/view-and-analyze-profile-data/_index.md, docs/sources/view-and-analyze-profile-data/explore-profiles.md, docs/sources/view-and-analyze-profile-data/pyroscope-ui.md
Updates for renaming Explore Traces to Traces Drilldown.  These changes were originally made in https://github.com/grafana/website/pull/23993
Repository: grafana/pyroscope
=> [v1.12.x] Rename Explore Apps to App Drilldown

pkg/phlare/phlare.go
Use of unbuffered synchronous logger affects ingestion latency. In the worst case, if the output is redirected to a file, and the disk system does not cope with the log rate, it may cause 10+ sec. p99 spikes. The problem here is that distributors are stateless but may suffer from side-effects caused by neighbours, which makes it hard to identify the culprit.
=> perf: add log buffer

.github/workflows/release.yml, .github/workflows/weekly-release.yml, .goreleaser.yaml, Makefile
- **Build goamd64 v2 without suffixes**:  This handles the breaking problem from #3948 
- **Upgrade goreleser to v2.7.0**: Done it while I am touching this
Address deprecations:
- **Handle nproc correctly, also rm-dist is removed by clean**: 
- **Address DEPRECATED:  archives.format_overrides.format  should not be used anymore, check https://goreleaser.com/deprecations#archivesformat_overridesformat for more info**
- **Address DEPRECATED:  snapshot.name_template  should not be used anymore, check https://goreleaser.com/deprecations#snapshotname_template for more info**
=> Fix goreleaser build of goamd64v2

cmd/profilecli/canary_exporter.go
The PR adds a delay between canary probe ingestion and query requests. The delay is set to 2s by default. This delay might be needed if ingestion is asynchronous, as an ingest followed by an immediate query might not retrieve the data.
@simonswine I'm somewhat reluctant to set a default value here. On the other hand, I don't see much harm in doing so. What do you think?
=> chore: add canary probe delay

.github/workflows/weekly-release.yml
This weeks release, did fail but the CI pipeline was successful.  This change "should" prevent this from happening.
I will reproduce it and doublecheck the CI build fails
=> chore(goreleaser): Fix error handling during release

pkg/api/api.go, pkg/settings/settings.go
If one of the new settings services (CollectionRules, RecordingRules) is not enabled, the server will 500 when those endpoints are requested:
Request:
```
curl --request POST \
--url http://localhost:4040/settings.v1.CollectionRulesService/ListCollectionRules \
--header 'content-type: application/json' \
--data '{}'
```
Response:
```
HTTP/1.1 501 Not Implemented
Accept-Encoding: gzip
Content-Type: application/json
Date: Fri, 28 Feb 2025 16:16:59 GMT
Content-Length: 110
Connection: close
{
"code": "unimplemented",
"message": "settings.v1.CollectionRulesService.ListCollectionRules is not implemented"
}
```
Instead, we should 404 if the underlying service has not been enabled.
```
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Fri, 28 Feb …
```
=> fix: Don't 500 when setting services aren't registered

pkg/experiment/compactor/compaction_worker.go, pkg/phlare/modules_experimental.go
yaml and flag representations were not matching
=> Rename yaml representation of `metrics.Config`

pkg/phlare/phlare.go, pkg/util/logger.go, pkg/util/logger_test.go
The PR adds asynchronous log writer.
Recently implemented buffered logger (#3947) does not address the issue with blocking log writes:
The implementation we use flushes the buffer synchronously, blocking all callers. To address the problem, we should use asynchronous writer. The implementation in the PR implements a queue that is processed in background:
* when the queue is full, new writes are discarded.
* by default, the queue is large enough to store 20K messages or 5MB.
* errors are ignored since we can't do anything if stderr is not available (which is the cause of errors).
=> perf: add async log writer

docs/sources/_index.md
Currently all links with `<GRAFANA_VERSION>` in them are broken because that resolves to the current version of the Pyroscope documentation. For example, `latest` in `/docs/pyroscope/latest/` but `v1.13.x` in `/docs/pyroscope/v1.13.x/`.
This uses `latest` as a reasonable default.
If specific versions of Pyroscope target specific versions of Grafana, it may be worth updating this on those branches to match.
[About version substitution](https://grafana.com/docs/writers-toolkit/write/shortcodes/#about-version-substitution)
I'd like to backport this to all supported versions and any older ones, I can fix in the website repository
=> Set `GRAFANA_VERSION` in front matter

pkg/phlare/modules.go
The change enables native histogram buckets for the `pyroscope_request_duration_seconds` metric. As of now, it might be overly coarse, especially if the measured value exceeds 500ms.
=> chore(v2): enable native histograms in server metrics

pkg/experiment/metastore/compaction/scheduler/metrics.go, pkg/experiment/metastore/compaction/scheduler/metrics_test.go, pkg/experiment/metastore/compaction/scheduler/scheduler_queue.go, pkg/experiment/metastore/compaction/scheduler/testdata/metrics.txt
I discovered a panic in the compaction scheduler stats collector. The issue is that the scheduler queue may have gaps in levels – this is a completely valid case that wasn’t taken into account:
```
github.com/grafana/pyroscope/pkg/experiment/metastore/compaction/scheduler.(*statsCollector).collectStats(0xc00090f740, 0xc0009c3f50)
/home/runner/work/pyroscope/pyroscope/pkg/experiment/metastore/compaction/scheduler/metrics.go:85 +0x185
/home/runner/work/pyroscope/pyroscope/pkg/experiment/metastore/compaction/scheduler/metrics.go:118 +0x7b
```
=> fix(v2): scheduler metrics collector panics

pkg/experiment/ingester/segment.go, pkg/experiment/ingester/service.go, pkg/util/retry/hedged_test.go
This change adds an explicit, configurable static timeout for segment uploads.
Currently, the timeout is inherited from the distributor and is too high (5s by default). This makes retries inefficient if the bucket client happens to connect to a slow server or encounters other high-latency issues.
Additionally, I have disabled the FailFast option for hedged requests to prevent a situation where a failed hedged request (which is not retried) cancels the upload.
=> chore(v2): add segment upload timeout

.github/workflows/test.yml
As part of #3961 I noticed the doc-validator having some bugs (or rather more the review dog component).
Speaking with @jdbaldry there is not much maintenance going into the doc-validator and that he's planning to focus on a centralised vale ruleset.
So removing this in the meantime
=> Remove doc-validator

pkg/experiment/block/compaction.go, pkg/experiment/block/metadata/metadata_labels.go, pkg/experiment/block/metadata/metadata_labels_test.go, pkg/experiment/block/metadata/metadata_test.go, pkg/experiment/ingester/segment.go
The change makes working with metadata labels easier.
=> chore(v2): simplify metadata labels

pkg/distributor/write_path/router.go, pkg/distributor/write_path/write_path.go
The PR disables pprof gzip compression in the distributor-to-segment-writer path by default. This should be handled at the transport level.
This allows to save roughly 5-10% of CPU time in both distributors and segment-writers. However, this is only beneficial for all-in-one and single-AZ deployments (in cross-AZ deployments, ingest traffic should not leave the home zone).
=> feat(v2): configurable write-path compression

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/reference-configuration-parameters/index.md, pkg/phlare/phlare.go
This PR adds a delay before termination.
Microservice deployments typically assume a load balancer in front of the distributor and query-frontend services. During rollouts, load balancers are often updated immediately while a termination signal is sent to pods simultaneously, leading to failed requests.
Kubernetes is known to suffer from this issue. A common mitigation is adding a `preStop` hook with a sleep command in the spec manifest. The newly introduced option helps simplify this process.
The delay is disabled by default, as enabling it may require adjusting the termination timeout (`terminationGracePeriodSeconds` in Kubernetes).
=> chore: add optional shutdown delay

cypress/e2e/smoke.cy.ts, package.json, yarn.lock
This bumps @cypress/request to expected version: 
```
$ yarn list --pattern @cypress/request
yarn list v1.22.22
└─ @cypress/request@3.0.8
```
=> bump cypress to 13.0.0

pkg/experiment/block/dataset.go, pkg/experiment/block/section_profiles.go, pkg/phlaredb/symdb/block_reader.go, pkg/phlaredb/symdb/block_reader_parquet.go
I've run into the issue where a parquet table [page index](https://parquet.apache.org/docs/file-format/pageindex/) cannot be read:
```
failed to initialize query context:
opening section profiles:
opening profile parquet table:
reading page index of parquet file:
decoding column index: rowGroup=0 columnChunk=0/18: missing required field: 1:FIELD<LIST>
```
It's worth noting that the problem only manifests in some (unknown) cases. I suspect that the parquet metadata might be incomplete. Disabling the index solves the problem (we don't use it in fact).
=> fix(v2): disable parquet page index

pkg/phlaredb/symdb/stacktrace_tree_test.go
During the past hackathon I was looking at trying to optimize performance of different Grafana products, and I've found that the `*stacktraceTree.insert` method was consuming lots of CPU and memory. Everything indicated that the calls to `append` were the responsible ones, so I've added a new benchmark to compare how the existing benchmark for this operation behaves against different initial sizes (currently `0`).
This benchmark can be slow, thus it won't run unless the `COMPARE_STACKTRACETREE_INSERT_DEFAULT_SIZES` environment variable is set to true. In addition, if the `-v` flag is passed to `go test` it will print the initial and max tree size after inserting all the samples from the test profile.
These are the results I've got on my local development machine:
```
$ env …
```
=> Compare `*stacktraceTree.insert` against different initial sizes

pkg/objstore/client/config.go, pkg/objstore/client/factory_test.go
Our validation has been overly strict, since inception of the project.
Although we failed to call the validate alltogether. This was fixed in
This PR loosens the criteria accordingly
Fixes #3968
=> fix: Storage prefix validation

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/ingester/otlp/ingest_handler.go, pkg/ingester/otlp/ingest_handler_test.go, pkg/model/labels.go, pkg/test/integration/ingest_otlp_test.go
When looking at otel-ebpf-profiler I noticed we ignored their specification:
https://github.com/open-telemetry/opentelemetry-go/blob/ecfb73581f1b05af85fc393c3ce996a90cf2a5e2/semconv/v1.30.0/attribute_group.go#L10011-L10025
=> feat: Align missing service_name behaviour with otel spec

pkg/experiment/metastore/fsm/boltdb.go, pkg/experiment/metastore/fsm/fsm.go, pkg/experiment/metastore/fsm/snapshot.go, pkg/experiment/metastore/metastore.go, pkg/experiment/metastore/test/create.go
The PR enables `zstd` compression for FSM snapshots. It is not configurable, as there is no reason to write uncompressed snapshots. The change is fully backward compatible but not forward-compatible.
The compression ratio is generally very good, with the compressed snapshot being around 30–40% of the original size (given the default compression level). It is much better that `snappy`, and slightly better than `lzma`, while is comparable in terms of CPU time. `gzip` gives decent compression level as well, but utilizes significantly more CPU time.
=> feat(v2): metastore snapshot compression

.github/workflows/e2e.yaml, .github/workflows/fuzzer.yml, .github/workflows/release.yml, .github/workflows/test-examples.yml, .github/workflows/test.yml, .github/workflows/test_ebpf.yml, .github/workflows/weekly-release.yml, .goreleaser.yaml, examples/golang-pgo/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile, examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator, examples/language-sdk-instrumentation/golang-push/simple/Dockerfile, examples/tracing/golang-push/Dockerfile, examples/tracing/golang-push/Dockerfile.load-generator
go1.23.7 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to cgo, the compiler, and the reflect, runtime, and syscall packages. See the [Go 1.23.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.7+label%3ACherryPickApproved) on our issue tracker for details.
=> Update golang version to 1.23.7

.github/workflows/test-examples.yml, Makefile, examples/language-sdk-instrumentation/golang-push/rideshare-alloy/docker-compose.yml
This will fix the cronjob which tests our SDK examples on a nightly basis.
- We were running out of disk: bigger runner
- The bigger runner wasn't able to run the test in time before they get shutdown: decrease parallelism
=> test: Increase runner size and reduce parallelity

pkg/experiment/metastore/tombstones/tombstone_queue.go, pkg/experiment/metastore/tombstones/tombstone_queue_test.go, pkg/experiment/metastore/tombstones/tombstones_restore_test.go, pkg/experiment/metastore/tombstones/tombstones_test.go
The PR fixes a bug that prevented the oldest batch of tombstones from being scheduled for removal, causing it to remain in the queue indefinitely.
=> fix(v2): tombstone queue iterator ignores oldest tombstone

pkg/og/convert/pprof/profile.go, pkg/og/convert/pprof/profile_test.go, pkg/test/integration/ingest_pprof_test.go
I believe we should remove the whole function name rewriting altogether, and solve this issue in frontend, but that's for another change.
=> fix(ingest pyspy): remove line numbers from synthetic function names

pkg/experiment/metrics/ruler.go, pkg/settings/recording/client/client.go
Fixing the url for the tenant settings client.
Also removing an unused const.
=> fix(v2): fix tenant settings client address

pkg/experiment/metastore/fsm/fsm.go, pkg/experiment/metastore/fsm/snapshot.go, pkg/util/ratelimit/ratelimit.go, pkg/util/ratelimit/ratelimit_test.go, pkg/util/ratelimit/writer.go, pkg/util/ratelimit/writer_test.go
The PR adds a configuration option to limit the rate at which FSM snapshots are written on disk. This is useful in cases when the same disk is used for both WAL and snapshots.
=> feat(v2): metastore snapshot write rate limit

pkg/experiment/block/metadata/metadata_labels.go, pkg/experiment/block/metadata/metadata_labels_test.go, pkg/experiment/metastore/compaction/compactor/store/block_queue_store.go, pkg/experiment/metastore/compaction/scheduler/store/job_state_store.go, pkg/experiment/metastore/dlq/recovery.go, pkg/experiment/metastore/index/index.go, pkg/experiment/metastore/index/index_cache.go, pkg/experiment/metastore/index/query.go, pkg/experiment/metastore/index/query_test.go, pkg/experiment/metastore/index/store/index_store.go, pkg/experiment/metastore/metastore.go, pkg/experiment/metastore/store/store.go, pkg/experiment/metastore/tombstones/store/tombstone_store.go, pkg/test/mocks/mockindex/mock_store.go
The PR addresses an issue with blocking metadata queries.
Currently, we have a thick cache layer over the index stored in BoltDB, which is fully loaded into memory. The problem is that the cache is too coarse: an entire partition shard is used as a cache item. This requires broad locks and sophisticated cache management to ensure consistency with the on-disk state. Worse still, in certain cases, reads block writes for an extended period (seconds).
In the new version, we have two caches: one for partition shards (without blocks) and another for individual blocks. The first is primarily used as a skip index, while the latter is used to minimize resources spent on unmarshaling.
Queries never block the writer for longer than the time it takes to load the shard into memory (without blocks, …
=> feat(v2): non-blocking metadata queries

pkg/experiment/ingester/segment.go, pkg/experiment/ingester/segment_test.go, pkg/experiment/ingester/service.go
The PR adds configuration options to control the metastore client in the segment-writer service.
=> chore(v2): add segment-writer metastore client options

pkg/experiment/block/metadata/metadata_labels.go, pkg/experiment/block/metadata/metadata_labels_test.go, pkg/experiment/metastore/index/index.go, pkg/experiment/metastore/index/query.go, pkg/model/labels.go
The change eliminates the majority of allocations in metadata label queries. Currently, we use the standard label merger; however, this approach doesn't scale well on large datasets. Querying thousands (5–10K) of services over the past 7–14 days takes around 10 seconds.
While the change doesn't fully solve the problem – we still scan all metadata entries within the time range – it lays the groundwork for further improvements. Additional speedups (2–10×) could be achieved by storing a shard-level index.
In the meantime, the optimization significantly reduces CPU consumption and GC pressure, and speeds up queries by 2–4×. I'll attach some flame graphs after more intensive testing.
Depends on #4079
=> perf(v2): metadata label query optimization

docs/sources/release-notes/_index.md
As pointed out on the community slack, we don't document what releases are supported.
=> docs: State which versions we do maintain

pkg/experiment/query_backend/block_reader_test.go, pkg/experiment/query_backend/query_profile_entry.go, pkg/experiment/query_backend/query_series_labels.go, pkg/experiment/query_backend/testdata/fixtures/series_labels.json, pkg/experiment/query_backend/testdata/fixtures/series_labels_by.json
If a `SeriesLabels` query hits the dataset index (tenant-wide) we cannot use `SeriesIndex` there as it points the dataset and not specific series within it.
=> fix(v2): query series labels from dataset index

pkg/objstore/read_only_file.go, pkg/objstore/read_only_file_test.go
An error that occurs during object downloading in compaction workers may result in a panic. The reason is that one of the named return values is closed in a defer statement, but it may be nil if the error path is taken.
=> fix(v2): object download error branch panic

pkg/experiment/ingester/client/client.go, pkg/experiment/ingester/client/client_test.go, pkg/experiment/ingester/segment.go, pkg/experiment/ingester/service.go
Currently, the segment upload timeout is applied to each individual attempt. In practice, I saw that a configuration with 3 attempts and 1s timeout may take up to 5 seconds, which is not desirable.
This change modifies the behavior so that the timeout covers the entire upload routine – including backoff intervals, delays, and other overhead – making the process more predictable.
If a single attempt takes too long (e.g., due to a slow connection), it may be recovered using a hedged request. Regular retries are intended to recover from transient errors.
=> fix(v2): segment upload timeout

pkg/experiment/metastore/fsm/boltdb.go, pkg/experiment/metastore/fsm/boltdb_test.go, pkg/experiment/metastore/fsm/fsm.go
In many cases, BoltDB compaction is unnecessary and provides little benefit. However, it involves creating a full copy of the database, which can be wasteful. I'm adding a configuration option to control whether compaction is performed when restoring the DB from a snapshot (disabled by default).
This change also ensures that the uncompacted DB is used if compaction fails, and fixes a bug where compaction could fail due to leftovers from previous failed attempts.
=> chore(v2): make boltdb compaction configurable

cmd/pyroscope/help-all.txt.tmpl, cmd/pyroscope/help.txt.tmpl, docs/sources/configure-server/anonymous-usage-staticss-reporting.md, docs/sources/configure-server/anonymous-usage-statistics-reporting.md, docs/sources/configure-server/reference-configuration-parameters/index.md, docs/sources/configure-server/reference-configuration-parameters/index.template, docs/sources/get-started/_index.md, pkg/usagestats/reporter.go, tools/doc-generator/parse/root_blocks.go
Adds a page to explain anonymous usage stats. Based off of the [equivalent page in Mimir](https://grafana.com/docs/mimir/latest/configure/about-anonymous-usage-statistics-reporting/#which-information-is-collected). 
Fixes: https://github.com/grafana/pyroscope-squad/issues/397
=> 397 Add doc for anonymous usage stats

pkg/phlare/phlare.go
One day, we should make our component management more ergonomic. The fact that the server starts serving requests before components are fully initialized — and continues serving them after they're de-initialized — is the root of countless hard-to-diagnose issues. None of our components expect to handle requests after `Stop` is called.
The assumption that clients only interact with instances reporting `/ready` = true is incorrect – and so is the assumption that an instance stops receiving requests immediately after `SIGTERM`.
=> fix(v2): register metastore readiness check

pkg/frontend/read_path/query_frontend/query_frontend.go, pkg/phlare/modules.go
The change is needed to skip old query-frontend initialization (and thus the dependency on the query scheduler) if it's not used.
=> chore(v2): skip query-frontend initialization if it is not used

pkg/experiment/ingester/client/client.go, pkg/experiment/ingester/client/client_test.go, pkg/experiment/ingester/client/connpool/conn_pool_ring.go, pkg/experiment/ingester/service.go
The change forces the conn pool to actually create connections at initialization.
Also fixes the segment-writer grpc client config: currently, default values are used.
=> feat(v2): segment-writer client conn pool warm up

pkg/experiment/distributor/placement/adaptive_placement/config.go, pkg/experiment/distributor/placement/adaptive_placement/shard_allocator.go, pkg/experiment/distributor/placement/adaptive_placement/shard_allocator_test.go
This change fixes a potential overflow in the shard allocation logic. Additionally, it increases some of the default limits, which were previously too conservative.
=> fix(v2): shard limit overflow

pkg/experiment/query_backend/query.go
We currently rely on an adaptive concurrency limiter with gradient-based control to prevent exhausting the resources of query backend instances. While it generally works well, not all queries are equal or comparable, which is necessary for the limiter to be effective. Moreover, intra-block concurrency (e.g., between datasets) introduces significant error into the logic, as resource marshalling increases.
This is a minor change aimed at preventing query backend instances from running OOM: we now synchronize dataset processing. In practice, this means that a query spanning multiple tenant services will process them sequentially within the block context. The vast majority of queries target a single dataset. For the rest, no performance degradation is expected, as most queries are CPU-bound, …
=> chore(v2): block reader synchronous execution

pkg/experiment/ingester/client/client.go
A follow-up to #4121: In all-in-one mode, the segment writer might not be available when the distributor attempts to start. Therefore, the "empty ring" situation is expected. Eventually, once all components are initialized, the client will establish connections.
A proper solution would be to introduce component dependencies for the all-in-one mode (e.g., the distributor should wait for ingesters, and so on) in addition to module dependencies.
=> fix(v2): allow empty ring in segment-writer client

pkg/experiment/metastore/raftnode/node.go, pkg/experiment/metastore/raftnode/snapshot.go, pkg/experiment/metastore/raftnode/snapshot_test.go, pkg/experiment/metastore/raftnode/testdata/snapshots/81-206944-1744474737935/meta.json, pkg/experiment/metastore/raftnode/testdata/snapshots/81-206944-1744474737935/state.bin, pkg/experiment/metastore/raftnode/testdata/snapshots/82-215276-1744546508773/meta.json, pkg/experiment/metastore/raftnode/testdata/snapshots/82-215276-1744546508773/state.bin, pkg/experiment/metastore/raftnode/testdata/snapshots/83-223473-1744577537873/meta.json, pkg/experiment/metastore/raftnode/testdata/snapshots/83-223473-1744577537873/state.bin
Previously, raft configuration accepted a single directory parameter for all raft-related files. In practice, it's often desirable to separate the WAL and snapshot storage. To facilitate this, two new configuration parameters have been introduced:
* `snapshots-dir`: specifies the directory where Raft snapshots are stored. Overrides the default location.
* `snapshots-import-dir`: an optional parameter that simplifies migration of existing snapshots.
=> chore(v2): add option to specify raft fsm snapshot directory

operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
An option to include extra volume claim templates. Might be very helpful, e.g., to place different data (e.g. split by tenant) on different volumes.
The new `extraVolumeClaimTemplates` option is part of the `persistence.` member, in spite of other `extra*`. This is done so to avoid ambiguity.
=> chore(helm): extra volume claim templates

pkg/phlare/modules.go
The fix inverts the logic used to decide whether to initialize the old read path: if the `enable-query-backend` option is not specified, or if `enable-query-backend-from` is non-zero, the old read path should be used alongside the new one.
=> fix(v2): query-frontend initialization

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go
#4144 has introduced a bug where queries may ignore local data altogether as they wouldn't initialize the phlaredb instance and wouldn't sync metadata from the disk, if there were no pushes.
=> fix: initialize phlaredb instance on query

.github/workflows/weekly-release.yml
Tested it here works without: https://github.com/grafana/pyroscope/actions/runs/14735759777/job/41361308736
cc @aleks-p
=> chore: Github actions weekly, remove `actions: write` for git tag

pkg/experiment/metastore/index/query.go, pkg/experiment/metastore/index/query_test.go
Fixes a rare case in v2 where datasets in L0 blocks are not correctly filtered by tenant.
This code path is only used in the `Series` endpoint, and only when requesting these 2 sets of labels AND no query selector is provided:
Set 1:
- `__profile_type__` 
- `service_name`
Set 2:
- `__name__` 
- `__profile_type__` 
- `__type__` 
- `pyroscope_app`
- `service_name`
=> fix(v2): add missing tenant filter for metadata label queries

operations/pyroscope/helm/pyroscope/templates/deployments-statefulsets.yaml
#4128 broke for users that were giving contrasting annotation to the ones hardcoded
=> helm: Handle conflict between hardcoded user-supplied annotations

pkg/experiment/block/metadata/metadata_labels.go, pkg/experiment/ingester/memdb/head.go, pkg/experiment/ingester/memdb/head_test.go, pkg/experiment/ingester/segment.go
This reverts commit b19fa15fa6312520623e9448175ef14683fb9346 from #4147 . Once deployed to dev, see a fair bit of panics, can you take another look. The diff looks weird, maybe a rebase gone wrong?
```
goroutine 83546 [running]:
github.com/grafana/pyroscope/pkg/util.PanicError({0x2954940, 0xc0ee2b0288})
/home/runner/work/pyroscope/pyroscope/pkg/util/recovery.go:46 +0x4d
github.com/grafana/pyroscope/pkg/util.init.WithRecoveryHandler.func3.1({0x43a2e8?, 0x1?}, {0x2954940?, 0xc0ee2b0288?})
/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/options.go:33 +0x27
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x3908970?, 0xc0edfdb950?}, {0x2954940?, 0xc0ee2b0288?}, 0xc02a7ae540?)
/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middle …
```
=> Revert "feat: add __unsymbolized__ label on ingest path (#4147)"

pkg/experiment/block/metadata/metadata_labels.go, pkg/experiment/ingester/memdb/head.go, pkg/experiment/ingester/memdb/head_test.go, pkg/experiment/ingester/segment.go, pkg/experiment/ingester/segment_test.go
This PR adds the __has_native_unsymbolized_profiles__ label on the ingest path.
Original [PR](https://github.com/grafana/pyroscope/pull/4147) that made us discover the panics.
=> feat: add __unsymbolized__ label on ingest path

pkg/experiment/metastore/index/query_test.go
Add additional test for QueryMetadata, this ensures tenants are filtered as expected when blocks are retrieved through QueryMetadata.
=> v2: Add additional test for QueryMetadata

.github/workflows/ci.yml, .gitignore, Makefile
This will deploy the latest main build to a dev environment.
It first builds and pushes the image and then informs the internal argo workflow about the image tag and commit, in order to roll this out to dev.
See also https://github.com/grafana/deployment_tools/pull/256757
=> chore: CI bring back deploy on main

.github/workflows/helm-release.yml
We were using a GitHub app without permission for that action, this is using the https://github.com/apps/grafana-pyroscope-releases app, as we used before. The secret is now available in vault.
cc @korniltsev
=> Update helm release workflow

pkg/test/integration/cluster/cluster.go, pkg/test/integration/microservices_test.go
This adds multi tenant read path tests to the existing micro-services integration tests.
This tests currently only cover the default architecture. I plan to address v2 with a follow up PR.
=> chore: Add integration tests about tenant isolation

cmd/profilecli/canary_exporter.go, cmd/profilecli/canary_exporter_probes.go
Adds more checks/probes for the canary exporter. They are ran by a new flag `--query-probe-set all` (without this we will run the same checks as before).
Covers all endpoints of the querier service (except AnalyzeQuery and Diff which is not used today) as well as  `/render` and `/render-diff`.
=> feat: extend canary exporter checks

pkg/experiment/query_backend/block_reader.go, pkg/experiment/query_backend/block_reader_test.go, pkg/experiment/query_backend/metrics.go, pkg/phlare/modules_experimental.go, pkg/phlare/phlare.go
Validating the read block request so we ensure no foreign dataset is read
=> pyroscope(v2): query-backend tenant isolation check

examples/tracing/java/Dockerfile, examples/tracing/java/docker-compose.yml
Update the OTEL Java agent to the latest version. This is a major version upgrade, but it only required a small change to keep tracing happy.
=> chore: update Java OTEL agent version in tracing example

docs/sources/view-and-analyze-profile-data/profile-cli.md
The documentation for Linux propose to download version **1.1.5** of profilecli.
But version 1.1.5 does not support the `profile` subcommand. So I propose to update the link to a more recent version.
=> [profile-cli.md] Update link to recent profilecli release

cmd/profilecli/canary_exporter.go, pkg/experiment/metastore/index/query.go, pkg/experiment/metastore/index/query_test.go, pkg/experiment/metastore/index/store/index_store.go, pkg/experiment/metastore/index/store/index_store_test.go, pkg/frontend/read_path/query_frontend/query_select_time_series.go
Currently when the metastore is asked for blocks within a time range, the range check is exclusive (for the most part). Shards and blocks that start / end exactly at the query boundaries are skipped. The impact is more noticeable in low-ingest-throughput environments.
This PR changes this behavior so that the metastore will return all shards and blocks at the query boundaries. The data within the blocks is still expected to be filtered by each read endpoint individually.
Additionally, `QuerierService.SelectSeries` in v1 adjusts the query start by the step. I've applied the same logic in v2 for consistency.
=> fix(v2): make the metastore index search more broad

examples/language-sdk-instrumentation/python/rideshare/flask/Dockerfile
Small bugfix for the tutorial [linked from the docs](https://grafana.com/docs/pyroscope/latest/get-started/ride-share-tutorial/)
Currently, running `docker compose up -d`, I get the following error:
```
> [us-east 2/4] RUN pip3 install flask pyroscope-io==0.8.11 pyroscope-otel==0.4.0:                                                                                             
2.342 Collecting flask                                                                                                                                                          
2.391   Downloading flask-3.1.1-py3-none-any.whl (103 kB)                                                                                                                       
2.414      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 kB …
```
=> examples: Bump deps to fix dependency incompatibility

docs/sources/configure-client/language-sdks/python.md
Unfortunately SIP gets in the way of profiling system binaries on macOS using pyspy.
https://github.com/benfred/py-spy/issues/397#issuecomment-2627389627
=> docs: Add instructions about profiling on macOS

pkg/experiment/block/section_profiles.go, pkg/experiment/block/section_profiles_test.go
This bug explains how the column index was "corrupted": Bigger parquet footer, would not fit the estimatedSize and the code to fetch the longer footerSize was broken.
I have additionally added some test coverage for this.
I am also proposing to revert the skipping of the page index (from #4036), it will be easier catching bugs like this and it also will avoid downloading the footer twice, as we free it after open: 
https://github.com/grafana/pyroscope/blob/9d8285c4a3126742f40ede91a5d0be0dfe20ace2/pkg/experiment/block/section_profiles.go#L95-L105
=> fix: [v2] Read parquet footer correctly, when bigger than estimated

pkg/experiment/query_backend/client/client.go, pkg/experiment/query_backend/client/client_test.go
=> chore: use in-memory network connection to avoid query-backend concurrency test flake

pkg/experiment/metastore/compaction/compactor/compaction_queue.go, pkg/experiment/metastore/compaction/compactor/compaction_queue_test.go, pkg/experiment/metastore/compaction/compactor/plan.go, pkg/experiment/metastore/compaction/compactor/plan_test.go
This fixes an issue where compaction could stop completely.
Comments should provide exhaustive context:
1. We had a bug in time-based compaction. Specifically, we stopped tracking updates for a given compaction key. This is a rare but possible scenario that occurs when the oldest batch in a tenant-shard-level queue is removed from the priority queue used to track updates, while the queue itself is not removed. Batches added after this point won't be tracked. It was assumed that all batches would be processed by the time the oldest one is flushed, but this is not guaranteed in practice.
2. It can also happen that a compactor removes blocks from the staging batch, which was not expected. This is possible because the leader may decide to flush blocks that are still staged from the follower's …
=> fix(v2): compaction queue corruption

pkg/experiment/metastore/compaction/scheduler/metrics_test.go, pkg/experiment/metastore/compaction/scheduler/schedule.go, pkg/experiment/metastore/compaction/scheduler/scheduler.go
There's a race condition when the stats collector accesses the queue levels slice – we can actually modify it without holding the mutex, which was introduced specifically for metrics. Since all methods are called synchronously in the context of raft command execution, this does not affect the behavior of the compaction scheduler.
It was partially fixed in #4194 for schedule updates, but the race is also possible on schedule planning. It's difficult to hit this in the real life because the level slice is bound and quickly reaches its cap when the state is restored, and the number of levels does not change after that.
=> fix(v2): race in compaction scheduler metrics collector

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/experiment/ingester/segment.go, pkg/experiment/ingester/segment_test.go, pkg/experiment/ingester/service.go, pkg/ingester/ingester.go, pkg/validation/usage_groups.go, pkg/validation/usage_groups_bench_test.go, pkg/validation/usage_groups_test.go
Adds a special meaning to usage groups with placeholders (`${labels.label_name}`) in their names. When encountered AND there is a match with the provided selector, we replace placeholders with the actual label values.
This allows for a simpler and more powerful configuration of usage groups where this:
```
distributor_usage_groups:
cart-service: '{service_name="cart-service"}'
user-service: '{service_name="user-service"}'
order-service: '{service_name="order-service"}'
```
can be replaced with:
```
distributor_usage_groups:
'${labels.service_name}': '{}'
```
Benchmark results:
```
go test -bench=BenchmarkUsageGroups -benchmem ./pkg/validation
goos: darwin
goarch: arm64
pkg: github.com/grafana/pyroscope/pkg/validation
cpu: Apple M2 Pro
BenchmarkUsageGroups_Regular-10            	12253587 …
```
=> feat: dynamically named usage groups

pkg/experiment/block/section_profiles_test.go
This particular test creates the requires parquet files itself.
=> fix: Use tempdir for test instead ./testdata

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/distributor/sampling/config.go, pkg/validation/limits.go, pkg/validation/usage_groups.go, pkg/validation/usage_groups_test.go, pkg/validation/validate.go
Adds support for distributors to drop requests based on probabilistic sampling rules. 
The feature is tied to usage groups. Operators need to define usage groups first using the `distributor_usage_groups` tenant override and then add sampling rules via the `distributor_sampling` override. The sampling rules should target existing usage groups and provide a probability (0.0 means no profiles get through, 1.0 means all profiles are allowed).
The feature can make use of dynamically named usage groups (#4210). A valid example would be:
```
anonymous: # tenant id
distributor_usage_groups:
service/${labels.service_name}: "{}"
distributor_sampling:
usage_groups:
service/${labels.service_name}:
probability: 0.5
service/my-special-service:
probability: 1.0
```
In this example, we drop 50% of all …
=> feat: fine grained sampling

pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
... to avoid test flake from network dependency.
Partial fix for https://github.com/grafana/pyroscope/issues/3923
See https://github.com/grafana/pyroscope/pull/4213 for prior work.
=> chore: Use in-memory connection for scheduler tests

pkg/api/api.go, pkg/api/api_experimental.go, pkg/api/connect_options.go, pkg/api/register_options.go, pkg/phlare/phlare.go
This change refactors how the API handlers are registered. I am doing
this as I am plannig to add an artificial delay middleware to both push
and /ingest endpoints.
Comparing the registration logs ideally there should have been no
mistake:
```
diff before-log.txt after-log.txt
19d18
< level=debug msg="api: registering route" methods=GET,POST,PUT,DELETE,HEAD,OPTIONS prefix=/api auth=false gzip=true
22a22
> level=debug msg="api: registering route" methods=all prefix=/api auth=false gzip=true
```
=> chore: Refactor API handler registration

pkg/experiment/symbolizer/symbolizer.go, pkg/experiment/symbolizer/symbolizer_test.go
The symbolizer was incorrectly overwriting already-symbolized locations when processing profiles with `HasFunctions=false` mappings, even though individual locations already contained valid symbol information.
This mainly affected OTEL eBPF profiles where:
- Profiler successfully symbolizes some locations during collection but sets `HasFunctions=false` at mapping level
- Symbolizer overwrites existing symbols
While we plan to fix this upstream (OTEL profiler should set `HasFunctions=true` when locations have symbols), this defensive check ensures robustness against:
- Legacy profiles with inconsistent metadata
- Other profilers with similar issues
- Future data consistency problems
Skip already-symbolized locations in `groupLocationsByMapping()` before creating symbolization requests
=> fix: skip already-symbolized locations to preserve existing symbols

docs/sources/configure-client/language-sdks/python.md
* Import `os` so we can use `os.getenv()`
* In order for the contents of a string to be evaluated it needs to start with `f`
=> docs(language-sdks/python): Fix import and f-string

pkg/validation/validate.go, pkg/validation/validate_test.go
This reverts commit #4238, as they break the OTLP integration tests
=> Revert "Fix: Handle duplicate validation correctly when sanitizing (#4238)"

docs/sources/configure-server/configuring-github-integration.md, docs/sources/view-and-analyze-profile-data/line-by-line.md
This adds and adapts the grafana-cloud Github integration. 
Let me know what you think?
=> Add OSS documentation on the Source Code GitHub integration

cmd/pyroscope/help-all.txt.tmpl, pkg/api/api.go, pkg/api/register_options.go, pkg/ingester/pyroscope/ingest_handler.go, pkg/ingester/pyroscope/ingest_handler_test.go, pkg/util/body/limit.go, pkg/util/body/limit_test.go, pkg/validation/limits.go, pkg/validation/testutil.go, pkg/validation/validate.go
Properly approaches https://github.com/grafana/pyroscope/pull/4275
=> chore: add ingest request body size limit

pkg/ingester/otlp/convert.go
I got some `mapping index is required` errors while exporting valid profiles to Pyroscope. For those profiles I don't have mapping information, thus I'm setting `location.mapping_index = 0` for each location. This is a fully described behavior in the [spec](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/profiles/v1development/profiles.proto#L456), as `mapping_table[0]` must always be some sort of null mapping.
Since `location.mapping_index` [was marked](https://github.com/open-telemetry/opentelemetry-proto/blob/b6ec07ea76b29f149667ff3e4f5f43988fd4a24a/opentelemetry/proto/profiles/v1development/profiles.proto#L437) `optional`, it becomes a `*int32` rather than an `int32` in [opentelemetry-proto-go](https://github.com/open-telemetry/opentelemetry-proto-go …
=> Use `GetMappingIndex()` to access the mapping index of OTLP locations

README.md, docs/sources/configure-client/_index.md, docs/sources/configure-client/language-sdks/_index.md, docs/sources/configure-client/language-sdks/dotnet.md, examples/README.md
Update to match correct name of the technology.
=> docs: Fix .NET naming

cmd/profilecli/main.go, cmd/profilecli/v2-migration.go, pkg/cfg/cfg_test.go, pkg/cfg/files.go, pkg/cfg/precedence_test.go
As part of the v1 to v2 migration it is useful to clear out the bucket of old v1 blocks. This command will help to dry run this step and then also run the actual deletion.
The idea is based on a script from @aleks-p.
Generally ideas is you would run this using `kubectl exec` in a pod that has access to the bucket anyhow.
This is what it produced for my test example:
```
$ profilecli admin v2-migration bucket-cleanup --config.file ./cmd/pyroscope/pyroscope.yaml
DRY-RUN: If ran with --dry-run=false, this will delete everything under:
-  adaptive_placement/phlaredb/
-  anonymous/phlaredb/
-  blocks/phlaredb/
-  segments/phlaredb/
DRY-RUN: If ran with --dry-run=false, this will delete those object store keys:
-  adaptive_placement/phlaredb/bucket-index.json.gz
- …
```
=> chore: Add profilecli command to delete v1 blocks

pkg/frontend/vcs/token.go, pkg/frontend/vcs/token_test.go
When the cookie contains valid base64 in json, with an empty token field. We return a nil token and eat the innerError, which leads to nil pointer exception down the line.
=> fix: vcs.decodeToken can eat an error

pkg/distributor/distributor.go, pkg/distributor/distributor_test.go, pkg/validation/usage_groups.go, pkg/validation/usage_groups_test.go
Improves handling of overlapping usage groups, when performing sampling in distributors. A sampling rule defined by a more specific usage group now wins over one defined by a dynamic usage group.
A future improvement could be to also take label selectors into account, when deciding if one usage group is more specific than another.
=> Improve distributor sampling rule evaluation

docs/sources/configure-client/language-sdks/dotnet.md, docs/sources/configure-client/language-sdks/go_push.md, docs/sources/configure-client/language-sdks/java.md, docs/sources/configure-client/language-sdks/nodejs.md, docs/sources/configure-client/language-sdks/python.md, docs/sources/configure-client/language-sdks/ruby.md, docs/sources/configure-client/language-sdks/rust.md, docs/sources/shared/locate-url-pw-user-cloud-profiles.md
Adds documentation for locating the user, password, and URL in the Grafana Cloud Profiles stack. 
This PR:
* Add a shared file that explains how to find the user, password, and URL in the Grafana Cloud Profiles stack. 
* Inserts the shared file into all of the SDK docs
Fixes https://github.com/grafana/pyroscope/issues/3672
Related: https://github.com/grafana/website/pull/26886
=> [DOC] Add doc for finding URL, password, and user in Cloud Profiles

pkg/distributor/distributor.go, pkg/distributor/metrics.go, pkg/distributor/model/push.go
Suggesting new metrics for these issues
https://github.com/grafana/pyroscope-squad/issues/557
https://github.com/grafana/pyroscope-squad/issues/346
1. `distributor_received_decompressed_bytes_total` - incremented for each received profile as soon we try processing the profile, before any ratelimit/sampling checks
2. `distributor_processed_decompressed_bytes` - incremented after ratelimit/sampling checks at the exit of the processing routine with `defer` (note : potentially after normalization if the profile is valid)
TODO: add tests
=> distributor: add new metrics

pkg/metastore/discovery/kuberesolver/kubernetes.go
fix the problem, update the TLS configuration in the `NewInClusterK8sClient` function so that the minimum TLS version is set to `tls.VersionTLS12` instead of `tls.VersionTLS10`. This change should be made directly in the assignment to the `MinVersion` field of the `tls.Config` struct on line 89. No other changes are required, as the rest of the TLS configuration is appropriate. The fix only requires changing the constant used for the minimum version.
Wikipedia: [Transport Layer Security](https://en.wikipedia.org/wiki/Transport_Layer_Security)
Mozilla: [Security/Server Side TLS](https://wiki.mozilla.org/Security/Server_Side_TLS)
OWASP: [Transport Layer Protection Cheat Sheet](https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Protection_Cheat_Sheet.html)
=> fix(update): Insecure TLS configuration

pkg/distributor/distributor.go, pkg/distributor/distributor_recvmetric_test.go, pkg/distributor/metrics.go, pkg/distributor/model/push.go
Simplified version of https://github.com/grafana/pyroscope/pull/4377
See https://github.com/grafana/pyroscope-squad/issues/557
- remove `distributor_processed_decompressed_bytes`
- add "stage" label to the `distributor_received_decompressed_bytes_total`
- deprecate `distributor_received_decompressed_bytes`
=> distributor: collect receive metrics at multiple stages

.idea/runConfigurations/help.xml, .idea/runConfigurations/v1.xml, .idea/runConfigurations/v2.xml
I recently started using git work trees more and now for each corktree I create new run configurations.
I usually do not commit run configurations to not confuse non-jet brains users, but this time thinking it may be a good idea.
Jetbrains themselves seem to commit some of their common run configurations https://github.com/JetBrains/intellij-community/tree/master/.idea/runConfigurations so it dos not look like something completely crazy.
Curious what other jetbrains users think and what running configurations they have
This PR adds v1 and v2 run configurations with embedassets go tag.
This is how to save one, btw
=> jetbrains: commit run configurations for v1 and v2

pkg/frontend/readpath/queryfrontend/query_frontend.go, pkg/frontend/readpath/queryfrontend/query_profile_types.go, pkg/frontend/readpath/queryfrontend/query_profile_types_test.go, pkg/test/integration/microservices_test.go
When updating the storage layer to v2, we introduced a breaking change in the ProfileTypes API, while in v1 we would return, the last hour of profile types, we stopped doing that in v2 and showed an error
instead:
```
{"code":"invalid_argument","message":"missing time range in the query"}
```
In Grafana Tempo's datasource configuration this call is used without start/end parameters and therefore fails, see https://github.com/grafana/grafana/issues/110211.
I am proposing we maintain the old behaviour for ProfileTypes endpoint, until we announce a breaking change change as part of a major release.
We also should ensure that Grafana uses it with start and end parameters.
=> fix: Breaking change in ProfileTypes v2

pkg/distributor/distributor.go, pkg/pyroscope/pyroscope.go
This will allow us to investigate write path problems better.
Here few examples:
```
ts=2025-08-29T11:58:20.380943Z caller=distributor.go:395 component=distributor tenant=anonymous user=anonymous trace_id=5174ff0105f9fb8e level=warn msg="profile rejected" service_name=profilecli-upload profile_id=bcf63641-d59f-4e93-a67e-4313c8492d0f err="resource_exhausted: push rate limit (4.0 MiB) exceeded while adding 9.3 MiB"
ts=2025-08-29T11:59:01.013059Z caller=distributor.go:395 component=distributor tenant=anonymous user=anonymous trace_id=2d91abf859d32e67 level=debug msg="profile accepted" service_name=pyroscope profile_type=process_cpu detected_language=go profile_time=2025-08-29T12:58:30.504+01:00 ingestion_delay=30.033s decompressed_size=29605 sample_count=28
ts=2025-08-29T11:59:02.815882Z …
```
=> chore: Log details about each profile processed

pkg/compactionworker/worker.go
While analyzing the performance of Pyroscope deployments, I identified a goroutine leak introduced in [https://github.com/grafana/pyroscope/pull/4148](https://github.com/grafana/pyroscope/pull/4148?utm_source=chatgpt.com).
The problem is specific to the Minio S3 implementation of the object store client (I've only seen it in AWS, and not in every deployment). I'd suggest fixing it in the thanos package we use, but the issue is quite specific: in `bucket.Iter`, if we return from the iterator before the context is canceled, the internal producer/generator goroutine blocks forever (not exact versions, but this bit is unchanged):
1. https://github.com/minio/minio-go/blob/f64cdbde257f48f1a44b0f5aeee0475bad7e0e8d/api-list.go#L781-L788
2. …
=> fix: goroutine leak in compaction-worker

Makefile
```
$ make pyroscope/build
make: *** No rule to make target `go/bin-pyroscope', needed by `pyroscope/build'.  Stop.
$ make profilecli/build
make: *** No rule to make target `go/bin-profilecli', needed by `profilecli/build'.  Stop.
```
=> fix: `pyroscope/build` and `profilecli/build` had undefined rules in Makefile

pkg/symbolizer/symbolizer.go, pkg/symbolizer/symbolizer_test.go
Reverts 7ee3759f88dada1adcb833c30b249d5542df31c2 since it doesn't fix the real issue. 
Moreover, we shouldn't rely anymore in `hasFunctions` and add fixes in top of that since it won't work with new otlp versions (see https://github.com/grafana/pyroscope/pull/4439)
=> fix: revert HasFunctions flags for mixed symbolization

cmd/profilecli/client.go
This allows to easily connect via Grafana data source proxies:
```
PROFILECLI_URL=https://ops.grafana-ops.net/api/datasources/proxy/uid/grafanacloud-profiles PROFILECLI_TOKEN=glsa_xyz profilecli query series --label-names "service_repository"
```
=> feat: Support for bearer tokens in profilecli.

pkg/metastore/metastore.go, pkg/metastore/raftnode/node.go, pkg/metastore/raftnode/node_bootstrap.go, pkg/test/integration/cluster/cluster_v2.go, pkg/test/integration/microservices_test.go
When we want to increase the number of metastore replicas (e.g., to increase availability), currently we need to rely on the admin UI and manually add the new replicas to the Raft cluster.
This change adds a `-metastore.raft.auto-join` flag. When set to `true` **and** the application has no raft state (is a freshly created replica) - we will attempt to add the node to an existing Raft cluster using the same API endpoint used by the admin UI. If auto-join fails, we fallback to the existing behavior and the replica will need to be manually added.
Tested in a local cluster, as well as with the provided integration test.
=> feat: metastore auto-join
