grafana/pyroscope

.babelrc
babel.config.js
package.json
webapp/__tests__/Label.spec.js

This adds Jest, Enzyme and associated libraries. Also adds test for Label component.
Resolve #3

Add testing setup

---

.github/workflows/tests.yml

Add webapp tests to github actions

---

README.md

I think it would be helpful for people to have a general idea of what, conceptually, they have to do once they've downloaded pyroscope.

Update main readme with pyroscope diagram

---

.gitignore
Makefile
go.mod
go.sum
pkg/agent/session.go
pkg/analytics/analytics.go
pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/example.yml
pkg/config/config.go
pkg/exec/cli.go
pkg/server/controller.go
pkg/server/ingest.go
pkg/server/render.go
pkg/server/stats.go
pkg/storage/cache/cache.go
pkg/storage/key.go
pkg/storage/segment/segment.go
pkg/storage/segment/segment_test.go
webapp/__tests__/format.spec.js
webapp/javascript/components/FlameGraphRenderer.jsx
webapp/javascript/util/format.js

sorry this is not super structured, this is a bunch of small cleanups / improvements I've been wanting to do

Release 0.0.13

---

examples/README.md

added og text from RP 
will make new pull req with changes

add og text

---

.eslintrc
go.mod
package.json
webapp/javascript/components/DateRangePicker.jsx
webapp/javascript/components/DownloadButton.jsx
webapp/javascript/components/FlameGraphRenderer.jsx
webapp/javascript/components/Footer.jsx
webapp/javascript/components/Header.jsx
webapp/javascript/components/Label.jsx
webapp/javascript/components/LabelsFilter.jsx
webapp/javascript/components/MaxNodesSelector.jsx
webapp/javascript/components/NameSelector.jsx
webapp/javascript/components/PyroscopeApp.jsx
webapp/javascript/components/RefreshButton.jsx
webapp/javascript/components/ShortcutsModal.jsx
webapp/javascript/components/SlackIcon.jsx
webapp/javascript/components/TimelineChart.jsx
webapp/javascript/components/ZoomOutButton.jsx
webapp/javascript/index.jsx

* Enable JSX Lint
* Convert class components to function components
* Will refactor FlameGraphRenderer in follow-up

Refactor and Modernize Webapp

---

package.json
webapp/javascript/components/DateRangePicker.jsx
webapp/javascript/util/formatDate.js
webapp/sass/components/daterangepicker.scss
yarn.lock

this pull request is related to issue  [#47](https://github.com/pyroscope-io/pyroscope/issues/47)

Added a date and time picker

---

webapp/javascript/util/formatDate.js

these changes fix the issue [#55](https://github.com/pyroscope-io/pyroscope/issues/55) but I'm not satisfied with the code 
it needs a lot of improvement like:
if you spot anything else that must be changed like the code logic,  repetition pls let me know

split the code into reusable pieces, fixed issue#55

---

webapp/javascript/components/DateRangePicker.jsx
webapp/sass/components/daterangepicker.scss

-Issue 57, wrapped the container in a flexbox with flex-direction row
-Create label divs for the To and From labels

Fix Update button from falling out, add date range labels

---

webapp/javascript/components/PyroscopeApp.jsx
webapp/javascript/components/TimelineChart.jsx
webapp/sass/profile.scss

-Implemented crosshair functionality when hovering over timeline graph (issue [51](https://github.com/pyroscope-io/pyroscope/issues/51))
-Used blue to make crosshair pop when overlayed the gold bars

Crosshair implementation

---

scripts/webpack/webpack.common.js
webapp/javascript/components/Footer.jsx

I had some issues adding commits to the last pr so I opened a new one.

Import pyroscope version from package.json

---

.github/workflows/tests.yml
Makefile
pkg/agent/cli/agent.go
pkg/agent/logger.go
pkg/agent/profiler/profiler.go
pkg/agent/selfprofile.go
pkg/agent/session.go
pkg/agent/upstream/remote/remote.go
pkg/cli/cli.go
pkg/dbmanager/cli.go
pkg/exec/cli.go

Improves logging in gospy agent

---

examples/python/main.py

Fix Python3 Indentation - Following PEP8 style

Fix Python3 Indentation - Following PEP8 style

---

examples/python/Dockerfile
pkg/agent/pyspy/placeholder.go
pkg/agent/pyspy/pyspy.go
pkg/config/config.go
pkg/exec/cli.go
pkg/server/ingest.go
third_party/rustdeps/Cargo.lock
third_party/rustdeps/Cargo.toml
third_party/rustdeps/pyspy.h

Pyspy: defaults to non-blocking mode, adds an option to enable blocking

---

pkg/convert/parser.go
pkg/server/ingest.go

add the error handler for paring the tries

fix issue#163: nil reference when paring the tries

---

pkg/agent/cli/agent.go
pkg/agent/profiler/profiler.go
pkg/agent/selfprofile.go
pkg/agent/session.go
pkg/agent/session_test.go
pkg/agent/upstream/remote/remote.go
pkg/agent/upstream/remote/remote_test.go
pkg/analytics/analytics_test.go
pkg/cli/cli.go
pkg/exec/cli.go
pkg/server/controller.go
pkg/server/ingest_test.go

1. handle error when starting the server, remove the panic
2. make the logger always available, remove the nil check
3. optimize some logics for remote uploading profile

handle error when starting the server

---

benchmark/main.go
pkg/build/build.go
pkg/server/build.go
pkg/server/build_test.go
pkg/server/config.go
pkg/server/config_test.go
pkg/server/controller.go
pkg/server/healthz.go
pkg/server/ingest.go
pkg/server/ingest_test.go
pkg/server/labels.go
pkg/server/render.go

This is useful for debugging / ops people.

Adds new build and config endpoints

---

pkg/agent/upstream/remote/remote_test.go
pkg/analytics/analytics_test.go
pkg/server/build_test.go
pkg/server/config_test.go
pkg/server/controller.go
pkg/server/ingest_test.go

I'm hoping this will fix flaky tests

Switches to httptest everywhere

---

pkg/storage/tree/tree_test.go

This PR adds tests for storage/tree.Merge to cover:
- merging 2 similar trees
- merging 2 trees with differences in structure

Add test for storage/tree.Merge

---

pkg/storage/storage.go

Recently added support for tags lacks ability to filter dimensions based on key labels. This PR fills the gap.

Add dimension lookup by key labels

---

pkg/storage/tree/tree.go
pkg/storage/tree/tree_test.go

Some small improvement

---

.gitignore
Dockerfile
Makefile
pkg/agent/phpspy/phpspy.go
pkg/agent/pyspy/pyspy.go
pkg/agent/rbspy/rbspy.go

* fixes the issues with builds on linux
* improves phpspy build process

improves build stability on linux

---

go.mod
go.sum
scripts/dbtool/cmd/get.go
scripts/dbtool/cmd/list.go
scripts/dbtool/cmd/remove.go
scripts/dbtool/cmd/root.go
scripts/dbtool/main.go

A tiny helper for simplifying debug.

Add dbtool

---

Makefile

Fixes #326 
Signed-off-by: Yash Sharma <yashrsharma44@gmail.com>

Added a make help target for listing out all the commands

---

pkg/server/controller.go
pkg/server/handler.go
pkg/util/updates/updates.go
webapp/javascript/components/Footer.jsx
webapp/sass/profile.scss
webapp/templates/index.html

Adds an "Updates Available" label to the footer

---

pkg/server/handler.go
webapp/javascript/components/Notifications.jsx
webapp/javascript/index.jsx
webapp/sass/profile.scss
webapp/templates/index.html

This is what it looks like right now:

Adds frontend support for notifications

---

.github/workflows/cypress-tests.yml
Makefile
cypress.json
cypress/README.md
cypress/fixtures/example.json
cypress/integration/basic.ts
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
cypress/tsconfig.json
package.json
webapp/javascript/components/Sidebar.jsx
yarn.lock

very basic implementation just to get started

Add cypress

---

cypress/integration/basic.ts
webapp/__tests__/__snapshots__/NameSelector.spec.js.snap
webapp/__tests__/__snapshots__/ProfilerHeader.spec.js.snap
webapp/javascript/components/FlameGraphRenderer.jsx
webapp/javascript/components/ProfilerHeader.jsx
webapp/javascript/components/ProfilerTable.jsx

https://github.com/pyroscope-io/pyroscope/issues/356
This is only the first item from the issue, just to dig my toe in the water.

tests for table/both/flamegraph buttons (issue #356)

---

Makefile
scripts/webpack/webpack.common.js
scripts/webpack/webpack.panel.js

adds a webpack config for grafana panel

---

pkg/storage/dimension/dimension.go
pkg/storage/dimension/dimension_test.go

Although the new implementation is pretty expensive, it should not be an issue given that it is still in order of microseconds (and will never be the main factor of querying performance). I also think we should migrate to bitmaps for better set operations.

Fix intersection

---

package.json
scripts/webpack/webpack.common.js
scripts/webpack/webpack.dev.js
yarn.lock

adds another server on port 4041
that serves the app with live reload

chore(webapp): add live reload

---

README.md
examples/python/README.md
examples/ruby/README.md
examples/ruby/lib/utility/utility.rb
examples/ruby/load-generator.py

Missed a few files in #429 and then also updated some links

Cleanup docs / add more links

---

package.json
webapp/javascript/components/ExportData.jsx
webapp/javascript/components/ExportData.tsx
yarn.lock

As per https://github.com/pyroscope-io/pyroscope/issues/451
Get rid of PDF exports

chore: get rid of pdf export

---

pkg/exec/cli.go
pkg/exec/cli_windows.go
pkg/exec/config.go
pkg/exec/config_test.go

I also think we need to include windows build into the PR pipeline, at least as a pre-flight check.

Fix redeclared exec

---

pkg/storage/labels/labels.go
pkg/storage/storage_delete.go
pkg/storage/storage_test.go

The PR is aimed to solve a bug when labels are not being deleted.

Remove labels on delete

---

package.json
scripts/webpack/webpack.common.js
yarn.lock

This should fix webpack's problem with nodejs v17:
https://github.com/webpack/webpack/issues/14532

Bump webpack version.

---

pkg/util/hyperloglog/hyperloglog_test.go

As explained in https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-async-testing

chore: migrate test for Ginkgo v2.

---

cypress.json

Seems 2 times is not enough (I had a PR failing due to that), let's see if 5 is a good number.

chore: increase cypress tests retries

---

Makefile

Latest version should fix compilation in some Linux systems.

chore: Bump phpspy version.

---

README.md
stories/Dropdown.stories.tsx
webapp/javascript/ui/Dropdown.module.scss
webapp/javascript/ui/Dropdown.tsx

https://github.com/pyroscope-io/pyroscope/issues/548
Created a dropdown component and a storybook story for it.

Dropdown component

---

.github/workflows/tests-go-linux.yml
.github/workflows/tests-go-windows.yml

- Added go-tests CI running on windows
- Rename Linux tests for consistency

Added windows tests CI ,rename linux tests CI

---

.github/workflows/tests-go.yml
README.md
benchmark/internal/cireport/cireport_test.go
pkg/admin/admin_integration_test.go
pkg/admin/admin_test.go
pkg/admin/client_test.go
pkg/admin/http_over_uds_server_test.go
pkg/cli/cli_suite_test.go
pkg/server/server_suite_test.go
pkg/storage/cache/cache_test.go
pkg/storage/storage_test.go

- Added matrix to specify OS Ubuntu and Windows

chore: Added support to run tests on windows

---

docs/storage-design.md
pkg/agent/pprof/proto.go
pkg/agent/session.go
pkg/storage/segment/timeline.go

Some typos that I noticed while working my way through code.

Fix typos.

---

README.md

Update gif in readme

---

examples/pull/kubernetes/manifests.yaml
examples/pull/static/docker-compose.yml

Replaces temp images with publicly accessibly ones.

chore: update pull example image

---

examples/python/README.md

fix: typo in readme

---

examples/adhoc/AdhocPush.java

It requires a release with https://github.com/pyroscope-io/pyroscope-java/pull/5 to work properly, and it'll still suffer from https://github.com/pyroscope-io/pyroscope-java/issues/6

docs: add adhoc push example in Java.

---

README.md
examples/ebpf/README.md
examples/golang/main.go
examples/grafana-integration/README.md
examples/grafana-integration/docker-compose.yml
examples/java/README.md
examples/java/docker-compose.yml
examples/metrics-export/app/Dockerfile

Noticed that several of our examples have gotten out of sync so this is to update them to make sure that they work as expected and have README.md with instructions:
Todo: 
- Check eBPF example

docs: Update/Audit Examples 

---

pkg/cli/server.go

perf: improves reliability of self profiler

---

scripts/webpack/webpack.dev.ts
stories/Dropdown.stories.tsx
webapp/javascript/components/TagsBar.jsx
webapp/javascript/ui/Dropdown.module.scss
webapp/javascript/ui/Dropdown.tsx
webapp/sass/components/tagsbar.scss

Related to #618 
* Use `@ui/Dropdown` component (which uses szhsin/react-menu under the hood)
* Add a scrollbar for when tags don't fit on the screen
* Add search bar for each tag
https://user-images.githubusercontent.com/6951209/147134054-e9f378a1-70dd-4f94-8f11-544bb27cd752.mp4

feat(frontend): new tags dropdown

---

examples/golang-push/rideshare/Dockerfile
examples/golang-push/rideshare/bike/bike.go
examples/golang-push/rideshare/car/car.go
examples/golang-push/rideshare/go.mod
examples/golang-push/rideshare/main.go
examples/golang-push/rideshare/scooter/scooter.go
examples/grafana-integration/docker-compose.yml

In #605 added a rideshare example, but then changing it to subdirectory broke it

Update rideshare example

---

go.mod
pkg/cli/server.go
pkg/scrape/discovery/file/file.go

add this feature. 
https://github.com/pyroscope-io/pyroscope/issues/640

feat(pull-mode): adds file discovery mechanism

---

examples/ebpf/docker-compose.yml
examples/golang-push/README.md
examples/golang-push/rideshare/bike/bike.go
examples/golang-push/rideshare/car/car.go
examples/golang-push/rideshare/scooter/scooter.go
examples/golang-push/rideshare/utility/utility.go
examples/python/README.md
examples/ruby/README.md

Adds golang blog similar to the Python and Ruby ones

Add golang blog/walkthrough

---

go.mod
pkg/cli/server.go
pkg/scrape/discovery/http/fixtures/http_sd.good.json
pkg/scrape/discovery/http/http.go
pkg/scrape/discovery/http/http_test.go
pkg/scrape/model/time.go

we need to scrape some targets temporarily. this way would be a convient way to add targets.

feat: add  http discovery mechanism

---

webapp/javascript/components/TimelineChartWrapper.jsx

…fixing almost all issues with selection
Related to:
- https://github.com/pyroscope-io/pyroscope/issues/621
- https://github.com/pyroscope-io/pyroscope/issues/713

fix(frontend): shifted actual data 5 seconds forward

---

webapp/javascript/components/FileUploader.module.scss
webapp/javascript/components/FileUploader.tsx

Updates drag and drop styling:
From this:
To this:

Update drag and drop styling

---

pkg/structs/flamebearer/html.go
webapp/javascript/components/FlameGraph/FlameGraphRenderer.jsx
webapp/javascript/components/ProfilerHeader.module.css
webapp/javascript/components/Toolbar.spec.tsx
webapp/javascript/components/Toolbar.tsx
webapp/javascript/standalone.module.scss
webapp/javascript/standalone.tsx
webapp/templates/standalone.html

This adds a logo to the top of the page and also add a footer with build info, it's implemented the same way as in the regular pages. 
Toolbar:
Footer:

chore(standalone): adds logos to standalone html

---

examples/adhoc/README.md
webapp/javascript/components/FileUploader.module.scss
webapp/javascript/components/FileUploader.tsx

Updating drag and drop styling and also sneaking in some changes to adhoc examples folder to simplify / shorten text

chore: Update adhoc drag-and-drop styling

---

examples/golang-push/rideshare/utility/utility.go

docs: update golang push example

---

.github/workflows/cypress-base-url.yml
.github/workflows/cypress-datasource.yml
.github/workflows/cypress-panel.yml
.github/workflows/cypress-tests.yml
.github/workflows/tests-js.yml

Relates to https://github.com/pyroscope-io/pyroscope/issues/696

ci: run actions/cache to cache yarn deps

---

package.json
pkg/server/controller.go
webapp/javascript/components/Settings/APIKeys/APIKeyAddForm.tsx
webapp/javascript/components/Settings/APIKeys/APIKeyForm.module.css
webapp/javascript/components/Settings/APIKeys/index.tsx
webapp/javascript/components/Settings/Preferences.tsx
webapp/javascript/components/Settings/Security/ChangePasswordForm.tsx
webapp/javascript/components/Settings/Security/Security.module.css
webapp/javascript/components/Settings/Security/index.tsx
webapp/javascript/components/Settings/Settings.module.css
webapp/javascript/components/Settings/SettingsTable.module.css
webapp/javascript/components/Settings/Users/UserAddForm.tsx
webapp/javascript/components/Settings/Users/UserForm.module.css
webapp/javascript/components/Settings/Users/UserTableItem.module.css
webapp/javascript/components/Settings/Users/UserTableItem.tsx
webapp/javascript/components/Settings/Users/index.tsx
webapp/javascript/components/Settings/index.tsx
webapp/javascript/components/Sidebar.tsx
webapp/javascript/redux/reducers/settings.ts
webapp/javascript/redux/reducers/user.ts
webapp/javascript/services/users.ts
webapp/javascript/ui/Button.module.scss
webapp/javascript/ui/Button.tsx
webapp/sass/login.scss
webapp/templates/login.html
webapp/templates/signup.html
yarn.lock

Short summary of changes are below:
Missed:

fix: visual inconsistency on user management pages

---

webapp/javascript/ui/Dropdown.tsx

Preventing submit on every dropdown change

fix(frontend): quickfix for wierd dropdown behaviour

---

pkg/adhoc/cli.go

fix: handle properly writing errors in adhoc mode.

---

pkg/adhoc/server/model.go
pkg/adhoc/server/server.go

feat: add an upload diff endpoint for adhoc mode.

---

package.json
scripts/oauth-mock/README.md
scripts/oauth-mock/oauth-mock.js
scripts/oauth-mock/pyroscope-config.yml
yarn.lock

cc @eh-am @kolesnikovae @shaleynikov

ci: adds oauth mock

---

pkg/adhoc/server/model.go

The old one had an invalid sample type.

docs: fix profile example in adhoc's upload model.

---

packages/pyroscope-flamegraph/package.json
packages/pyroscope-flamegraph/src/index.spec.tsx
packages/pyroscope-flamegraph/src/index.tsx
packages/pyroscope-panel-plugin/package.json

until we figure out a nice watermark

fix: disable pyroscope logo

---

cypress/integration/panel/basic.ts
packages/pyroscope-panel-plugin/src/module.ts

Otherwise grafana will try to load it and raise an exception.

fix(panel-plugin): don't load CSS file since it's loaded using css modules

---

Makefile

fix: correct typo in dev Makefile target's depedency.

---

pkg/api/authz/authz.go
pkg/server/controller.go

Closes https://github.com/pyroscope-io/client/issues/7.

fix: agent authorization

---

.github/workflows/fix-conflicts.yml

This PR will solve the Issue #692

chore: Added action to solve conflicts on yarn.lock and go.sum

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.jsx
stories/Flamegraph.stories.tsx

Previously there was a bug where a profile would change but the component would not be refreshed.

fix(flamegraph): rerender when 'profile' changes

---

examples/tracing/jaeger/go.mod
examples/tracing/jaeger/go.sum
examples/tracing/jaeger/log/log.go
examples/tracing/jaeger/ride/ride.go

Add `trace_id` and `profile_id` to logs

chore: add trace logger example

---

webapp/javascript/components/NameSelector.tsx
webapp/javascript/components/TagsBar.tsx
webapp/javascript/ui/Dropdown.tsx

Fixed: https://github.com/pyroscope-io/pyroscope/issues/758
Demo: https://monosnap.com/file/FIVtgpV6YC2mk5jvihNQTaJojkczRa
Demo for tag selector: https://monosnap.com/file/YJ6cuKemgjpRQHkWC59SpqlFbdwUTh

chore(webapp): app and tags selectors search position adjustment

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
packages/pyroscope-flamegraph/src/Toolbar.spec.tsx
packages/pyroscope-flamegraph/src/Toolbar.tsx

Closes https://github.com/pyroscope-io/pyroscope/issues/970

fix(flamegraph): only show diff options when in diff mode

---

pkg/util/hyperloglog/hyperloglog_test.go

chore: disable hyperlog tests on windows

---

examples/rust/basic/Cargo.lock
examples/rust/basic/Cargo.toml
examples/rust/basic/src/main.rs
examples/rust/rideshare/server/Cargo.lock
examples/rust/rideshare/server/Cargo.toml
examples/rust/rideshare/server/src/main.rs

refactor(rust): update rust examples

---

webapp/javascript/services/appNames.ts
webapp/javascript/services/tags.ts
webapp/javascript/ui/Dropdown.tsx

* allows for more customization in `Dropdown` component
* allows for label-values to work on pages other than `/`

refactor(frontend): small improvements

---

packages/pyroscope-models/package.json

Closes https://github.com/pyroscope-io/pyroscope/issues/1020

build(models): publish models as npm package

---

examples/tracing/jaeger/README.md
examples/tracing/jaeger/docker-compose.yml
examples/tracing/jaeger/jaeger-ui/Dockerfile

docs(examples): adds a custom jaeger ui

---

examples/tracing/jaeger/docker-compose.yml
examples/tracing/jaeger/jaeger-ui/Dockerfile
examples/tracing/jaeger/pyroscope.yaml

Update tracing example to have proper embedded flamegraph

Update tracing example

---

examples/tracing/jaeger/README.md
examples/tracing/jaeger/ride/ride.go

Updates jaeger example to exhibit the "baseline" behavior

docs: Update jaeger example

---

webapp/sass/profile.scss

Reverts pyroscope-io/pyroscope#1053

Revert "fix(flamegraph): fix table contrast"

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Header.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.spec.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx

FIX: https://github.com/pyroscope-io/pyroscope/issues/1072

feat(flamegraph): User should be able to adjust title visibility over the Flamegraph

---

webapp/javascript/services/render.ts

I saw this in Network tab, I think this is a typo
/cc @eh-am

chore: fix a typo

---

packages/pyroscope-flamegraph/package.json
scripts/webpack/webpack.flamegraph.ts

Closes https://github.com/pyroscope-io/pyroscope/issues/1101
Plus ships sourcemaps.

fix(flamegraph): don't ship react-dom

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/DiffLegendPaletteDropdown.module.css

fix: flamegraph palette selector button styles

---

examples/tracing/jaeger/ride/ride.go

Introduced an error in #1128 this fixes that

docs: cleanup tracing example

---

examples/java-jfr/rideshare/README.md

Fixes a few typos and cleans up the example

docs: Update java rideshare example

---

webapp/javascript/components/FileList.jsx
webapp/javascript/components/FileList.module.scss

[#1173](https://github.com/pyroscope-io/pyroscope/issues/1173)
https://user-images.githubusercontent.com/47758224/176410781-fe028a35-e8c2-45a1-9513-bb29277a49f2.mov

feat: add adhoc sort by date

---

packages/pyroscope-flamegraph/src/ProfilerTable.module.scss
packages/pyroscope-flamegraph/src/SharedQueryInput.module.scss
webapp/javascript/components/CustomDatePicker.module.scss
webapp/javascript/components/ExportData.module.scss
webapp/javascript/components/FileList.module.scss
webapp/javascript/components/FileUploader.module.scss
webapp/javascript/components/NameSelector.module.scss
webapp/javascript/components/NameSelector.tsx
webapp/javascript/components/Settings/Settings.module.css
webapp/javascript/components/Settings/SettingsTable.module.css
webapp/javascript/components/Settings/Users/Users.module.css
webapp/javascript/pages/IntroPages/IntroPages.module.css
webapp/javascript/pages/IntroPages/SignIn/buttons.module.css
webapp/javascript/ui/Box.module.scss
webapp/javascript/ui/Button.module.scss
webapp/javascript/ui/Dropdown.module.scss
webapp/javascript/ui/Input.module.scss
webapp/javascript/ui/Modals/Modal.module.css
webapp/javascript/ui/Select.module.scss
webapp/javascript/ui/Sidebar.scss
webapp/javascript/ui/Tooltip.module.scss
webapp/sass/common.scss
webapp/sass/components/button.scss
webapp/sass/components/daterangepicker.scss
webapp/sass/components/labels.scss
webapp/sass/components/tagsbar.scss
webapp/sass/variables.css

cleaning up / consolidating more variables and fixing color of application input box

chore: cleanup / consolidate variables

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/canvas.module.css
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.spec.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlamegraphRenderer.module.scss
packages/pyroscope-flamegraph/src/NoProfilingData.module.scss
packages/pyroscope-flamegraph/src/NoProfilingData.tsx
packages/pyroscope-flamegraph/src/ProfilerTable.jsx

[#1061](https://github.com/pyroscope-io/pyroscope/issues/1061)
https://user-images.githubusercontent.com/47758224/176726578-82d0fbef-fcfe-4fa6-861c-d42e73958623.mov

feat(frontend): show "No profiling data available for this application / time range." message independently of the visualization

---

packages/pyroscope-flamegraph/src/SharedQueryInput.module.scss
webapp/javascript/components/CustomDatePicker.module.scss
webapp/javascript/components/ExportData.module.scss
webapp/javascript/components/FileList.module.scss
webapp/javascript/components/FileUploader.module.scss
webapp/javascript/pages/IntroPages/IntroPages.module.css
webapp/javascript/pages/IntroPages/SignIn/buttons.module.css
webapp/javascript/ui/Box.module.scss
webapp/javascript/ui/Button.module.scss
webapp/javascript/ui/Dropdown.module.scss
webapp/javascript/ui/Input.module.scss
webapp/javascript/ui/Modals/Modal.module.css
webapp/javascript/ui/Select.module.scss
webapp/javascript/ui/Tooltip.module.scss
webapp/sass/common.scss
webapp/sass/components/button.scss
webapp/sass/components/daterangepicker.scss
webapp/sass/components/labels.scss
webapp/sass/components/tagsbar.scss
webapp/sass/variables.css

Cleaning up immutable variables / giving better names

chore: cleanup immutable variables

---

webapp/javascript/components/Settings/APIKeys/APIKeyAddForm.tsx
webapp/javascript/components/Settings/APIKeys/APIKeyForm.module.css

#1076 
https://user-images.githubusercontent.com/47758224/177331808-3d7e59c0-85dd-4478-bd06-8dc027e5394c.mov

feat: add an explanation for what each API Key Role is for

---

cypress/integration/webapp/basic.ts
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.spec.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.tsx
webapp/javascript/components/TimelineChartWrapper.tsx
webapp/javascript/components/TimelineTitle.module.scss
webapp/javascript/components/TimelineTitle.tsx
webapp/javascript/pages/ContinuousComparisonView.tsx
webapp/javascript/pages/ContinuousDiffView.tsx
webapp/javascript/pages/ContinuousSingleView.tsx
webapp/sass/profile.scss

feat: add titles to charts / flamegraphs

---

webapp/javascript/hooks/populateLeftRightQuery.hook.ts
webapp/javascript/pages/ContinuousComparisonView.tsx
webapp/javascript/pages/ContinuousDiffView.tsx
webapp/javascript/pages/ContinuousSingleView.tsx

https://user-images.githubusercontent.com/47758224/177382161-31767f11-d859-4a6c-b16e-6e644493b7c1.mov

fix: single view app update should change comp/diff view left and right apps

---

webapp/javascript/ui/Sidebar.scss
webapp/sass/variables.css

fix: add sidebar separation lines

---

webapp/javascript/components/AppSelector/SelectorModal.module.scss
webapp/javascript/components/AppSelector/SelectorModal.tsx

Noticed a couple of bugs in the flow when using demo-dev.pyroscope.io and cleaned up a little extra code too.
cc @pavelpashkovsky

frontend: improves app name grouping logic

---

examples/golang-push/rideshare/main.go
examples/golang-push/simple/main.go

Related to https://github.com/pyroscope-io/pyroscope/issues/198
Let's show error handling in examples, so that people are aware it's possible and a good practice to do so.

docs(golang-push): show error handling in examples

---

.eslintrc.js
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Flamegraph_render.ts
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/search.ts
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
packages/pyroscope-flamegraph/src/ProfilerTable.jsx
packages/pyroscope-flamegraph/src/search.spec.ts
packages/pyroscope-flamegraph/src/search.ts

* filter items in the table when a query is input
* add a hidden state that distinguishes between an item in the table being selected
* update highlight case insensitive
https://user-images.githubusercontent.com/6951209/177862371-5c1573d0-7230-418f-8dbc-7a4b2d00f697.mp4

feat(flamegraph): allow to filter items in table

---

README.md

Adds a table to the readme to replace the list of bullet points:

docs: Add readme table

---

examples/golang-push/rideshare/docker-compose.yml
webapp/javascript/components/AppSelector/SelectorModal.module.scss
webapp/javascript/components/ExportData.module.scss
webapp/javascript/components/Sidebar.tsx
webapp/javascript/components/TagsBar.module.css
webapp/javascript/ui/Button.module.scss
webapp/javascript/ui/Dropdown.module.scss
webapp/javascript/ui/Select.module.scss
webapp/sass/components/daterangepicker.scss
webapp/sass/variables.css

we're getting closer and closer to lightmode being release-able
things that still need some love
- single timeline: yellow is hard to see on white background
- timeline tooltip: ugly border
- comparison timeline: both pink and blue should be different colors probably

chore: Update light mode colors

---

.gitignore
cypress/integration/webapp/basic.ts
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.module.scss
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.spec.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.tsx
webapp/sass/components/tagsbar.scss
webapp/sass/variables.css

[#1234](https://github.com/pyroscope-io/pyroscope/issues/1234)

feat: add new tooltip design

---

examples/nodejs/express-pull/docker-compose.yml
examples/nodejs/express-pull/index.js
examples/nodejs/express-pull/server.yml
examples/nodejs/express-ts/docker-compose.yml
examples/nodejs/express/docker-compose.yml
examples/nodejs/express/index.js

Fixes #1247 
`express`
`express-pull`
`express-ts`

fix: rideshare nodejs example anonymous functions 

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/ContextMenu.module.scss
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/RightClickIcon.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.module.scss
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/Tooltip.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.spec.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphComponent/index.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
packages/pyroscope-flamegraph/src/Toolbar.spec.tsx
packages/pyroscope-flamegraph/src/Toolbar.tsx
packages/pyroscope-flamegraph/src/__snapshots__/Toolbar.spec.tsx.snap
webapp/sass/variables.css

https://github.com/pyroscope-io/pyroscope/issues/1235
https://user-images.githubusercontent.com/6951209/179028292-20ba6fe0-333f-4a09-bb65-c9cf47c4833a.mp4

feat: update right-click context menu

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
packages/pyroscope-flamegraph/src/convert/convertJaegerTraceToProfile.ts
packages/pyroscope-flamegraph/src/index.tsx

Closes https://github.com/pyroscope-io/pyroscope/issues/1264

feat: remove trace field from FlamegraphRenderer

---

examples/tracing/jaeger/go/rideshare/go.sum

docs: updates tracing example with the right package name

---

packages/pyroscope-flamegraph/src/ProfilerTable.module.scss
webapp/javascript/components/FileList.module.scss
webapp/sass/common.scss
webapp/sass/variables.css

chore: cleanup light mode highlight color

---

packages/pyroscope-flamegraph/README.md
packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx

Updates flamegraph message as well as the NPM readme and somehow in #1284 it didn't trigger a new version on npm so this is partially to try and trigger that

chore: Update flamegraph message and readme

---

webapp/javascript/components/Settings/APIKeys/APIKeyAddForm.tsx
webapp/javascript/services/apiKeys.ts

The services code doesn't infer types very well, so if you are not careful you may point to a wrong type :/

chore: fix type

---

pkg/agent/ebpfspy/session_linux.go

Here we read until eof synchronously 
https://github.com/pyroscope-io/pyroscope/blob/9cb58b167c45a667da1ebb1010d28bff2f454672/pkg/agent/ebpfspy/session_linux.go#L103 
Here we read one line of stdout asynchronously and block because the used channel is not buffered
https://github.com/pyroscope-io/pyroscope/blob/9cb58b167c45a667da1ebb1010d28bff2f454672/pkg/agent/ebpfspy/session_linux.go#L87
When `profile-bpfcc` receives SIGINT it tries to write a bunch of lines and blocks hitting kernel limit (I suppose 64k) and blocks. When it receives SIGINT it retries.
```
sudo strace -fp $(pgrep bpf)
strace: Process 63089 attached
write(1, "ThreadPoolForeg;start_thread;bas"..., 6969) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} --- …
```

fix(ebpf) fix stderr reading deadlock

---

pkg/cli/command.go
pkg/cli/flags_test.go
pkg/cli/server.go
pkg/cli/testdata/substitutions.yml

Still need to handle $1:$2 case properly, I have an idea for it, just need to implement it.

feat: implements support for environment variable substitutions in config file

---

pkg/server/export.go

Added Handle errors when flamegraph.com responds with non 2xx

---

README.md

See https://pyroscope.io/docs/aws-lambda/.

[docs] Adds AWS Lambda extension to 3rd party list

---

pkg/structs/transporttrie/serialize.go

This change stems from the conversation on #573

call ReadFrom directly instead of CopyN

---

webapp/javascript/components/AppSelector/SelectorModal.module.scss
webapp/javascript/components/AppSelector/SelectorModal.tsx

https://github.com/pyroscope-io/pyroscope/issues/1337

feat: add app dropdown footer

---

packages/pyroscope-flamegraph/src/Tooltip/Tooltip.tsx
packages/pyroscope-flamegraph/src/format/format.spec.ts
packages/pyroscope-flamegraph/src/format/format.ts

https://github.com/pyroscope-io/pyroscope/issues/1332

feat: add tooltip table text for when units is undefined

---

pkg/scrape/scrape.go

Fixes typo in logging message #1360

chore: fix typo in logging message

---

go.mod
go.sum
pkg/server/controller.go

feat: support for content-encoding request header

---

packages/pyroscope-flamegraph/src/ProfilerHeader.module.css

https://github.com/pyroscope-io/pyroscope/issues/1359

fix: export flamegraph "head" select styles

---

webapp/javascript/pages/TagExplorerView.module.scss
webapp/javascript/pages/TagExplorerView.tsx
webapp/javascript/redux/reducers/continuous.ts

https://github.com/pyroscope-io/pyroscope/issues/136
https://user-images.githubusercontent.com/47758224/183453662-150b3a1f-44c0-404b-93ab-05805cb3f6b3.mov

feat: add loader to tag exlorer page

---

webapp/sass/common.scss

https://github.com/pyroscope-io/pyroscope/issues/1358

feat: add ProfilerTable arrow color

---

webapp/javascript/pages/TagExplorerView.tsx

https://github.com/pyroscope-io/pyroscope/issues/1364

feat: support high number of series in explore view timeline

---

pkg/server/index.go
webapp/javascript/components/Protected.tsx
webapp/javascript/components/Settings/index.tsx
webapp/javascript/components/Sidebar.tsx

Fixes an issue introduced in https://github.com/pyroscope-io/pyroscope/pull/1355

fix(webapp): fixes auth

---

go.mod
go.sum
pkg/agent/clib/logging.go
pkg/agent/debugspy/debugspy.go
pkg/agent/dotnetspy/dotnetspy.go
pkg/agent/ebpfspy/ebpfspy_linux.go
pkg/agent/ebpfspy/sd/k8s.go
pkg/agent/ebpfspy/session_linux.go
pkg/agent/gospy/gospy.go
pkg/agent/gospy/gospy_test.go
pkg/agent/log/logger.go
pkg/agent/logger/logger.go
pkg/agent/phpspy/phpspy.go
pkg/agent/profiler/profiler.go
pkg/agent/pyspy/pyspy.go
pkg/agent/rbspy/rbspy.go
pkg/agent/session.go
pkg/agent/spy/spy.go
pkg/agent/upstream/remote/remote.go
pkg/exec/ebpf.go

- ignore pods with empty containerID
- add logger to spies
- add some debug logging to k8s
- add offsets to unknown symbols like [unknown module.so+0x4242]

fix(ebpf): ignore pods with empty containerID

---

webapp/javascript/ui/Notifications.tsx

https://user-images.githubusercontent.com/6951209/188214368-1665810b-6a73-4708-9a6d-ab2f7f16b1fa.mp4

feat(webapp): display timer for notifications

---

pkg/server/ingest.go

Reverts pyroscope-io/pyroscope#1482
This breaks remote-write flow.

Revert "fix: add pprof format during ingestion to RawProfile"

---

pkg/server/httputils/default.go

Just something minor I found out. `Content-type` header wasn't being sent properly:
```
❯ curl -X POST -d '{ "test": "" }' localhost:4040/api/keys -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:4040...
* Connected to localhost (127.0.0.1) port 4040 (#0)
> POST /api/keys HTTP/1.1
> Host: localhost:4040
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 32
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Vary: Accept-Encoding
< Date: Thu, 08 Sep 2022 16:37:47 GMT
< Content-Length: 34
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{"errors":["invalid credentials"]}⏎
```
```
< Content-Type: text/plain; charset=utf-8
``` …

chore(server): set content-type correctly

---

webapp/javascript/pages/TagExplorerView.tsx

renames to tag breakdown in preparation for #1477

chore: rename descriptive statistics title

---

webapp/javascript/components/TimelineChart/TimelineChartWrapper.tsx
webapp/sass/profile.scss

- https://github.com/pyroscope-io/pyroscope/issues/1400
- added crosshair cursor
- removed circles in data points on line charts
- changed lineWidth to line chart from 1 to 0.8
- I think that simply reducing the line width for line charts is not the best option, and we need to do this dynamically based on the lengths of dataPoints and Apps arrays. Reducing the width looks good for large time periods (and big data), but almost useless for small
https://user-images.githubusercontent.com/23450818/186914561-e0d707d9-6cb9-4f89-baec-28110d336d7b.mov

chore(webapp): timeline chart, removed circles on dataPoints, added crosshair cursor

---

examples/dotnet/fast-slow/Dockerfile
examples/dotnet/fast-slow/example/Example.csproj
examples/dotnet/web/Dockerfile
examples/dotnet/web/example/Example.csproj

See https://github.com/pyroscope-io/docs/pull/120

chore: update dotnet version in examples

---

pkg/server/exemplars_merge.go
pkg/server/exemplars_query.go

There are two minor improvements:
1. Make it so that only selected area time range is read if heatmap is disabled
2. float Min and Max values are rounded so that Max-Min >= 1 (if Max != Min)

chore: improve exemplars selection

---

pkg/service/annotation.go
pkg/service/annotation_test.go

Closes https://github.com/pyroscope-io/pyroscope/issues/1507

fix(backend): upsert annotations

---

webapp/javascript/components/Heatmap/Heatmap.module.scss
webapp/javascript/components/Heatmap/Heatmap.spec.tsx
webapp/javascript/components/Heatmap/HeatmapTooltip.tsx
webapp/javascript/components/Heatmap/constants.ts
webapp/javascript/components/Heatmap/index.tsx
webapp/javascript/components/Heatmap/utils.ts
webapp/javascript/components/TimelineChart/getFormatLabel.ts
webapp/javascript/redux/reducers/continuous.ts
webapp/javascript/services/tags.ts
webapp/javascript/util/formatDate.ts

- 
- moved heatmap legend
- add loading indicator when fetching profile data after selection
- add basic tooltip with time
- show tooltip when hover on selected area
- add common timestamp format
- fix labels failing request
- same tooltip logic (mouseenter/mouseleave/mousemove events) should be reused between FlamegraphTooltip/TableTooltip and new HeatmapTooltip components

feat: heatmap improvements

---

examples/python/rideshare/README.md

Update rideshare Python example

docs: Update Python Rideshare example

---

webapp/javascript/ui/Dialog/Dialog.tsx

typo, should've exported as a named export

chore(webapp): fix DialogActions export

---

webapp/javascript/components/Heatmap/Heatmap.module.scss

- https://github.com/pyroscope-io/pyroscope/issues/1554
- remove gridlines in Heatmap
-

feat: remove gridlines in Heatmap

---

webapp/javascript/components/Heatmap/Heatmap.module.scss
webapp/javascript/components/Heatmap/Heatmap.spec.tsx
webapp/javascript/components/Heatmap/index.tsx
webapp/javascript/components/Heatmap/utils.ts
webapp/javascript/pages/ExemplarsSingleView.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1553
- add ticks to x and y-axis
-

feat: add ticks to x and y-axis

---

webapp/javascript/pages/ExemplarsSingleView.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1573
- add table view to heatmap flamegraph
-

feat: add table view to heatmap flamegraph

---

webapp/javascript/ui/Dialog/Dialog.module.css
webapp/javascript/ui/Dialog/Dialog.tsx
webapp/javascript/ui/InputField/InputField.module.css
webapp/javascript/ui/InputField/index.tsx

Fixes some css bugs, makes modals look more like cloud modals, makes things more consistent

chore(frontend): style changes

---

webapp/javascript/components/ExportData.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1450
-  close export dropdown when clicking outside or clicking export button
https://user-images.githubusercontent.com/47758224/193238454-4dd7d9d0-d235-49a0-8057-aedc9391c5d5.mov
-

fix: export dropdown should close when clicking outside

---

Dockerfile
pkg/agent/phpspy/phpspy.go

- removed rbspy, phpspy, rustdeps from building inside docker
- update alpine to 3.16, go to 1.19, php to 7.4, node to 18
- add `apk upgrade` to pickup latest patches

chore: update deps in dockerfile

---

pkg/convert/jfr/parser.go
pkg/convert/jfr/parser_jvm_generated_class_merge_test.go

changes 
`libzstd-jni-1.5.1-16931311898282279136.so.Java_com_github_luben_zstd_ZstdInputStreamNoFinalizer_decompressStream`
to 
`libzstd-jni-1.5.1-_.so.Java_com_github_luben_zstd_ZstdInputStreamNoFinalizer_decompressStream`

fix: merge zstd lib generated so names for jfr

---

examples/ruby/rideshare_rails/Gemfile
examples/ruby/rideshare_rails/Gemfile.lock
examples/ruby/rideshare_rails/config/initializers/pyroscope.rb
examples/tracing/jaeger/ruby/rideshare/Gemfile
examples/tracing/jaeger/ruby/rideshare/Gemfile.lock

- add otel-profiling-ruby to ruby rails example
- also update otel-profiling-ruby to fix a bug https://github.com/pyroscope-io/otel-profiling-ruby/commit/810d1e498bd32afc6ec6c1f4b508da700f6cb3a9

docs: add exemplars to rideshare rails example

---

webapp/javascript/pages/ServiceDiscovery.module.scss
webapp/javascript/pages/ServiceDiscovery.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1624
- refactored styles for Service Discovery page
https://user-images.githubusercontent.com/7372044/196435213-84bddda3-6302-40dc-84d5-999ca7862591.mp4

refactor(webapp): Service Discovery table styles

---

webapp/javascript/components/AppSelector/AppSelector.module.scss
webapp/javascript/components/AppSelector/SelectButton.module.scss
webapp/javascript/components/AppSelector/SelectButton.tsx
webapp/javascript/ui/Modals/ModalWithToggle.module.scss

- https://github.com/pyroscope-io/pyroscope/issues/1616
- updated styles for app selector
- DEMO https://pr-1630.pyroscope.io/

refactor(webapp): Make app selector dropdown adapt to width of content

---

webapp/javascript/components/TimelineChart/ExploreTooltip/index.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1487
- updated percentage calculating logic
- DEMO: https://pr-1631.pyroscope.io/

refactor(webapp): Show percentages based on values for the same time period, not all time

---

.tool-versions

I may be the only one that currently uses it, but at least it works as documentation.

chore: asdf

---

pkg/server/controller.go

not an optimal solution but a quick fix for demo-dev to work

fix: make /apps respect remoteRead

---

webapp/javascript/components/CustomDatePicker.module.scss
webapp/javascript/components/CustomDatePicker.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1632

refactor(webapp): Update time selector dropdown styling

---

packages/pyroscope-flamegraph/src/convert/sandwichViewProfiles.ts

chore(frontend): sandwich view fix

---

packages/pyroscope-flamegraph/src/FlameGraph/FlameGraphRenderer.tsx
packages/pyroscope-flamegraph/src/FlameGraph/FlamegraphRenderer.module.scss

- https://github.com/pyroscope-io/pyroscope/issues/1686
- fix arrow styles for comparison view
-

fix: sandwich view prompt in comparison view

---

webapp/javascript/pages/ExemplarsSingleView.tsx

- 
- add TagsBar component to exemplars single view
-

feat: add TagsBar component to exemplars single view

---

webapp/sass/variables.css

chore: update light mode sandwich prompt

---

webapp/javascript/ui/Tooltip.module.scss
webapp/sass/variables.css

chore: update light mode tooltip color

---

webapp/javascript/pages/TagExplorerView.tsx
webapp/javascript/pages/formatTableData.ts
webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChart/Interactivity.plugin.ts
webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChart/index.tsx
webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/PieChartTooltip/index.tsx
webapp/javascript/pages/tagExplorer/components/TotalSamplesChart/index.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1706
- DEMO: https://pr-1720.pyroscope.io/

feat(webapp): Display units in pie chart tooltip

---

webapp/javascript/pages/TagExplorerView.module.scss
webapp/javascript/pages/TagExplorerView.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1666
- DEMO: https://pr-1718.pyroscope.io/

fix(webapp): WHERE selector width when value too long for displaying

---

webapp/javascript/pages/tagExplorer/components/TagsSelector.module.scss

- add min-width to left and right(base/comp) column
- add max-width to container component
https://user-images.githubusercontent.com/47758224/204571681-3bf2cf2b-50dc-43e5-b241-1be0fb47a8e5.mov

fix: refactor tags dropdown width

---

packages/pyroscope-flamegraph/src/ProfilerTable.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1770
- add ability to sort by diff column

feat(flamegraph): allow sorting by diff percentage

---

packages/pyroscope-flamegraph/src/Toolbar.module.scss
packages/pyroscope-flamegraph/src/Toolbar.tsx
packages/pyroscope-flamegraph/src/__snapshots__/Toolbar.spec.tsx.snap

- fix console MMUI warning
- fix tooltip on disabled item
- add missing divider
- return back divider margins
https://user-images.githubusercontent.com/47758224/204797769-8ee603ba-6b07-4c1e-8e64-e9c09d1080c6.mov

fix: small toolbar fixes

---

stories/Tabs.stories.tsx
webapp/javascript/pages/adhoc/AdhocComparison.tsx
webapp/javascript/pages/adhoc/AdhocDiff.tsx
webapp/javascript/pages/adhoc/AdhocSingle.tsx
webapp/javascript/pages/exemplars/ExemplarsSingleView.tsx
webapp/javascript/ui/Tabs.spec.tsx
webapp/javascript/ui/Tabs.tsx

- https://github.com/pyroscope-io/pyroscope/issues/1769
- Added `TabPane`;
- Added stories for Tabs
- Added basic tests
**Demo:**  https://pr-1783.pyroscope.io/

chore(webapp): Cleanup tabs

---

packages/pyroscope-flamegraph/src/Toolbar.module.scss

- https://github.com/pyroscope-io/pyroscope/issues/1780
DEMO: https://pr-1785.pyroscope.io/

fix(webapp | flamegraph): toolbar overlaps annotation

---

examples/auth-env-var/docker-compose.yml
examples/auth-env-var/server.yml

This issue was brought up in our slack channel.
Basically add a minimal example showing how to overwrite configs via env vars.

example: add minimal example on how to use env vars to set config

---

webapp/javascript/components/EnhancedAppSelector/EnhancedAppSelector.module.scss
webapp/javascript/components/EnhancedAppSelector/EnhancedAppSelector.tsx
webapp/javascript/components/EnhancedAppSelector/SelectButton.module.scss
webapp/javascript/components/EnhancedAppSelector/SelectButton.tsx
webapp/javascript/components/EnhancedAppSelector/SpyNameIcons.tsx
webapp/javascript/components/EnhancedAppSelector/useFilters.ts
webapp/javascript/components/EnhancedAppSelector/useFiltersValues.ts
webapp/sass/variables.css

Superseeds https://github.com/pyroscope-io/pyroscope/pull/1792
* Create an `EnhancedAppSelector`, not in use in the current application
* Still keep an `AppSelector`
The motivation is to not have a PR lingering, and to develop/improve that implementation in parallel, not breaking the existing implementation.
It still requires some work to be prod ready.

chore: enhanced app selector

---

.size-limit.js

Bundle was increased in https://github.com/pyroscope-io/pyroscope/pull/1759

build: increase size-limit loading time

---

.github/workflows/ci-profiling.yaml

build: ci profiling

---

webapp/javascript/components/TimelineChart/AnnotationMark/index.tsx
webapp/javascript/components/TimelineChart/Annotations.plugin.tsx
webapp/javascript/pages/continuous/contextMenu/AddAnnotation.menuitem.module.css
webapp/javascript/pages/continuous/contextMenu/AddAnnotation.menuitem.tsx
webapp/javascript/pages/continuous/contextMenu/AnnotationInfo.tsx
webapp/javascript/ui/Popover.tsx

Closes https://github.com/pyroscope-io/pyroscope/issues/1806
#Before

fix(webapp): always render annotations in the viewport

---

CONTRIBUTING.md

It works. But maybe better to update it.

docs: update outdated link in CONTRIBUTING.md

---

packages/pyroscope-flamegraph/src/ProfilerTable.tsx

Related: https://github.com/grafana/pyroscope/pull/1906
Basically when a node name is for ex `toString`, this bit here
https://github.com/grafana/pyroscope/blob/6b274aa4c189621fbf09e3c946028ba0bfc6e838/packages/pyroscope-flamegraph/src/ProfilerTable.tsx#L101
will return the original `toString` method (from the prototype chain), which we then mutate:
https://github.com/grafana/pyroscope/blob/6b274aa4c189621fbf09e3c946028ba0bfc6e838/packages/pyroscope-flamegraph/src/ProfilerTable.tsx#L53-L55
Leaking to all objects!
```js
function toString()
length: 0
name: "toString"
self: 0
total: 771
type: "single"
<prototype>: function ()
```
I didn't see this bug affecting anything though.
Btw, I found where this was by creating a proxy:
```js
Object.prototype.toString = new …
```

fix(pyroscope-flamegraph): ProfilerTable polluting prototype

---

webapp/javascript/components/AppSelector/Label.tsx
webapp/javascript/components/AppSelector/index.tsx
webapp/javascript/components/Toolbar.tsx

So that we can replace in phlare's ui

chore(webapp): allow overwriting app selector label

---

examples/dotnet/rideshare/Dockerfile
examples/dotnet/web-new/Dockerfile

docs(dotnet): update example

---

pkg/api/adhoc.go
pkg/api/router/router.go
pkg/cli/flags_test.go
pkg/config/config.go
pkg/server/controller.go

- configure adhoc max file size instead of hardcoding 5M
- better error message when the limit is reached

chore(adhoc): max file size

---

examples/grafana-agent/agent/config/config.river

remove phlare references in agent flow configuration
depends on https://github.com/grafana/agent/pull/4013

fix(docs): update grafana-agent example

---

examples/grafana-agent/README.md

docs: Update Grafana Agent example readme

---

webapp/javascript/components/ExportData.tsx

to fix: https://github.com/grafana/pyroscope/issues/1971

fix export pprof/html in baseurl

---

.github/workflows/weekly-release.yml
.goreleaser.yaml

This will fix the weekly build in preparation for Monday's weekly release.

Update image name in goreleaser

---

pkg/phlaredb/block/list.go
pkg/phlaredb/compact.go
pkg/phlaredb/compact_test.go
pkg/phlaredb/profile_store.go
pkg/phlaredb/schemas/v1/profiles.go
pkg/phlaredb/schemas/v1/profiles_test.go
pkg/phlaredb/schemas/v1/schema_test.go
pkg/pprof/testhelper/profile_builder.go

This also adds a bunch of tests that were missing.
I still needs to add Compact Test with querying and deduping.

Fixes a compaction bug in series rewriting

---

pkg/parquet/row_writer.go
pkg/phlaredb/compact.go
pkg/phlaredb/compact_test.go

This adds even more tests and fixes 2 bugs surfaced with them:
- We were writing twice the last series.
- We were not correctly setting the column seriesIndex in the profile parquet file.

Fixes compaction incorrect profile seriesRef column

---

docs/sources/_index.md

need a change to cause a deploy

Update Grafana Phlare to Grafana Pyroscope

---

.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/weekly-release.yml

This one support the repository parameter

Switch to tibdex/github-app-token@v1 workflow

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml
docs/sources/_index.md

- Switch to master branch of the website
- Make a change so it gets deployed

Switch docs deploy to master of website

---

docs/sources/configure-client/grafana-agent/_index.md
docs/sources/configure-client/grafana-agent/go_pull.md

Add grafana agent index page

---

docs/sources/configure-client/grafana-agent/_index.md

Fix docs text

---

Makefile

This fixes an additional trailing `/` on #2210

Fix branch name

---

Makefile

Ensure jb is in PATH for updater, continued #2222

Ensure jb is in PATH for update

---

docs/sources/upgrade-guide/_index.md
docs/sources/upgrade-guide/upgrade-to-v1.md

It is ready. I split it from [the old PR](https://github.com/grafana/pyroscope/pull/2190)

docs: v1 upgrade guide

---

pkg/phlaredb/symdb/block_reader.go

Trying to fix these errors: https://github.com/grafana/pyroscope/actions/runs/5907340093/job/16025109835

chore: trying to fix a test

---

pkg/model/flamegraph_diff.go
pkg/model/flamegraph_diff_test.go
pkg/model/tree.go
pkg/model/tree_test.go

Fix OOM caused by big max_nodes parameter

---

pkg/model/flamegraph.go
pkg/model/flamegraph_test.go

Fixes a panic when flamegraph is nil 

---

examples/golang-pull/kubernetes/README.md
operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
operations/pyroscope/helm/pyroscope/values.yaml
operations/pyroscope/jsonnet/values.json

once we merge it this it will release helm chart

chore: helm v1.0.0 release

---

docs/sources/configure-client/_index.md
docs/sources/configure-client/grafana-agent/_index.md
docs/sources/configure-client/grafana-agent/ebpf.md
docs/sources/configure-client/grafana-agent/go_pull.md
docs/sources/configure-client/language-sdks/_index.md
docs/sources/configure-client/language-sdks/java.md
docs/sources/deploy-kubernetes/helm.md
examples/grafana-agent/README.md
operations/pyroscope/helm/pyroscope/templates/NOTES.txt

now that we have the latest docs live we can change this back

docs: s/next/latest/g

---

README.md

Update pyroscope readme

---

.github/workflows/release.yml

This should automated brew releases

build: adds automation for brew releases

---

docs/sources/configure-server/about-tenant-ids.md

Multiple community report of confusion that this was disable by default and not on.

Improve mulitenancy default behaviour documentation

---

operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml

Includes #2360, #2289, #2363, #2364

Bump chart version

---

pkg/phlaredb/testdata/01HA2V3CPSZ9E0HMQNNHH89WSS/profiles.csv

In https://github.com/grafana/pyroscope/pull/2431 I committed a scratch file on accident. Let's remove that,

Remove test file

---

examples/golang-push/rideshare/loadgen.go

I somehow forgot to include this change here https://github.com/grafana/pyroscope/pull/2478
I already applied it in dev cluster

fix: rideshare loadgen fix

---

pkg/phlaredb/symdb/block_reader.go

The change removes unused wait group.

Load stack trace chunks synchronously

---

go.mod
go.sum

seen in https://github.com/parquet-go/parquet-go/issues/70

Updates parquet-go to avoid data corruption 

---

docs/internal/RELEASE.md

adding a note about not deleting releases

docs: Update RELEASE.md

---

operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
operations/pyroscope/helm/pyroscope/values.yaml
operations/pyroscope/jsonnet/values.json

This updates helm to use the latest helm chart from yesterday's release

Update helm chart to use latest version of pyroscope image

---

examples/golang-push/rideshare/loadgen.go

this makes it so that go version resembles the [python version](https://github.com/grafana/pyroscope/blob/main/examples/python/rideshare/django/load-generator.py) more — that one produces slightly more interesting looking graphs in demos
cc @Rperry2174 @korniltsev

docs: improves loadgen program

---

Makefile

This is useful for testing helm chart changes

Allow specifying of extra helm args

---

operations/pyroscope/helm/pyroscope/ci/micro-services-values.yaml

We acutally didn't update this in a while and so don't fully test those services.

Update microservices values for ci tests

---

tools/monitoring/.gitignore
tools/monitoring/environments/default/monitoring.libsonnet
tools/monitoring/vendor/.gitignore

Something we forgot to rename for a while 🙂

Renames in deploy-monitoring

---

examples/golang-push/rideshare/main.go

see [this slack convo](https://raintank-corp.slack.com/archives/C0594CM22JX/p1698077978942139?thread_ts=1698076551.971159&cid=C0594CM22JX) for more context

docs: improves naming in rideshare example

---

examples/golang-push/rideshare/rideshare/rideshare.go

This will use relevant OTLP tags as loki labels

Rideshare: Make sure loki extracts the right labels with OTLP

---

pkg/phlare/phlare.go
pkg/util/http.go

Not sure why we don't want to see those :).

Logs body of 500s http responses

---

.husky/pre-commit
package.json
yarn.lock

Just to prevent Prettier to fail the build.

chore(DevX): Add lint-staged to launch Prettier when commiting

---

cmd/profilecli/parquet.go

While looking at some stats, I realised it wasn't making sense for some rowgroups and in fact it was wrong.
We were always using stats for pages of the first rowgroups.
This PR fixes and add more page size stats (min,max).
```
Row group: 29
Row Count: 100000
Row size: 1.9 GB
Columns:
+--------------------------------------------------+----------------------+-----------+---------------------+-----------------------+-------------+-------+-----------+--------------------------------+
|                       COL                        |         TYPE         |  NUMVAL   | TOTALCOMPRESSEDSIZE | TOTALUNCOMPRESSEDSIZE | COMPRESSION |   %   | PAGECOUNT |            PAGESIZE            |
+--------------------------------------------------+----------------------+-----------+---------------------+---- …
```

Fixes the page stats in parquet inspect

---

pkg/distributor/distributor.go
pkg/distributor/distributor_test.go

Aggregation does not play well with sessions randomization. The change makes it so that mechanisms can be leveraged together.

Randomize sessions after aggregation

---

docs/sources/configure-client/language-sdks/dotnet.md
docs/sources/configure-client/language-sdks/java.md
examples/dotnet/fast-slow/Dockerfile
examples/dotnet/fast-slow/musl.Dockerfile
examples/dotnet/rideshare/Dockerfile
examples/dotnet/rideshare/example/Program.cs
examples/dotnet/rideshare/load-generator.py
examples/dotnet/rideshare/musl.Dockerfile
examples/dotnet/web-new/Dockerfile
examples/golang-push/rideshare/go.sum
examples/java/fib/Dockerfile
examples/java/rideshare/Dockerfile
examples/java/rideshare/build.gradle.kts
examples/java/simple/Dockerfile
go.mod
go.sum

- run `make tools/update_examples`
- update dotnet example to open /dev/null 1024 times

chore(examples): update examples

---

cmd/pyroscope/help-all.txt.tmpl
cmd/pyroscope/help.txt.tmpl
docs/sources/configure-server/reference-configuration-parameters/index.md
pkg/frontend/frontend.go
pkg/frontend/frontend_diff.go
pkg/frontend/frontend_select_merge_span_profile.go
pkg/frontend/frontend_select_merge_stacktraces.go
pkg/model/flamegraph_diff.go
pkg/querier/querier.go
pkg/validation/exporter/exporter.go
pkg/validation/exporter/exporter_test.go
pkg/validation/limits.go
pkg/validation/testutil.go
pkg/validation/validate.go
pkg/validation/validate_test.go

Please also see https://github.com/grafana/pyroscope-app-plugin/issues/170

Make max flamegraph nodes limit configurable

---

pkg/usagestats/stats.go

I guess a better solution would be using a flat `sync.Map` of atomics (or just pointers to integers) with structured keys (`{dimension string, stat string}`), and upserting new values with `LoadOrUpdate`. However, I don't think the optimisation is warranted at this point

fix: stats race condition

---

pkg/distributor/distributor_test.go

Discovered in https://github.com/grafana/pyroscope/actions/runs/6872731032/job/18691976067

fix: flaky aggregation test

---

pkg/frontend/frontend_label_names.go
pkg/frontend/frontend_label_values.go
pkg/frontend/frontend_profile_types.go
pkg/frontend/frontend_scheduler_worker.go
pkg/frontend/frontend_select_merge_profile.go
pkg/frontend/frontend_select_merge_span_profile.go
pkg/frontend/frontend_select_merge_stacktraces.go
pkg/frontend/frontend_select_series.go
pkg/frontend/frontend_series.go

This adds missing informations but specially maxNodes.

feat: Improve tracing span tags in the query-frontend.

---

pkg/querier/querier.go

This is a refactor that aligns how we query series with the MergeStacktraces

Refactor Series to use storeQuery

---

ebpf/pprof/pprof.go

address #2788  comments
nothing's really changed, just make code little bit cleaner

fix(ebpf): #2788 followup

---

examples/golang-push/rideshare/go.work.sum
pkg/util/spanprofiler/README.md
pkg/util/spanprofiler/spanprofiler.go
pkg/util/spanprofiler/spanprofiler_test.go
pkg/util/spanprofiler/tracer.go
pkg/util/spanprofiler/tracer_test.go

Preparing to move the package to https://github.com/grafana/dskit
@cyriltovena It would be great if you could take a look when you get a chance. Especially, the [README](https://github.com/grafana/pyroscope/blob/54ae77caf092f026cefc0f58c5d45b72c94e2f18/pkg/util/spanprofiler/README.md) note: I want it to be comprehensive and exhaustive

chore: refine span profiler documentation

---

cmd/profilecli/bucket.go
pkg/operations/admin.go
pkg/operations/handlers.go
pkg/operations/handlers_test.go

Use the request context for the admin handlers

---

public/app/constants/profile-metrics.json

Updates metric in profilemetrics

Update metric in profile-metrics.json

---

docs/sources/configure-client/language-sdks/java.md
examples/golang-push/rideshare/rideshare/rideshare.go
examples/python/rideshare/django/app/hello_django/settings.py
examples/python/rideshare/flask/lib/server.py
examples/ruby/rideshare_rails/config/initializers/pyroscope.rb
examples/rust/rideshare/server/src/main.rs

removes old api key format from examples

remove old api key format from example docs

---

docs/sources/configure-client/language-sdks/dotnet.md

Updates supported .NET versions and platforms 
related: https://github.com/grafana/pyroscope-dotnet/pull/51

Update supported .NET platforms / versions

---

docs/sources/release-notes/_index.md
docs/sources/release-notes/v1-0.md
docs/sources/release-notes/v1-1.md
docs/sources/release-notes/v1-2.md

Add release notes for Pyroscope version 1.0 through 1.2.
Fixes: https://github.com/grafana/pyroscope/issues/2735

[DOC] Add release notes

---

pkg/distributor/distributor.go

feat: Logs push failure information

---

ebpf/sd/target.go

While reading the ebpf code and documentation I figured we can easily support docker swarm.

Support discovering docker swarm tasks for ebpf.

---

operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml
operations/pyroscope/helm/pyroscope/values.yaml
operations/pyroscope/jsonnet/values.json

To merge once https://github.com/grafana/pyroscope/actions/runs/7221213176/job/19675730049 is done.

helm: update pyroscope to v1.2.1

---

docs/sources/release-notes/v1-2.md

Create release notes for version 1.2.1. 
Note: I haven't added links to the docs that are mentioned. ideally, we should have inline doc links to any new features that have docs.

[DOC] Create release notes for v1.2.1

---

pkg/distributor/model/push.go
pkg/distributor/model/push_test.go

Addresses a new upcoming value for `pyroscope_spy` mentioned here: https://github.com/grafana/pyroscope/pull/2823#issuecomment-1858650902
Related to https://github.com/grafana/agent/pull/5985

Add grafana-agent.java language mapping

---

docs/sources/ingest-and-analyze-profile-data/self-vs-total.md

Add self vs total docs

---

pkg/compactor/bucket_compactor.go
pkg/compactor/compactor.go
pkg/phlaredb/block/block.go
pkg/phlaredb/block_querier_symbols.go
pkg/phlaredb/compact.go
pkg/phlaredb/validate.go

feat: Add tracing integrations to compaction

---

docs/sources/configure-client/aws-lambda.md
docs/sources/configure-client/memory-overhead.md

Add doc for memory overhead for the Pyroscope client.

[DOC] Add memory overhead doc

---

operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml

Update the chart for 1.3.0 release

chore: bump chart app version

---

README.md
docs/sources/configure-client/_index.md

update deployment diagram ... im sure there are other links somewhere that are missed

Update deployment diagram

---

docs/sources/configure-client/grafana-agent/ebpf/configuration/_index.md

https://github.com/grafana/agent/commit/73253f7a5bba658a7111e37ae70a32a23a35de18

docs: copypaste docs bout __process_pid__ label

---

docs/sources/configure-client/language-sdks/dotnet.md
docs/sources/configure-client/language-sdks/go_push.md
docs/sources/configure-client/language-sdks/java.md
docs/sources/configure-client/language-sdks/nodejs.md
docs/sources/configure-client/language-sdks/python.md
docs/sources/configure-client/language-sdks/ruby.md
docs/sources/configure-client/language-sdks/rust.md

* docs: fix pyroscope product link
* Change other occurences for consistency
---------
Co-authored-by: Christian Simon <simon@swine.de>
(cherry picked from commit 5c29551d3771f8fcc810c1aba3b8add167c9a38d)

[release/v1.3] docs: fix pyroscope product link

---

docs/sources/configure-client/_index.md
docs/sources/configure-client/grafana-agent/go_pull.md
docs/sources/configure-client/grafana-agent/java/_index.md
docs/sources/configure-client/language-sdks/_index.md
docs/sources/configure-client/language-sdks/dotnet.md
docs/sources/configure-client/language-sdks/java.md
docs/sources/configure-client/language-sdks/python.md
docs/sources/configure-client/language-sdks/ruby.md
docs/sources/configure-client/language-sdks/rust.md
docs/sources/introduction/pyroscope-in-grafana.md

Addresses links modified because of this PR: https://github.com/grafana/pyroscope/pull/3026
Note that the changes in this PR may cause some conflicts in text (but doesn't impact the links): https://github.com/grafana/pyroscope/pull/3028

[DOC] Update links for new examples folder

---

docs/sources/configure-client/_index.md
docs/sources/configure-client/go-span-profiles.md
docs/sources/configure-client/grafana-agent/go_pull.md
docs/sources/configure-client/grafana-agent/java/_index.md
docs/sources/configure-client/language-sdks/_index.md
docs/sources/configure-client/language-sdks/java.md
docs/sources/configure-client/language-sdks/python.md
docs/sources/configure-client/language-sdks/ruby.md
docs/sources/configure-client/language-sdks/rust.md
docs/sources/configure-server/about-server-api.md

[release/v1.4] Update example links to point to branch

---

docs/sources/configure-client/_index.md
docs/sources/configure-client/grafana-agent/go_pull.md
docs/sources/configure-client/language-sdks/_index.md
docs/sources/configure-client/language-sdks/java.md
docs/sources/configure-client/language-sdks/python.md
docs/sources/configure-client/language-sdks/ruby.md
docs/sources/configure-client/language-sdks/rust.md
docs/sources/configure-server/about-server-api.md

[release/v1.3] Update example links to point to branch

---

.github/workflows/test.yml

Updating the docs-validator version to bring in the latest changes. Note that the reference link format changes with this update.
FYI @jdbaldry

Update docs-validator version

---

README.md

cc @Rperry2174 there might be more of those problem looming somewhere 😂

Fix example links in README.md

---

pkg/phlaredb/symdb/resolver_pprof.go
pkg/phlaredb/symdb/resolver_pprof_test.go
pkg/phlaredb/symdb/symdb.go

fix: ensure pprof strings[0] is always ""

---

docs/sources/view-and-analyze-profile-data/flamegraphs.md

Add link to the Pyroscope UI doc in the flame graph doc.

[DOC Update flamegraphs.md

---

.github/workflows/fuzzer.yml

Allow fuzzer to run manually

---

pkg/phlaredb/query/repeated.go

perf: tune row iterator buffer size

---

.github/workflows/e2e.yaml
.github/workflows/fuzzer.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/test_ebpf.yml
.github/workflows/weekly-release.yml
.goreleaser.yaml
examples/golang-pgo/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/simple/Dockerfile

See: https://groups.google.com/g/golang-announce/c/eoj5XPifNtA/m/WJAi2b2WBQAJ

Update golang version to 1.21.10

---

examples/README.md

Update the REAMDE for examples using content from the Configure the client doc. 
Fixes: https://github.com/grafana/pyroscope/issues/3225

[DOC] Update the README for examples

---

docs/sources/configure-client/_index.md
docs/sources/configure-client/grafana-agent/ebpf/setup-kubernetes.md
docs/sources/configure-server/_index.md
docs/sources/deploy-kubernetes/_index.md
docs/sources/get-started/_index.md
docs/sources/introduction/_index.md
docs/sources/reference-pyroscope-architecture/_index.md
docs/sources/release-notes/_index.md
docs/sources/upgrade-guide/_index.md
docs/sources/view-and-analyze-profile-data/_index.md

This doc PR does several things: 
* Fixes a few minor linting issues
* Corrects the page weight for the table of contents
* Updates some text to use Alloy and Agent 
* Added the Alloy admonition to one of the pages

[DOC] Fix page weights for the table of contents

---

pkg/og/structs/flamebearer/flamebearer.go
pkg/og/structs/flamebearer/flamebearer_test.go

Tries to address #3320. Without the actual input, it is only a guess that this is what caused it.

Improve validation for Ad Hoc profile uploads

---

cmd/profilecli/client.go
cmd/profilecli/query.go
cmd/profilecli/upload.go

This allows to switch out the connect protocol for either json or grpc-web.

feat(profilecli): Allow to use different protocols

---

cmd/pyroscope/Dockerfile
cmd/pyroscope/debug.Dockerfile

Fixes #3355
Not quite released yet 😢

Update alpine version to 3.18.7

---

.github/workflows/e2e.yaml
.github/workflows/fuzzer.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/test_ebpf.yml
.github/workflows/weekly-release.yml
.goreleaser.yaml
examples/golang-pgo/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/simple/Dockerfile

Backport fd207b19b46dfe03a0466a8238639958bfa8eeab from #3365

[release/v1.6] Update golang version to 1.21.11

---

operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/micro-services-hpa.yaml
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml

This updates the image version in helm

chore: Update helm to point to version v1.6.1

---

cmd/profilecli/query.go

This exposes the stacktrace selectors to profilecli. 
Was useful in investigating #3411

feat(profilecli): Add stacktrace selectors to query merge

---

pkg/phlaredb/profile_store.go

this likely never happened, but still

profileStore: add err check, return err if phlareparquet.CopyAsRowGroups returns err

---

.github/workflows/helm-ci.yml
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/templates/ingress.yaml
operations/pyroscope/helm/pyroscope/values-micro-services.yaml
operations/pyroscope/jsonnet/values-micro-services.json

They were so far not exposed in the values.yaml
This also adds them to ingress object.

chore: Deploy tenant-settings and adhoc-profiles microservices

---

docs/sources/configure-client/grafana-agent/ebpf/_index.md
docs/sources/configure-client/grafana-agent/ebpf/configuration/_index.md
docs/sources/configure-client/grafana-agent/go_pull.md
docs/sources/configure-client/grafana-agent/java/_index.md
docs/sources/configure-client/grafana-agent/sampling.md
docs/sources/configure-client/trace-span-profiles/_index.md
docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md
docs/sources/configure-client/trace-span-profiles/java-span-profiles.md
docs/sources/configure-client/trace-span-profiles/python-span-profiles.md
docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md
docs/sources/introduction/pyroscope-in-grafana.md

Fix broken links in the docs. 
Fixes: #3439

[DOC] Fix broken links

---

docs/sources/configure-client/grafana-agent/ebpf/setup-docker.md
docs/sources/configure-client/grafana-agent/ebpf/setup-kubernetes.md
docs/sources/configure-client/grafana-agent/ebpf/setup-linux.md
docs/sources/configure-client/grafana-agent/go_pull.md
docs/sources/configure-client/grafana-agent/java/_index.md
docs/sources/view-and-analyze-profile-data/_index.md

Fix the broken links from the docs 404 report.
Fixes #3488

[DOC] Fix broken links from doc 404 report

---

.github/workflows/update-contributors.yml
tools/update-contributors/main.go

- **Newline after contributors**
- **Use the PAT for pushing changes correctly**

chore: Another try to fix update-contributors

---

pkg/distributor/write_path/write_path_test.go

The PR fixes (reduces) flakiness of  a write path test

fix: flaky write-path test

---

docs/sources/configure-client/grafana-agent/java/_index.md

Add links to the Alloy instrumentation page to the updated Alloy examples.

[DOC] Add links to updated Alloy examples to docs

---

docs/sources/configure-client/grafana-alloy/ebpf/setup-kubernetes.md

got this request in slack: 
Docs don't make it super clear -- this is trying to improve that

docs: Update k8s + alloy setup docs

---

docs/sources/configure-client/language-sdks/dotnet.md
examples/language-sdk-instrumentation/dotnet/fast-slow/Dockerfile
examples/language-sdk-instrumentation/dotnet/fast-slow/musl.Dockerfile
examples/language-sdk-instrumentation/dotnet/rideshare/Dockerfile
examples/language-sdk-instrumentation/dotnet/rideshare/musl.Dockerfile
examples/language-sdk-instrumentation/dotnet/web-new/Dockerfile
examples/language-sdk-instrumentation/python/rideshare/django/app/requirements.txt
examples/language-sdk-instrumentation/python/rideshare/fastapi/Dockerfile
examples/language-sdk-instrumentation/python/rideshare/flask/Dockerfile
examples/language-sdk-instrumentation/python/simple/requirements.txt

run `make tools/update_examples`

chore(docs): update examples

---

.github/workflows/e2e.yaml
.github/workflows/fuzzer.yml
.github/workflows/release.yml
.github/workflows/test.yml
.github/workflows/test_ebpf.yml
.github/workflows/weekly-release.yml
.goreleaser.yaml
examples/golang-pgo/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/simple/Dockerfile

This is a small part of what we plan on doing in docs week.

chore(go): Update golang version to 1.22.10

---

examples/language-sdk-instrumentation/golang-push/rideshare-k6/README.md
examples/language-sdk-instrumentation/golang-push/rideshare-k6/docker-compose.yml
examples/language-sdk-instrumentation/golang-push/rideshare-k6/go.mod
examples/language-sdk-instrumentation/golang-push/rideshare-k6/go.sum
examples/language-sdk-instrumentation/golang-push/rideshare-k6/grafana-provisioning/pyroscope/config.yml
examples/language-sdk-instrumentation/golang-push/rideshare-k6/load.js
examples/language-sdk-instrumentation/golang-push/rideshare-k6/main.go

This fixes a variety of small issues with the Pyroscope k6 integration example.

Fix k6 example

---

pkg/experiment/metastore/raftnode/node.go
pkg/experiment/metastore/raftnode/node_metrics.go
pkg/experiment/metastore/raftnode/node_read.go
pkg/experiment/metastore/raftnode/observer.go

chore(v2): raft node metrics

---

tools/update_examples.Dockerfile

Fix https://github.com/grafana/pyroscope/actions/runs/12351303604/job/34465988406
```
/bin/sh: 1: cargo: not found
```

fix(examples): fix update_examples action, adding cargo

---

docs/sources/configure-client/language-sdks/nodejs.md

Missing a closing ` in the Nodejs documentation

chore: Update nodejs.md typo

---

docs/sources/release-notes/v1-12.md

This is the release note for the recently released v1.12.0

docs: Add v1.12 release notes

---

docs/internal/RELEASE.md

Clarify the release notes process to include Updates and breaking changes.

Update README for doc rel notes process

---

examples/tracing/golang-push/tempo/tempo.yml
examples/tracing/java/tempo/tempo.yml
examples/tracing/python/tempo/tempo.yml
examples/tracing/ruby/tempo/tempo.yml
examples/tracing/tempo/tempo/tempo.yml

See https://github.com/grafana/pyroscope/issues/3853

fix: update tracing tempo configs to point to localhost

---

pkg/frontend/read_path/query_service_handler.go
pkg/frontend/read_path/read_path_test.go
pkg/frontend/read_path/router.go

The series limit parameter is ignored when the query backend is enabled and the query is not split.

fix(v2): honour series limit in query router

---

.goreleaser.yaml

chore(ci): disable arm7 builds

---

go.mod
go.sum
tools/update_examples.go

Include these fixes
https://github.com/grafana/jfr-parser/commit/241171721abade88259627584b7c48f971c901b2 
https://github.com/grafana/jfr-parser/commit/b51778c4eb38e7db638a321c1c2937ff1b05bdf0

Jfr-parser bump dependency

---

.github/workflows/test.yml
docs/sources/_index.md
docs/sources/configure-client/trace-span-profiles/dotnet-span-profiles.md
docs/sources/configure-client/trace-span-profiles/go-span-profiles.md
docs/sources/configure-client/trace-span-profiles/java-span-profiles.md
docs/sources/configure-client/trace-span-profiles/python-span-profiles.md
docs/sources/configure-client/trace-span-profiles/ruby-span-profiles.md
docs/sources/configure-server/configure-shuffle-sharding/index.md
docs/sources/configure-server/configuring-memberlist.md
docs/sources/configure-server/storage/configure-disk-storage.md
docs/sources/configure-server/storage/configure-object-storage-backend.md
docs/sources/get-started/_index.md
docs/sources/reference-pyroscope-architecture/about-grafana-pyroscope-architecture/index.md
docs/sources/reference-pyroscope-architecture/bucket-index/index.md
docs/sources/reference-pyroscope-architecture/components/compactor/index.md
docs/sources/reference-pyroscope-architecture/components/distributor.md
docs/sources/reference-pyroscope-architecture/components/ingester.md
docs/sources/reference-pyroscope-architecture/components/querier.md
docs/sources/reference-pyroscope-architecture/components/query-frontend/index.md
docs/sources/reference-pyroscope-architecture/components/query-scheduler/index.md
docs/sources/reference-pyroscope-architecture/components/store-gateway.md
docs/sources/reference-pyroscope-architecture/deployment-modes/index.md
docs/sources/reference-pyroscope-architecture/hash-ring/index.md
docs/sources/reference-pyroscope-architecture/memberlist-and-the-gossip-protocol.md
docs/sources/upgrade-guide/_index.md
docs/sources/view-and-analyze-profile-data/analyze-profiles/_index.md

For https://github.com/grafana/website/issues/24017
Removes all relref shortcodes.
Created-By: reverse-changes
Repository: grafana/pyroscope
Website-Pull-Request: https://github.com/grafana/website/pull/24449

[v1.11] Remove relref shortcodes

---

pkg/distributor/aggregator/aggregator_test.go

@kolesnikovae I have seen quite a few flakes from this.
When the second aggregations happens (at ts=2), it sometimes might be fast enough to have the aggegrationKey deleated already.
I amended the test, that it accepts either outcome of the ts=2 following aggreagtions. But it also makes sure the aggregation eventually recovers.

fix(distributor): Test flake in the aggregator

---

package.json
yarn.lock

https://github.com/grafana/pyroscope/security/dependabot/743

chore: Upgrade prismjs in old frontend

---

globalTeardown.js
package.json
yarn.lock

This fixes https://github.com/grafana/pyroscope/security/dependabot/742

chore: Update @pyroscope/node-js

---

pkg/experiment/metastore/index/query_test.go

The newly introduced test suite may be flaky when run in CI

chore(v2): lighten metadata query test suite

---

cmd/pyroscope/help.txt.tmpl
pkg/objstore/providers/gcs/config.go

chore: mark GCS HTTP options advanced

---

pkg/experiment/query_backend/block_reader_test.go
pkg/experiment/query_backend/query_pprof.go

Fixes https://github.com/grafana/pyroscope-squad/issues/383
I'd prefer to handle that in the query-frontend, but I don't want it to be too aware of the data models.

fix(v2): set pprof sample and profile type

---

.github/workflows/update-examples-cron.yml
Makefile.examples
tools/get-latest-go-version.sh
tools/upgrade-go-version.sh

Rearranged steps in update-examples-cron workflow and added a dedicated step for Go version upgrades. Introduced scripts for fetching the latest Go patch version and updating build files automatically. Improved automation for managing Golang updates and generating corresponding pull requests.

Refactor workflows to streamline Go version updates

---

.github/workflows/e2e.yaml
.github/workflows/fuzzer.yml
.github/workflows/release.yml
.github/workflows/test-examples.yml
.github/workflows/test.yml
.github/workflows/test_ebpf.yml
.github/workflows/weekly-release.yml
.goreleaser.yaml
examples/golang-pgo/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/simple/Dockerfile
examples/tracing/golang-push/Dockerfile
examples/tracing/golang-push/Dockerfile.load-generator

Backport b0a4a4f24cba4aedc7da6ce3de51b3544f275ac2 from #4106

[release/v1.13] Update golang version to 1.23.8

---

pkg/experiment/metastore/compaction/compactor/plan.go

It's currently possible that compaction planning performs excessive loops while trying to build a job plan. This causes excessive CPU usage and may be harmful if the compaction queue is large (e.g., due to a delay in compaction).

perf(v2): optimize compaction planning

---

pkg/validation/limits.go

The change allows to reuse the tenant shard limit defined for shuffle sharding in the placement rules.

chore(v2): add support for the ingestion_tenant_shard_size limit

---

.golangci.yml
pkg/experiment/block/metadata/metadata_labels.go
pkg/experiment/block/section_profiles.go
pkg/experiment/distributor/distributor.go
pkg/experiment/distributor/placement/adaptive_placement/distribution_stats_test.go
pkg/experiment/distributor/placement/adaptive_placement/load_balancing.go
pkg/experiment/distributor/placement/adaptive_placement/shard_allocator_plot_test.go
pkg/experiment/ingester/client/client_test.go
pkg/experiment/ingester/memdb/head_test.go
pkg/experiment/ingester/memdb/profile_index_test.go
pkg/experiment/ingester/memdb/profiles.go
pkg/experiment/ingester/memdb/profiles_test.go
pkg/experiment/ingester/memdb/testutil/querier.go
pkg/experiment/ingester/segment.go
pkg/experiment/ingester/segment_test.go
pkg/experiment/ingester/service.go
pkg/experiment/metastore/admin/admin.go
pkg/experiment/metastore/compaction/compactor/plan_test.go
pkg/experiment/metastore/compaction/scheduler/scheduler_queue.go
pkg/experiment/metastore/discovery/dns.go
pkg/experiment/metastore/discovery/kuberesolver/builder.go
pkg/experiment/metastore/discovery/kuberesolver/kubernetes.go
pkg/experiment/metastore/discovery/parse.go
pkg/experiment/metastore/fsm/snapshot.go
pkg/experiment/metastore/index/index_cache.go
pkg/experiment/metastore/index/store/index_store.go
pkg/experiment/metrics/observer.go
pkg/experiment/query_backend/client/client_test.go

Cleaning up experimental modules: mostly tests and unused code. It does not affect functional parameters.

chore(v2): lint /experimental

---

.github/workflows/test.yml
.github/workflows/weekly-release.yml

- Pull secrets for docker hub from vault
- Use github token for publishing release

Refactor github actions

---

.github/workflows/release.yml

we need to put the app secrets into vault. I don't have access to the app to generate secrets, I will ask IT
asked platform
https://raintank-corp.slack.com/archives/CEXAGGYVC/p1745989364521239

reenable release workflow

---

pkg/ingester/ingester.go
pkg/ingester/ingester_test.go

This builds on top of #4151 and #4144, as previously initialised heads already created a folder on all ingesters. 
Hence the check is not detecting that there are actually no local blocks to be considered.

fix: Do not initialise local querier, when there are no local blocks

---

.github/workflows/update-examples-cron.yml

run every 8h instead of every 1h

chore(examples): run examples cron every 8h

---

examples/language-sdk-instrumentation/golang-push/rideshare-alloy/README.md
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/config.alloy
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/docker-compose.yml

Better to merge after https://github.com/grafana/pyroscope/pull/3951.

examples: use new Alloy release and use service_name for relabeling

---

.github/zizmor.yml

This should allow PRs from forks to pass the zizmor check

Add a default zizmor config

---

pkg/experiment/metastore/client/client.go
pkg/experiment/metastore/client/client_test.go
pkg/experiment/metastore/client/server_mock_test.go

Part of series of fixes for #3923
Verified that the output of
```
go test -v ./pkg/experiment/metastore/client
```
looks qualitatively the same across this PR.

chore: Use in-memory network connection for metastore client tests

---

pkg/util/gziphandler/gzip_test.go

chore: Use in-memory network connection for a gzip test

---

pkg/adhocprofiles/adhocprofiles.go
pkg/settings/bucket.go
pkg/settings/store/store.go

same as https://github.com/grafana/pyroscope/pull/4237
I did not change https://github.com/grafana/pyroscope/blob/main/pkg/storegateway/block.go#L43  since it works well 
@kolesnikovae please review this PR

fix: goroutine leak

---

pkg/experiment/metastore/raftnode/observer.go

This fixes a race condition where a raft state change could occur during metastore initialization – specifically while state change handlers are being registered. In practice, we notify about the current state immediately after the handler is registered, ensuring at-least-once delivery (it's not possible for a handler to miss a notification). The race was discovered during integration testing

fix(v2): raft state observer registration race

---

pkg/distributor/distributor.go
pkg/distributor/distributor_test.go
pkg/validation/limits.go

A small change I forgot to push when working on #4231

Improve override name for sampling

---

examples/grafana-alloy-auto-instrumentation/ebpf-otel/Dockerfile
examples/grafana-alloy-auto-instrumentation/ebpf-otel/kubernetes/otel-collector.yaml
examples/grafana-alloy-auto-instrumentation/ebpf-otel/kubernetes/pyroscope.yaml

Solves https://github.com/grafana/pyroscope/issues/4282

examples: update ebpf-otel versions

---

.github/workflows/publish-technical-documentation-next.yml
.github/workflows/publish-technical-documentation-release.yml
.github/workflows/update-make-docs.yml

Took the workflows from tempo: https://github.com/grafana/tempo/tree/main/.github/workflows

docs: Reenable the docs publishing workflow

---

docs/sources/_index.md

After #4291 we still need a change in that folder in order to trigger the workflow

docs: Add some more keywords, to trigger a docs publish

---

pkg/embedded/grafana/grafana.go

This is something, which has not been updated in a long time. I would like to give this another go in my development workflow.

chore: Update embedded grafana's version

---

.github/workflows/e2e.yaml
cypress/support/e2e.ts
package.json
yarn.lock

This hopefully should fix the non-blocking test errors

chore: Update cypress to latest version

---

pkg/distributor/distributor.go
pkg/distributor/metrics.go
pkg/distributor/model/push.go

distributor: add new metrics (#4367)

---

examples/grafana-alloy-auto-instrumentation/ebpf-otel/docker/docker-compose.yml

chore: Docker ebpf-otel example matches k8s versions

---

.github/workflows/ci.yml
.github/workflows/fuzzer.yml
.github/workflows/release.yml
.github/workflows/test-examples.yml
.github/workflows/weekly-release.yml
.goreleaser.yaml
api/go.mod
examples/golang-pgo/Dockerfile
examples/golang-pgo/go.mod
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare-alloy/go.mod
examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare-k6/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare-k6/go.mod
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile
examples/language-sdk-instrumentation/golang-push/rideshare/Dockerfile.load-generator
examples/language-sdk-instrumentation/golang-push/rideshare/go.mod
examples/language-sdk-instrumentation/golang-push/simple/Dockerfile
examples/language-sdk-instrumentation/golang-push/simple/go.mod
examples/tracing/golang-push/Dockerfile
examples/tracing/golang-push/Dockerfile.load-generator
examples/tracing/golang-push/go.mod
go.mod
go.work
lidia/go.mod

Updating golang version before creating the OSS release.

chore: update golang version to 1.24.8

---

docs/sources/release-notes/v1-15.md
operations/pyroscope/helm/pyroscope/Chart.yaml
operations/pyroscope/helm/pyroscope/README.md
operations/pyroscope/helm/pyroscope/rendered/legacy-micro-services-hpa.yaml
operations/pyroscope/helm/pyroscope/rendered/legacy-micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/micro-services-v2.yaml
operations/pyroscope/helm/pyroscope/rendered/micro-services.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary-v2.yaml
operations/pyroscope/helm/pyroscope/rendered/single-binary.yaml

I've recently released v1.15.0.

chore: Add release notes and update helm release for v1.15.0
